### ISSUE TITLE
Generate OS X installer binary

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#100]
See #66

**Comment by cbeams** [comment]
@ManfredKarrer, FYI for your usability testing, etc.: you can build the OS X installer by switching to the `native` branch and running `gradle build`. Afterward, you'll find the .dmg, .pkg and .app files in `build/distributions`.

**Comment by ManfredKarrer** [comment]
@cbeams: I just tried to build it from the latest version (native branch) but got that error:

Manfreds-iMac:bitsquare-native mk$ gradle build
:compileJava
/Users/mk/Downloads/bitsquare-native/src/main/java/io/bitsquare/locale/BSResources.java:57: warning: non-varargs call of varargs method with inexact argument type for last parameter;
        return MessageFormat.format(BSResources.get(key), arguments);
                                                          ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processResources
:cssToBin SKIPPED
:classes
:jar
:jfxJar FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':jfxJar'.
  
  > com/oracle/tools/packager/Log
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by cbeams** [comment]
Oops. Sorry, I should have mentioned that JDK 8u20 or better is required for this part of the build to work.

**Comment by ManfredKarrer** [comment]
ah ok need to update, btw. could you add install instructions for java on linux. I remember that it was a bit tricky and some linux guys are not familiar with java...

**Comment by cbeams** [comment]
Yeah, funny enough, they're actually embedded in our Travis config (at least for the moment, until Travis updates their default JDK to 8u20 or better): https://github.com/bitsquare/bitsquare/blob/native/.travis.yml#L5-L8
- sudo apt-get purge openjdk*
- sudo add-apt-repository -y ppa:webupd8team/java
- sudo apt-get update
- sudo apt-get install oracle-java8-installer

Of course that's just for Debian and its variants. Not sure what it looks like with RPM, Yum, etc.

**Comment by ManfredKarrer** [comment]
@cbeams: I updated java now but get that error:

23:05:17.459 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling

23:05:17.426 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :jfxJar FAILED
23:05:17.426 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :jfxJar (Thread[main,5,main]) completed. Took 0.225 secs.
23:05:17.427 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 7.598 secs, idle: 0.009 secs
23:05:17.432 [ERROR] [org.gradle.BuildExceptionReporter] 
23:05:17.434 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
23:05:17.434 [ERROR] [org.gradle.BuildExceptionReporter] 
23:05:17.435 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
23:05:17.435 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':jfxJar'.
23:05:17.435 [ERROR] [org.gradle.BuildExceptionReporter] > org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
23:05:17.438 [ERROR] [org.gradle.BuildExceptionReporter] 
23:05:17.439 [ERROR] [org.gradle.BuildExceptionReporter] \* Exception is:
23:05:17.440 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jfxJar'.
23:05:17.441 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
23:05:17.441 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
23:05:17.441 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
23:05:17.442 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
23:05:17.442 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
23:05:17.442 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
23:05:17.442 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
23:05:17.443 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
23:05:17.443 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
23:05:17.443 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:289)
23:05:17.444 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
23:05:17.444 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
23:05:17.445 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
23:05:17.445 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
23:05:17.445 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
23:05:17.445 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
23:05:17.446 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
23:05:17.446 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
23:05:17.446 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
23:05:17.447 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
23:05:17.447 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
23:05:17.447 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
23:05:17.448 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:166)
23:05:17.448 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
23:05:17.448 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
23:05:17.448 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
23:05:17.449 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
23:05:17.449 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
23:05:17.449 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
23:05:17.450 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
23:05:17.450 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
23:05:17.450 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
23:05:17.451 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
23:05:17.451 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
23:05:17.451 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
23:05:17.452 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
23:05:17.452 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
23:05:17.452 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
23:05:17.452 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.doAction(Main.java:46)
23:05:17.453 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
23:05:17.453 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.main(Main.java:37)
23:05:17.453 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
23:05:17.454 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
23:05:17.454 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
23:05:17.454 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
23:05:17.455 [ERROR] [org.gradle.BuildExceptionReporter]    at org.bitbucket.shemnon.javafxplugin.tasks.JavaFXJarTask.this$dist$invoke$4(JavaFXJarTask.groovy)
23:05:17.455 [ERROR] [org.gradle.BuildExceptionReporter]    at org.bitbucket.shemnon.javafxplugin.tasks.JavaFXJarTask$1.methodMissing(JavaFXJarTask.groovy)
23:05:17.455 [ERROR] [org.gradle.BuildExceptionReporter]    at org.bitbucket.shemnon.javafxplugin.tasks.JavaFXJarTask$1.info(JavaFXJarTask.groovy:85)
23:05:17.455 [ERROR] [org.gradle.BuildExceptionReporter]    at com.oracle.tools.packager.Log.info(Log.java:77)
23:05:17.456 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.javafx.tools.packager.PackagerLib.packageAsJar(PackagerLib.java:172)
23:05:17.456 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.javafx.tools.packager.PackagerLib$packageAsJar.call(Unknown Source)
23:05:17.456 [ERROR] [org.gradle.BuildExceptionReporter]    at org.bitbucket.shemnon.javafxplugin.tasks.JavaFXJarTask.processResources(JavaFXJarTask.groovy:99)
23:05:17.457 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
23:05:17.457 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
23:05:17.457 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
23:05:17.458 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
23:05:17.458 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
23:05:17.458 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
23:05:17.459 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
23:05:17.459 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
23:05:17.459 [ERROR] [org.gradle.BuildExceptionReporter]    ... 43 more
23:05:17.459 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling
23:05:17.460 [ERROR] [org.gradle.BuildExceptionReporter]    ... 58 more
23:05:17.460 [ERROR] [org.gradle.BuildExceptionReporter] 
23:05:17.460 [LIFECYCLE] [org.gradle.BuildResultLogger] 
23:05:17.461 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

**Comment by cbeams** [comment]
Make sure you run with ./gradlew. Your locally installed Gradle is probably too old.

```
brew update && brew upgrade gradle
```

Should work as well.

**Comment by ManfredKarrer** [comment]
Great now its working. I just din't see the popups first but that was an issue of the controlsfx lib, we need to update to version org.controlsfx:controlsfx:8.0.6_20 (to bew compatible with the latest java version). I have checked that in both master and native branch.

**Comment by cbeams** [comment]
Resolved with d16c274.

**Comment by cbeams** [comment]
Superseded by #243.
