### ISSUE TITLE
Write a trading bot using the Bisq API

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1054]
Write a trading bot using the Bisq API. Best to build on existing trading bot frameworks.

**Comment by ManfredKarrer** [comment]
@dan-da @mrosseel Maybe you can add some input here.

**Comment by dan-da** [comment]
yeah, I had planned to do this, but having trouble finding time.  on holiday right now.   Any pointers to existing trading bot frameworks?

**Comment by mrosseel** [comment]
@r8d8 @dulanov

**Comment by r8d8** [comment]
We (with @dulanov) started drafting bot here: https://github.com/1531/bisq-bot
[geeko](https://github.com/askmike/gekko) and [zenbot](https://github.com/carlos8f/zenbot) BTC trading bots looks like mature one, will take a look into them.
If anyone has non Javascript examples, they will be also usefull.

**Comment by ghost** [comment]
@mrosseel  our main idea - write a simple cli application running via docker to simplify this step to automate final steps for BTC/ETH, ETH/BTC, BTC/ETC, ETC/BTC pairs trading. `bisq-bot` should just monitor both blockchain explorers in order to know when the BTC or ETH or ETC will come and make confirmation via Trading API in bisq automatically. That's all for beggining, just a simple prototype in Go language.

**Comment by mrosseel** [comment]
sounds good, do you need a dockerfile for the headless API?

**Comment by ManfredKarrer** [comment]
Please consider the issues I posted at: https://github.com/bisq-network/exchange/issues/1047
"One challenge will be how to assign the transaction if there are several transactions with the smae amount and sender/receiver address. It can be that the same trade pair traded repeatedly with the same amount.
Another challenge is that many users do not use the altcoin address defined in the account for sending the altcoin, only for receiving we have that guaranteed. So that can also lead to unclear situations."

**Comment by r8d8** [comment]
@mrosseel, yeap, docker file will be very usefull.
@ManfredKarrer, thanks, will take this in account.

**Comment by mrosseel** [comment]
@r8d8 docker file was pushed, just do 'docker-compose up -d' and point your browser to localhost:8080/swagger (takes a few seconds to start up)

**Comment by ghost** [comment]
FYI: I made a quick overview for actual java trading frameworks ([more here](https://github.com/topics/trading?l=java)):

1. https://github.com/gazbert/bxbot
2. https://github.com/paritytrading/parity

Also take some interest:

* For technical analysis - https://github.com/ta4j/ta4j

**Comment by mrosseel** [comment]
Thx for the overview @dulanov - my personal opinion is that at the moment Bisq is not suited for high frequency trading type techniques, you probably just have to work with the spread and profit from that. So I don't think these traditional bots are a good fit for the Bisq API - but happy to be proven wrong of course.

My idea of a 'minimum viable product' Bisq bot is this:
- choose a market pair with good block explorers (BTC/LTC, BTC/ETH)
- bot makes sure you always have a buy offer at e.g. -3% off market price and a sell offer at +3% market price
- bot handles lifecycle of the offer: creation, checking that crypto arrives at your address, advancing offer status

**Comment by Quenos** [comment]
The problem using Bisq for automated trading other than market making is the fact that it is costly to cancel orders. Since cancelling orders is key to successful trading IMO (you want to be the maker, rather than the taker) it is probably not easy to rewrite existing bots. 
From the white paper I took that the costs for cancelling orders is a design choice this will probably not chance either. 

So I concur with @mrosseel that a market maker bot should be created first.

**Comment by ManfredKarrer** [comment]
It is on open issue to figure out how we can do that without breaking the security function of the trade fee: 
See: https://github.com/bisq-network/exchange/issues/1043

**Comment by dginovker** [comment]
Has further progress or new ideas been made on this subject? I don't see anything in the API that would support making a bot yet.

**Comment by rocket-pig** [comment]
I too am interested.  

..aside from functional trading bots, how does one ever expect a (active, volume-inous) market to develop on bisq?

**Comment by csaroff** [comment]
@Quenos Could you elaborate on the cost of canceling orders?  When would orders need to be canceled?

**Comment by Quenos** [comment]
When you cancel an order on bisq you will lose some of the fees you’ve paid.
If you’re an active trader you want to put in a sell order at a resistance level e.g. but if the resistance is broken, you might want to cancel the order if you think price will go up because of the break-out.

Or, if you want to be a market maker you put in a sell and buy order at the same time, but when other exchanges the price move you want to adjust these orders constantly.

Hope this helps

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
I was looking through the issues, if there was already some discussion about having an automated fiat cost average trading bot. So, that a certain amount of fiat [or shitcoin] is always sold for bitcoin for every time period. 

this issue seems to be the closest to the idea, so I'm asking here.

What I imagine being tricky is that the trading partner might be a different one for every trade, thus there cannot be a recurring fiat bank transfer, as the receiver is different all the time.

Further, bisq trades to require user interaction to review and approve the trade, signing the multisig transaction. 

So, I'm not sure how to do this, but it would be a fantastic feature for sure!
