### ISSUE TITLE
Investigate hardware wallet (Trezor) integration

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1063]
We would like to support hardware wallets but it has limitations because the trade requires automated transaction signing (in case a peer takes your offer) and that is not possible with hardware wallets.
But to connect Trezor (or other hardware wallets) and use them to swap the funds would be still a great feature to avoid risks for larger BTC amounts in the users Bisq wallet. That swapping would be a normal BTC transaction.

**Comment by r8d8** [comment]
I have experience with Ledger HD wallet - integrated support for them inside [Emerald Vault](https://github.com/ethereumproject/emerald-rs).  `Nano S` and `Blue` models share the same communication protocol. Can't say that Ledger  has transparent manuals or any solid documentation.

**Comment by ManfredKarrer** [comment]
We have been in contact with Jochen Hoenicke about Trezor integration (wanted to use it for the arbitrator but was too complicate for that user case - signing custom txs). 
That task would require some UI work/concept as well. How to make it user friendly that user  swap over their saving to the Hardware wallet. They need to understand that they cannot use that for trading directly then...

**Comment by mrosseel** [comment]
one of the issues with trezor integration were bugs in the (3rd party) trezor java library

**Comment by disinqa** [comment]
Maybe [Trezor Connect API](https://github.com/trezor/connect) solves what you're looking for @ManfredKarrer

**Comment by antsykarbo** [comment]
Been thinking about this every time I transfer BTC between Bisq and Trezor. Some ideas for how to implement:
A. Fork, rename and refactor [trezor/trezor-android](https://github.com/trezor/trezor-android) to remove dependencies on Android
B. Implement Trezor communication as a standalone Java lib from scratch
C. Use [trezor/connect](https://github.com/trezor/connect), as suggested by @disinqa 

A and B seem similar in the amount of effort, but I haven't done anything with USB devices from Java, so don't have a good feel for how much work that would be.

C would require the user to have the Trezor bridge installed, and the Bisq client to run an HTTP server and open a browser on user's computer every time user wanted to use Trezor to move funds. UX might be awkward, but this might be the fastest way forward because it doesn't require messing around with low-level USB stuff or an Android-dependent codebase.

Thoughts?

**Comment by blabno** [comment]
@antsykarbo What exactly do you need Bisq HTTP for?
I'm already working on an API, so I would like to learn about any new requirements.

**Comment by antsykarbo** [comment]
@blabno in this case the HTTP server would serve an HTML page and a bunch of javascript on a local port so that the user could interact with Trezor Connect JS API in a browser. I presume this page would then have to call back to Bisq via an HTTP API of sorts to send the transaction signed by Trezor back to Bisq.

Apologies for a rushed description. Happy to write up the proposed approach if anyone else thinks that using a browser outside of Bisq for funding/withdrawal txs is a viable idea.

**Comment by peterzen** [comment]
There is now a 3rd party Java library: https://github.com/gary-rowe/trezor-java

Rather work in progress and only has low level functionality but might be worth keeping an eye on.  It is (will be?) built on top of BitcoinJ.

**Comment by mrosseel** [comment]
Was checked out a few years ago and had some error in it, the author also
didn't seem to have time to look into it. Maybe it has changed in the mean
time, be sure to look of there are any recent releases/commits

**Comment by danimesq** [comment]
It should also support Ledger, KeepKey and status-keycard

**Comment by HausIndustries** [comment]
I have experience with HW integration and would personally also appreciate hardware wallets connected as I keep my coins/tokens split between my trezor and my software wallet to be ready for trading.  It does seem like interest has fallen off but with hardware wallets like trezor zero at 40 bucks on amazon no one really has an excuse not to have one. I can def get trezor and likely ledger done pretty well, I have an old keepkey thats dead (idk what happened doesnt turn on anymore) and haven't used other wallets or their integration but really getting one done its just about as easy to get most if not all of them done. Would people be passionate enough about this to push for a BSQ bounty for it. I normally would just do it in my free time and not really care but I'm out of work (kinda in a funk but actually looking to move from my old job to the crypto space) and could really use the money if possible. If not, either way I could outline enough of it that it could be done either by me or someone else interested in helping.

**Comment by seanpk** [comment]
I am interested in seeing support for this added.
In lieu of software support, a howto guide for doing it manually as alluded to by @antsykarbo in [this comment](https://github.com/bisq-network/bisq/issues/1063#issuecomment-375682975) would be very valuable. i.e.:
> Been thinking about this every time I transfer BTC between Bisq and Trezor.
