### ISSUE TITLE
Please consider providing a mirror

### ISSUE THREAD

**Issue by mohamnag** [bisq-network/bisq#1086]
The Github release uses AWS which could be extremely slow depending on different conditions (as for me) like geographical location and so on. It would be very nice if you could provide a mirror or maybe use a torrent for distribution too. 

As the links generated by Github are also tokenised and time limited, slow download rate could mean one has to restart the download again and again. I have already tried it 3 times today.

thanks in advance.

**Comment by ghost** [comment]
Similar to #1013.

**Comment by cbeams** [comment]
Manfred closed this as deferred because this sort of thing just doesn't have any priority for us right now. If this looks like an issue affecting lots of people, of course we'll reconsider, but the best thing that could happen is for someone to step up and manage a mirror on their own, get compensated for it via the Bisq DAO, and so forth. We're open to that, just can't prioritize it at the moment.

See also #1164.
