### ISSUE TITLE
Changing base currency erases national currency accounts

### ISSUE THREAD

**Issue by lordbah** [bisq-network/bisq#1104]
When I changed base currency from Bitcoin to Dash and restarted, I was surprised to find that I didn't have any national currency accounts any more. Looks like settings for currencies in market feed got reset too. These things aren't dependent on the base currency, it makes no sense that the software would erase them.

**Comment by ManfredKarrer** [comment]
All the data are completely separated. But you can export and then import the payment methods accounts.

**Comment by lordbah** [comment]
If I'm selling both Bitcoin and Dash, I have to continually change base currency and restart?

**Comment by mrosseel** [comment]
you could do that, but you can also run two instances of Bisq, since they use their own data directories they won't interfere with each other. Having it all integrated in one app would be better, but that's a lot of work and at the moment not yet justified by the trading volume in LTC or Dash. 
Maybe someday that perception will change ;)

**Comment by lordbah** [comment]
Does two instances work? The second instance on startup popped up a Tor network settings dialog, and the first instance's market feed went blank. On the second, I closed the dialog, and it kept trying to initialize, but eventually came back to the same dialog. AFAIK my ISP doesn't block Tor, since bisq showed offers yesterday.
