### ISSUE TITLE
Taker fee transaction ID visual bug

### ISSUE THREAD

**Issue by montvid** [bisq-network/bisq#1105]
When one opens a Trade ID in bisq one sees all the info about the trade and and if the fees and deposits and payouts are confirmed in the blockchain with a tick mark (V). The visual bug is in the Taker fee transaction ID space - the transaction is confirmed but there is no tick mark (V) on it. Other 3 ticks are intact.

**Comment by cbeams** [comment]
Could you paste a screenshot of what you're talking about, @montvid?

**Comment by ManfredKarrer** [comment]
@montvid That is because the other peers trade ID is not received by your wallet. BitcoinJ gets only transactions which are related to your wallet keys. We would need to request that tx from a block explorer to know the confirmation status. But if the deposit tx is confirmed both trade tx are confirmed as well as they are used for the inputs.

**Comment by montvid** [comment]
Ah, ok, it is not a bug. I was curious. Thanks for the reply.
