### ISSUE TITLE
Sent deposit but it doesn't get confirmed

### ISSUE THREAD

**Issue by Yummis** [bisq-network/bisq#1106]
here is my deposit ID: 6fc25e39289c2c88fbcad4155c03261df469e1e174f22c296961694d9d86600e
I does not get confirmed is there anything I can do? or can I consider my 0.11 Bitcoin as lost, (Worth almost $2,000) this is only part of many issues I experienced lately with Bisq

**Comment by cbeams** [comment]
You can do a couple things:

1. Wait. This is not confirming because of a spike in unconfirmed transactions in the Bitcoin mempool. This spike is falling back off as we speak, and it means that your tx will probably soon confirm.

2. Run your tx through ViaBTC's free transaction accelerator. You need to do this right on the hour, i.e. 15 minutes from the time I'm writing this message: https://pool.viabtc.com/tools/txaccelerator/. That won't cause it to get confirmed right away, but it'll get confirmed in whatever the next block that ViaBTC mines is.

**Comment by Yummis** [comment]
@cbeams, thanks for your quick help, however I've done yesterday and today everything you've said but the transaction is still not confirmed, what can I do 
This is the TX: 6fc25e39289c2c88fbcad4155c03261df469e1e174f22c296961694d9d86600e

**Comment by cbeams** [comment]
Hm. So you ran this tx through ViaBTC's transaction accelerator yesterday—and got it _accepted_ when you did—and it still hasn't confirmed? That doesn't make sense, as ViaBTC has mined plenty of blocks in the last day (see https://coin.dance/blocks). Their tx accelerator definitely works, so I'm inclined to think there must be some misunderstanding.

**Comment by Yummis** [comment]
It hasn’t been confirmed

**Comment by cbeams** [comment]
That was a poor response to my question, and I am inclined to ignore this thread now. If you want my help, you have to respond more fully than this.
