### ISSUE TITLE
Bisq client allowed me to pay Taker transaction which is confirmed in blockchain although maker transaction is still not confirmed after a week

### ISSUE THREAD

**Issue by nuschpl** [bisq-network/bisq#1211]
For me it's a bug for another issue that it relies on i (guess TOR) peers communications rather than on what already published in blockchain. 
Trade id: ooeeaqe3-8a9c6703-129c-485e-8284-598056f36a1b-063

**Comment by montvid** [comment]
I came to find out that only the tx you make get confirmed in bisq with a tick sign. Bisq does not use a block explorer to search if the other party's tx got confirmed. See my #1105 I hope this is what you ask.

**Comment by ManfredKarrer** [comment]
Yes the peers trade fee tx is not connected to your wallet and SPV wallets onlr receive transactions which are connected to addresses in your wallet. 
We cannot wait for the confirmation of the makers fee tx as that would slow down the trade process, e.g. the offer would not be valid until it got confirmed the fee tx.
The current issues with not confirmed/broadcasted tx are now fixed in the master branch and will be released very soon. Such cases that the maker fee does not get confirmed should not happen (as it was the case in the past).
