### ISSUE TITLE
Add additional information for security deposit

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1216]
At some screens we don't explain the reasoning behind the security deposit (e.g. Create offer). On all screens where we require the user to accept or change a security deposit we should display a information icon, that explains the reasoning behind it and what value a user should go for.

*Create offer to sell*
![Create offer to sell](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/b5f50529-afc0-4262-8e8f-b40fa0313cc1)

**Comment by ripcurlx** [comment]
In the buyer screen it could look something like this:
![security deposit info](https://user-images.githubusercontent.com/170962/35972085-b1840346-0cd0-11e8-9263-8ee4e9dde410.png)

**Comment by ripcurlx** [comment]
Actually on this screen I think we should write:
> **Set your security deposit**
> Security deposit: [0.01 BTC]

instead of:

> **Set buyer's security deposit**
> Security deposit for BTC buyer: [0.01 BTC]

I don't think it makes it easier for the user to understand what this security deposit is all about by talking about the user in the third person IMO.

**Comment by ripcurlx** [comment]
Here's an updated design for this screen (different text and pop over)
![security deposit info](https://user-images.githubusercontent.com/170962/36026557-f3d4c4b6-0d97-11e8-8f54-8582912b042d.png)

**Comment by mrosseel** [comment]
looks good, some suggestions:
* is it 'might' result or 'will' result?
* propose to rephrase to 'result in losing your security deposit' - sounds a bit less threatening

**Comment by ripcurlx** [comment]
I wasn't sure if you'll loose the security deposit in any case you cancel an ongoing trade.
@cbeams Is it correct that you'll loose the security deposit if you don't complete an ongoing trade?
![security deposit info](https://user-images.githubusercontent.com/170962/36027848-38895cac-0d9d-11e8-9624-71e54be16cec.png)
I also just recognized that we only show the buyer deposit to the seller in the confirmation screen. We also don't show the user if this is the default deposit or if the trader has set the deposit to the minimum value. Maybe we should think about warning the user in this case like in following screen:
![warn user for low security deposit](https://user-images.githubusercontent.com/170962/36027983-a7c604ee-0d9d-11e8-830b-585d7ba226a3.png)

**Comment by ripcurlx** [comment]
And here is the version for creating a sell offer:
![security deposit seller](https://user-images.githubusercontent.com/170962/36028468-5a5011bc-0d9f-11e8-8ddc-2c37f0bac525.png)

**Comment by mrosseel** [comment]
loosing => losing

**Comment by ripcurlx** [comment]
Thanks for pointing out the typo! I'm also not sure if we should talk about "canceling a trade" as there is no real "cancel" button, but more a not following of the trade protocol. Not following the trade protocol on the other hand sounds very complicated to me and I would immediately be afraid, that I could lose my deposit if I'm doing little mistakes.

**Comment by ripcurlx** [comment]
Maybe we should add the security deposit information already in the take offer screen, if a buy offer is taken? Of course it's not really a payment information - maybe it needs it's own section. Or we add an info field only in the case if the security deposit is below the default.
![seller security deposit warning](https://user-images.githubusercontent.com/170962/36029155-4c113f6a-0da2-11e8-81dc-1b87aebdf747.png)

**Comment by ripcurlx** [comment]
Or if we don't want trades to be taken, that have a security deposit that is below the default we could just add a warning bar 😉. Is there a good reason to change the security deposit at all? If the trade is below the default value than this might be the case, but do we really have trades that are below 0.01 BTC?
![warning bar](https://user-images.githubusercontent.com/170962/36029410-5baa691e-0da3-11e8-913d-841a54f6159f.png)

**Comment by cbeams** [comment]
> I wasn't sure if you'll loose the security deposit in any case you cancel an ongoing trade.
> @cbeams Is it correct that you'll loose the security deposit if you don't complete an ongoing trade?

That _may_ happen depending on the circumstances and details of the case. I'd leave it out here for that reason.

But perhaps more importantly, I'd leave it out because it's irrelevant and confusing to talk about it here at all. In the screenshot shown at https://github.com/bisq-network/exchange/issues/1216#issuecomment-364424353, the maker-as-seller is specifying the security deposit that the buyer must pay in order to take this offer. Telling the seller that they will lose their security deposit if the cancel after the trade is taken is a non-sequitur here; I mean, even if it were perfectly true, it doesn't have anything to do with the decision that the seller needs to make here, which is all about the _buyer's_ security deposit, not their own.

Likewise, I'd kill the note about the security deposit being returned after the trade completes. That is again true enough, but irrelevant in this context.

Also, it's "lose" your security deposit not "loose"—this is a common error, even for native speakers.

I really like the way the hover looks by the way, with regard to color, iconography and slider!

**Comment by cbeams** [comment]
By the way, @ripcurlx, I'd be happy to chat about this topic sometime next week. Real-time discussion might be most efficient in sorting some of this stuff out. Just let me know if you'd like to do that.

**Comment by ripcurlx** [comment]
@cbeams and @ManfredKarrer: Yes, maybe it would be best to discuss everything regrading the security deposit in a quick call today. Would 6pm (CET) work for you guys?

**Comment by cbeams** [comment]
I’ll take this to Slack for coordinating a call, thanks.

**Comment by ManfredKarrer** [comment]
@ripcurlx 
I like the slider!!!!

There is still some missing context:
Only the buyers security deposit can be set because the buyer can "cancel" the trade (not a term we should use - better: not follow the trade protocol) in case the btc price has move more as he would lose from the deposit. E.g. you make a buy offer with 1 btc for 10 000. next day price is 9000. if u continue you pay 1000 usd more as new market price. if you "cancel" by not transferring fiat/altcoin you lose deposit. if deposit is < 1000 USD then its economically reasonable to do that. 
We had such cases and to prevent that we leave it to the maker to set the deposit. We cannot avoid all cases as volatility can be very high specially with altcoins.  But it can be also seen as a max. loss for time of high volatility. The taker cannot do much as he only release when received the fiat/alt, he cannot "cancel", thats why the sellers deposit is fixed an rather low.

I think the deposit should not be shown in the payment method as that is the users payment method (he can have multiple - then there is a dropdown).
If we show it in the main screen i would show it at the price section. In older versions i think we had an extra section with that, but i removed it as it was too much info. But open to add it again. Info is important as otherwise nobody understands it.

**Comment by ManfredKarrer** [comment]
Re: warning if outside of recommendation:
I am not sure if a warning is good as it is reasonable to set it in times of high or low volatility.
Maybe better to signal if its default or custom set? Maybe just add "(default)" if so? Or use the slider as well so show in which range it is?

**Comment by ManfredKarrer** [comment]
A high deposit means more security for seller. A low deposit means less money locked up for buyer. A maker as seller who wants to attract buyers can set it low, taking more risk of cancellations.

**Comment by ManfredKarrer** [comment]
I think we should use the volatility alone and remove the option that the user can set it. See #1346

**Comment by ripcurlx** [comment]
Yes, I would also prefer a solution, where we don't have to educate the user about the correct usage.

**Comment by ripcurlx** [comment]
This issue is blocked until the automatic deposit setting is implemented.

**Comment by ManfredKarrer** [comment]
Btw. We should change the defautl sec. deposit to a % value based on the trade amount. That wooudl reflect then the volatility. E.g. if you expect that the BTC price will go up or down 5-10% then you should set the deposit to that % value. Default might be about 10% but should be delivered by a service anyway.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ghost** [comment]
I profit from this thread.
It would be nice if the security deposit could reflect in some way in the avatar.
eg the avatar being replaced by a horizontal bar, with a cursor showing how high is the deposit.
Atm, the avatar conveys 0 information by itself, while it could be. That's a bit a pity.
