### ISSUE TITLE
Funds should be renamed to Wallet

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1220]
Thanks for the input on that @changalberto! This is something to be discussed for sure.
At the moment we guide the user through the creation of the Bisq wallet when she wants to trade on Bisq. Unfortunately afterwards, there is no UI element anywhere else in the app on what I can do with the wallet or for what it is used. Actually we do have a section where the wallet activity is displayed or a user can interact with it --> `Funds`.  I think the only tab within the Funds section that is not 100% only about the wallet is the `transactions` tab. Maybe we could live with this special case within the Funds section and still rename it to Wallet. Maybe @ManfredKarrer and @cbeams could give their input on this, as I guess there is definitely a good reason why it is not named `wallet` atm.

![Funds - Transactions](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/3b4f8f0e-14d7-424a-bfbf-f57f71653778)

**Comment by cbeams** [comment]
I agree it would be good to get people thinking about Bisq as a first-class wallet. The `Send`, `Receive` and `Transactions` screens under what is currently called `Funds` would easily make sense if they were under a section called `Wallet`, but the concepts of `Reserved funds` and `Locked funds` are not something familiar or idiomatic to the wallet metaphor.

Better and more inclusive would actually be the word `Account`, because:
 - you can send funds from an account,
 - you can receive funds into an account,
 - you can have a history of transactions in an account (i.e. a list of all past sends/receives),
 - you can have funds reserved from an account, and
 - you can have funds locked in an account.

`Account`, is a somewhat overloaded term, and a menu item already exists for `Account` on the far right next to settings, but I'd argue that we should rethink that anyway. What's under the current `Account` tab is a bit of a grab-bag; certainly not all stuff strictly account-related (e.g. Backup, Wallet password, Arbitrator selection).

Requires more discussion, but this is actually something that I've been thinking a lot about lately. Glad you brought it up @changalberto.
