### ISSUE TITLE
Fix issues with not being able to delete the SPV file 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1289]
Some users on Windows reported that the resync of the SPV file failed. We don't have more detailed log files about the issues but in the code the delete is not using the canonical file and seems for Windows that is required.

**Comment by ManfredKarrer** [comment]
Hopefully fixed with https://github.com/bisq-network/exchange/commit/648a7d4a0b3549d1d9d1bbfdb6f20da414063765

**Comment by cbeams** [comment]
Closing as superseded by #1290 (the PR that contains commit 648a7d4 referenced above).

**Comment by cbeams** [comment]
Actually, I'm removing the `was:superseded` label and leaving this issue slated in 0.6.5, closing as fixed by #1290. It's worth having the separate issue show up in the milestone, as the use case it's dealing with (resyncing SPV file) is different that #1290, which is about restoring from seed words. We think the commit in question addresses this use case, though, so it's really about killing two (apparently different) bugs with one stone.
