### ISSUE TITLE
Add payment method:  Moneybeam

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1349]
Investigate if Moneybeam (N26) can be added to Bisq.
See: https://bisq.community/t/n26-moneybeam/4773/3

**Comment by ManfredKarrer** [comment]
@flix1 Are you familiar with Moneybeam?

**Comment by tomatopeel** [comment]
* Charge-back risk - probably negligible but could confirm with N26 support if necessary

* Mandatory data fields - I've just realized this method is designed to work with people who are your contacts in your mobile phone. There's the option to search for additional people by either name, e-mail or phone number. So presumably if tried over Bisq, traders would need to provide e-mail or phone number associated with their N26 account in order to discover one another for this method.

* Proof of transfer - A MoneyBeam transfer shows up as a transaction very similar to a SEPA transfer i.e. displaying the name, IBAN, BIC and message (reason for transfer) both within the mobile app and at https://my.n26.com. The only difference is that it says "MoneyBeam" under the name, as opposed to "Outgoing Transfers" which it says for a SEPA transfer.

* Extra consideration - regarding the "reason for payment", it would need to be made very clear that the MoneyBeam synonym for this is the "message" which is prompted for after selecting the person to send the payment to in the app.

**Comment by ManfredKarrer** [comment]
Sounds all good. Will add it is there are no concerns.

**Comment by ManfredKarrer** [comment]
<img width="939" alt="screen shot 2018-02-13 at 20 03 39" src="https://user-images.githubusercontent.com/1449498/36182737-1b7edfd8-10f9-11e8-85d1-c1f91c652f52.png">

**Comment by ripcurlx** [comment]
I'm not sure if people will know immediately that MoneyBeam is the N26 MoneyBeam. Maybe It's just me (I do have a N26 account), but I wouldn't be sure if that's the case. Maybe we should write it like that: MoneyBeam (N26) or N26 MoneyBeam

**Comment by ripcurlx** [comment]
Not directly related to N26 MoneyBeam, but if I want to enter the maximum amount of 0.031250 in the create offer dialog the value is rounded to 0.0313, so I'm only able to trade for 0.0312 in the beginning.
![Payment limit](https://user-images.githubusercontent.com/170962/36584597-99b29be6-187a-11e8-8cea-0848971a0cfd.png)

**Comment by ripcurlx** [comment]
As we have the fixed precision in creating the amount maybe we should also floor the limits to a precision of four decimals.

**Comment by ripcurlx** [comment]
Or if we have issues with existing limits in previous versions we could ceil the limit to a precision of four decimals.

**Comment by ManfredKarrer** [comment]
Changed the limit to avoid that issue. I will rename it to MoneyBeam (N26)
