### ISSUE TITLE
Provide the user with information where/how to buy bitcoin for the deposit, trading & mining fee

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1413]
We should make it easy for users how to buy their first bitcoin. Maybe we could add a link **I don’t have any bitcoins** to the deposit information popup and link it to our FAQ entry. Are there any community updated sites out there, which have recommendations where to buy bitcoin by country?

**Comment by ripcurlx** [comment]
Maybe we could link from our FAQs to BTC meetup groups providing this information like for Austria: https://bitcoin-austria.at/de/bitcoininfo/wie-bekomme-ich-bitcoins

**Comment by mike223** [comment]
Today I hated Bisq for the second time after my first test about a year ago: It is against common sense to have an exchange where you need to buy BTC before you can use it to buy BTC. No excuses. That is just a no-go. 
--> Have at least the possibility to trade a small amount of cash or altcoins for BTC to get started.

**Comment by ripcurlx** [comment]
@mike223 We are aware that the requirement to have a small amount of bitcoin upfront to be able to trade on Bisq, is a problem for many people. The reason behind this is to make it expensive to spam the network with fake offers and also to encourage both parties to follow the trade protocol, as they could loose their deposit if the trade goes into arbitration. Yes, it is a big hurdle for Bisq to be a mainstream exchange, but it also secures the network. One way to get this initial amount of bitcoin for the deposit could be a micro-lending system, where people could lend each other bitcoin and get them back with an interest rate.

**Comment by mrosseel** [comment]
@ripcurlx this is indeed the correct response for the current Bisq implementation, I did however have another idea recently (not very original probably).

We could have a special 'bitcoin virgin' offer, which is an offer to buy BTC with whatever payment method. The amount should be low but enough to pay the trading fees of 'normal' offers. 

There is no deposit needed, as spam protection we use a POW which ties the user's computer for maybe even an hour if needed,  before the offer can be propagated to the network. All peers check that enough work has been done, just like in bitcoin. Mining monero is another option, but not sure how peers can easily check this has been done.

The only thing which can go wrong is when the price moves against the buyer, he will cancel. Since these offers will be 10/20 euro, this won't happen a lot and would not bother the other party too much.

Of course this is not a trivial amount of implementation. Any critique on the idea itself?

**Comment by ManfredKarrer** [comment]
@mrosseel I don't think that the marginal benefit of serving those users will justify to add a different version of the trade protocol. I would estimate at least 1 months work for me to do that without testing...The POW needs to be considered well, we might want to support mobile clients in future, there the POW would not match well a desktop performance....

We need a more simple approach. I would suggest to use the forum based private micro credits and if we see that is really much used we can add a micro payment app (also some effort but could be an interesting add on).
From my experience with those credit though it that most simply forget to pay back. Random stranger don't care if they have nothing to lose, so without security deposit we also might run in problems that those newbies just forget about it as they have nothing on stake...

**Comment by mrosseel** [comment]
@ManfredKarrer agree that it's too much work for the benefit it provides, you never know one day... . For the more immediate future I think we should probably stop promoting the forum lending because who wants to give away free bitcoin? 

Some ideas to put into the FAQ @ripcurlx suggested: 
- Links to a map with ATM machines (https://coinatmradar.com/). ATM's might have a big markup but they only need a little to start with Bisq.
- Links to our bounties, where people can earn BSQ and sell them for BTC

**Comment by ManfredKarrer** [comment]
I have not followed closely how the lending worked out for others.
- Bounties is nice idea, but they cannot sell bsq without having btc for sec. deposit...

**Comment by mrosseel** [comment]
Yes bounties could be otc with a trusted contributor or someone they know

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
Still relevant.
