### ISSUE TITLE
Blockconfirmation indicator is too large

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1421]
The block confirmation indicator is now larger as it it in the current release version. IMO it is too large in relation to other icons.

<img width="918" alt="screen shot 2018-03-05 at 10 55 52" src="https://user-images.githubusercontent.com/1449498/36984856-cdb230b4-2063-11e8-8eaa-8a602bea3db1.png">

**Comment by cbeams** [comment]
Strongly agree. Have been meaning to create an issue about this. Thanks.

Incidentally, @ManfredKarrer, what is the droplet image intended to mean? It's not obvious to me at first glance.

**Comment by ripcurlx** [comment]
Didn't change anything about that on intend, but I'll re-size it to match the other icons. I think the difference is related to the fact, that the other icons are Fontawesome icons and resize with the font size and the block confirmation indicator is a regular graphic.

**Comment by ripcurlx** [comment]
The problem is not with the indicator icon itself. It just renders dependent on the size that is available for this component. I could of course just lock the size to match the original one, but I'll have a look why the rows are rendering with a higher row height by default atm. I think it is because of the Hyperlink component that is now used in this table view.

**Comment by ManfredKarrer** [comment]
@cbeams re "what is the droplet image intended to mean?" Its for fee burning. But yes it might not be the best icon, just wanted to make burning not too negative with ire icon or so...
