### ISSUE TITLE
Error at traderSignAndFinalizeDisputedPayoutTX

### ISSUE THREAD

**Issue by jrwashburn** [bisq-network/bisq#1435]
Received this error in Bisq UI when clicking on Buy BTC. (I do not think the error is related to the Buy BTC screen I was browsing (I had just been viewing that screen without any issues) but rather to the closure of a dispute ticket.) 

Error at traderSignAndFinalizeDisputedPayoutTx io.bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@12860656, [B@6296bcf4, [B@259ffee0]

[bisq-error at traderSignAndFinalizeDisputedPayoutTx - log snippet 20180307.txt](https://github.com/bisq-network/exchange/files/1790814/bisq-error.at.traderSignAndFinalizeDisputedPayoutTx.-.log.snippet.20180307.txt)

![screenshot 2018-03-07 15 35 18](https://user-images.githubusercontent.com/891888/37117470-55bc3362-221f-11e8-89bf-98c765e2e132.png)

The dispute was related to https://github.com/bisq-network/support/issues/78

**Comment by ManfredKarrer** [comment]
Did you received the payout? If not please let the arbitrator know so that he can do a manual payout.

**Comment by jrwashburn** [comment]
I did not receive it and let the arbitrator know in the ticket; however the ticket is closed so I do not know if s/he will see it. Let me know if you need more of the log file to help diagnose.

**Comment by ManfredKarrer** [comment]
Try to get in touch with them (@cbeams @keo-bisq) here or on the Forum. Post the arbitrator address and trade ID so they can see if it was their dispute.

**Comment by cbeams** [comment]
@jrwashburn, what is the trade ID in question?

**Comment by jrwashburn** [comment]
0628491-00f869e2-1a3c-4082-9265-7791f1f097f4-067, arbitrator is swfmgmb2aoyqxkte

**Comment by cbeams** [comment]
This payout transaction has actually occurred. It took several hours, but that's because the payout transaction is co-signed between arbitrator and buyer. The buyer's client probably wasn't online for a few hours. When it came online, it received the message to co-sign and broadcast the payout transaction, and it did just that. I'm leaving out the link to the payout transaction here, but you can find it by following deposit transaction for this trade.
