### ISSUE TITLE
Create a networks statuses page, and link it from Bisq

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1575]
We have, quite often, Bisq users who come on the discourse forum or on the github, and are anxious about the delays of their trade(s).
In some case, the delays are due to broadcasting issues internal to the Bisq network or bugs, but in many other cases the delays are simply due to **congestion** in the bitcoin network, or to issues specific to the Tor network.
And BTC network congestion may happen more and more often in the future.

In order to try to reduce the anxiety of Bisq users (and they asking for support), I propose to add a « networks statuses » page somewhere (inside the website), so the Bisq users can: 
- by themselves have a look there, 
- or we can point them there when they ask for support, 
- or even they can decide to have a look to the network status **before** engaging, or not, in a trade. And possibly postpone their trade for their own benefit.

Example of congestion graphic for yesterday : https://jochen-hoenicke.de/queue/#1,2w
shows clearly what was happening, that it's the worse peak in the last 2 weeks, and may help some traders to wait a better moment.

Links to such a page could be added where useful : somewhere in the Bisq appli.
This should be beneficial for everybody.

**Comment by ManfredKarrer** [comment]
I basically agree that a monitor page would be good.
The BTC fees should be ok since we have our fee estimation. I have not seen issues with BTC congestion the last months. In December there have been congestion (https://jochen-hoenicke.de/queue/#1,6m). 
Basically we should fix the issues and not delegate the work to the users who have mostly not the skills to interpret such statistics accordingly. @ripcurlx will work on some improvements for the trade messages to make them more reliable (add confirmation messages). 
For a general monitoring for all services there is a bounty issue open since several months. I don't have time to work on that myself, so we hope some dev show up and take that task.

**Comment by ManfredKarrer** [comment]
@ripcurlx As soon we have a solid monitoring page we should add a link to it in settings/network

**Comment by freimair** [comment]
we have the [monitor](monitor.bisq.network) up and running for quite a while now. Closed.
