### ISSUE TITLE
Have the tx fees seeable in the offer book ?

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#1582]
Hello,
Actually, we do not see the tx fees in the offer book (probably because it varies ?).
This may be surprising at some occasion, especially of course when there is congestion in the mempool.
Would it be possible to display the tx fees in the offer book ?
Or at least at the moment we take an offer, in order to confirm, or not, the taking ?

**Comment by ManfredKarrer** [comment]
When you take an offer you will see the tx fee you need to pay.

**Comment by ghost** [comment]
Thanks @ManfredKarrer , but at the moment I take an offer and see the tx fee,
is it still possible to cancel the offer taking or not ?
I mean, can I do something with the fee information (taking/refusing the offer),
or the fee information is just an information ... but too late to do something with ?

**Comment by ManfredKarrer** [comment]
Yes, the offer is not taken as long you don't confirm it in the popup at the end of the take offer process. You cannot change the fee as it would influence the trade and so the other trader if you would use a too low fee (risk that the trade dispute tx does not get confirmed in time).

**Comment by osnwt** [comment]
A bit different, but related question:

If I remember correctly, Bisq says that until an offer is taken, the maker's security deposit does not leave the wallet and is not locked. But trying to use BISQ, people realised they cannot cancel or edit made offers without loosing the maker fee (which may be significantly higher than Bitcoin tx fee).

Could you explain why? Few people I talked to refused to continue with BISQ since making a trade offer and losing around 0.01 BTC when cancelled/changed is definitely unacceptable solution.

Also there is no explicit maker fee seeable when you make an offer (or it is called somehow else). So you don't know what it will cost you if you want to cancel the offer later.

**Comment by ripcurlx** [comment]
@osnwt Since version 0.7.0 there is the possibility to edit existing offers.

**Comment by osnwt** [comment]
https://bisq.network/faq/#editOffer  tells it is not possible. I also didn't find any menu items or context menu (on mac, at least). Could you please show how?

EDIT: found it in Portfolio. Would be much better to provide a context menu on the offers on Buy/Sell screens.

And could you please confirm that it really may cost 0.01 BTC to cancel an offer?

**Comment by ripcurlx** [comment]
Thanks for the hint regarding the FAQs - I'll create a PR for it to change it.

If you cancel a trade the maker fee is lost. The height of the fee is dependent on following parameters (see https://bisq.network/faq/#6):

> Min. fee (MinFee) = 0.00005 BTC, default fee (DefFee) = 0.002 BTC/per Bitcoin, market price factor (MF) = square root of percent value (e.g. 1% -> 1, 9% -> 3, 0.01% -> 0.1).
Makers trading fee = max(MinFee, DefFee * amount * MF). E.g. 0.002 BTC for 1 BTC trade at 1% market price distance equivalent to 0.2% of the trade amount.

e.g. for a 0.25 BTC trade with 0% price distance you pay as maker fee: 0.0005 BTC. 

To pay 0.01 BTC as a maker fee with the highest amount possible per trade (1 BTC) you have to have a market price distance of 25% which is a pretty unrealistic scenario. 

If you are talking about the security deposit, this is returned if you cancel a trade.

**Comment by osnwt** [comment]
OK, thanks.
