### ISSUE TITLE
Issues in "Edit offer"

### ISSUE THREAD

**Issue by fedegrc** [bisq-network/bisq#1597]
Two open offers with different currency:

![screenshot_20180629_234057](https://user-images.githubusercontent.com/14953828/42120768-371204a0-7bf7-11e8-9424-9ffd5feea975.png)

When I edit the first offer, it looks to be ok:

![screenshot_20180629_234156](https://user-images.githubusercontent.com/14953828/42120773-67171a32-7bf7-11e8-88a4-66855d656cb2.png)

When I edit the last offer I see two issued:
- "Above % from market price" = 2803.27 (should be 0.5)
- The currency should be ARS

![screenshot_20180629_234237](https://user-images.githubusercontent.com/14953828/42120778-86add69c-7bf7-11e8-9157-e19a874eebe1.png)

**Comment by ManfredKarrer** [comment]
That is a bug in the edit offer feature which gets fixed with the upcoming release.
To "fix" it temporary do following: Go and open edit offer on the offer which has the wrong currency. Then got to create offer (leave edit offer open) and use the currency selector of the payment method you used and select the currency which the offer had originally. Go back to edit offer and you should see the correct currency again. Close it.
