### ISSUE TITLE
Cannot build 0.7.1

### ISSUE THREAD

**Issue by suvayu** [bisq-network/bisq#1603]
After updating my checkout directory to the release tag (`v0.7.1`), when I run `./gradlew build` I get the following errors:

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring root project 'bisq-desktop'.
    > Could not resolve all dependencies for configuration ':compile'.
       > Could not find network.bisq:bisq-core:0.7.1.
         Searched in the following locations:
             https://jcenter.bintray.com/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.pom
             https://jcenter.bintray.com/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.jar
             https://jitpack.io/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.pom
             https://jitpack.io/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.jar
             https://raw.githubusercontent.com/JesusMcCloud/tor-binary/master/release/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.pom
             https://raw.githubusercontent.com/JesusMcCloud/tor-binary/master/release/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.jar
             https://dl.bintray.com/jerady/maven/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.pom
             https://dl.bintray.com/jerady/maven/network/bisq/bisq-core/0.7.1/bisq-core-0.7.1.jar
         Required by:
             project :
       > Could not find network.bisq:bisq-p2p:0.7.1.
         Searched in the following locations:
             https://jcenter.bintray.com/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.pom
             https://jcenter.bintray.com/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.jar
             https://jitpack.io/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.pom
             https://jitpack.io/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.jar
             https://raw.githubusercontent.com/JesusMcCloud/tor-binary/master/release/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.pom
             https://raw.githubusercontent.com/JesusMcCloud/tor-binary/master/release/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.jar
             https://dl.bintray.com/jerady/maven/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.pom
             https://dl.bintray.com/jerady/maven/network/bisq/bisq-p2p/0.7.1/bisq-p2p-0.7.1.jar
         Required by:
             project :

**Comment by ManfredKarrer** [comment]
Hm, seems some issue with jitpack.

https://jitpack.io/network/bisq/bisq-p2p/0.7.1/build.log reports that 
https://jitpack.io/network/bisq/bisq-common/0.7.1 is not found but 
https://jitpack.io/network/bisq/bisq-common/0.7.1/build.log shows a successful build.

@cbeams Any idea?

**Comment by suvayu** [comment]
If I may, this is the second time in a few months where building from source hasn't worked on release day. I'm not familiar with how everything is setup, but maybe it's worth a second look how to handle (internal) dependencies? Building from source (of a released tag) should be the most straight-forward way to get any FOSS project up and running.

**Comment by cbeams** [comment]
/cc @ripcurlx 

The problem was that a previous attempt to build bisq-p2p:0.7.1 had failed due to tags for bisq-common not having been published. This failed build was cached at JitPack and needed to be purged in order for it to be rebuilt. I have done that purge, and checking out and build bisq-desktop `v0.7.1` from source works as expected now. If you do still have trouble, try passing `--refresh-dependencies` to ./gradlew and that should clear everything up.

@ripcurlx, the root problem here, I believe, is that when you're building the bisq-desktop binaries during the release process, you're doing so from the root `bisq` repository. This causes all bisq-* dependencies to be resolved internally by Gradle within the context of the composite build. This works very conveniently for development purposes, but it can (and in this case did) hide underlying problems with resolving dependencies by tag from JitPack.

I think we have two choices here. The first is to build bisq-desktop binaries without the composite build in play, such that all dependencies are resolved from JitPack, just as would happen if a user / contributor wanted to build from source. The downside of this approach is that we have an intermediary (JitPack) in the mix when building our binaries, and that opens up an attack vector. I know @ManfredKarrer has wanted to avoid this in the past, and I agree it's worth avoiding, especially since we don't verify the checksums of bisq-* dependencies.

The second option is to continue with the status quo of building bisq-desktop binaries from within the composite build, but to add a step to the release process where we verify that bisq-desktop can in fact be checked out by tag and built by resolving JitPack dependencies. Doing this will catch problems like the one @suvayu ran into here. Of course, this step should be done _before_ final bisq-desktop binaries are built and published from the composite build.

I think the second option is probably the way to go. WDYT @ripcurlx?

@suvayu, please confirm that you're now able to build from source as expected. Thanks for reporting this.

And @ripcurlx, please assign this issue to me, thanks.

**Comment by suvayu** [comment]
Everything works again!  Thanks a lot for the quick response :)

**Comment by ghost** [comment]
Thanks for reporting @suvayu

**Comment by ManfredKarrer** [comment]
@cbeams Thanks for looking into it. I prefer the second option.

**Comment by cbeams** [comment]
This can be closed whenever you're ready @ripcurlx.

**Comment by ripcurlx** [comment]
@cbeams Regarding bisq-common tags not been published. Do you mean the tags where not pushed?I also prefer the second option. But I'm not sure if it makes sense to create the tag before building the release as I don't build it based on the JitPack dependencies and wouldn't see any issues during the build process. On the other hand if I run into any issues during testing I would need to remove the tags, fix the problem and tag again.

Just to understand how the process would work. To be able to test it I would need to push all repos first (including the new tag and the revert to the snapshot) and then checkout the bisq-desktop release tag and try to build it. Isn't that something that Travis could do? Or is there an easy way to simulate that locally?

**Comment by cbeams** [comment]
Afk now, will get back about this.

**Comment by cbeams** [comment]
@ripcurlx wrote:

> Regarding bisq-common tags not been published. Do you mean the tags where not pushed?

No, they have all been published, but at some point during the release process, something triggered a `bisq-p2p:0.7.1` build that attempted to resolve `bisq-common:0.7.1` before bisq-common's `0.7.1` tag was actually published. This left `bisq-p2p:0.7.1` in a bad state on JitPack, making it impossible to resolve (by `bisq-desktop:0.7.1`) until the bad build was purged.

So the main thing is to ensure that builds are not attempted until all tags have been pushed. Just an order of operations thing in the release process.

But in any case, if we go with option two above, you'll catch any of these problems before they affect users like @suvayu, and you'll be able to fix them by purging any bad builds, re-triggering builds, etc, just like I did to fix this situation.

So I think the main thing is to insert a step in the build process where you check out bisq-desktop by tag and build it yourself to ensure all tagged JitPack deps work as expected. I would do this *before* putting together the final (composite-build driven) bisq-desktop binaries, just in case there's some issue you need to go back and correct.

**Comment by ripcurlx** [comment]
So I would need to push the tags together with the revert commit of the version (back to -SNAPSHOT) from all repos before being able to test it locally in the bisq-desktop project, right?

**Comment by cbeams** [comment]
Yeah. Technically, you can push them as soon as they exist, even before you've reverted to `-SNAPSHOT`, but practically, yes, you can push them just after pushing the revert commit.

**Comment by ripcurlx** [comment]
Would it cause any other problem if I push the commits containing the version information together with the release tags before pushing the revert to -SNAPSHOT commit? So I don't need to make the version, revert commits in all repos again if something comes up during the final build process?

**Comment by cbeams** [comment]
What you describe is fine to do, and should not cause any problems. It is what I meant above when I wrote "you can push [the tags] as soon as they exist".

**Comment by ripcurlx** [comment]
Ok, then I'll do it like that for the next release 👍

**Comment by ripcurlx** [comment]
Done like described in last release. Won't occur anymore in the new mono repository.
Closing as complete.
