### ISSUE TITLE
Non-ASCII characters in account name

### ISSUE THREAD

**Issue by Matteljay** [bisq-network/bisq#1698]
I've noticed some crypto sellers have weird non-ascii characters in their depositor account name.
My bank doesn't accepted non-ascii characters in people's names. Could you adjust the software so that only ascii characters are allowed, so no ë, ó, ì,... Thanks!

**Comment by ManfredKarrer** [comment]
I think its better that you just use a similar character instead (e.g. e instead of ë,....). For Austria for instance ö is quite usual and using oe instead would be strange to an Austrian. 

Some banking webpages have arrived in the 21st century already and discovered UTF8 as standard for international text. The other hopefully will disappear before the end of the century ;-).
 
I will close the issue but feel free to continue discussing if you feel strong about it.
