### ISSUE TITLE
Set up SSL for bitsquare.io and subdomains

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#171]
Related to: #84

**Comment by btcll** [comment]
SSL Cert will need to cover: 
- docs.bitsquare.io
- www.bitsquare.io
- bitsquare.io
- etc

**Comment by btcll** [comment]
Ideally we want SHA-1 for maximum compatibility (any higher and we lose Windows XP support). Expiring on or before December 31 2015 to avoid the current Chrome warning issues:
http://www.symantec.com/connect/blogs/google-s-sha-1-deprecation-plan-chrome

**Comment by btcll** [comment]
Applied with Global Sign's project where they offer a free open source certificate for Open Source Projects. Will see what they say :)
https://www.globalsign.com/ssl/ssl-open-source/

**Comment by btcll** [comment]
Otherwise we will be looking at $199~ for one like this:
https://www.rapidssl.com/buy-ssl/wildcard-ssl-certificate/

I'll keep looking for cheaper (but reliable/secure) options :)

**Comment by btcll** [comment]
Encouraging news! Will pursue this tomorrow :) No hint as whether it is wildcard or not. I'll update this issue tomorrow.

![ssl-cert](https://cloud.githubusercontent.com/assets/8958455/4579779/17d01386-4fd0-11e4-86d3-b1df4f596a2b.jpg)

**Comment by ManfredKarrer** [comment]
Great!

Am 09.10.2014 um 18:20 schrieb Lloyd notifications@github.com:

**Comment by cbeams** [comment]
@btcll wrote in https://github.com/bitsquare/bitsquare/issues/169#issuecomment-58584006:

> Update on the SSL - it's only going to cover www.bitsquare.io and bitsquare.io. We could have added docs.bitsquare.io for $99/year -or- paid $200+ for a wildcare SSL Certificate. I decided not to (we can always do this later). This means we need to migrate from docs.bitsquare.io to https://www.bitsquare.io/docs/
> 
> Is that okay by you @cbeams ? Or do you have a better suggestion?

Hey, thanks for digging into this. A few thoughts:
- Is it important to have a `www` subdomain in the first place? Aesthetically, I prefer unqualified 2LDs for sites, e.g: http://bitsquare.com vs. http://www.bitsquare.com. I know the argument for keeping 'www' in place often comes up in the context of using [cookie-free domains](https://developer.yahoo.com/performance/rules.html#cookie_free), and it does make sense, but plenty of big sites shun this advice anyway. Consider GitHub itself, while we're here... no www, and all their images are sourced from a subdomain (assets-cdn.github.com). This means they're ignoring the cookie-free domain advice; don't see why we can't do the same. Is there another rationale for using a www subdomain that you have in mind?
- If we did drop www, would we have what we need for bitsquare.io and docs.bitsquare.io? I.e., does GlobalSign's cert cover any two domains, or is it strictly the 2LD + a 'www' subdomain?
- Barring the above, I think that for the time being—especially given that the docs are brand new and not even finished yet—I'd rather just leave docs.bitsquare.io unprotected by SSL. This allows us to leave things as-is, get the docs finished / into a place where we're happy with them and then decide later about expanding our wildcard cert or moving everything under a docs/ subdir of www.

In the end, putting the docs under a subdomain or a subdir isn't an enormously big deal, but all other things equal, I'd prefer keep systems that have no dependency on one another separate from one another. This allows for independent maintenance and evolution, etc. For example, bitsquare.io is a WP site put together by you, and should therefore be run and maintained exactly how you wish to work most effectively. docs.bitsquare.io is a collection of static HTML generated and deployed by an automated build, and it would be good if it were not entangled with the WP-based system at all (i.e. special exclusions for /docs/, etc). The idea is to avoid creating systems that are unnecessarily tangled with one another and therefore more fragile, harder to tease apart / replace / migrate / delegate control over, etc.

I realize that was a bit lengthy. I don't mean to get us into a long textual distraction here. Happy to discuss this on tonight's call, or otherwise via voice if it's easier for you.

> My intention is to do the migration following the HTTPS being setup. I'll need to email you fresh FTP/SSH info. I'm not sure we ever got to the bottom of the SSH issues for you either so let me know on IRC and we can troubleshoot that further.

I've been OK on the SSH front, and so too is the Travis CI build. Not sure what did the trick, but it's all good for now anyway.

**Comment by btcll** [comment]
Very happy to go with http://bitsquare.io without the www. The SSL Cert covers both www. and without at the moment.

Will see if dropping the www. will give us docs. and let you know :)

**Comment by btcll** [comment]
Contacted them. The free SSL only includes www., root domain and the M$ Exchange related subdomains. docs.bitsquare.io is an extra $99/year. 

In the end we have SSL for these domains:
    autodiscover.bitsquare.io
    mail.bitsquare.io
    owa.bitsquare.io
    www.bitsquare.io

Sorry I couldn't get docs. too. I'm very happy to run it without SSL for now like you suggested and add it later when we have more project funds available.

Marking this closed. Please let me know if you notice any problems with the SSL Certificate in the mean time!

**Comment by btcll** [comment]
If anyone is on Windows XP please let me know if any warnings are displayed. There is a small chance we might need a dedicated IP for the website to not have SSL Warnings on Windows XP.

**Comment by btcll** [comment]
Actually, just had a thought to apply for a second SSL Certificate for free as an Open Source project. So did that via: https://www.globalsign.com/ssl/ssl-open-source/
This will be for: docs.bitsquare.io

Will see what they say ^.^
