### ISSUE TITLE
Dash DNS Seeders Offline

### ISSUE THREAD

**Issue by HashEngineering** [bisq-network/bisq#1714]
Recently, we have learned that several of the DNS seeders for Dash have gone offline.  This caused a major disruption in the Dash Wallet android app that was depending on these seeders.

Since I wrote the code used by Bisq for Dash, bisq may be having the same problems connecting to the Dash network if that functionality is still part of the application.  We found that some users in various parts of the world could not access any of the seeders, while other could.  Of the 4 in the source code, 3 are offline:
https://github.com/bisq-network/libdohj/blob/master/core/src/main/java/org/libdohj/params/DashMainNetParams.java#L87

Depending on the location of the user, the 4th (dnsseed.dash.org) may not be working either.

Have users been having any issues with Dash?

**Comment by ghost** [comment]
We didn't get any complaints about issues with Dash recently. Neither on forum/GH/slack/reddit.
There is however (unfortunately) no great activity with Dash on Bisq (~1 trade per month).
The last Dash trade is from sept 9th, and the previous one is from july.

**Comment by mrosseel** [comment]
@HashEngineering thanks for your report! Unfortunately, due to low activity dash can no longer be used as base currency. We started 3 alternative base currencies: LTC, DOGE and DASH. They never took off in volume though, and as far as I know, all of them have been shut down. So there is not impact on Bisq at this moment, because all BTC/DASH trades use bitcoin's multisig.

**Comment by HashEngineering** [comment]
Ok, thanks.  I will close this issue.
