### ISSUE TITLE
Add warning for cash deposit with BofA

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#1814]
See: https://bisq.community/t/banks-tightening-deposit-rules/3595

**Comment by m52go** [comment]
Here's some possible text for a warning:

"Please confirm your bank accepts cash deposits into other peoples' accounts. For example, Bank of America and Wells Fargo no longer accept such deposits."

In addition, as another check (since at least some users will ignore the warning and fail to check) perhaps we could also consider popping a warning when a user tries to add an account from a bad bank (i.e., maintain a blacklist of bank routing numbers within the software).

**Comment by m52go** [comment]
EDIT

"Please confirm your bank allows you to send cash deposits into other peoples' accounts. For example, Bank of America and Wells Fargo no longer allow such deposits."

The sending bank's rules prevail, so the text should reflect that.

**Comment by ManfredKarrer** [comment]
Implemented with https://github.com/bisq-network/bisq/pull/1822
I have only added a popup for now. To filter the bank data would require a bit more research which routing numbers are used, etc...
