### ISSUE TITLE
TX considered non-standard due to unknown version number 2

### ISSUE THREAD

**Issue by iljah** [bisq-network/bisq#1832]
Noticed this in log after funding offer from external wallet (github.com/bitcoin/bitcoin):
```
[NioClientManager] WARN  b.c.b.w.BisqRiskAnalysis: TX considered non-standard due to unknown version number 2                                                                                         
[NioClientManager] WARN  o.b.w.Wallet: Pending transaction was considered risky: Risky due to non-standard tx 
...
  version 2                                                                                                     
  time locked until block 547727                                                                                
  opts into full replace-by-fee                                                                                 
     in   PUSHDATA(71)
...
[NioClientManager] WARN  o.b.w.Wallet: There are now 1 risk dropped transactions being kept in memory
```
According to internets version 2 transactions should be old news (https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki), can I safely ignore this or should I worry?

**Comment by ManfredKarrer** [comment]
I think you can ignore that. The BitcoinJ release on which our fork is based on is already quite old and seems it was not updated with that version field.

**Comment by iljah** [comment]
Ok thanks.

**Comment by ManfredKarrer** [comment]
I will leave the issue open as it should be investigated and fixed....

**Comment by oscarguindzberg** [comment]
This is all about analyzing the risk of unconfirmed txs. 
The issue was fixed on a not-yet-released bitcoinj commit https://github.com/bitcoinj/bitcoinj/commit/850f21960723dfcb664f795404f3f42004bd32eb#diff-e110a400ca7d22795d2fce31b6935813L136
The fix considers Version 2 txs standard. If an unconfirmed tx uses Version 2 and BIP 68’s CSV it prints a non-final tx warning and the tx is considered risky (just using version 2 does not make a tx risky).

**Comment by oscarguindzberg** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/2127

**Comment by ripcurlx** [comment]
Closing as complete.
