### ISSUE TITLE
Allow placing sell offers and just deactivate the take offer buttons there.

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#184]

**Comment by cbeams** [comment]
Hey Manfred, I added #193 without realizing you'd already added this one (see https://github.com/bitsquare/bitsquare/issues/193#issuecomment-58748265 specifically). Closing this issue, then, as I've already referenced #193 in a number of other places.

Also, as far as "deactivating the take offer button", I believe you're referring to the buyer's ability to take an offer (#192)? Note that that issue is scheduled for v0.3 per our discussion—perhaps there's still some kind of disabling of that button required for v0.1 though, I don't know.

**Comment by cbeams** [comment]
Duplicates #193
