### ISSUE TITLE
Screen Launches But Nothing Enabled - Error Message After A While

### ISSUE THREAD

**Issue by DawBin** [bisq-network/bisq#1888]
[bisq.log](https://github.com/bisq-network/bisq/files/2554902/bisq.log)

**Comment by ghost** [comment]
Which error message did you get ?
Do you have an AV (AntiVirus) running ?

log contains:
Nov-06 14:08:50.669 [InputHandler-ef5qnzx6znifo3df.onion:8000] INFO  b.n.p.n.Connection$InputHandler: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 
Nov-06 14:08:50.671 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: onDisconnect called: nodeAddress=Optional[ef5qnzx6znifo3df.onion:8000], closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} NO_PROTO_BUFFER_ENV 
Nov-06 14:08:50.673 [JavaFX Application Thread] INFO  b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} NO_PROTO_BUFFER_ENV, nodeAddressOpt=Optional[ef5qnzx6znifo3df.onion:8000] 

Not sure if it has to do, or not, with the issue.

**Comment by DawBin** [comment]
The message said something about "too many GC" but I could not copy it and
I did not think to take a snapshot. I will next time. Yes running windows
defender. After receiving the message and closing the error dialog it
seemed to work.

**Comment by ManfredKarrer** [comment]
If you mean "We have too many connections open" that is nothing critical but normal P2P management. 
I assume your AV software is doing something. Some are deleting files one was even deleting the wallet!

**Comment by xmijo** [comment]
I think I just had the same error, never gotten it before. Took a very long time for bisq to start up, laptop fans started spinning, thought it had crashed. But eventually a pop-up box appeared saying "too much GC overhead" or something similar. But after closing it, bisq seemingly was working as normal. This was on mojave, bisq 0.8.0.

**Comment by ManfredKarrer** [comment]
Was it first run after download? Latest version 0.8.1?

**Comment by xmijo** [comment]
> Was it first run after download? Latest version 0.8.1?

No, it was not the first run. And the version is 0.8.0 - I didn't know there was a newer version out, it hasn't asked me to update yet.

Anyway, I've started bisq several times since and it starts normally without the error message. It seems like it was just a temporary issue.
