### ISSUE TITLE
Currency code for Venezuelan bolivar has changed

### ISSUE THREAD

**Issue by madacol** [bisq-network/bisq#1920]
The app shows "VEF", but this year that code changed to "VES"

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar

Thanks for signaling.

**Comment by MwithM** [comment]
A trader in Venezuela has pointed out this issue on Twitter. This should be addressed.
Is it easy to change? If not, at least we should let them know that it won't change, but I think there best is to change the Bolivar VEF to VES.

Edit to ping @HarryMacfinned because not sure if a closed issue will alert someone a new post.
