### ISSUE TITLE
Bisq fills drive with PreventAppNap soundfiles

### ISSUE THREAD

**Issue by iljah** [bisq-network/bisq#1931]
Bisq fills /tmp on fedora 28 with files Bis-N-PreventAppNap-soundfile where N is some large number. As /tmp is in memory only it fills up pretty quickly at which point bisq start generating exceptions about not being able to create QR codes when I try to create sell offers.

**Comment by ghost** [comment]
Thanks for reporting.
Do you have screen lock activated ? or sleep mode ? or something like that.

**Comment by iljah** [comment]
Screen locks itself regularly, no sleep mode.

**Comment by iljah** [comment]
Screen also shuts itself off (laptop) regularly but that doesn't trigger locking which happens later.

**Comment by ManfredKarrer** [comment]
@iljah Thanks for reporting. I will look into it.

**Comment by ManfredKarrer** [comment]
Just tested it on OSX and here it gets deleted when app is closed (even if its hard killed).

 ```
File soundFile = File.createTempFile("Bisq-", "-PreventAppNap-soundFile");
soundFile.deleteOnExit();
```

Seems the `deleteOnExit` does not work on your system for some unknown reason. If you are a developer could you try to debug into that? Otherwise could you send me the log file (manfred at bitsquare dot io)?

@freimair Do you have any idea or do you know if there are issues on Linux with temp files and `deleteOnExit`?

**Comment by ManfredKarrer** [comment]
Actually I think using temp file for that use case was not a good idea anyway. Will prob. change that to a file in the data directory.

**Comment by iljah** [comment]
> Seems the deleteOnExit does not work on your system for some unknown reason

It probably works fine but I just didn't exit... It took maybe 20-40 files before this started happening, didn't check whether bisq was using most space or something else.
