### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by leafcutterant** [bisq-network/bisq#1962]
I propose creating a portable version of Bisq (one which doesn't require to be installed and doesn't leave a trace outside the application directory).

**Comment by ManfredKarrer** [comment]
Bisq doesn't leave a trace outside the application directory. Any idea how to run the app without installation? I doubt that is possible. On OSX you can run it from the dmg file (mounted disk) but on other OS, specailly on Windows i think that is not possible.

**Comment by leafcutterant** [comment]
> Bisq doesn't leave a trace outside the application directory.

I'm sure it does because the application and the user data reside in separate folders, which, in addition, are subfolders of system folders. A feature of portability is that the user can choose where the application resides.

As on the how, I'm not sure I can help with that. I think it  has to do with ridding the application of dependence on the OS's assets and other installed resources. Many crypto clients (both full and light) managed to do this, e.g. Bitcoin Core and Electrum.

**Comment by devinbileck** [comment]
On Windows, application and data files are currently installed/stored in separate folders within the users directory. I would assume it should be possible to create a portable version that stores this data within the same directory that the app is launched from.

**Comment by leafcutterant** [comment]
Bad bot. Request for reopening.

**Comment by BabyRdx** [comment]
Not sure if you figured this out yet leafcutterant but you can get Bisq to be portable* for the Windows family.  Start by installing the application directly on the USB medium.  By default Bisq stores application data at C:\Users\<user>\AppData\Roaming.

To get around this there is two things you can do.
1. Copy your Bisq AppData to the USB stick
2. Create a shortcut of the application you installed on USB.
3. Edit the shortcut so that Target ends with  --appDataDir "D:\AppDataFolder" where D:\AppDataFolder is the path to the AppData on USB.

The drawback of this method is that I don't believe shortcuts support relative paths, meaning you would have to assign the same letter to your drive each time you wanted to use it.

The second method can get around this.
Create a new shortcut on the USB drive.  In the target place: %COMSPEC% /C .\Bisq\Bisq.exe --appDataDir ".\AppData"  
Replace .\Bisq\Bisq.exe with the relative path to the exe and .\AppData with the path to the AppData.

Hope this helps.  This may not truly be portable as I am not sure how Bisq interacts with the registry and what traces it leaves in there.

**Comment by manyfew** [comment]
New to Bisq and a huge fan of portable apps. Bisq should have been portable from the get-go.
