### ISSUE TITLE
Another trade failure

### ISSUE THREAD

**Issue by Tharrso** [bisq-network/bisq#1980]
I tried to take another trade and again got the message that it timed out and I may have lost my deposit and I should restart Bisq. When I do I get the message: "You must have bootstrapped before adding data to the P2P network."
Bisq asks that I attach the bisq log along with this. But where is it?

**Comment by Tharrso** [comment]
Also this time the transaction appears in the FAILED tab with this explanation:
![failed](https://user-images.githubusercontent.com/44954997/49060579-118a6780-f1c3-11e8-91cf-1caf19dcdda2.png)
What to do?

**Comment by ghost** [comment]
For the Bisq file locations:
Mac OSX: /Users/username/Library/Application Support/Bisq 
Linux: /home/username/.local/share/Bisq 
<del>Windows 7,8,10: C:\Documents and Settings\username\AppData\Roaming\Bisq </del>
Windows 7,8,10:  C:\Users\username\AppData\Roaming\Bisq
Windows XP: C:\Documents and Settings\username\Application Data\Bisq

**Comment by devinbileck** [comment]
@HarryMacfinned BTW, the proper location for Windows 7,8,10 is C:\Users\username\AppData\Roaming\Bisq

**Comment by ghost** [comment]
Thanks @devinbileck , I'll correct.

**Comment by Tharrso** [comment]
Thanks, guys. Here is the bisq.log for yesterday. Today I am not getting any error messages about this trade. I note that in the above screenshot it says "Taker fee published". Does that mean I have paid and lost the taker fee?
[bisq.log](https://github.com/bisq-network/bisq/files/2621445/bisq.log)
Here's the screenshot of my FAILED tab:
![failedtab](https://user-images.githubusercontent.com/44954997/49104640-4fbf6f80-f233-11e8-984c-d601e56a5926.png)

**Comment by ghost** [comment]
@Tharrso wrote:
> I note that in the above screenshot it says "Taker fee published". Does that mean I have paid and lost the taker fee?

Yes, it means you have paid the taker fee.
However, if you consider that the trade's failure is not your fault and that you respected the protocol, you can either open a support ticket (if possible), either contact directly the arbitrator for this trade.
And he will refund you if the failure was not your fault.
What is the onion address of the arbitrator in this case ?

**Comment by Tharrso** [comment]
Well this is strange. Today this trade still appears in my FAILED tab, but also in my OPEN TRADES tab it appears to be progressing normally while waiting for seller's payment confirmation. Still 3 days to wait until the time expires. I guess I will wait and see what happens.

**Comment by ManfredKarrer** [comment]
@Tharrso If you have lost the trade fee due a bug you can ask for reimbursemnet here: 
https://github.com/bisq-network/support/issues/

One known reason for those problems is that at least on OSX standby mode reduces network and CPU resources to such a low limit that trade messages become very unreliable. We fixed that so that the OS cannot send the application to standby mode with the upcoming 0.9 version (release planned next week). 
Beside that undstable network connections can be another reason.

**Comment by Tharrso** [comment]
Well if the trade completes then I guess I will not have lost the trade fee, right?
Good to know about the OSX fix. That's probably what caused my problem.

**Comment by ManfredKarrer** [comment]
Yes if the trade completes all is fine. The lost trade fee usually only happens if at the last step at the take offer attempt the last message from the maker does not arrive (network broken). Then the takers trade fee is alreayd paid but the trade never really started (if the deposit tx is not created).
