### ISSUE TITLE
Security recommendation prompt is shown multiple times when importing multiple accounts

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1981]
When importing accounts (either national currency or altcoins), the security recommendation prompt will be shown once for each imported account (multiple times if importing multiple accounts):
![image](https://user-images.githubusercontent.com/603793/49068037-8cab4800-f1da-11e8-87ba-a8fa7ea2d561.png)

before it shows the final result prompt indicating which accounts were imported.

Also, the security recommendation prompt should be shown after the result prompt.

**Comment by ManfredKarrer** [comment]
That is related to other issues and caused by the cahnge to tabs instead of the old side menu. The activate methods get called on all tabs now triggering such popups.

**Comment by ripcurlx** [comment]
It's not related to the old side menu. It was also the same in the old version. 
https://github.com/bisq-network/bisq/blob/63b7c2c75df6a4ee0acf723d508d4cdfa3020a83/core/src/main/java/bisq/core/app/BisqSetup.java#L677-L684
The problem is that the global listener listens to changes in the payment accounts and when they are imported it changes with every new entry which triggers this listener and the corresponding popup every time. I'll see if I can add the payment accounts at once so it is only triggered once.

**Comment by ripcurlx** [comment]
Actually I think we shouldn't show the security recommendation in that case at all, as the user has seen it anyways when she created the payment account in the first place.
