### ISSUE TITLE
Changing BTC network does not have any effect

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2048]
If user changes the BTC network in settings and restarts MAINNET will be selected again even if the user has changed to testnet. There is probably some bug in the option parsing. @freimair will look into it.
For now users who want to try out the testnet DAO need to add a program argument: 
'--baseCurrencyNetwork=BTC_TESTNET ' to enable testnet.

**Comment by freimair** [comment]
I have been able to track the issue down to 83e1dd37f975a97c56c8aa5337fda29a4b10a063. (and probably the issue, where the appdir uses the default dir as well).

### The issue

https://github.com/bisq-network/bisq/blob/83e1dd37f975a97c56c8aa5337fda29a4b10a063/core/src/main/java/bisq/core/app/BisqExecutable.java#L478-L482 introduces a default value which is used by the options parser if required (i.e. whenever you do not add ```--baseCurrencyNetwork=BTC_TESTNET```)

However, due to https://github.com/bisq-network/bisq/blob/83e1dd37f975a97c56c8aa5337fda29a4b10a063/core/src/main/java/bisq/core/app/BisqEnvironment.java#L338-L340
Bisq first parses the ```commandLineProperties``` (which already provides the default values due to the abovementioned changes), and thus, the  getProperty-call is satisfied already and the ```getAppDirProperties()``` are never asked.

This all boils down to a mostly useless ```bisq.properties``` at the moment.

### Fix
Now, it is not trivial to change the behaviour while keeping the (most welcome) changes of 83e1dd37f975a97c56c8aa5337fda29a4b10a063.
- if we change the order of the property sources, we foreclose overriding bisq.properties-properties with cmdline options
- if we partially revert 83e1dd37f975a97c56c8aa5337fda29a4b10a063, we create a permanent minefield for future developments
- we could use ```bisq.properties``` as defaults where applicable. However, we would have to open the ```BisqEnvironment``` to ```BisqExecutable```
- ???

all in all, I do not want to decide on that alone: @cbeams, @ManfredKarrer any ideas?

### other
- does 83e1dd37f975a97c56c8aa5337fda29a4b10a063 deprecate things? for example https://github.com/bisq-network/bisq/blob/83e1dd37f975a97c56c8aa5337fda29a4b10a063/core/src/main/java/bisq/core/app/BisqEnvironment.java#L207-L335
and 
https://github.com/bisq-network/bisq/blob/83e1dd37f975a97c56c8aa5337fda29a4b10a063/core/src/main/java/bisq/core/app/BisqEnvironment.java#L445-L502
which might cleanup the minefield a bit
- for the appdir issue #2019 https://github.com/bisq-network/bisq/blob/83e1dd37f975a97c56c8aa5337fda29a4b10a063/core/src/main/java/bisq/core/app/BisqExecutable.java#L425-L428 might to be responsible.

**Comment by ManfredKarrer** [comment]
Ah great you found out the reason!

Same issue was with log path which was now always 'Bisq'.

I don't have strong opinions and its not my field of expertise. Leave it to @cbeams to suggest how we should resolve it, but would be good to resolve it soon as people cannot switch to testnet in the UI and it might affect other options as well.

**Comment by CaveSpectre11** [comment]
I stumbled across this when I was playing with 0.9.0, but I hadn't had enough time to fully determine if I was doing something wrong or if there actually was a problem; I'm using the Windows client.  One thing that may be relevant to bring up:  I tried changing the field in the config file (I don't have access to my PC at this moment to specify exactly what the config file name was), and it reverted back to MAINNET after starting the client.  Initially I tried this when the client was running, then restarted.   I then tried it after shutting it down, and it also changed the contents of the file on startup.

**Comment by cbeams** [comment]
Thanks, @freimair for the careful analysis above. Please see #2063, where I've fixed this specific problem, and you'll see in the comment there where I suggest a larger and more general fix.

I have a number of additional changes to our option handling infrastructure queued up locally that I have not yet submitted as a pull request. I'll see about working the more general fix into those changes before I submit it.
