### ISSUE TITLE
Improve Windows installer so it deletes old app directory

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2066]
We got a lot of reports with that release that users cannot run the new version. After deleting the app directory (.../Local/Bisq) it works. We got those issues also in the past but less often. I assume as with Java 10 we have a different runtime that this cause imcompatibility with almost all Windows users old installation.

Is there a way to configure in the java packager that the installer runs a pre-install script where we rename the app directory to Bisq_0.8 or the like to get rid of that issue? Or we simply set the property which is used to name the Bisq directory to Bisq_0.9.0, so with every version that directory gets newly created. Would avoid future issues as well. That might be the easiest way to deal with it.

@devinbileck Any idea?

**Comment by devinbileck** [comment]
@ManfredKarrer I am not familiar with the java packager and whether it can do that. But am willing to investigate, unless @ripcurlx knows?

**Comment by ripcurlx** [comment]
@devinbileck Would need to look through the documentation myself.

**Comment by devinbileck** [comment]
It should be possible to script deleting or renaming the folder. Looking at the [documentation](http://www.jrsoftware.org/isinfo.php#features), it mentions the following:

> Integrated Pascal scripting engine option for advanced run-time install and uninstall customization.

And after briefly familiarizing myself with the existing packaging scripts, I have realized there is room for improvement and refactoring since the process assumes the jar is built and updated on MacOS, then transferred to Windows/Linux to do the packaging. If I want to dig into this further, I will need to update the scripts to be able to build and package exclusively on Windows. Which I don't mind doing since I am interested in the process.

**Comment by ripcurlx** [comment]
@devinbileck Just a heads up, that I'm working on a quick fix for our Windows issue. It will be a small script that is executed before installation takes place. I works for me if I run the Inno Setup manually. But we have the problem right now, that all our custom parameters are not used by the Javapackager right now. That's also the reason why all installer icons and so on are not applied. I'm looking into this atm.

**Comment by devinbileck** [comment]
@ripcurlx sounds good. I noticed that too regarding the icons as I have started refactoring the Windows script.
