### ISSUE TITLE
BTC / CAD Rates not consistent

### ISSUE THREAD

**Issue by astupidmoose** [bisq-network/bisq#2073]
I've been taking a look at the rates from BitcoinAverage and inside Bisq and they are not in line for BTC/CAD. 

All other currencies are pulling good rates, however even when bitcoinaverage shows a rate of 5174.62, Bisq is showing 5515.48 for example. 

This is not reflective of the market. Makers/Takers are having to adjust their rates by 5-10%. 

![image](https://user-images.githubusercontent.com/3916318/49567003-5445f100-f8e1-11e8-90ae-5973e96297df.png)

**Comment by ManfredKarrer** [comment]
Global price at BTCA is the USD price converted to CAD, that can be very diferetn to the local price from local exchanges. We use the local price if available.

**Comment by astupidmoose** [comment]
Local price must be way off then on BTCA, the global price is very much more in line with prices and has been for months. Perhaps something here needs to be looked and see how it can be done differently?

See attached screenshot of CAD exchanges and volumes (source: [www.cbix.ca](www.cbix.ca) . Only one exchange is in line with Bisq. The others are all in line with each other. 

![image](https://user-images.githubusercontent.com/3916318/49599987-1673b780-f937-11e8-841c-143ba8f91f56.png)

**Comment by ManfredKarrer** [comment]
There have been in the past complaints about the CAD price and I forwarded it to BTCA but from what I rememebr they did not see anything broken. Could you try to get in touch directly with Shaun Gilchrist <shaun@bitcoinaverage.com>? You have more local background knowledge to discuss why their preice is so far away from the others. They can adjust the weighting to get a more realistic price.

**Comment by ManfredKarrer** [comment]
If you hear anything back would be great to keep us informed here...

**Comment by j3ko** [comment]
I was actually in contact with Darko from BTCA a few days ago about this issue, I didn't realize there was a GitHub issue about this.  The problem was QuadrigaCX was given too high a weighting in the CAD bitcoin average price.  

QuadrigaCX has been having issues with the big banks here in Canada for quite some time and clients have been able to deposit funds easily but not withdraw it reliably.  Because of this, the price on QuadrigaCX is artificially inflated.  It seemed to have gotten worse in recent months.

This has been fixed with BTCA, they lowered the weighting of QuadrigaCX and added CoinSquare to the list of CAD exchanges.  The CAD rates seem a lot more realistic after the changes.

![screen shot 2018-12-25 at 7 38 00 pm](https://user-images.githubusercontent.com/2643197/50422368-c2485d00-087c-11e9-8d39-f7d98278ab6f.png)

**Comment by ManfredKarrer** [comment]
@j3ko Great thanks for helping to resolve that! Feel free to make a compensation request for those efforts!
