### ISSUE TITLE
getProperty(AppOptionKeys.APP_DATA_DIR_KEY) is returning default value

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2084]
If you use option `--appName=Bisq-1` the result from `environment.getProperty(AppOptionKeys.APP_DATA_DIR_KEY);`
is `Bisq` instead of `Bisq-1`.
If accessed with `environment.getAppDataDir();` it is correct.

The default value is applied.

Caused bug at backup (backups Bisq instead of Bisq-1).

**Comment by freimair** [comment]
That is because --appDataDir is not set and instead, the default is used:
https://github.com/bisq-network/bisq/blob/83e1dd37f975a97c56c8aa5337fda29a4b10a063/core/src/main/java/bisq/core/app/BisqExecutable.java#L425-L428

same cause as https://github.com/bisq-network/bisq/issues/2048#issuecomment-444149682

I would suggest reverting https://github.com/bisq-network/bisq/pull/1961 as @cbeams suggested in #2063 for the https://github.com/bisq-network/bisq/milestone/21.

However, as the changes of #1961 are much welcome and do clean up the command line API pretty good, I would suggest planning a refactoring of the option processing for a future release.

**Comment by ManfredKarrer** [comment]
Maybe we can revert only those parts of #1961 where the setting of the defaults have been changed. Seems those are the problematic issues. Would be good to get that asap to get it shipped with the next release mid next week.

**Comment by cbeams** [comment]
Reverting the removal of the `description` method and its replacement with JOptSimple’s `defaultsTo` In commit 83e1dd3 would be enough. Reverting the entire PR would be overkill, as the custom HelpFormatter introduced is effectively separate and not causing any issues.

**Comment by ManfredKarrer** [comment]
Ah thanks @cbeams - the benefits of granular clean commits ;-)
