### ISSUE TITLE
DAO: Dash and Litecoin duplicated in the list of assets within the asset listing fee view

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2091]
![image](https://user-images.githubusercontent.com/603793/49680457-65117680-fa49-11e8-92ee-fd12ba4eb593.png)

**Comment by ManfredKarrer** [comment]
Yes thats known issues. Those ex-base currencies have 3 subtypes for mainnet, testnet and regtest. 
We show all mainnet currencies in regtest or testnet as otherwise there would be only those who have defined those subtypes (BTC, and the ex-base currencies).
It would either require to add extra filtering to avoid that those are displayed or better to remove the testnet/regtest support for those and treat them as that what they are: just another altcoin.
