### ISSUE TITLE
Portfolio History - Export to CSV Feature Request

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#2106]
I’m looking to track my profit/loss trading and would like to see trading fees and security deposits added to the data available to be exported into a csv file.

This would add information regarding the cost-to-trade which would help tracking trade profit/loss.

**Comment by ManfredKarrer** [comment]
Yes would be nice to improve the export features. Any dev up for it?

**Comment by dougbebber** [comment]
Could we also include offer info in Portfolio History?

From a trade management perspective I think it makes sense to track orders (offers) as well as executed trades. Trades are the result of accepted offers. However, orders may be partially filled in a trade and tracking both orders and trades makes for a more comprehensive set of information for individual trade and money management. 

I see that Offers have details that include an Offer ID, Creation date as well as details such as offer type, BTC amount, Min. BTC amount, Altcoin amount, security deposit,etc.

Trade details are also available. Being able to link trades to offers would help in trade management analysis. Questions like, how long did it take for my offer to be accepted in a trade.

What I would like to see is the data necessary to see how much value has been spent (including fees and deposits) along with how much value has been received. This would allow for the effective management of a traders P&L.

Please feel free to contact me as I would be more than willing to assist to make this happen.

**Comment by ManfredKarrer** [comment]
Offer ID is same as trade ID. The only missing data (I assume, not verified by code now) is the offer amount and min. amount. The trade details shows the trade amount but not the offers original amount range. The data is there (trade contains the offer object), so should be trivial to add that to the UI and/or export data. Though we need to find a balance for how much data to display in the UI otherwise scrolling is required. The JSON data might be an option to show the full technical data for those who want to see all, without overloading the UI with details.
But agree that it would be good to show the relevant offer data. Maybe in the trade details there can be a button for the offer details, though might lead to popup hell :-).... Anyway any good UI solution is welcome as pull request!  

But a maybe more interesting effort might be to work on a real P&L overview screen. Would require a bit of conceptual/UI design first but would be a nice feature to get a new screen where u see how successful the trades have been. Some charts there might be nices as well...

If you can make a proposal for such woudl be great. A wireframe layout would be enough. We don't have the dev resources atm to work on that, but if you can preovide a PR we would be happy to integrate. @ripcurlx can help with the app integration (adding tab in portfolio).

**Comment by ManfredKarrer** [comment]
And of couse such work is up for BSQ compensation requests!

**Comment by thedon-chris** [comment]
Is this feature complete, and is this issue still open for work?

**Comment by ripcurlx** [comment]
@thedon-chris This is up to be taken. If you want to work on it please contact @ManfredKarrer to add you as a contributor and I'll assign you.

**Comment by niyid** [comment]
Hi @ManfredKarrer

I have checked the **`PORTFOLIO > HISTORY`** screen.

I am up for it.

Regards.
![Screenshot from 2019-07-22 01-42-24](https://user-images.githubusercontent.com/20237127/61599592-5ebfbb80-ac22-11e9-96f6-add95f73eecb.png)

**Comment by ManfredKarrer** [comment]
Would only require to some more data so that traders get a more complete data set. No clearly defined spec but its part of the task to think about whats best to add.

**Comment by niyid** [comment]
The initial request was to add more data to allow for profit/loss analysis. I think these should be added:

1. security deposit
2. trading fee
3. offer amount

Any other data will not really enhance the initial target.

What do you suggest?

**Comment by sqrrm** [comment]
@niyid If you could get some input from traders that require this feature that would be best. Sounds like a good start with what you suggest but try to get a discussion going with users that want the feature as well.

**Comment by niyid** [comment]
@sqrm

Thanks for the great suggestion. Are there any particular fora that will reach a large target audience either under or outside of the  https://bisq.community/ forum and Slack channels?

**Comment by niyid** [comment]
@ManfredKarrer 

Can I get this assigned? I thought it was already.
