### ISSUE TITLE
DAO: Need to be able to determine a compensation request came from the actual contributor

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2114]
I am able to create a compensation request for work that I did not contribute:
![image](https://user-images.githubusercontent.com/603793/49836073-37347680-fd56-11e8-8aac-147143ec2e2a.png)

There should be some way to determine which compensation request came from the actual contributor.

**Comment by ManfredKarrer** [comment]
That is an interesting topic. I was thinking to add some additional proce (e.g. signature). But I am not sure if it is really required at least at the current state. Any contribuor should do due dilligence to report any suspicious proposal and sepcially of they detect a proposal using their own one. E.g. in the example if the DAO voting process would not detect that a scammer has abused Christophs request, neither Christoph nor the other DAO stakeholder had cared enough to avoid that. So that would signal that the DAO as a social body is in a pretty bad shape.

The fees are in place to make trolling/abusing the DAO infrastructure expensive. If we would get trolls we can increase the fee to a level where only contributors who really care will partizipate.

Or do you have any scenario in mind where this still can become problematic?

**Comment by devinbileck** [comment]
Yes, true. It is highly likely this would be detected and hopefully before anyone has cast a vote without first realizing it is a fraudulent request.

If this situation is encountered, I guess both the valid and fraudulent requests would have to be rejected by stakeholders as there is no way to tell which one is which. Meaning that the real contributor would have to wait for the following voting period to submit their compensation request again.

And with the current proposal fee at only 2 BSQ (est. $2 USD), there is a potential for abuse if a bad actor wants to prevent any contributor from receiving compensation.

**Comment by ManfredKarrer** [comment]
There are data available to detect the real one (txId) but it is not displayed yet (open TODO to show all the detail data in a popup). 
I don't see a high risk for kind of sabotage attacks like that at the current state and if it would really happen we can fix it quickly with an update. So I agree it should be solved but has lower prio for me (highest prio is stability and security - not being able to create a tx which is not correctly interpreted).

**Comment by ManfredKarrer** [comment]
If anyone wants to work on that (e.g. popup with all detail info) would be great though!

**Comment by ManfredKarrer** [comment]
I added a issue for the details popup (https://github.com/bisq-network/bisq/issues/2334) and will close that one.
