### ISSUE TITLE
Focus color of buttons should be more saturated/darker not lighter

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2134]
Atm giving a button focus by tabbing through or by default focus shows the button with a lighter color as focus indicator.

Focus color should always be a more saturated color or darker to prevent seeing it as disabled by mistake.

**No focus**
![Bildschirmfoto 2018-12-18 um 10.29.29.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/87b489a9-ce78-4f24-ba3a-e9bba7b0debb)
**Focus**
![Bildschirmfoto 2018-12-18 um 10.29.36.png](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/e14cd87a-1745-41f3-b730-4bc04ead22a5)

**Comment by CaveSpectre11** [comment]
I know where the change needs to be made; setup one of my old laptops to run linux to setup a development environment.  Going to try and get this one banged out.

**Comment by CaveSpectre11** [comment]
Sorry it took a while, I was battling with Idea; it seemed to be building fine but it didn't update bisq-desktop.  I assumed, obviously, that I was changing the wrong thing, rather than it not getting built into image.

I didn't notice the part about tabs at first, but I got that taken care of to.  However, I'm not sure I like the action that occurs when you tab over to it.  It's darker, but instead of staying vivid, it fades... and I've not figured out what is causing that yet.   I'm going to PR as it is, and if the action fade is needed to be resolved, I'll look further into that.

**Comment by CaveSpectre11** [comment]
This has been updated with PR #2187

**Comment by ripcurlx** [comment]
Closing as complete.
