### ISSUE TITLE
Make "filter by currency" field searchable/editable

### ISSUE THREAD

**Issue by userzer0x** [bisq-network/bisq#2226]
as said in title, it would be so much more convenient to type in the currency in the "filter by currency" field, instead of continuously scrolling through a long list of currencies..its a bit tedious

**Comment by devinbileck** [comment]
Related (or potentially duplicates) to https://github.com/bisq-network/bisq/issues/112

**Comment by justpaulgmx** [comment]
Agreed, close this issue?

**Comment by userzer0x** [comment]
@ManfredKarrer please confirm. if this is duplicate.

**Comment by userzer0x** [comment]
PS: this should also be the case for the Market Price at the top. type in currency EUR or USD, etc.

**Comment by ripcurlx** [comment]
I wouldn't see this as a duplicate, but more a related issue, that might be fixed in one go.

Within the `Available offers > Filter by currency` I'm not sure if it is necessary to have a searchable combobox, as you can also edit the list of coins (alt, fiat) you want to see. So you should have a pretty short list in most cases. But I do think the "edit list" is a little bit hard to find at the end of the list.
<img width="364" alt="bildschirmfoto 2019-01-09 um 10 13 14" src="https://user-images.githubusercontent.com/170962/50889023-36dfd780-13f7-11e9-8a1f-ad404b3f0a1b.png">

This list also effects the market prices at the top.

<img width="269" alt="bildschirmfoto 2019-01-09 um 11 48 05" src="https://user-images.githubusercontent.com/170962/50894787-73fe9680-1404-11e9-932e-2da40b41623e.png">

The searching of the currencies could be done like in the account > altcoin accounts > add new account screen. 

<img width="634" alt="bildschirmfoto 2019-01-09 um 10 07 45" src="https://user-images.githubusercontent.com/170962/50894678-19fdd100-1404-11e9-8b1e-bdff68e10d79.png">

We could introduce the searchable comboboxes in:
- Markets > Offer book > Currency
- Markets > Trades > Currency

**Comment by ManfredKarrer** [comment]
Still relevant

**Comment by ripcurlx** [comment]
Still relevant
