### ISSUE TITLE
Vote result exception

### ISSUE THREAD

**Issue by alexej996** [bisq-network/bisq#2304]
I get a vote result exception when I open Bisq. There were no issues during vote reveal phase.

Here is the log file from that Bisq session:
[issue.log](https://github.com/bisq-network/bisq/files/2780715/issue.log)

**Comment by ManfredKarrer** [comment]
Yes I am aware of it. It is caused because the seed nodes have been very unstable at vote reveal time and voters had received different set of blind vote data from the network. 
Will fix the popup in next release, for now just close it, it has no further consequences beside that the vote period was invalid as there was no 80% majority who had the same p2p network data.

**Comment by ManfredKarrer** [comment]
Already fixed but not deployed in Binary.
