### ISSUE TITLE
Add export to csv feature for dao vote result screen

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2477]
It would be nice to have a export to csv feature of all the voting cycles with their results. It might be a bit tricky hwo to get it into a flat format as it is a tree structure (cycle has proposals, proposal has received votes,...).

**Comment by ManfredKarrer** [comment]
I would offer a 1000 BSQ bounty for any developer who can implemnet that.
A secondary goal is to have a determinisic data which we could easily compare between users to see if the vote result is 100% the same. So the file should not contain data specific to my own vote (as in the UI).

**Comment by ben-kaufman** [comment]
@ManfredKarrer I'll try to implement that this week.

**Comment by ben-kaufman** [comment]
I'm still thinking about how should this feature be implemented.
The problem is, as @ManfredKarrer noted, that the data is in a tree structure. This makes it difficult to output to a CSV file. I currently have a few ideas for possible implementations for this feature.

1. Export a separate CSV file for each data structure. This means that we will have a CSV file of all the cycles, a different CSV file of all the proposals etc. This is probably the simplest solution as most of the code for needed for that already exists. The problem is that the data is separated into multiple files.

2. Export all data into a single CSV. There are multiple ways we could export all the data into a CSV (e.g. Like with solution 1 but in a single file, Have all cycles proposals under cycle row and all votes under each row of a proposal). This is very messy in my opinion but can be done.

3. Export all data into as a JSON file, as suggested by @blabno on the Slack chat. JSON would be much easier here as it supports complex data structure as we have here. I think this would be the best solution but I'm not sure if it would be fine not to use the CSV format as specified in the issue.

@ManfredKarrer do you (or anyone else) have any thoughts on how this feature should be implemented?

**Comment by ManfredKarrer** [comment]
@ben-kaufman 
I agree that the JSON option sounds like the best one. People can choose then toold for converting it further if needed. A main goal is to get a easy to share data structure for checking data consistency between peers. I will work on other more low level tools for that as well (hash chains) but to have a simple text format based output would be good to have.
