### ISSUE TITLE
Various issues with ZOC asset + ZOC/BTC market

### ISSUE THREAD

**Issue by deadthings** [bisq-network/bisq#2493]
Since a recent update, ZOC no longer appears in BTC pair list at https://bisq.network/markets/ and the market page at https://markets.bisq.network/?market=zoc_btc appears to no longer exist. 

If I attempt to edit an existing order in the ZOC/BTC market, I get "Error: No value present." 

Application reports 0 offers despite the obvious presence of >0 offers, as per screenshot:

![image](https://user-images.githubusercontent.com/33961641/53702844-6ef10e80-3dd9-11e9-9aa2-1570c923f0bd.png)

Log file attached. 

[bisq.log](https://github.com/bisq-network/bisq/files/2923760/bisq.log)

**Comment by ghost** [comment]
ZOC has been removed in the last release 
see -> https://bisq.network/roadmap/
(probably due to insufficient trading)

You see it still in your instance probably because you have selected it from the `add altcoin` list when it was still available, but other users who didn't add it don't see ZOC anymore in v0.9.4+ (at least, that's the case for my instance).
