### ISSUE TITLE
UI: allow to copy address and txid from the lists

### ISSUE THREAD

**Issue by Talkless** [bisq-network/bisq#2495]
"Funds" tab shows addresses and transaction ids in various places, and allows to view them in external explorer (in blockstream at the moment) by clicking with mouse.

It would be nice to have "copy to clipboard" button or other mean to copy that text and use your own local node/explorer to check these addresses and transactions for better privacy.

Or is there a way to copy them already? At least RMB (no popup menu), hover & ctrl+c guesses did not produce required result (on KDE, Debian Buster).

**Comment by ripcurlx** [comment]
If you click on this kind of a link you can decide how you want to handle it. In your case you shouldn't click on `Open the webpage and don't ask again`.
![bildschirmfoto 2019-03-07 um 15 48 17](https://user-images.githubusercontent.com/170962/53965039-bd135400-40f0-11e9-860e-4fd4b5884e22.png)

You can reset your local setting by clicking on Settings > Preferences > Reset all "don't show again" flags.
![bildschirmfoto 2019-03-07 um 15 50 02](https://user-images.githubusercontent.com/170962/53965086-d1575100-40f0-11e9-965a-84c9a6d66956.png)
After that you can always copy the link instead of opening your default explorer.

**Comment by ripcurlx** [comment]
Closing this issue, as the requested feature already exists.

**Comment by Talkless** [comment]
> Settings > Preferences > Reset all "don't show again" flags.

Ooh.. True, thanks!
