### ISSUE TITLE
Bisq IOS notification app stuck on Pairing

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/bisq#2496]
I am trying to pair Bisq to the IOS notification app installed on iPhone X, but it remains stuck in the pairing screen, the only options I have is "Pair" or "Learn more".  I can go into those two options, but I cannot get out of there.  

I sent the token to myself by email, I pasted it into Bisq (installed on Windows 7 professional 64 bits), but nothing happens on the IOS app.

When I receive a notification and try to open it, I get an error "Could not Decrypt"

I´ve reinstalled the app on my iPhone but that didn´t solve the problem

**Comment by ripcurlx** [comment]
@joachimneumann Do you have an idea what is going wrong?

**Comment by mpolavieja** [comment]
I reinstalled the notificacion app today and I finally got it paired with Bisq.   But I keep getting the error "Could not Decrypt" when receiving price/offer alerts.  I haven´t received any trade notification yet, so I don´t know if the "Could not decrypt" error is showing for those notifications as well.  As soon as I receive one I´ll update here.

**Comment by ripcurlx** [comment]
@mpolavieja Does it work for your in the meantime already?

**Comment by qx4p** [comment]
After pairing I'm also stuck with the error "COULD NOT DECRYPT".
(iPhone SE, IOS13.3)

**Comment by mpolavieja** [comment]
> @mpolavieja Does it work for your in the meantime already?

Sorry, I missed the notification of this thread.   It worked for me for trade notifications.  I never got to work price notifications.

By the way, since a month ago or so, something weird is happening.  When I receive a trade event, I recieve the notification in my mobile, but when I click into the Bisq app, the details of the notification are not there.

**Comment by ripcurlx** [comment]
> By the way, since a month ago or so, something weird is happening. When I receive a trade event, I recieve the notification in my mobile, but when I click into the Bisq app, the details of the notification are not there.

Did you try to re-pair again? Just in case there was an issue during decryption.

**Comment by ripcurlx** [comment]
> After pairing I'm also stuck with the error "COULD NOT DECRYPT".
> (iPhone SE, IOS13.3)

Could you please post a screenshot of this error?

**Comment by ripcurlx** [comment]
@joachimneumann Could you help out on this issues?

**Comment by qx4p** [comment]
@ripcurlx here's a screenshot from 2 weeks ago:
![IMG_1276](https://user-images.githubusercontent.com/46604348/75096722-a2a4e580-55a2-11ea-9c4b-6b5b0f9624f0.PNG)
I paired it again today and now it seems to work:
![IMG_1318](https://user-images.githubusercontent.com/46604348/75096753-f0215280-55a2-11ea-95e1-2d78ae9a1cd1.PNG)

**Comment by brainharrington** [comment]
Also having trouble getting iphone app paired.

- Clicked pair
- No web cam, send token
- Send email
- Copy paste in code
- Get initial notification immediately but no details, it just says Bisq notification

Then past that nothing happens inside the iphone app, I just exit out of the QR code screen and I'm back at the initial screen where the only buttons are pair and learn more.

**Comment by caldwyn** [comment]
Maybe problem with localization... I switched to English version and in log there are still Czech titles ("americký dolar" instead of "US dollar").

My app is paired successfuly, but never received any notification (trade alert, price alert, offer alert), except the first that confirms pairing.

Log says:
čvn-22 15:07:43.577 [JavaFX Application Thread] ERROR b.c.n.a.p.PriceAlert: Your price alert got triggered. The current americký dolar price is 20280.80 BTC/USD 
čvn-22 15:07:43.578 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: Send message: 'Your price alert got triggered. The current americký dolar price is 20280.80 BTC/USD' 
čvn-22 15:07:43.578 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: sendMessage message=MobileMessage(sentDate=1655903263577, txId=, title=Price alert for americký dolar, message=Your price alert got triggered. The current americký dolar price is 20280.80 BTC/USD, mobileMessageType=PRICE, type=PRICE, actionRequired=, version=1) 
čvn-22 15:07:43.579 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: json {"sentDate":1655903263577,"txId":"","title":"Price alert for americký dolar","message":"Your price alert got triggered. The current americký dolar price is 20280.80 BTC/USD","type":"PRICE","actionRequired":"","version":1} 
čvn-22 15:07:43.580 [JavaFX Application Thread] ERROR b.c.n.a.p.PriceAlert: java.lang.Exception: [encrypt] Input length not multiple of 16 bytes

**Comment by devinbileck** [comment]
There have been several releases published to the Apple app store since this ticket was opened that should hopefully address the original issue. Therefore, I will assume this ticket can be closed. @ripcurlx please!

@zdick I see that you created a separate ticket for your issue. Thanks!
