### ISSUE TITLE
Invalid rate for btc/xdr

### ISSUE THREAD

**Issue by vlad-khramov** [bisq-network/bisq#2503]
![image](https://user-images.githubusercontent.com/1215671/53893765-e7590900-403f-11e9-8677-ab5590e0806f.png)

xdr/btc is 2768. It is wrong. Must be btc/xdr = 2768  (1 xdr ~= 1.39)

For example see https://www.coingecko.com/en/coins/bitcoin/xdr

--
Orders with XDR couldn't be created since difference with this rate > 30%

**Comment by ghost** [comment]
@quantum13 
yes there seems to be a problem with this price.
(I can't even find XDR on poloniex.com)

**Comment by vlad-khramov** [comment]
0.9.5

**Comment by ripcurlx** [comment]
If I start in locally on Regtest I actually see `N/A` which is correct as Poloniex doesn't deliver a price ticker for this altcoin. On Production I get from the pricenodes the wrong value as mentioned above.

@ManfredKarrer Do you have an idea how the price node gets this ticker if Poloniex doesn't return anything?

**Comment by ghost** [comment]
Something is provided, since 
eg http://5bmpx76qllutpcyp.onion/getAllMarketPrices
returns a XDR field.


180 |  
-- | --
currencyCode | "XCP"
price | 0.00042221
timestampSec | 1551969634894
provider | "POLO"
181 |  
-- | --
currencyCode | "XDR"
price | 2772.27
timestampSec | 1551969455149
provider | "BTCA_G"

but it's not from Poloniex.

(I guess BTCA_G means BitcoinAverage ?)

I notice that the field #180 is XCP, provided from Poloniex, and which seems delisted. (neither in the display altcoins list, neither in the add altcoin list).
Maybe there is some slippage between the 2 ?

**Comment by ripcurlx** [comment]
The problem is that the PR for XDR didn't comply with https://docs.bisq.network/exchange/howto/list-asset.html#the-asset-ticker-symbol-must-not-conflict-with-national-currency-tickers.

There is a fiat currency with the same currency code XDR (https://en.wikipedia.org/wiki/Special_drawing_rights). 

So the PR shouldn't have been merged in the first place.

**Comment by ManfredKarrer** [comment]
xdr has to be removed as it conflicts with our requirements.

**Comment by vlad-khramov** [comment]
@ManfredKarrer I will create PR for renaming XDR to something else, sorry

**Comment by ManfredKarrer** [comment]
https://bitcoinaverage.com/en/bitcoin-price/btc-to-xdr
