### ISSUE TITLE
The Bisq wallet doesn't take into account all funds

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2585]
I've loaded the Bisq wallet's seed word into Electrum and I've been experimenting with its better output control to split the outputs when funding the Bisq wallet. Some of the outputs resulting from this process don't even show up on the Bisq wallet.

My Bisq wallet shows two different outputs available to be sent under the "Send" tab but when taking an offer it only recognizes on of them. Plus, when hovering the over the balances on the top right of the screen, the amount in EUR in the pop up is of "0.00 EUR" despite the BTC value being over 0.

I've deleted the SPV file and resynched to no effect.

**Comment by ManfredKarrer** [comment]
Can you check with cmd+e the balance displayed there?
If that is as expected the AddressEntryList file in the db folder is out of sync. You can try to delete that if you don't have open offer/trades/disputes. Otherwise its more safe to do that after all those are completed/closed. Make a backup before changing anything.

**Comment by huey735** [comment]
Thanks @ManfredKerrer, that worked.
