### ISSUE TITLE
Add replace-by-fee for trades

### ISSUE THREAD

**Issue by Sylo44** [bisq-network/bisq#2611]
As talked about in this Thread:
https://bisq.community/t/trade-stuck-at-wait-for-blockchain-confirmation/7318/7

Traders sometimes have problems getting their confirmations when the mempool is filled up again and especially newer users get anxious about their BTC and trades. Also when using trades with 24h or 1h windows people don't want to wait 24h+ just for the trade to start and could just increase their fee with the replace-by-fee option.

**Comment by ManfredKarrer** [comment]
RBF does not work as the tradeprotocol would require a re-negotiation with the peer. 

Bisq fee is on the higher end of the spectrum and we did not had issues since long, but currently if fee rise quickly it can be problematic.
The trade fee cannot be changed by the user, only the tx fee used for normal transfers.

Our fee: http://37.139.14.34:8080/getFees
Good estimation service: https://whatthefee.io/ 

I will close is as RBF is definitely not a solution but I am aware that its an open problem, just not one which can be fixed easily....
