### ISSUE TITLE
Why is gridcoin delisted but still being traded??

### ISSUE THREAD

**Issue by userzer0x** [bisq-network/bisq#2631]
Currently gridcoin is listed in a trade, however has been delisted. I dont understand how a user can still trade this if its been delisted...
![gridcoin](https://user-images.githubusercontent.com/44409182/55518434-5728d680-5674-11e9-9db9-64c100b9a719.png)
Possible to re-list this then?

**Comment by ghost** [comment]
It is not a trade, it is an offer.
And it is only seeable in the Market/spread tab.
It is not seeable in the Market/Offer tab. At least on my PC.

The devs know this issue (-> https://github.com/bisq-network/bisq/issues/2518 )
But there are higher priority issues to solve before.

If GRC has been delisted due to insufficient trading, wanting traders will have to wait for the DAO launch (possibly this month) in order to relist it.

**Comment by ripcurlx** [comment]
Closing as complete based on https://github.com/bisq-network/bisq/issues/2631#issuecomment-479788005. Feel free to reopen if there is an ongoing problem.
