### ISSUE TITLE
wallet restore

### ISSUE THREAD

**Issue by purpurato** [bisq-network/bisq#2640]
I am trying to restore a wallet from seed but cannot send funds to another wallet. Attached the log 
[bisq.log](https://github.com/bisq-network/bisq/files/3044204/bisq.log)

**Comment by oscarguindzberg** [comment]
The log shows you have 0 btc balance on your wallet and you are trying to empty that wallet.
Could you confirm you don't have 0 btc balance?

**Comment by purpurato** [comment]
Yes, there are bitcoins on that wallet. I installed Linux a few weeks ago and forgot to save data from Bisq, however I got the seed, so i thought that could do the job.

**Comment by ManfredKarrer** [comment]
@purpurato Do you use the lastes Bisq version? If not install that and try again.

**Comment by oscarguindzberg** [comment]
1) Please, correct me if I am wrong, the problem is not at restore from seed but when you want to empty your wallet before doing a restore from seed, right?

2) do you plan to restore from seed to use a different wallet? Or the reason to use restore from seed is to fix the currently "broken" wallet?

**Comment by oscarguindzberg** [comment]
3. Could you go to Funds/Transactions screen and tell me whether all your txs are confirmed or not.

**Comment by purpurato** [comment]
My bad, I just checked transactions and see that wallet was emptied by myself. Forgive the inconvenience
