### ISSUE TITLE
v1.0.1 account > 365 days gets warning it is < 2 months

### ISSUE THREAD

**Issue by pickausername2001** [bisq-network/bisq#2755]
With 1.0.1 I noticed that I get warnings that my account (way older than 365 days) is not old enough to trade > 0.25 BTC and it needs to grow older than 2 months.
<img width="587" alt="bisq_foo" src="https://user-images.githubusercontent.com/49812028/56457620-d65d2080-637d-11e9-8beb-9de5d38d1192.png">

**Comment by alexej996** [comment]
I am not sure what the limit is for fiat accounts when they are older then 2 months.
Either way the pop up is misleading since it sounds like it is saying all restrictions are removed after 2 months, which is not the case. All accounts have trading limits which change all the time with new releases.

**Comment by ManfredKarrer** [comment]
Thats an issue as we had 0.5 BTC before as limit so an offer with 0.2501 was valid. Not the trade limits have been reverted to the older limits of 0.25 and that offer cannot be taken. Hope the maker will remove it...
