### ISSUE TITLE
Using IPFS in bisq

### ISSUE THREAD

**Issue by 0zAND1z** [bisq-network/bisq#2845]
Great progress has been made on bisq so far & I am very much eagered to see the full DAO functionalities on the bitcoin blockchain.

In this regard, I think its important to re-consider how to handle the knowledge sources for the DAO. 

Hence, I am requesting the community to consider the following applications of IPFS in the bisq network, especially from a DAO perspective:
1. Moving the [bisq binaries from GitHub](https://github.com/bisq-network/bisq/releases) to IPFS
2. Moving the [documentation](https://docs.bisq.network/dao.html) to IPFS
3. Move the [Network Stats](https://bisq.network/markets/)  data to IPFS
4. Move the entire [bisq.network website](https://bisq.network/) to an IPNS (published to the same DNS)
5. Move any [governance related documents](https://docs.bisq.network/dao-user-reference.html#bisq-dao) such as proposal data, voting results, MoM etc. on IPFS

It would be great if we can share our thoughts & come up with more ideas, and derive the best out of IPFS. Looking forward to all your thought, thanks.

**Comment by sqrrm** [comment]
I like it. In particular I think the proposal data for the DAO that's currently hosted on github would benefit. If that's lost it won't be possible to follow the reasoning behind the historical DAO votes.

**Comment by 0zAND1z** [comment]
@sqrrm , thanks for the input. I have revised point number 5.

**Comment by JotaPe** [comment]
That's a great idea to make Bisq even more decentralized, it's a good measure for future, if using a DEX or making a DEX becomes illegal all work will be already saved in a decentralized file system that is IPFS.

**Comment by 0zAND1z** [comment]
@JotaPe , thanks for your observation!

Please feel free to share this to many more in the community.

I am welcoming all sorts of inputs from everyone.

**Comment by reipichu** [comment]
I would like to add a few words of caution about relying too heavily on IPFS for hosting files that are critical to the Bisq project and the DAO, particularly concerning the assumption that it would be a solution to future censorship:

* IPFS does not guarantee durability[1]. It requires "pinning" of data on nodes for the data to be consistently available, which would mean hosting our own IPFS nodes to ensure the data is pinned, or paying a pinning service to make the data available continually. 
* IPFS is not built to be censorship resistant[2]. There is already a DMCA blacklist[3][4] which IPFS nodes can optionally subscribe to, to prevent them from serving or relaying copyrighted content that has been served DMCA takedown requests. The fact that this functionality is already built in to the network means that there is no guarantee that any other type of data might not be censored in future (such as crypto-related services) if a hostile government were to crack down on services hosting such data.
* IPFS is not designed to preserve anonymity[5]. Anonymity is very closely related to censorship resistance, since without it a censor can target the identified users who are requesting the censored materials. Even if you publish data to IPFS through an anonymizing network transport (Tor), the users requesting the data still need to know to protect their own anonymity in order to protect against a censoring government[6].

I am not opposed to the idea of using IPFS as a backup in case the centralized services we use decide to censor the project, but it would be best as a mirror rather than a primary copy, in my opinion. We should also work on the conservative assumption that if our centralized services (GitHub, DNS registrar, web hosts etc.) decide to censor the Bisq project, that censorship on IPFS will be the next risk to address.

[1] https://docs.ipfs.io/guides/concepts/pinning/
[2] https://github.com/ipfs/faq/issues/36#issuecomment-140567411
[3] https://github.com/ipfs/community/blob/master/code-of-conduct.md#copyright-violations
[4] https://github.com/ipfs/refs-denylists-dmca
[5] https://github.com/ipfs/faq/issues/18#issuecomment-96303862
[6] https://github.com/ipfs/notes/issues/281#issuecomment-370594779

**Comment by 0zAND1z** [comment]
@reipichu , thanks. You have made valid observations.

Before I address them, let me expect some more thought by the community members & I will surely revert on your inputs.

**Comment by JotaPe** [comment]
> I would like to add a few words of caution about relying too heavily on IPFS for hosting files that are critical to the Bisq project and the DAO, particularly concerning the assumption that it would be a solution to future censorship:
> 
> * IPFS does not guarantee durability[1]. It requires "pinning" of data on nodes for the data to be consistently available, which would mean hosting our own IPFS nodes to ensure the data is pinned, or paying a pinning service to make the data available continually.
> * IPFS is not built to be censorship resistant[2]. There is already a DMCA blacklist[3][4] which IPFS nodes can optionally subscribe to, to prevent them from serving or relaying copyrighted content that has been served DMCA takedown requests. The fact that this functionality is already built in to the network means that there is no guarantee that any other type of data might not be censored in future (such as crypto-related services) if a hostile government were to crack down on services hosting such data.
> * IPFS is not designed to preserve anonymity[5]. Anonymity is very closely related to censorship resistance, since without it a censor can target the identified users who are requesting the censored materials. Even if you publish data to IPFS through an anonymizing network transport (Tor), the users requesting the data still need to know to protect their own anonymity in order to protect against a censoring government[6].
> 
> I am not opposed to the idea of using IPFS as a backup in case the centralized services we use decide to censor the project, but it would be best as a mirror rather than a primary copy, in my opinion. We should also work on the conservative assumption that if our centralized services (GitHub, DNS registrar, web hosts etc.) decide to censor the Bisq project, that censorship on IPFS will be the next risk to address.
> 
> [1] https://docs.ipfs.io/guides/concepts/pinning/
> [2] [ipfs/faq#36 (comment)](https://github.com/ipfs/faq/issues/36#issuecomment-140567411)
> [3] https://github.com/ipfs/community/blob/master/code-of-conduct.md#copyright-violations
> [4] https://github.com/ipfs/refs-denylists-dmca
> [5] [ipfs/faq#18 (comment)](https://github.com/ipfs/faq/issues/18#issuecomment-96303862)
> [6] [ipfs/notes#281 (comment)](https://github.com/ipfs/notes/issues/281#issuecomment-370594779)

Really valid points, the IPFS is a protocol, some people are already trying to push some software to make it more secure and anonymous like using I2P gateways and TOR gateways too.

**Comment by 0zAND1z** [comment]
Hey guys, what can we do to keep this warm?

**Comment by 0zAND1z** [comment]
I would like to contribute as much as I can. Any plans before that would be nice.

**Comment by ghost** [comment]
Copy/paste of material to an onion site may be a good first step ?
