### ISSUE TITLE
"java.lang.NullPointerException" when opening up Bisq

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/bisq#2883]
java.lang.NullPointerException

[bisq.log](https://github.com/bisq-network/bisq/files/3273138/bisq.log)

It had been a day or two since I closed Bisq and this occurred on my first attempt at reopening the app.

It seemed to be syncing the blockchain and taking a little longer than usual.

**Comment by sqrrm** [comment]
I'm unable to reproduce, but it's not a serious issue, just looks ugly and makes the experience worse. Would be nice to figure out why it happens. Could be a Windows specific issue. Might be related to #2885

```
        root.getScene().heightProperty().addListener(sceneHeightListener);
        UserThread.execute(() -> updateTableHeight(root.getScene().getHeight()));
```

The exception happens on the second line there, which is strange considering the scene was found in the line before.

**Comment by devinbileck** [comment]
Had your computer just gone to sleep prior to receiving this exception?
That is what I assume happened looking at the log just prior. In particular these lines:
```
Jun-10 12:32:07.144 [JavaFX Application Thread] INFO  b.common.Clock: We have been in standby mode for 402 sec 
Jun-10 12:32:07.176 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: onAwakeFromStandby 
```

**Comment by Mycelial1** [comment]
Seems like it happened after closing my laptop and going into standby, and then reopening the laptop. My laptop uses a remote viewer to connect to my bisq app btw.

**Comment by UnityJon** [comment]
I'm not a java programmer (C/C++/C#) but the brackets look very suspect in that 2nd line.  Instead of 
execute(() -> update
I suspect it should be:
execute() -> update
with one less close bracket on end of line.  Rather than running execute() on the selected thread it would seem to be trying to pass ().execute (i.e. running execute on null) as a parameter.  But as I said I'm a C/C++/C# programmer so am guessing.  Was only looking as I have a similar (but in different place) error.

**Comment by freimair** [comment]
@UnityJon Java lambdas...
