### ISSUE TITLE
How to deal with (potential) scammers?

### ISSUE THREAD

**Issue by spogulis** [bisq-network/bisq#2911]
Yesterday and today I've received three warnings for when a person named Andreas Friman decided to take my Buy order. 
[REMOVED by @ripcurlx because of potential privacy issue]

Notice that this person's bank is in the Netherlands. Today a person with the same name from Lithuania successfully took my offer but, considering the previous warnings, I don't want to send him the money. How does one cancel and blacklist such potential fraudsters?

Onion address of the new user:
[REMOVED by @ripcurlx because of potential privacy issue]

Btc seller payment details: [REMOVED by @ripcurlx because of potential privacy issue]

**Comment by ripcurlx** [comment]
@spogulis Thanks for reporting! I removed the account details of the new account from LT because of privacy reasons. Just to be sure that we are not black listing the real "Andreas Firman": Could you please open a dispute so the arbitrator can contact the other party to make the decision for black listing.
