### ISSUE TITLE
Wester Union restricted to the same country

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#2922]
**Ricardosaurio** ([from this thread on bisq.community](https://bisq.community/t/western-union-in-the-same-country-only/7941/2)) found this message when creating a Buy offer and it seems to imply that only traders on the same country as them can accept the trade which doesn't make sense to me. Is this a glitch or is it intended this way?
![image](https://bisq.community/uploads/default/original/2X/d/d6d1afac258b04f3f860c5c03af38ae3dfabafe2.jpeg)

**Comment by huey735** [comment]
Still relevant
@sqrrm @ripcurlx  @battleofwizards

**Comment by mpolavieja** [comment]
I have the same problem.  I have posted an offer in BTC-USD market with western union as payment method and it seems it can only be taken from my country (Spain - ES).

**Comment by huey735** [comment]
Still relevant
@sqrrm @ripcurlx

**Comment by mpolavieja** [comment]
Maybe the offer can really be taken by anyone, but it works as a warning for the taker that the Western Union payment fees are going to be more expensive if the offer is from a foreign country?

**Comment by huey735** [comment]
@mpolavieja that doesn't seem to be the case. The pop up window shows the following message:
> To take this offer, you will need to set up a payment account using this payment method.
> Would you like to do this now?

**Comment by m52go** [comment]
Hypothesis is that this is an unnecessary limitation in Bisq. To test it, we're having someone create a Western Union account outside of Spain (but set as Spain and USD within Bisq), take the offer, and then try to complete the transfer. Will report results when available, should be in the next couple of days.

**Comment by huey735** [comment]
@m52go I've tried a similar scenario and the problems seems to lie with Bisq.

**Comment by m52go** [comment]
> I've tried a similar scenario and the problems seems to lie with Bisq.

Yes, this seems to be the case, as the transfer went fine. 

Feedback from this experience indicate the following:

- there is no need to specify receiver's city, just country
- there should be no need to specify currency in the payment account, since the whole point of Western Union is to work internationally regardless of currency
  - exception: countries with currencies in which Western Union has no presence in (a list should be made; but I assume most major countries are included)
  - it's possible users in some countries might not want to send money to users in certain other countries...in this case, country is already being specified in the payment account, and the offer taker can see it before accepting the offer. there should be no reason to completely block traders in different countries from taking western union offers.
- the trade protocol for Western Union currently requires payment sender to _email_ a copy of the receipt to the receiver...surely this can be changed, since trader chat is now available?
- fees are stupid high, obscene, and exorbitant (all at the same time)

With that said, Western Union's online bank-to-bank service seems to have a totally different fee structure (much more reasonable), and it might have potential as a new payment method...will investigate it over the next few days and open a new thread if it's worth adding to Bisq.

**Comment by huey735** [comment]
>there should be no need to specify currency in the payment account, since the whole point of Western Union is to work internationally regardless of currency 

Surely, there needs to be a currency for the offer to be priced in. right?

>there should be no reason to completely block traders in different countries from taking western union offers.

Sanctions may be relevant here. I'm not very knowledgeable here though.

**Comment by m52go** [comment]
> Surely, there needs to be a currency for the offer to be priced in. right?

Yes, bad wording on my part -- what I meant was, it makes sense to specify a currency, but not to require that both taker and maker use the same currency (or to require that they be in the same country, or in any particular country), as is the case right now.

> Sanctions may be relevant here.

Yes again -- sanctions are primarily what I had in mind. Maker country should be shown in offer details, so taker can evaluate if sending money to maker's country is acceptable to them before taking the offer. But again, as indicated above, this shouldn't be a determination the software makes for the user.

**Comment by fubyo** [comment]
This is relevant.

**Comment by pazza83** [comment]
Hi @fubyo, @huey735 and @m52go I think this issue is now being addressed here: https://github.com/bisq-network/bisq/issues/5498
