### ISSUE TITLE
Error Message: The change output of 5.45 BSQ is below the min. dust value of 5.46

### ISSUE THREAD

**Issue by ctonbton** [bisq-network/bisq#2960]
I got this message when trying to buy BTC using BSQ to pay for fees.
My current 5.49 BSQ balance will fall to 5.45 if I was allowed to spend .04 BSQ on the fees.

So is this an error? The text in the window said to report this "bug".
It would make sense that I may not be able to withdrawl the dust of 5.46BSQ  but all I'm trying to do is pay for fees using BSQ. Is this not allowed or an error?

No matter what your balance has to remain above 5.46 BSQ in order to do anything?... Pay for fees, withdrawl, vote?

So am i forced to go buy more BSQ in the Altcoins market if just make sure I never go below 5.46 BSQ if all I really want to do is use the BSQ to pay for fees .03-.05 at a time?

Sorry for second Issue request in a few days.  Everything was going well up to this past week  - now two separate issues.

Thanks for any help or input!!!
![1](https://user-images.githubusercontent.com/34559154/61176589-ed7c6a80-a588-11e9-8fe0-7fc1fd38d535.jpg)

**Comment by sqrrm** [comment]
546 satoshi is the dust limit, that is 5.46 BSQ. That means a transaction with an output of less than 546 satoshi won't get propagated or mined. So what you say is correct, you need to have more than 5.46 BSQ left after paying for fees. This is a result of BSQ being a colored coin on top of Bitcoin.

I realize that's quite annoying, especially in your situation right now. Probably would be a good idea to make that more obvious.

You can still send the last 5.46 BSQ to someone else to sell if you want since the output is then more than the dust limit.

**Comment by ctonbton** [comment]
Got it... So i will buy more BSQ.
Thanks for the clarification!
