### ISSUE TITLE
portfolio open trades tab java fails

### ISSUE THREAD

**Issue by sr2darren** [bisq-network/bisq#2962]
pending trades can not be viewed, nor support ticket opened on any trades
[bisq.log](https://github.com/bisq-network/bisq/files/3389915/bisq.log)

**Comment by a123b** [comment]
Download, install and run "Bisq-cleanup-trades" from [here](https://github.com/bisq-network/bisq/releases/tag/v1.1.3). After that, upgrade to the regular Bisq v1.1.3. This should fix your issue.

**Comment by sr2darren** [comment]
Of course I downloaded the 1.1.3 before I saw this email, hoping it would
resolve the issue. I then ran the trade cleanup, and started 1.1.3 again,
but the issue is still there. Any idea on how to fix it now that I’ve gone
out of order, or is my punishment Bisq death? Thanks for the hand holding
in any event.

**Comment by a123b** [comment]
It shouldn't be a problem that you updated before running the cleanup... Maybe your issue wasn't even caused by the bug this cleanup build is intended for, but is just very similar.

Would you do the following to help with debugging?
* Rename/delete your current bisq.log file
* Start Bisq and go to the Open Offers tab
* Stop Bisq
* Rename the bisq.log to bisq-pending-tab.log
* Start Bisq and go to the Support tab
* Stop again and rename the log to bisq-support-tab.log
* Make screenshots of how the broken tabs look like

Log files specific to each tab's error might make it easier to find the issue!

**Comment by sr2darren** [comment]
Attached, hope this helps!

[image: image.png]

[image: image.png]

**Comment by freimair** [comment]
@sr2darren ahm the images do not show on github. Can you respond via the github website and up drag and drop the images here?
