### ISSUE TITLE
Improve BSQ block requests

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#3094]
Currently we request BSQ blocks from only one seed node. If it fails there is a rather long timeout until we try the next. In case a Bisq node does not receive a new block (after initial parsing is completed) there is currenttly no mechanism in place to request missing blocks and the user has to restart. 
We should look into strategies how to get the initial block request more reliable and resiliant as well as to repeat requests in case we are not on the chaintip with our BSQ blocks.

Another open issue is that in case of a resync from genesis is triggered, the node only receives max. 6000 blocks as that is the limit a seednode provides (ddos protection). At the moment there is no mechanisma for repeating the call so that the missing blocks are requested again and to be able to get to the chain tip. A restart is atm required to get the rest of the blocks. We should add a request from another seednode for the missing blocks once the parsing of the first 6000 blocks is done.

The parsing must not be interrupted, so we need some smart handling of parallel received data and handling of yhe data deltas.

**Comment by freimair** [comment]
> Currently we request BSQ blocks from only one seed node.

it is quite hard to change that behavior, because we only request "from blockheight" (without "until blockheight"). So if we query multiple seednodes at the same time, we create a much higher network load

> If it fails there is a rather long timeout 

There is one or more bugs hiding in the code. This is what I found until now (for documentation purposes):
if the first attempt fails, the retry timer engages. there are different possible outcomes:
- if the desired connection already exists
   - everything works as expected -> rarely
   - although we get the data we asked for, the retry timer keeps on going -> more often
- a new connection has to be created
   - it tends to not have the required capabilities

**Comment by chimp1984** [comment]
The problem to not received BSQ blocks still exists. Just saw it today again.

**Comment by ghost** [comment]
Experienced this today in support.  User reported their DAO rebuild stopped syncing without any feedback.  Upon restarting Bisq the resync would start but eventually stall again.  Logs revealed that it was downloading blocks from a seednode, then after some time it would get disconnected and a connection would be made to a new seednode.  After 3 such disconnects it would simply give up with the log message "We tried 4 times but could not connect to a seednode".

https://github.com/bisq-network/bisq/blob/d0e88f7e2a63ca4dfd75c757c79deaa5be5c845e/core/src/main/java/bisq/core/dao/node/lite/network/LiteNodeNetworkService.java#L354-L358

I propose removing the MAX_RETRY limit and change the retry backoff time to `(retryCounter * RETRY_DELAY_SEC)` so that the subsequent seednode connection attempts get further and further apart, much like how login screens increase the time before you can make another attempt at entering your password.
