### ISSUE TITLE
Incorrect account age used for trade amount limititation

### ISSUE THREAD

**Issue by littlebit2big** [bisq-network/bisq#3247]
I hope I'm in the right place. I tried in Slack and Bisq forum first but keep getting referred here. 

I'm getting an error message regarding trade amount limitation based on <2 months old which contradicts the actual age of my account which is displayed in the same message box.

v1.1.5

![Trade Limit and Account Age Error](https://user-images.githubusercontent.com/49798544/64723208-0d9fab80-d49e-11e9-99a0-ce615ecd7895.png)

**Comment by wiz** [comment]
What payment method is this?

**Comment by niyid** [comment]
Is the 2 month restriction period a blanket rule or does the period vary depending on the payment account?

I also noticed the extra "days" already handled by formatted account age in resource bundle key: **`offerbook.warning.tradeLimitNotMatching`**.

Who is assigning?

**Comment by tc1176** [comment]
Same problem: https://www.reddit.com/r/bisq/comments/e5s86s/huh/

v1.2.3

**Comment by sqrrm** [comment]
@Sethadon Since March of 2019 the limit for buying using most fiat methods has been 0.01 BTC. This change hasn't been reflected in all the popups and warnings.

With the 1.2.0 release there is a signing mechanism to raise the limits for buying BTC with fiat. After doing a successful buy trade with a counterparty that's a signer your account will get signed and 30 days later the limits will increase.

@littlebit2big For this particular issue it looks a bit strange if this is a fiat trade. Maximum for fiat trades is 0.25 BTC so the 0.49 BTC indicate it's probably an altcoin trade. The warning looks strange, that account should have a 2 BTC limit.

**Comment by rafaelpac** [comment]
PR #3847 fixed that, this can be closed.

**Comment by rafaelpac** [comment]
> 
> 
> Is the 2 month restriction period a blanket rule or does the period vary depending on the payment account?
> 
> I also noticed the extra "days" already handled by formatted account age in resource bundle key: **`offerbook.warning.tradeLimitNotMatching`**.
> 
> Who is assigning?

This was fixed by #3804, but now the message is all changed to reflect the account signing protocol.
