### ISSUE TITLE
UI does not reflect transaction ID in case of a null value due corrupted trade data

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#327]
When making two test trades with another user both trades were given the same Deposit Transaction ID:

Trade 1:
![](http://i.imgur.com/yn22yBl.png)

Trade 2 (buyer's side):
![](http://i.imgur.com/F0xAYiB.png)

Trade 2 (seller's side):
![](http://i.imgur.com/NT5AYcP.png)

The first trade was made and we were waiting ages for the first confirm. We thought maybe this was going so slow as it had been paid from a web wallet so we created a separate trade. Both offers were made by the same user (User 1 - @btcll) and accepted by the same user (User 2). We were communicating during the process via IRC.

Please comment if more info is needed about this scenario.

**Comment by cbeams** [comment]
I've updated the description by embedding screenshots from buyer's and seller's sides.

**Comment by ManfredKarrer** [comment]
The first trade has missing data in the table, so that means that there was something wrong with that. I assume the UI just dont update the tx id as there is not data in the first trade, though need to be fixed, that the UI resets also in case of a null value the display fields. The error handling for a failed trade is currently only very partial implemented, that trade should never show up in the tabe but a error msg displayed. I will change the title to reflect that.
