### ISSUE TITLE
Show warning if user has a pruned Bitcoin node locally running

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3273]
BitcoinJ requires a non-pruned Bitcoin node. We get frequently issues that users who don't know that run into problems. We should find a way to detect if a local node is running in pruned mode and if so show a popup to tell the user to either shut down that pruned node and connect to the provided bitcoin nodes or change their pruned node to a non-pruned node. 
Related is that a Bitcoin node cannot be used while it is syncing with the network. Not sure if that can be detected.

If there is no way to detect pruned mode from Bisq (we cannot use RPC for that), we could use the special exceptions thrown in BitcoinJ to catch those and react on those to show a popup.

**Comment by acrual** [comment]
@chimp1984 not only detecting a prune node but also if the local node is not running itself. 
In my case I had chosen my local node, yet I had forgotten to start it. I didn't realize that was the problem until the bsq tx didn't get through

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by ripcurlx** [comment]
@dmos62 will be working on it.

**Comment by ripcurlx** [comment]
It would be also good to detect, if possible, if the bloomfilter configuration is set properly.

**Comment by dmos62** [comment]
@ripcurlx how do we want to handle misconfiguration of a local node? We can detect whether the local BTC node is well configured (not pruned and allows bloom filters) before initializing the wallet, i.e. there's no need to wait for an exception for example. Currently my idea is, if a bad local node is detected: disable its use, reverting to non-local setup, and display a pop-up explaining what happened. Sounds good?

**Comment by Kixunil** [comment]
@dmos62 reverting to non-local setup without user agreement doesn't sound good. Showing a popup with a button to switch would be much better.

**Comment by dmos62** [comment]
@Kixunil If all goes well I should start testing tomorrow, so I've not actually seen what happens when you use a pruned node for example. I was under the impression that a local node cannot be used if it's pruned or has bloom filters disabled. Am I wrong? If not, what would the button do? @ripcurlx could you provide some input?

My thinking was to show a popup in case of a detected, but misconfigured local node. I've not considered that we might need to give the user an option to not continue the setup in case he doesn't want to use non-local mode. Hm, gonna have to think about that one.

**Comment by Kixunil** [comment]
I mean a popup with text like "There's a problem with your node configuration. Your node is pruned."
And three buttons "Retry", "Quit Bisq" "Switch to a random public node"
Possibly even a button "Try reconfigure autoatically" which attempts to change bitcoind config if it's used in a well-known setup.

Retry is obviously useful, if the user fixed the configuration while the dialog was open.

**Comment by dmos62** [comment]
Good ideas. I'd be against "autoreconfigure", but the three other choices are spot on, I think. I'm trying to figure out how much refactoring will be required to be able to pause the setup.

**Comment by ripcurlx** [comment]
@dmos62 @Kixunil Yes, I think if we detect a misconfiguration of the local bitcoin core node we should prompt the user if she wants to continue with the default configuration (using nodes provided by Bisq core contributors, public network is deactivated atm completely because of the potential v0.19+ problem) or if the user wants to quit Bisq. I wouldn't do any autoconfiguration as you probably need more write permissions (different per OS) and I personally wouldn't allow any app to just write anywhere on my system. Retry is a nice-to-have but not a must IMO. So in the simplest implementation it would be a warning with the options `Continue` and `Quit`.

**Comment by Kixunil** [comment]
That's why I suggested "*Try* reconfigure automatically", just detect if it's one of the supported scenarios, if not, give up. If someone doesn't feel comfortable using the button/giving permission, just don't click the button. I agree that this is low priority feature. And `Continue` and `Quit` are must-have.
