### ISSUE TITLE
[UI] Update DAO launch popup

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq#3291]
![feediscount](https://user-images.githubusercontent.com/44140017/65156375-e6f5ed80-da26-11e9-8be2-c33d0910b1ed.png)

"Since fees have now been increased." @m52go 

Related: https://github.com/bisq-network/bisq-docs/pull/163 https://github.com/bisq-network/bisq/pull/2688 https://github.com/bisq-network/bisq/issues/2632

@ripcurlx

**Comment by m52go** [comment]
Yes, actually I think we could remove the whole box from the next release. It's fulfilled its purpose, no?

Otherwise, at a minimum, we should remove the [90% figure](https://github.com/bisq-network/bisq/blob/master/core/src/main/resources/i18n/displayStrings.properties#L2484):

```
popup.dao.launch.cheaperFees=Get a discount on trading fees when you use BSQ. Save money and support the project at the same time!\n\n
```

If we decide the latter, I can make a PR. Otherwise would be better for a developer to handle.

**Comment by freimair** [comment]
But there still is a discount isn't there?

**Comment by m52go** [comment]
Yes, but there are a couple of issues with the box itself.

- it was originally intended as an alert for existing users for the DAO launch; they have already seen it by now
- it makes the Bisq experience for new users even more complicated and overwhelming than it already is...all they wanted to do was buy some bitcoin, but now they have to learn about "governance"
- it promotes a new "token" and "DAO" which can sound scammy (this is from real feedback)

People will notice that BSQ fees are a lot lower every time they make/take offers:

![Screenshot from 2019-09-19 08-57-59](https://user-images.githubusercontent.com/735155/65245978-a1cfcb00-dabb-11e9-9e4e-e57826f07c12.png)

I'm not sure it's critical to tell them this the second they open Bisq for the first time.
