### ISSUE TITLE
Java Heap Space - Qubes

### ISSUE THREAD

**Issue by tapir1** [bisq-network/bisq#3343]
Version: 1.1.7 and 0.8.0
OS: Both Debian 9 and Fedora 30
RAM: Up to 4GB, initial set max to 2GB

Log: https://anonfile.com/X8Z2ed78n7/bisq_log

**Comment by ripcurlx** [comment]
Related to: #3128, #3657, #3918, #3917, #3787, #3786, #3686, #3677, #3343

**Comment by pabpas** [comment]
~~I was having this same issue in a debian10 qube until today. It was the first time that bisq finished parsing the DAO transactions since I use Qubes.~~

~~They only recent change I can recall is updating the dom0 kernel to 5.5.7-1 (from 4.19.100).~~

My previous comment can be ignored, I successfully synced a new bisq from scratch and the only requirement is to set Max Memory for the Qube to 6GB and make sure that you have enough memory free.

**Comment by cd2357** [comment]
I confirm this now works (even with max memory for the qube of 4 GB)

So I'd say this issue can be closed.

**Comment by chimp1984** [comment]
6GB should not be needed. 1-2 GB should be more then enough. I guess it is some JVM confirm issue with Qubes and some Linux versions (Arch users report often of those issues).

**Comment by chimp1984** [comment]
Can you try out the recommendations at https://github.com/bisq-network/bisq/issues/3918#issuecomment-607198677 ?

**Comment by cd2357** [comment]
@chimp1984 for Qubes, the memory reservation is for the entire OS + applications. I believe it also covers for video RAM, since Qubes has very basic graphics drivers.

If a Qube is setup with some RAM limit, and then if the qube reaches the limit, by default Qubes will "borrow" memory from other VMs (or from the unallocated dom0 RAM) and expand dynamically as necessary. However, to do this, it has a service that pings / checks / adjusts the memory allocation every second, which actually slows Bisq down according to my tests.

Turns out its better to disable this dynamic memory allocation and just set a high enough value for the entire qube, to cover OS + any service + any application (incl. Bisq).

After some experimentation, the settings in #4386 were the most stable and reliable for me. Also, increasing resources beyond that didn't improve Bisq performance (load times, UI responsiveness etc) so those values seem to be the sweet spot.

So for Qubes, I'd say 6GB (and with no dynamic memory mgmt) is probably the best option for a debian Qube that runs only Bisq.

Of course, would be great if others can test and verify this as well, on their setups.

**Comment by cd2357** [comment]
> My previous comment can be ignored, I successfully synced a new bisq from scratch and the only requirement is to set Max Memory for the Qube to 6GB and make sure that you have enough memory free.

Closing, as issue is now fixed for OP.

For more details about running Bisq on Qubes, see https://bisq.wiki/Running_Bisq_on_Qubes
