### ISSUE TITLE
Adding LBRY Credits $LBC to the platform

### ISSUE THREAD

**Issue by finer9** [bisq-network/bisq#3385]
Please fill in the following data to request for a new asset to be listed on Bisq. For more details, be sure to read [the full documentation](https://docs.bisq.network/exchange/howto/list-asset.html) on adding a new asset.

### 1. Asset name
LBRY Credits

### 2. Ticker
LBC

### 3. Block explorer URL
https://explorer.lbry.com

### 4. Additional technical requirements (yes/no)
no

### 5. Initial coin offering (yes/no)
no

**Comment by kauffj** [comment]
CEO of LBRY here. We have thorough documentation about LBRY available at [lbry.tech](https://lbry.tech). However, since our blockchain codebase is originally a fork of Bitcoin and Bitcoin APIs remain, this documentation is more to satisfy curiosity than necessary for implementation.

If you or anyone has questions, I am available at jeremy@lbry.com. Our CTO is @lyoshenka and our blockchain lead is @brannonking.

**Comment by lyoshenka** [comment]
We filed PR #3407 so this issue can be closed.

**Comment by finer9** [comment]
Closed as per @lyoshenka
