### ISSUE TITLE
my Bisq is no longer working, can't withdraw funds

### ISSUE THREAD

**Issue by marian001** [bisq-network/bisq#3462]
### Description

Recently my Bisq stopped working completely. I can start the application, but I can't trade because I'm unable to send funds to anyone and I can't withdraw my remaining balance.

#### Version

v1.1.7

### Steps to reproduce

When I try to sell some BTC and I accept an offer from another user, when I click 'Review: Take offer to sell Bitcoin', I get an error saying no funds have left my wallet etc..

### Expected behaviour

Expected behaviour is that some of my funds are locked until trade clears...

### Actual behaviour

When I try to sell some BTC and I accept an offer from another user, when I click 'Review: Take offer to sell Bitcoin', I get an error saying no funds have left my wallet etc..

In addition, when I try to withdraw funds to my wallet outside Bisq, the application seems to generate a transaction, but that is never visible on the blockchain. So my funds are locked in Bisq...

### Screenshots

screenshot of an attempt to withdraw account balance..

![Capture44](https://user-images.githubusercontent.com/6951694/67529043-4e086100-f6bb-11e9-8675-d12b3c17a33b.PNG)

#### Device or machine

notebook
windows 10

#### Additional info

NA

**Comment by marian001** [comment]
attaching bisq.log
[bisq.log](https://github.com/bisq-network/bisq/files/3769660/bisq.log)

**Comment by marian001** [comment]
attaching screenshot of failed trade
![Capture55](https://user-images.githubusercontent.com/6951694/67529257-e6064a80-f6bb-11e9-927c-1875a551801f.PNG)

**Comment by freimair** [comment]
> ### Steps to reproduce
> When I try to sell some BTC and I accept an offer from another user, when I click 'Review: Take offer to sell Bitcoin', I get an error saying no funds have left my wallet etc..

I understand that that is what the second screenshot you provided says. The "No funds have left your wallet" only says that even something went wrong, you have not lost any funds. **More interesting is the information about "Insufficient money".** Basically, you cannot take the offer because you cannot afford the fees. Please be aware of the trading fees (can be payed with BSQ) AND the transaction fees required for BTC.

That being said, are you sure that you have sufficient funds to do what you want to do? Furthermore, how many BTC addresses are in use (go to [Funds][Send Funds] to check) and do they have enough funds to pay the fees? Have you selected [Amount INCLUDES mining fees] in your efforts to retrieve funds?

might be loosely related to #3451

**Comment by wiz** [comment]
There is a bug which can prevent in-trade chat and support chat from working on bugged trades, so please join Bisq's #support channel on Keybase to communicate with arbitrators and developers directly.

**Comment by ripcurlx** [comment]
@marian001 Was your issue solved already by using a newer version of Bisq? Please re-open this issue if you are still having problems.
