### ISSUE TITLE
Deactivate power nap mode

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#351]
We want to avoid that network connections get dropped when OS goes to hibernate mode.
If we cannot prevent it, we should get an event from the OS to remove the offers.

Disable power nap mode for Mac:
/Applications/Utilities/defaults write io.bitsquare.Bitsquare NSAppSleepDisabled -bool YES
Adding an entry to Info.plist does nto work:
<key>NSAppSleepDisabled</key>
<bool>YES</bool>

Investigate how to disable it on mac and how it is handled on other OS.

**Comment by codeboost** [comment]
From what I've read, it's not possible for an app to disable the power nap - and it kind of makes sense, since it would suck if apps could stop your laptop from sleeping. 
If user wants his computer not to sleep, he has to do it from the Energy Saver app in the Mac System Preferences.

What we could do instead is to register for notifications from the OS and restart the networking when the computer wakes up. 

This is what you should do to receive these notifications (in Swift):

```
func applicationDidFinishLaunching(aNotification: NSNotification)
{
    NSWorkspace.sharedWorkspace().notificationCenter.addObserver(self, selector: "willSleep:", name: NSWorkspaceWillSleepNotification, object: nil);
    NSWorkspace.sharedWorkspace().notificationCenter.addObserver(self, selector: "didWakeup:", name: NSWorkspaceDidWakeNotification, object: nil);
}

func didWakeup(note: NSNotification)
{
    NSLog("Just woke up!");
}

func willSleep(note: NSNotification)
{
    NSLog("Going to sleep now");
}
```

**Comment by ManfredKarrer** [comment]
Thanks @codeboost!
When looking into activity monitor I see a few apps like Firefox which have disabled power nap. So I guess there might be a way to achieve it. 
Would be interesting as well how I can get those notifications (NSWorkspaceWillSleepNotification,NSWorkspaceDidWakeNotification) in java from the OS. Probably I  need to use native bindings.
Here someone seems to has found a method to turn off app nap: https://stackoverflow.com/questions/21688823/disabling-app-nap-in-java (https://github.com/shannah/Java-Objective-C-Bridge)

**Comment by ManfredKarrer** [comment]
Related to https://github.com/bitsquare/bitsquare/issues/358
