### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by tortugaverde98** [bisq-network/bisq#3538]
### Description
There is not appimage for bisq.

Without an appimage, the developers must create many different builds for the various versions of linux. With an appimage, only the appimage is required. See this example, note that the only option for Linux is an appimage:
https://electrum.org/#download

Go here for a quick overview:
https://github.com/AppImage/AppImageKit/wiki

One of the AppImage developers has expressed willingness to help developers create appImages, feel free to contact https://github.com/probonopd.

When there is an appimage I will be able to join the pool of Bisq users!

**Comment by dlalinsp** [comment]
This is a bit inconvenient for Linux users. Support for _any_ universal packaging format makes life a lot easier for both developers and end-users alike. Otherwise, maintaining different builds which support very specific distros leaves out a lot of other users. It is also more work for the development team. Please consider distributing Bisq as a Appimage/Snap/Flatpak.
