### ISSUE TITLE
Cannot buy BTC - Error message possiblePaymentAccounts.isEmpty()

### ISSUE THREAD

**Issue by trigger-xyz** [bisq-network/bisq#3663]
### Description

I wanted to accept a buy order to purchase BTC with euro, with payment method SEPA(IT).
When clicking on the button I have a popup with an error message telling :
possiblePaymentAccounts.isEmpty()

#### Version

V1.2.3

### Steps to reproduce

I just opened BSQ, went to "buy BTC" and clicked on "accept buy order"

### Expected behaviour

The "payment process" should start

### Actual behaviour

Popup with error, and then when I click again on the "accept buy order" button, nothing happens.

### Screenshots

![image](https://user-images.githubusercontent.com/10185784/69450625-e1d25900-0d5d-11ea-9c0f-d67c7d8f2b81.png)

#### Device or machine

Classic computer with a i7 7700k on Windows.

#### Additional info

It is the first time I try to use my SEPA account. I created it some days ago.

[bisq - Copie.log](https://github.com/bisq-network/bisq/files/3880887/bisq.-.Copie.log)

**Comment by p7996619** [comment]
Seems like the fix is already merged (#3625), but I'm also waiting since 1.2.3 release for a new one, as it basically prevents me from taking any interesting offers.

**Comment by incogneatoe** [comment]
Description: 
I am also having the same issue. When clicking on the "TAKE OFFER TO BUY BTC" button, there is a popup with an error message stating:
possiblePaymentAccounts.isEmpty()

Version:
V1.2.3

Steps to reproduce:
Open Bisq application, from top menu select "BUY BTC", and then click "TAKE OFFER TO BUY BTC"

Expected behavior:
The "payment process" should start.

Actual behavior:
Popup with error message stating "possiblePaymentAccounts.isEmpty()", and unable to proceed with the payment process. Then I exit back to the main "BUY BTC" page and attempt to click a different "TAKE OFFER TO BUY BTC" button, nothing happens with no error message, the page is stuck.

Device or machine
MacBook Pro MacOS 10.15.1, as well as, Toshiba PC laptop Windows 8.1

Additional info
Had a successful process the day prior, but since then, each attempt has had the same error message. Also, attempted this process on V1.2.2 and V1.2.3 with the same result.

**Comment by trigger-xyz** [comment]
I downloaded the last version of the code (future 1.2.4) and was not able to reproduce it. It seems fixed to me.
@incogneatoe @ForteUnited could you try ? Maybe when 1.2.4 is out .

**Comment by trigger-xyz** [comment]
I am closing the issue if OK for everyone ?

**Comment by ForteUnited** [comment]
yes Sent from Mail for Windows 10 From: trigger67Sent: Thursday, December 12, 2019 1:02 PMTo: bisq-network/bisqCc: ForteUnited; MentionSubject: Re: [bisq-network/bisq] Cannot buy BTC - Error message possiblePaymentAccounts.isEmpty() (#3663) I am closing the issue if OK for everyone ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ForteUnited** [comment]
> I am closing the issue if OK for everyone ?

yes

**Comment by rafaelpac** [comment]
Yes, I fixed it in PR #3625, which was merged and is effective since 1.2.4.

**Comment by trigger-xyz** [comment]
Fixed in v1.2.4
