### ISSUE TITLE
Compilation to native apps for Windows/Mac/Linux

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#37]

**Comment by ManfredKarrer** [comment]
Native app for mac working from intellij internal setup. needs testing for other os and better maven packaging tasks (exclude jvm)

**Comment by cbeams** [comment]
Superseded by #243.

**Comment by Brajendra** [comment]
Debian packages should specify a license.  The absence of a license will cause some linux distributions to complain about the quality of the application.
[fx:deploy] java.io.IOException: Cannot run program "fakeroot" (in directory "/tmp/fxbundler9106010369641330926/images/linux-deb.image"): error=2, No such file or directory
[fx:deploy]     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[fx:deploy]     at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:146)
[fx:deploy]     at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
[fx:deploy]     at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
[fx:deploy]     at com.oracle.tools.packager.linux.LinuxDebBundler.buildDeb(LinuxDebBundler.java:846)
[fx:deploy]     at com.oracle.tools.packager.linux.LinuxDebBundler.bundle(LinuxDebBundler.java:352)
[fx:deploy]     at com.oracle.tools.packager.linux.LinuxDebBundler.execute(LinuxDebBundler.java:898)
[fx:deploy]     at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:506)
[fx:deploy]     at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:471)
[fx:deploy]     at com.sun.javafx.tools.ant.DeployFXTask.execute(DeployFXTask.java:285)
[fx:deploy]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[fx:deploy]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[fx:deploy]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[fx:deploy]     at java.lang.reflect.Method.invoke(Method.java:497)
[fx:deploy]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[fx:deploy]     at org.apache.tools.ant.Task.perform(Task.java:348)
[fx:deploy]     at org.apache.tools.ant.Target.execute(Target.java:435)
[fx:deploy]     at org.apache.tools.ant.Target.performTasks(Target.java:456)
[fx:deploy]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[fx:deploy]     at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[fx:deploy]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[fx:deploy]     at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
[fx:deploy]     at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[fx:deploy]     at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:452)
[fx:deploy]     at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:139)
[fx:deploy] Caused by: java.io.IOException: error=2, No such file or directory
[fx:deploy]     at java.lang.UNIXProcess.forkAndExec(Native Method)
[fx:deploy]     at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
[fx:deploy]     at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[fx:deploy]     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[fx:deploy]     ... 24 more

BUILD FAILED
/home/india/Desktop/Demo/build/build.xml:208: Error: Bundler "DEB Installer" (deb) failed to produce a bundle.
