### ISSUE TITLE
Creating altcoin offer not throwing error during high security deposit

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3717]
### Description
creating altcoin offer with default security deposit percent not enabling 'Next step' option and not throwing any error also. 

#### Version
1.2.4

### Steps to reproduce
1. create altcoin (eth) offer from alice
2. fill 1 btc and let the default(50%) for security deposit.
3. Next step button not enabling as well as no error in any input boxes

### Expected behaviour
any one of error hint should be there 

### Actual behaviour
no error hints in this case

### Screenshots
![Screenshot from 2019-11-29 20-28-44](https://user-images.githubusercontent.com/55691179/69877179-7ea96f00-12e7-11ea-85a2-3735eeb48bf0.png)

#### Device or machine
Ubuntu

**Comment by ripcurlx** [comment]
50% isn't the default deposit. Actually input for altcoins cannot be bigger than 20% which is why the next step is not active. The problem is here that somehow the validation logic wasn't triggered properly in the field. Do you have a way how to reproduce this in a structured way? I think it has something to do when switching trading accounts back and forth, the validation seems to be not cleared out properly for each field.

**Comment by beingindot** [comment]
yes, i'll check on it.
