### ISSUE TITLE
UX Issue: Support->Mediation buttons are grey on Closed state, but still clickable

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/bisq#3729]
### Description

When going back to view a "Closed" mediation issue, the text and buttons are grey as if they are disabled, but clicking on "SELECT" and "DETAILS" still creates actions.

#### Version

c2e8806d1

### Steps to reproduce

1. Create localnet and take a trade through mediation process.
2. Go to Support->Mediation and try to see details from the result

### Expected behaviour

As a user, I would like to know that DETAILS is clickable so that I can view the trade details. SELECT is also useful since it allows me to view the chat log.

### Actual behaviour

SELECT and DETAILS are greyed out so it looks like I can't click them to get information about my previously mediated trade.

### Screenshots

![closed_mediations_clickable](https://user-images.githubusercontent.com/8082291/70007453-3d9e9e00-1525-11ea-8c99-c4dee96c1a2d.JPG)

#### Device or machine

Ubuntu 19.10

**Comment by chimp1984** [comment]
I think the deactive style is applied to the list row including all buttons. If it was applied per button it could easily be removed so they stay displayed with the active style. For mediators it is very helpful to have it clearly visible which cases are closed, so I am not sure if changing the style would cause more potential confusion than it intends to solve. But I agree its not logical as it is now.... Maybe a different style for closed state instead of deactivate style would be the best solution.
