### ISSUE TITLE
Inquiry - How does Bisq Network validate clients?

### ISSUE THREAD

**Issue by niyid** [bisq-network/bisq#3759]
### Description

I have thought about the possibility of a developer downloading the Bisq code and then modifying for his own purposes. In so doing, he could intentionally introduce wrong calculations and other attempts to con the system.

How does Bisq prevent this from happening?
#### Version
v 1.x.y (all versions).

### Steps to reproduce

1. Download the Bisq source code.
2. Alter some code to do some calculations.
3. Commit/persist data.
### Expected behaviour

For the Bisq network to prevent a user with customized/altered source code from accessing the network by validating the service methods have not been altered.
### Actual behaviour

The source code can be altered and in so doing intentionally introduce wrong data.

**Comment by sqrrm** [comment]
You're always trading with a counterparty that supposedly run an unmodified version and the counterparty will verify the data on their side. Like with Bitcoin, "Don't trust. Verify."

If you both run a modified version then there will be agreement over the modified calculations and all is good, otherwise the trade will fail.

Outside of trades you still have to follow the network protocol or you won't even be able to connect to the network.

**Comment by niyid** [comment]
Great. Thanks for the explanation. I like the fact that modified versions
will be compatible.
