### ISSUE TITLE
Bitsquare stuck on loading screen.

### ISSUE THREAD

**Issue by deafboy** [bisq-network/bisq#376]
I'm running the 64bit deb package on Elementary Freya (Ubuntu 14.04).

Bitsquare worked fine for the first time right after the installation. I've set up my fiat account, created a password protection and posted a SELL order just fine.

Now when I try to start the application it will be stuck in the loading screen forever most of the times.
I'm not sure if it's related, but if it manages to start, all the peer connections via tor are lost once every few minutes. It doesn't matter if I keep my tor daemon running or shut it down before starting Bitsquare.

Here's the [video](http://deafboy.cicolina.org/igelitka/bitsquare/bitsquare_startup.ogv) and [log](http://deafboy.cicolina.org/igelitka/bitsquare/bitsquare_startup.log). Right after recording this yesterday it started fine. Today I'm out of luck again.

**Comment by ManfredKarrer** [comment]
Thanks a lot for the effort to put up a video!
I found already that bug as anotehr use had the same issue. 
Its simply that with pressing enter you close the password popup. Fixed already for the next version. 
So if you **confirm the pw by clicking the button** instead of pressing enter all is fine.

Re Tor: Bitsquare use its owen integrated tor binary. So u dont need to start Tor.

Re connection lost:
Hm thats strange. Can u send me logs when that happens?

**Comment by AndreKoster** [comment]
I had the same thing. Wanted to open an issue, then I saw this. Indeed, clicking instead of return works.

**Comment by ManfredKarrer** [comment]
Yes, was a stupid but. Normally with enter or escape you can close a popup, but at startup the pw popup must not be closed.... Forgot to deactivate that key handler....

**Comment by ManfredKarrer** [comment]
@AndreKoster: Could you contact me by email?

**Comment by ManfredKarrer** [comment]
Fixed in 0.4.1.
