### ISSUE TITLE
To be received BTC missing after error and support ticket being closed

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#378]
I recently bought 0.1 BTC with trade ID 59460570-b0b8-4764-9569-1d7d918b13db .
## After the state of the trade was set to FIAT_RECEIVED (by the seller, I presume), this error occurred:

An error occurred at task: SignAndFinalizePayoutTx
## I was suggested to open a support ticket, which I did. This morning the ticket was closed, with this result:

Ticket closed on 13.04.2016 03:17:38

Summary:
Buyer/offerer delivered tamper proof evidence: No
Buyer/offerer did ID verification: No
Buyer/offerer did screencast or video: No
Payout amount for buyer: 0.11 BTC
Payout amount for seller: 0.01 BTC
Arbitrators dispute fee: 0.00 BTC

Summary notes:
## Thanks for helping testing! Paid out th ebtc to you.... u can see it under funds/tx

It seems to me that "Payout amount for buyer: 0.11 BTC" means that I would receive 0.11 BTC. However, I haven't received this, yet (not under funds/tx). If I look at the funds with a block explorer, I see that the funds in 39AugXkXQSiYHj7YeUAUVvAkHxr15WKXWC are unspent:

https://blockchain.info/address/39AugXkXQSiYHj7YeUAUVvAkHxr15WKXWC

Indeed, I don't see a line "Multisig payout: 59460570" in my Transactions tab, and my tabs "Reserved funds" and "Locked funds" are empty as well.

Perhaps I'm overlooking sonething, but what happened to the 0.11 BTC that I'm supposed to receive?

**Comment by ManfredKarrer** [comment]
hi @AndreKoster 
Thats why I asked you to contact me by email. I discovered that bug after I closed the support ticket.
I have fixed that bug and will publish soon a new verison (needs more testing but I hope I can do it today).

The reason of the bug is following:
Your tradingwallet cannot create the payout transaction which was signed by the arbitrator because you have been offline and at startup password protection delays the setting of the key in the tradingwallet. Unfortunately the P2P message from the arbitrator with the half signed tx triggered  the creation of the pyout tx before the password unlocked the wallet. 
I changed that now so that the P2P message cannot trigger anything before the wallet is unlocked at startup. I did not test sufficently the use cases when password protection is enabled. Sorry.
The UI does not display correctly the balance as it assumes that the trade was closed.

How to fix it now?
If you have a bit patience, I will have a look how I can repair that case with the next version (will be deployed today or tomorrow). The money is still in the MS and we both have the keys in the wallet so no worry the money is not lost. It is just not accessible with the current UI as the sate of the trade was set to closed and I cannot open up a new dispute.
If ok for you I will update you here how we proceed. But no worry we will get out your money.

**Comment by AndreKoster** [comment]
Thanks for explaining (btw, I wasn't aware that you asked me to contact you by email -- do I have your email address?)

I am not worried, and I have patience. ;) I am aware this is a beta software and needs to go through this phase of discovering issues. You're doing a great job building bitsquare, and that's why I decided to participate in trying it out. So I'm cool. 

Looking forward to the next version.

**Comment by ManfredKarrer** [comment]
I added a msg at the other github issues.... my email is manfred [at] bitsquare [dot] io.
my pgp u can find at the contact page at bitsquae webpage.

Thanks for your understanding, seems you are developer yourself :-).

I just looked into  a way how to repair that case with a updated version but its a bit complicate. Basically I need a new feature for such exceptional bugs that the arbitrator can revert the "close ticket" action. But I dont feel comfortable to add such a complex feature now so close before the Beta release and I am also very busy with promotional work.
So I wanted to ask you if you are ok with sending me your data directory (you can open it under account/backup). please unlock your wallet first so i can access it and send me by email the zipped data dir and a btc address where you want to receive the locked up funds. if you have any offers open please close those before. withdraw any funds which are availabel for withdrawal, so the wallet is as empty as possible. If you have trades open I will not touch the other funds but after your trades are finished, better delete the data directory and start with a new wallet (so the wallet you sent me is dead :-)).

**Comment by ManfredKarrer** [comment]
@AndreKoster I have deployed a new version. Can you try if you get the missing locked btc out with that version? I don't expect it but worth a try. If not please send me by email a zipped data directory (with password deactivated). Then I can hack to get yoru funds out.

**Comment by AndreKoster** [comment]
I tried, but no. I'll send you my data folder as you requested, and an address.

**Comment by ManfredKarrer** [comment]
Closed as funds transferred.
