### ISSUE TITLE
Frozen on 1.2.4 but 1.2.3 works fine (Ubuntu)

### ISSUE THREAD

**Issue by dextertd** [bisq-network/bisq#3816]
### Description

Bisq 1.2.3 works on clean Ubuntu but not 1.2.4

#### Version

1.2.4

### Steps to reproduce

Delete all Bisq data, download Bisq 1.2.4 .deb from site and install. Attempt to launch (from GUI or terminal) - stuck on loading screen.

### Expected behaviour

Bisq launches into main screen.

### Actual behaviour

Launch Bisq. Bisq stutters and eventually freezes on either step 1 or 2 (of 4) of loading. Freezes whole machine, cannot move mouse. If listening to audio, audio will stutter and stop. Machine will either: 1. unfreeze after Bisq closes itself; 2. freeze then go to lockscreen, after logging in all programs have closed; 3. freeze for a long time, so user has to manually power off machine.

#### Device or machine

Ubuntu 18.04.3 LTS

#### Additional info

https://pastebin.com/cC93xUmV
Find conversation in Keybase #support 2019/12/20 starting at 2:55 PM.

After updating to 1.2.4 from 1.2.3 I seem to have two copies of Bisq installed - 1.2.3 and 1.2.4. 1.2.3 boots up just fine and again prompts me to update to 1.2.4, whilst 1.2.4 causes the issues outlined above.

**Comment by dikdust** [comment]
#3825 maybe same problem ? I tought is a matter of bad performance on my hardware ...

**Comment by dextertd** [comment]
@dikdust Possibly although I don't even get an error screen. Although we both have AMD GPUS...

**Comment by dexter-2** [comment]
@dikdust Possibly although I don't even get an error screen. Although we both have AMD GPUS...

**Comment by quantverse** [comment]
Same issue here. Kubuntu 18.04.
Bisq 1.2.4 fresh install.

Whole desktop frozen because of Bisq after few minutes of using it. Had to CTRL+ALT+F2 to get to text console and kill the Bisq process. That recovered the desktop.

The application was pretty slow anyway (taking 1-2 seconds to react to mouse clicks) before the freeze.

The machine is quite recent (4 cores, 16GB RAM), so this is not a HW issue. Also noticed that the Bisq process did not consume all the RAM, so there was not swapping / out of memory situation.

**Comment by dextertd** [comment]
Closed as successfully updated to 1.2.5 which works perfectly.
