### ISSUE TITLE
when seller as taker using min btc range security deposit is higher

### ISSUE THREAD

**Issue by beingindot** [bisq-network/bisq#3869]
### Description
when seller takes an offer and fills min btc amount, security deposit is around 75%

#### Version
1.2.5

### Steps to reproduce
1. alice puts buy offer with 0.05 - 0.25 btc range
2. alice pays security deposit of 0.0375 btc
3. bob takes that offer
4. bob fills 0.05 as btc amount
5. bob pays 0.0375 btc as security deposit which is way more 15%

### Expected behaviour
security deposit is 15%

### Actual behaviour
security deposit is calculated based on max btc range

### Screenshots
![Screenshot from 2020-01-07 16-56-48](https://user-images.githubusercontent.com/55691179/71894869-7578b100-3175-11ea-8a22-7f21965eacbd.png)
![Screenshot from 2020-01-07 16-56-55](https://user-images.githubusercontent.com/55691179/71894881-7b6e9200-3175-11ea-8c27-0d0fcfc2c1ff.png)

#### Additional info
Please close this if not a bug @chimp1984

**Comment by ripcurlx** [comment]
It is not a bug as the minimum security deposit is 0.006 BTC. But we need to change the display in the create offer step if the minimum security deposit is used.

**Comment by sir-plankton** [comment]
Maybe I'm not understanding something because this is a bug to me.

I just tried to take a seller's offer that ranged from .007 to .052 BTC (50% security deposit setting). Because I'm a new user, the max I can buy is .01, fine.  But...
The next screen says my security deposit is .026 (327% "of the trade amount") !  This makes no sense.
I'm trying to buy .010 and the deposit is .026 !
The security deposit should be 50% * desired_buy_amount, or .005
Why is the security deposit calculated with the **maximum** of the seller's range?

The seller would not be happy that prospective buyers like me are choosing other sellers because she/he allowed a range.
Under the current code, sellers who allow buyers to pick a range are being penalized because their offers are burdened with unreasonably high (and unintended) security deposits.  The sellers probably don't realize this is happening to their offers.

**Comment by pazza83** [comment]
Hi @sir-plankton, I think this is due to the way the trade protocol works. When an offer is done as a range min-max. The security deposit used is based on the maximum amount.

This is due to the maker of the offer having to allocate the security deposit amount at the time of the trade. As it is not know what offer will be taken the maximum amount is used. As both traders needs to allocate the same security deposit the maximum amount is used.

I think it is unusual to see offer with such a large range. 

You could try and take another offer, fixed amount of BTC, with a lower security  deposit if this would be preferable.

**Comment by sir-plankton** [comment]
@pazza83 , ok so it's because when the offer is created, the creator/maker must deposit (on-chain) the max security deposit of the range.  However, if the taker buys **less** than the range's max, then the taker should not have to send a 327% security deposit because the maker is OK with 50%.

So I think this should be allowed: maker depositing .026 and taker depositing .005 (which satisfies the maker's 50% requirement on a .010 buy). At the end of the trade, maker gets .026 back and taker gets .005 back.

Can that work?

**Comment by pazza83** [comment]
Hi @sir-plankton 

It is likely that at the time the offer was created (before April 2021) the security deposit was a fixed amount of 0.006 BTC. This has only recently been reduced. See the issue here where they were reduced: https://github.com/bisq-network/proposals/issues/323

Old offers that were placed before this change all have a 0.006 BTC security deposit. These offers will likely disappear from Bisq soon as they get taken or cancelled. 

To see when the offer was created you can click on the (i) next to the payment method and it will give you a creation date.

Hope that helps. Apologies if my initial reply was confusing.
