### ISSUE TITLE
Offer has localhost:9999 instead of Tor onion address

### ISSUE THREAD

**Issue by deltahandler** [bisq-network/bisq#3927]
### Description

Onion address of a trader for Buy BTC for BSQ shows localhost:9999 instead of Tor onion address.

### Screenshots
<img width="1106" alt="Screen Shot 2020-01-30 at 19 31 46" src="https://user-images.githubusercontent.com/52250737/73502506-3534d900-4397-11ea-8e5f-16cfece4dad7.png">

**Comment by djhilli** [comment]
I have the same problem when I am under tails
bisq start and then make an offer, everything seems to be good but nobody buys it, I then tried to buy my own offer from another computer that I created under tails then comes as an error message user is not online.  and it shows  on picture "localhost:9999"

If there is no solution that bisq works with tails, the solution below only works to buy, but no one can buy a created offer, please help, because bisq and tails would be the best.

to start:

made authcookie readable:
sudo chmod o+r /var/run/tor/control.authcookie

added iptables rules to to connect to nodes:
sudo iptables -I OUTPUT 3 -d 127.0.0.1 -o lo -p tcp --dport 8333 --syn -m owner --uid-owner amnesia -j ACCEPT # bisq
sudo iptables -I OUTPUT 3 -d 127.0.0.1 -o lo -p tcp --dport 8000 --syn -m owner --uid-owner amnesia -j ACCEPT # bisq

and started bisq:
./Bisq --torControlPort 9052 --torControlCookieFile=/var/run/tor/control.authcookie --torControlUseSafeCookieAuth --seedNodes=ef5qnzx6znifo3df.onion:8000,s67qglwhkgkyvr74.onion:8000 --socks5ProxyBtcAddress=127.0.0.1:9050 --socks5ProxyHttpAddress=127.0.0.1:9050 --useLocalhostForP2P=True --useTorForBtc=True

**Comment by deltahandler** [comment]
@djhilli 
The argument `useLocalhostForP2P=True` is the problem. That causes to use localhost network not Tor. Did you copy that from some doc? If so we should fix that at this place.

@ripcurlx It is not a Linux issue....

**Comment by ripcurlx** [comment]
> @djhilli
> The argument `useLocalhostForP2P=True` is the problem. That causes to use localhost network not Tor. Did you copy that from some doc? If so we should fix that at this place.
> 
> @ripcurlx It is not a Linux issue....

True, I missed the `useLocalhostForP2P` option in the start-up command

**Comment by djhilli** [comment]
@ripcurlx  @deltahandler 


Yes the problem is if you start it in Tails then it won't work without the entry "useLocalhostForP2P", because then no connection to the network will be established. And with the entry you can accept offers both buy and sell, but if you create an offer yourself, the other localhost see: 9999 and this offer cannot be accepted.

But think that only appears in connection with tails, but at least with the above syntax, at least to accept the offers.

as I said Tails + Bisq + public Wifi is a statement people

**Comment by Bisq-knight** [comment]
I Have one mediation case where one of parties has localhost as his address(and he doesn't reply, no wonder). Would it be of value to get the logs from the other guy?

**Comment by freimair** [comment]
@djhilli 

> Yes the problem is if you start it in Tails then it won't work without the entry "useLocalhostForP2P", because then no connection to the network will be established.

Can you be more specific? Maybe provide Bisq logs without the "useLocalhostForP2P"?

**Comment by freimair** [comment]
https://bisq.wiki/Bisq_on_tails
