### ISSUE TITLE
Bisq fails to start because of data directory issue

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#3998]
### Description

Based on https://bisq.community/t/new-install-not-starting-up/8963/25

Users cannot start version v1.2.7 because of following exception being thrown:
```
$ /opt/Bisq/Bisq
error: Application data directory '/home/xxx/.local/share/Bisq' could not be created
```

#### Version

Regression bug affecting version v1.2.7.
Does work in v1.2.5.

### Steps to reproduce

Unfortunately not 100% clear why this is happening.
Every time this users start v1.2.7 with an existing data directory the app fails to start.
Reverting back to v1.2.5 solves the problem and app starts as expected.

### Expected behaviour

App starts.

### Actual behaviour

App fails to start.

#### Device or machine

We know about one affected user on Windows and one on Linux.

**Comment by cbeams** [comment]
_The following comment is cross-posted from https://bisq.community/t/new-install-not-starting-up/8963/31:_

I have been unable to reproduce this error. Here are the steps I took:

1. Install a fresh Ubuntu 18.04.4 LTS VM via VirtualBox
2. Download and install the Bisq v1.2.5 .deb from https://github.com/bisq-network/bisq/releases/tag/v1.2.5
3. Run Bisq successfully with no command line options
4. Notice that the app starts up without error
5. Inspect `~/.local/share/Bisq` and notice that everything is in place as it should be
6. Click the link within the running Bisq application to download and verify the v1.2.7 release
7. Close Bisq v1.2.5, install and run the newly-downloaded v1.2.7 .deb.
8. Notice that the app starts up without error
9. Inspect the `~/.local/share/Bisq` directory and the contents of the `bisq.log` file within and notice that everything is as it should be.

Since I cannot reproduce this myself, what's needed now is to get more information about the reason for the failure to create the (already existing) `~/.local/share/Bisq` directory. I've just published a patch that will ensure a stack trace is printed to the console in the case of this kind of directory creation failure. @tieck and/or @DrFredPhD, could one of you build and run from source using the following commands and report the stack trace back here?

First you will need to have JDK 10, 11 or 12 installed locally. Use JDK 10 if you don't have anything installed already. You can get it from https://jdk.java.net/. When complete, check your java version at the command line and you should see the following:

```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

Next, you need to build and run Bisq with my patch applied. Here's how to do it if you have `git` installed. If you don't, see the alternative instructions that follow:
```
git clone --depth=50 --branch=debug-appdir-creation https://github.com/cbeams/bisq
cd bisq
./gradlew :desktop:run
```

If you do not have `git` installed, you can download the source as a zip file, unzip it and run the `./gradlew :desktop:run` command within the `bisq` directory it unzips into:

1. Download and unzip https://github.com/cbeams/bisq/archive/debug-appdir-creation.zip
2. `cd bisq`
3. `./gradlew :desktop:run`

Note that on Windows, you will need to run `gradlew.bat :desktop:run` instead of `./gradlew :desktop:run`

You should end up with an error that begins with the following lines:

```
> Task :desktop:run FAILED
fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
...
```

Please copy and paste your entire error message here.

**Comment by cbeams** [comment]
`@tieck` wrote via https://bisq.community/t/new-install-not-starting-up/8963/32:

> It seems that the new version does not handle symbolic links in the path of the Bisq application directory the same way anymore.
> 
> I could reproduce the behavior in first moving away the application directory and then creating a symbolic link at its place:
> 
> ```
> $ mkdir ~/tmp
> $ mv ~/.local/share/Bisq/ ~/tmp
> $ ln -s ~/tmp/Bisq/ ~/.local/share/Bisq
> $ ./gradlew :desktop:run
> 
> > Task :desktop:run FAILED
> fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
> java.io.UncheckedIOException: Application data directory '/home/xxx/.local/share/Bisq' could not be created
>         at bisq.common.config.Config.mkAppDataDir(Config.java:805)
>         at bisq.common.config.Config.<init>(Config.java:644)
>     at bisq.core.app.BisqExecutable.execute(BisqExecutable.java:76)
>     at bisq.desktop.app.BisqAppMain.main(BisqAppMain.java:57)
> Caused by: java.nio.file.FileAlreadyExistsException: /home/xxx/.local/share/Bisq
>     at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
>     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
>     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
>     at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385)
>     at java.base/java.nio.file.Files.createDirectory(Files.java:689)
>     at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
>     at java.base/java.nio.file.Files.createDirectories(Files.java:742)
>     at bisq.common.config.Config.mkAppDataDir(Config.java:803)
>     ... 3 more
> ```

**Comment by DrFredPhD** [comment]
Hello yes. I didn't build yet but I am using symbolic link in data path

**Comment by cbeams** [comment]
Perfect timing, @DrFredPhD. I've just submitted PR #4002, which fixes this problem. Thanks for getting back.
