### ISSUE TITLE
Wrong market price for MYR currency

### ISSUE THREAD

**Issue by AndreKoster** [bisq-network/bisq#410]
The Bitcoin market price for MYR sometimes goes haywire. It currently is around MYR 1,790, this screenshot shows it to be around MYR 3,600,000.

![bitsquare](https://cloud.githubusercontent.com/assets/18371058/14894496/2456d4e2-0d74-11e6-990c-febfa5cb70f8.png)

**Comment by ManfredKarrer** [comment]
We get the price from BitcoinAvergage (@bitnumus ) and they use an official exchange rate to USD to calculate the non USD currencies. We got some similar issue with Venezuela as their government apply wishful thinking to the exchange rate rather then real economics ;-).
I think Malaysia will not have that issues, but maybe the provider for MYR/USD delivers wrong data. 
Is it always wrong? Or just some times?

See also: https://github.com/bitsquare/bitsquare/issues/145

**Comment by shaun-ba** [comment]
ours - "MYR": {"rate": "3.895784", "name": "Malaysian Ringgit"}

xe.com - 1.00 USD   =   3.89210 MYR

https://api.bitcoinaverage.com/ticker/global/MYR/

{
  "ask": 1744.3,
  "bid": 1742.27,
  "last": 1743.49,
  "timestamp": "Thu, 28 Apr 2016 17:15:52 -0000",
  "volume_btc": 0.0,
  "volume_percent": 0.0
}

@ManfredKarrer Seems like this maybe a bug your end?

**Comment by ManfredKarrer** [comment]
@bitnumus  Thanks! I have not looked yet into it but will do now... Seems to be a strange bug on my side...

**Comment by AndreKoster** [comment]
> Is it always wrong? Or just some times?'

Today is the first time I noticed it was wrong. In the past hour I've seen it flip between right and wrong a few times.

**Comment by ManfredKarrer** [comment]
I found the bug Myriadcoin has the same tickersymbol. Need to seperate altcoins with fiat.

**Comment by ManfredKarrer** [comment]
Added a requirement for altcoins to not conflict with ISO codes (https://en.wikipedia.org/wiki/ISO_4217). Changed Myriadcoin ticker symbol to MYRC (of I will remove it if they dont agree).
So with the next release that will be fixed. I will close that issue.

**Comment by dan-da** [comment]
It is misleading to the user to display a price from bitcoinaverage without labeling it as such.

The typical usage of "Market Price (Last)" in a trading platform represents the last trade for this orderbook I'm looking at.   I can understand why that would be difficult to achieve in a p2p environment, but there should be some visual indicator that the price displayed comes from a 3rd party source.  Otherwise, the trades in the orderbook may not match up, and it then appears to be a bug in the software, or anyway confusing.

**Comment by ManfredKarrer** [comment]
Yes I agree, will try to push in the Logo of BitcoinAverage and Poloniex...though there is little space there.

**Comment by shaun-ba** [comment]
> Yes I agree, will try to push in the Logo of BitcoinAverage and Poloniex...though there is little space there.

@ManfredKarrer  let me know if you need a vector or something for that.

**Comment by dan-da** [comment]
Logo is good if possible.  Would be great to add tooltip text with brief explanation also, to appear on mouse hover.

**Comment by dan-da** [comment]
One more thought on this... 

Since you are pulling from bitcoinaverage.com anyway, why not making the source pluggable/configurable?

This way, one or more parties could start watching the p2p network and setup a service/api for serving the last trade info, per market.  And users would have real "Last" info about the orderbook, and possibly even market history info for graphs, etc.

I recognize that there can be some trust issues with this, but by making it configurable, at least it is up to the users to decide, and I think that if an API provider were trying to manipulate the market, it would be caught fairly quick and posted about on reddit, etc.

just a thought.   decentralize all the things, right?

**Comment by ManfredKarrer** [comment]
@bitnumus Thanks that would be indeed useful. There is little space so I need to squeeze it in somehow, so fi you can mail me a vector graphic that would be great!

@dan-da: Tooltip is good, will chekc whats the best solution.

Using other feed providers would be good as well but unfortunately not easy as we use that for dynamic prices, so if the 2 traders would use diff. price providers with different prices that would conflict. Of couse as both are not synced there might be conflicts as well, but that is usually in a very small range which falls into a tolerance window.

**Comment by ManfredKarrer** [comment]
Done. Will be in next release.

![bildschirmfoto 2016-06-21 um 21 21 16](https://cloud.githubusercontent.com/assets/1449498/16243137/22220cf8-37f6-11e6-8d66-461ab13bee71.png)
![bildschirmfoto 2016-06-21 um 21 21 23](https://cloud.githubusercontent.com/assets/1449498/16243138/2227f8ca-37f6-11e6-9afd-7fcfdc7f00c0.png)
