### ISSUE TITLE
BTC Sellers Stop Answering

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq#4126]
### Description

Bisq's biggest problem regarding user-experience is that **if** the btc seller stops answering (or doesn't confirm he received the funds) the btc buyer won't get his funds back for **20 DAYS** In some cases, traders are leaving Bisq for this reason. A user that does everything correctly cannot be penalized this much time even if he Is awarded the other party's deposit. This really needs to be addressed, please comment ideas on how this could be solved. this is high priority.

**Comment by MwithM** [comment]
I've been thinking about this lately, and I think this 2 measures would improve the situation:
- Reduce by half the time allowed for mediation and arbitration (5 days for altcoin mediation is more than ennough), and it would be strange that fiat requires more than 10 days to solve a dispute.
- We are calling refund agent to a role that still is operating as an arbitrator, a second order investigator and final judge. Refund agent should be just that, an agent which main purpose is to perform dispute payouts. Refund agent should not need to request any more info than what mediators already suggest, and add an extra charge to disappeared trader for not accepting mediator's suggestion. That would encourage the settlement by trading peers while still reduce the impact on diligent traders.
After mediation, I had to wait 5 days to be refunded because the arbitrator needed to know what the other part had to say. The other part already had 10 days to show up, but he did not. Mediator and refund agent should share information to speed up the dispute process.

**Comment by leo816** [comment]
> Reduce by half the time allowed for mediation and arbitration 

I agree with that. I think the fact that users **that use the platform correctly**  have to go through this long process and keep presenting their case, while the other party received their payment on time and never responded, makes no sense. I suggested that the refund agent should get an automatic summary report by the mediator on every case he gets. This hurts the user-experience significantly.

> and add an extra charge to disappeared trader for not accepting mediator's suggestion

besides cutting down the waiting time for the party who made the payment on time, it seems that this solution still treats the same the person who never showed up and caused all the trouble for the other. Unless you are suggesting that the extra charge is made as well as the deposit from the other party as penalty.

**Comment by MwithM** [comment]
> besides cutting down the waiting time for the party who made the payment on time, it seems that this solution still treats the same the person who never showed up and caused all the trouble for the other. Unless you are suggesting that the extra charge is made as well as the deposit from the other party as penalty.

Of course, penalty should be applied to offender to reward offended party. On the case I had, refund agent decided to still leave some of the deposit to the offender, and it was a future trade.

**Comment by ripcurlx** [comment]
Still relevant.

**Comment by chimp1984** [comment]
We could consider to block onion addresses of users who do not respond as well as flagging his signed witness. Problem would be if the reason are caused due a bug or network issues. But I guess those are very few. For altcoins onion blocking will have limited effect as user can create new one. For fiat banning the signed witness has more effect. Of course it introduce more centralization from mediation side as well for the filter feature. 

Lets see first how the increased security deposit will help...

**Comment by chimp1984** [comment]
Automated altcoon confirmation like for XMR (https://github.com/bisq-network/bisq/pull/4378) would help as well for those cases where the user was just lazy. Of course his app need to be online.

**Comment by chimp1984** [comment]
Another idea: https://github.com/bisq-network/proposals/issues/241
