### ISSUE TITLE
Revolut account should use revolut username

### ISSUE THREAD

**Issue by eboukamza** [bisq-network/bisq#4155]
### Description

User has three ways for sending funds in revolut:

- username (`@revolut_username`)
- phone number / email
- IBAN

Actually funds are sent by phone number but seller has no way to check the phone number of the buyer into revolut app. To be compliant with `Trader Rules` (verify trade contract information before confirm the payment) seller should add phone number in their contact list and then compare this username with the username of the payment.

#### Version

1.3.1

### Steps to reproduce

Trade with revolut

### Expected behaviour

Revolut accounts in Bisq should use revolut usernames. It is also more private than a phone number.

### Actual behaviour

Actually phone number is used for revolut trades

#### Additional info

Related: https://github.com/bisq-network/bisq/issues/3728 https://github.com/bisq-network/bisq/pull/3777 #1312

**Comment by Bisq-knight** [comment]
The username feature is gradually being rolled out to revolut users. I know people who don't have it yet. 

We should look into it when it's in general availability and the editing feature is there

**Comment by ivopashov** [comment]
It can be both username and phone with one of them being mandatory. Username is much more convenient when there.

**Comment by pingiun** [comment]
I believe usernames now are generally available. They are much better than phone numbers for privacy reasons, I think the UI should be changed so people can enter their handle instead of phone number. I think this will also solve the issue of Revolut giving payment links when a new phone number is entered.

**Comment by svrnhdl** [comment]
How is this going? I was added to a WhatsApp group with 'Bisq Sellers' recently and it spooked me.

Will there be an option to change to username and keep the account signing?

**Comment by crowphale** [comment]
I did a couple of transactions through Revolut and always ended up asking for username since Revolut wouldn't send to phone number (even after adding it to Contacts, which is not something people should need to do since often that's synced somewhere in the cloud).

So +1 for this change. If anyone has pointers on how to start on this, I'm  happy to help.

**Comment by ripcurlx** [comment]
This change will be shipped with v1.3.8.

**Comment by ripcurlx** [comment]
Closing as complete.
