### ISSUE TITLE
Error BuyerVerifiesPreparedDelayedPayoutTx

### ISSUE THREAD

**Issue by Glugstar** [bisq-network/bisq#4183]
Hi,

I tried to take an offer to buy BTC, but AFTER I deposited the taker fee, the application returned an error:

> An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
> Donation address is invalid.
> Address used by BTC seller: 3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp
> Recent donation address:3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV
> Default donation address: 1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7

Trade ID: hvpcfuy-649b707f-52e0-4d5e-93ee-7e7cc85e0089-132
Maker fee transaction: 129031e5db59b603aebb952c878b5e86e8ac383af1166f5ecae4ac411f90f812
Taker fee transaction: a6b51a82255eed0ef51e7d136c697281cb7753f030dc3c34752764246d2420ad

Had 1.3.1 when the bug happened, now I updated to 1.3.2
Running on Windows 7, 64bit

![1](https://user-images.githubusercontent.com/30003087/79767229-561f2180-8329-11ea-94f9-088d9c4f49cc.png)

![2](https://user-images.githubusercontent.com/30003087/79767252-5ddec600-8329-11ea-93a2-e0ed65c06eb5.png)

See attached log file from today. It probably includes one additional completed trade.

[logs.txt](https://github.com/bisq-network/bisq/files/4504348/logs.txt)

Best regards,
Alex

**Comment by ghost** [comment]
## Fixed in v1.3.3
 
Verification of the DAO donation address was not taking into account that some clients' database are old and therefore using an older donation address. [Now both old and new donation addresses are accepted.](https://github.com/bisq-network/bisq/blob/246d5ee37af225e68c1c0fe8f757ef575c55362b/core/src/main/java/bisq/core/trade/DelayedPayoutTxValidation.java#L162)
