### ISSUE TITLE
QR code not matching BTC amount when using BSQ for trading fee

### ISSUE THREAD

**Issue by eigentsmis** [bisq-network/bisq#4194]
When making an offer and selecting to pay the trading fee with BSQ the QR code will lead to a different BTC amount than what is printed in the transaction summary in Bisq.

**Comment by ghost** [comment]
@eigentsmis good find!  Adding a few extra relevant pieces of information here:

- this issue seems to have been around for a while.  Screenshot below shows it in v1.2.9
- it also happens using BTC for the fee (not only BSQ), as shown below.
- if you click on the small QR code there is an enlarged QR code shown which has the correct amount (see second screenshot below)
- initial thoughts as to the cause is that the small QR code is initialized on offer creation, but does not listen to changes from the data model like the other fields.  The fees are calculated asynchronously on a different thread causing the data model / amount to be updated, but the QR code does not recieve that updated value.


### offer creation, QR code for incorrect amount:

![image](https://user-images.githubusercontent.com/47253594/80260106-c640e680-864c-11ea-8087-0e67dc70745a.png)

### same offer, larger QR code, correct amount:

![image](https://user-images.githubusercontent.com/47253594/80261250-84fe0600-864f-11ea-8d10-b3985c3aa133.png)

**Comment by eigentsmis** [comment]
Had no idea the QR code is clickable :) ...maybe there should be a UI hint or something?
Anyhow, I can confirm it shows the correct amounts in the bigger QR code.
Regarding QR codes for BTC fee offers - it seems to be better but still not working 100%. Throughout my testing I found that either of the solutions below will result in the correct small QR code for BTC fees:
1). Move all of the available balance in Bisq to another wallet and retry creating offer OR
2). Cancel offer screen and retry creating the offer.
Like you said, it might be a race condition due to different threads leading to this intermittent behaviour.
