### ISSUE TITLE
Updates of percentage based prices not sync with top display

### ISSUE THREAD

**Issue by MarcSte** [bisq-network/bisq#422]
When there's a lot of action in the markets, price in top display is not sync with offer prices.

Additionally, I'd vote for more frequent price updates.

**Comment by ManfredKarrer** [comment]
You mean the % based price in the offers in the table is not updated with the changed price?
Fiat and altcoin prices are loaded differently and are not synced in time. Fat loads selected currency every 90 sec. and all fiat currencies every 3 min. So if USD is selected and gets an update only the USD offers reflect that. The others will get updated later (3 min. interval).
Altcoins get updated every 3 min as well (always loaded all as the API does not support single currency).

Too frequent updates result in ip blocking. Also data for all prices is quite big so that would generate quite a bit of traffic over a day if we set it to 1 min. Also price providers are not updating that frequent as well, Bitcoinaverage wrote less than a minute is pointless.

**Comment by MarcSte** [comment]
I understand what you said according to frequent updates and agree.

According to the %based price i mixed up bid and ask price. 

While in the Buy BTC tab the ask price is displayed in the top display, the percentage price in the offers refers to the bid price. Therefore there is a difference in prices if you have 0.0% offers.

This makes sense but made my head spin.

I'm closing this as it is solved.

**Comment by ManfredKarrer** [comment]
Yes that is a bit confusing but makes sense as the offers are the opposite of what u see.
