### ISSUE TITLE
an error ocurred at task

### ISSUE THREAD

**Issue by sombra-dot** [bisq-network/bisq#4227]
I get this error when trying to post an order using BSQ to pay for the fees; An error ocurred at task: CreateMakerFeeTx

**Comment by 4NobleTruths** [comment]
Get the same error trying to create offer using BTC fee and funding from external wallet.
Funds go into Bisq wallet.
Worked ok in previous version 1.3.2

Version 1.3.4
Steps to reproduce
Create offer as usual, and fund from external wallet.

Expected behaviour
Create offer

Actual behaviour
CreateMakerFeeTx error and funds go into Bisq wallet. 

Screenshots
![CreateMakerFeeTx](https://user-images.githubusercontent.com/7483645/81035261-1eb88500-8e92-11ea-8444-68e4d67164c7.png)

Device or machine
Debian 9

**Comment by 4NobleTruths** [comment]
I think something wrong with fee estimation, because log has lines such as:

> [JavaFX Application Thread] WARN  o.b.w.Wallet: Insufficient value in wallet for send: needed 0.00000094 BTC more 
[JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: CreateMakerFeeTx org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.00000094 BTC

There was certainly sufficient money, because the funding tx cleared onchain within one block, and it was being funded from external wallet, and there is much more than 94 sat even in the local wallet.

**Comment by 4NobleTruths** [comment]
Putting 3x tx fee on funding tx from external wallet caused a "null" error, but created offer.

**Comment by ghost** [comment]
"Insufficient value in wallet" error seems like the same as reported in https://github.com/bisq-network/bisq/issues/2293.  @4NobleTruths @sombra-dot  log excerpts of the error messages would be useful.  Also detailed steps taken prior to the error manifesting, including amount & price entered.

**Comment by ghost** [comment]
One way to cause this issue is when fee estimator produces a higher estimate during the time between the user entering the offer details and pressing the `review: place offer to sell bitcoin` button on the create offer screen.

This is the only way I've found to reproduce the error consistently.  If anyone knows other steps to reproduce, please post a comment.

### Steps to reproduce:



- Empty Bob's bisq wallet to an external wallet.
- Bob enters an offer to buy BTC, funds it from external wallet (exact amount), BUT DOES NOT YET PLACE THE OFFER.
- Bob leaves the `review: place offer to sell bitcoin` message up for some time.  This is to allow a new fee estimate to arrive from the web.  For this problem to manifest, fees should be rising.
- Finally Bob hits the button to review, then place the offer.
- The error dialog pops up: "An error occurred at task: CreateMakerFeeTx"  "Insufficient money, missing 0.xxxx BTC".


For most users the fee estimate does not change between funding and creating the offer since:
- the fee Web API is only queried every 5 minutes, and 
- the user does not pause very long between funding and placing the offer.


I'm working on a fix for this issue.
