### ISSUE TITLE
Implement simplest possible trading script

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/bisq#4257]
After implementing rpc wallet protection methods ([ISSUE 4214](https://github.com/bisq-network/bisq/issues/4198) + [PR 4214](https://github.com/bisq-network/bisq/pull/4214)), we need a  minimum set of endpoints to enable trading from the gRPC API, and a bats script for test / demo purposes.

The goal of the set of PRs that will accompany this issue is to allow a user to perform all of the following functions with the gRPC API  (the UI should not be needed for any setup).

- [x] Get Funding Addresses

  Method Signature:	`getfundingaddresses`

  Show existing unused BTC addresses in the wallet.
  If there are no unused addresses in the wallet, the server will create one.

  Analog to bitcoin-cli method [getnewaddress](https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/getnewaddress) 

- [x] Get Address Balance

  Method Signature:	`getaddressbalance address`

  Show BTC balance for given address in the wallet, with number of confirmations of the most recent transaction included.  (TODO  Show list of txIds included as well?)

   Analog to bitcoin-cli method [listreceivedbyaddress](https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/listreceivedbyaddress) 

- [x] Fund a BTC wallet

  No new method is needed to fund a wallet.  User sends BTC from an external wallet to a Bisq "Fund your wallet" address, then awaits confirmations.

  Use Case:
      * User finds an unused funding address by calling `getfundingaddresses`.
      * User sends BTC via `bitcoin-cli sendtoaddress "addr" amt`.
      * User polls status of the funding TX by calling `getaddressbalance address` and/or `getbalance`.

- [x] Create a Payment Account

  Method Signature:	`createpaymentacct acct-name paymentmethod acct-number currency`

  (The different payment methods will have different attributes, the above signature is specific to PerfectMoney)

  In the interest in keeping it simple at this stage, the 1st impl can only create a "PerfectMoney dummy" account, mimicking the default payment method created by the UI when running Bisq in regtest / dev mode with the DAO setup used to test every new release.

- [x] Get Payment Accounts

  Method Signature:	`getpaymentaccts`

  Show list of all payment methods created by the user in the UI or `createpaymentacct`.  The returned id is a required parameter of the `createoffer` method.
  
- [x] Get Existing Offers

  Method Signature:	`getoffers buy | sell, currency` 

  Output would display same info as UI's Offer Book, plus a unique identifier to be used in
a `takeoffer` method.

- [x] Create Offer

  Method Signature:	`createoffer buy|sell [TBD]`	

  BUY  Offer Parameters:  `payment-method  amt  currency  pct-from-mkt-price  min-amt [pct-sec-deposit]`

  SELL Offer Parameters:  `payment-method  amt  currency  pct-from-mkt-price  min-amt [pct-sec-deposit]`

  _Note: there may be differences in the non-unique BUY/SELL offer params shown above (todo)._

- [x] Take Offer

  Method Signature:	`takeoffer offer-id`	

  Taker must have a matching payment-method associated with selected offer.

  Funding source defaults to Bisq wallet.
  Fee currency defaults to BTC. 
  (Support for displaying BSQ balance and paying trade fee with BSQ not in scope.)

- [x] Get Offer Status

  Method Signature:	`getofferstatus offer-id`	

  Displays status of offer, including trade protocol steps that have and have not been completed.

  Offer creators & takers will see different offer status information, but both will see the same 
initial state:	

    `WAITING_FOR_BLOCKCHAIN_CONFIRMATION` (of deposit fees)

  Offer States seen by Takers:

	`START_PAYMENT`
	`WAITING_FOR_PAYMENT_ARRIVAL`

  Offer States seen by Creators:

	`WAITING_FOR_PAYMENT`
	`PAYMENT_RECEIVED`

  Note: there may be some states unique to SELL offer creators/takers and BUY offer creators/takers.			

  Creators and takers will also see the same final status:

 	`COMPLETED` (can move funds)
 	
- [x] Start Payment

  Method Signature:	`paymentstarted offer-id`		

  Called by BTC buyers after submitting a payment.
		
- [x] Payment Received

  Method Signature:	`paymentreceived offer-id`		

  Called by BTC sellers after receiving a payment.

- [x] Cancel Offer

  Method Signature:	`canceloffer offer-id`

  Allow user to cancel an existing offer that has not passed the `START_PAYMENT` stage of the trade protocol.

- [x] Move BTC from completed trades to Bisq BTC wallet

  Method Signature:	`movefunds`    

  Move BTC funds and trade fees to Bisq wallet after a successful trade completion.

- [x] Withdraw BTC to an external wallet

  Method Signature:	`withdrawfunds "addr"`    

  Withdraw BTC from Bisq wallet to external BTC address

- [x] BATS test script(s) to test and demo end-to-end functionality

**Comment by ghubstan** [comment]
@cbeams, These method names are not well thought out, and I'll work on improving them.  

I will also stub out some of the new endpoints in branch [rpc-wallet-protection+scratch](https://github.com/ghubstan/bisq/tree/rpc-wallet-protection+scratch), or a new branch based on master, if you merge [PR 4214 ](https://github.com/bisq-network/bisq/pull/4214) before you go no break.

Have a good long break.

**Comment by cbeams** [comment]
Thanks, @ghubstan. Please see my comments about this in the video I just posted at keybase://chat/bisq#grpc-api/657

**Comment by ghubstan** [comment]
> Please see my comments about this in the video I just posted at keybase://chat/bisq#grpc-api/657

@cbeams , You may have already turned into a pumpkin, but here's my feedback regarding the video.

I'm OK with switching from a gRPC to REST API if that's what will be needed to get Bisq into `mynode`, and I know how to work with SpringWeb & REST.  I also agree with what you said about a switch to REST != wasted efforts.   Thanks for the head's up.

I'll study the :daemon readiness problem, and work on the this issue while you're away -- keeping in mind what you talked about in the recording.

**Comment by dmos62** [comment]
Can we consider not using Bitcoin Core's convention for API naming withoutanyspacesorcapitalization? It's a pain to read and to write too, because it's hard to spot a typo. I suggest using_snake_case_which_means_putting_underscores_where_spaces_would_be.

Before someone suggests CamelCase, while it would be just like writing Java, I would be against it, because its space economy leads to some awkward reading as well: LikeWhenThereIsAShortWordInTheName.

**Comment by cbeams** [comment]
I'd recommend holding off on such a change until closer to an initial release, and to think really carefully about it. The reason for mimicking Bitcoin Core is not because all lower case is necessarily best, but because it is perhaps most familiar to people in this space, and more likely to "feel right" to someone working with Bitcoin Core a lot. If we were to follow more general *nix command line utility conventions, I'd recommend kebab case, e.g. the way many unix utilities are named, e.g. `gpg-agent`, `ssh-agent`, `ssh-add` and the way multi-word git subcommands are named, e.g. `git update-index`. This approach gets verbose, though, particularly when we have get/set/remove names like `set-wallet-password`. In any case (pun intended!), I would not recommend using camel case / mixed case / pascal case, because they smell like Java. The CLI should not telegraph the preferences and conventions of the underlying programming language; it should be designed to fit well and feel right in a *nix environment / Bitcoin protocol stack environment. Likewise, if we went with snake case, it would feel perhaps more Python-esque than *nix-native.


Note that it could also be (not now, later) that we choose to go with a more sophisticated approach to the cli involving subcommands, e.g. `bisq-cli order create`, `bisq-cli wallet unlock`, `bisq-cli wallet show`, similar to the way, again, that the Git CLI is designed, (`git remote add <url>`, `git remote show origin`, etc).

So again, my 2 sats are to just hold off for now and let the continuing implementation inform the final design. Make this change once, later, when we're more confident about it, ideally with some real world users having tried things out and given some feedback. HTH.

**Comment by ghubstan** [comment]
Suggestions on improving the format of `cli` output were made in issue [4348](https://github.com/bisq-network/bisq/issues/4348).

**Comment by ghubstan** [comment]
All functionality required for a simplest possible trading script was merged in PRs before and including  https://github.com/bisq-network/bisq/pull/4966.  Work on scripts is in progress.

**Comment by ghubstan** [comment]
Issue will be closed when https://github.com/bisq-network/bisq/pull/5093 is merged.

**Comment by Kixunil** [comment]
Hey, great to see this merged. Quick question: would it be possible to write an alternative UI using this API? I'm mainly interested in having UI running on desktop detached from backend running on server, not changing the contents of the UI.

**Comment by ghubstan** [comment]
> Hey, great to see this merged. Quick question: would it be possible to write an alternative UI using this API? I'm mainly interested in having UI running on desktop detached from backend running on server, not changing the contents of the UI.

I can't say absolutely *not*, but it would be weird.  The api does not yet support all features of the Bisq desktop, and the api's server only works with the `gRPC` CLI.  (You can build scripts that run the CLI, see the regtest trading simulation scripts in `apitest`.)

If there is good adoption of the api after a louder release -- and it is stable, works and scales -- there is a good chance the back-end will be modified to serve RESTful HTTP 1.1 clients. When and if that happens would be the time start building alternative UIs.

**Comment by Kixunil** [comment]
Thanks for the answer! This is not urgent and I'm not concerned with gRPC vs REST - anything would work for me. Having all required APIs and a headless server is more important.

**Comment by ghubstan** [comment]
> there is a good chance the back-end will be modified to serve RESTful HTTP 1.1 clients.

I meant to say REST clients "too".  But there will have to be consensus among devs about how.  It will be awhile...

**Comment by Kixunil** [comment]
AFAIK REST can be auto-generated from gRPC spec (I believe LND does this), not sure about the details, so that way shouldn't be too difficult. Anyway, no rush, a few months is completely fine for me.

If my priorities change there's a good chance I will contribute to it myself, will let you know if it happens.

**Comment by ghubstan** [comment]
> AFAIK REST can be auto-generated from gRPC spec

Here is an experiment I did with a reverse proxy https://github.com/ghubstan/bisq-grpc-gateway.
But this is more than a few months away, even if the team agrees to do it this way.
