### ISSUE TITLE
Bisq allows deletion of a payment account despite open offers still using it

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#4274]
@sqrrm
#### Description

Bisq does not check if a payment account is in use before allowing the user to delete the payment account

#### Version

v1.3.4

### Steps to reproduce

1) have Alice create payment account X
2) have Alice create offer A with payment account X
3) have Alice delete payment account X with offer still open
4) have Bob take offer A from Alice

### Expected behaviour

After step 3, Alice should receive an error that she cannot delete payment account due to open offers using it

### Actual behaviour

After step 3, Alice can delete payment method despite having open offers using it.
After step 4, Alice receives the error popup in screenshot

### Screenshots

![9FBC7D2A-C06E-4EED-97AE-3B6CAA10AD14](https://user-images.githubusercontent.com/232186/82892045-b9841b00-9f89-11ea-9baf-611c835577af.jpg)

**Comment by ghost** [comment]
Bisq already checks to see if a payment account is in use before allowing the user to delete it.  I tried both fiat and altcoin accounts.  Is there another way the scenario outlined above can happen?

1. have Alice create payment account X
2. have Alice create offer A with payment account X
3. have Alice delete payment account X with offer still open

`You cannot delete that account because...` 

![image](https://user-images.githubusercontent.com/47253594/82947739-1b328e00-9f66-11ea-914b-98f09cff715a.png)


The current check:

        boolean isPaymentAccountUsed = openOfferManager.getObservableList().stream()
                .anyMatch(o -> o.getOffer().getMakerPaymentAccountId().equals(paymentAccount.getId()));
        isPaymentAccountUsed = isPaymentAccountUsed || tradeManager.getTradableList().stream()
                .anyMatch(t -> t.getOffer().getMakerPaymentAccountId().equals(paymentAccount.getId()) ||
                        paymentAccount.getId().equals(t.getTakerPaymentAccountId()));
        if (!isPaymentAccountUsed)
            user.removePaymentAccount(paymentAccount);
