### ISSUE TITLE
Error while confirming take offer

### ISSUE THREAD

**Issue by joetheedge** [bisq-network/bisq#4277]
### Description
After clicking Confirm Take Offer while buying btc process times out with error message requesting the issue be posted here. Log attached below

#### Version

v 1.3.4

[bisq_27-05-20.log](https://github.com/bisq-network/bisq/files/4698296/bisq_27-05-20.log)
#### Device or machine

Laptop i7 running Win10

**Comment by ghost** [comment]
In the log file above, the error `Insufficient money, missing 0.0001 BTC` was reported by the maker.  This is the same error fixed by PR #4182 which is scheduled to be part of the next release 1.3.5.
See also: https://github.com/bisq-network/bisq/issues/2293#issuecomment-616920070

**Comment by joetheedge** [comment]
So in the meantime I can't take this trade?

**Comment by ghost** [comment]
The offer maker did not sufficiently fund the trade with enough bitcoin (due to a bug when editing an open offer).  No one will ever be able to take that trade, its parameters are bad.  The offer needs to be canceled, but as far as I know only the person who entered it can do that.

After release 1.3.5 those kind of bad offers won't be able to be created any more, but the ones existing in the system will hang around until canceled.
