### ISSUE TITLE
Bisq tries to connect to local (pruned) node even if I specified custom node IP address.

### ISSUE THREAD

**Issue by Talkless** [bisq-network/bisq#4303]
### Description
I've been using `Use custom Bitcoin Core node` for quite some time. It lives on different computer on may LAN.

Recently I've started using _second_ instance of bitcoind, running on my laptop, in pruned mode.

`Use custom Bitcoin Core node` is still set, but Bisq still tries (and fails) and fails to use that local node:
```
birž.-14 14:56:35.702 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Attempting connection to [127.0.0.1]:8333     (0 connected, 1 pending, 1 max)    
birž.-14 14:56:35.702 [NioClientManager] INFO  o.b.net.NioClientManager: Connected to /127.0.0.1:8333                                                        
birž.-14 14:56:35.702 [NioClientManager] INFO  org.bitcoinj.core.Peer: Announcing to /127.0.0.1:8333 as: /bitcoinj:0.14.7.bisq.1-SNAPSHOT/Bisq:1.3.4/ 
birž.-14 14:56:35.703 [NioClientManager] INFO  org.bitcoinj.core.Peer: [127.0.0.1]:8333: Got version=70015, subVer='/Satoshi:0.18.1/', services=0x1036, time=
2020-06-14 14:56:35, blocks=634697                                                                                                                           
birž.-14 14:56:35.704 [NioClientManager] INFO  org.bitcoinj.core.Peer: [127.0.0.1]:8333: Peer does not have a copy of the block chain.         
birž.-14 14:56:35.704 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup: [127.0.0.1]:8333: Peer died      (0 connected, 0 pending, 1 max)
```

#### Version

v1.3.4, built from Git.

### Steps to reproduce

- Set `Use custom Bitcoin Core node` option and specify custom archival butcoind IP address.
- Launch local pruned `bitcoind`.
- Start Bisq.

### Expected behaviour

Bisq should not use local node if custom node IP address is explicitly specified.

### Actual behaviour

Bsiq trys to use bitcoind on localhost even if custom node IP address is specified.

#### Device or machine

Debian Sid amd64.

**Comment by ghost** [comment]
Have you tried using command line parameter `--ignoreLocalBtcNode=true`

**Comment by wiz** [comment]
@jmacxx I think he means that specifying custom Bitcoin nodes should automatically disable the local detected node

**Comment by ripcurlx** [comment]
> @jmacxx I think he means that specifying custom Bitcoin nodes should automatically disable the local detected node

I think that should be the case. @dmos62 do you remember the current setup of this flags?

**Comment by dmos62** [comment]
@ripcurlx how we setup our BTC client is complicated. [This](https://github.com/bisq-network/bisq/blob/d9eb1d8435fd58150a7fe60dd906155ad8c81a78/core/src/main/java/bisq/core/btc/nodes/LocalBitcoinNode.java#L53) is a place (not _the_ place, because there's more than one that makes this decision) where we define when to ignore a local BTC node and it doesn't take into account custom BTC nodes being passed.

I worked on cleaning these things up around the time of your leave and made progress, but eventually got bogged down by how difficult it is to describe what the correct behaviour is given all the various parameters, and also because I realised that I'll be more help doing other things at this time, because we're spread thin, so I shelved it (https://github.com/bisq-network/bisq/pull/4292).

Somewhat tangential, but there's also a PR gathering dust that adds detection and handling of misconfigured (e.g. pruning) nodes, including the local node: https://github.com/bisq-network/bisq/pull/4081 in this case it would cause Bisq to not use the pruning local bitcoin node.

**Comment by Talkless** [comment]
> @jmacxx I think he means that specifying custom Bitcoin nodes should automatically disable the local detected node

Yes.

**Comment by phenomeus** [comment]
> Have you tried using command line parameter `--ignoreLocalBtcNode=true`

still trying to connect to BTC Network. 
had to start with `./Bisq --ignoreLocalBtcNode=true` inside `cd /Volumes/Macintosh\ HD/Applications/Bisq.app/Contents/MacOS/` to get it to ignore a local and pruned BTC Node :/ 
before that I had it already working and pointing to a raspiblitz node. 

there is an update needed to the UI to get a warning and configuration possibility at the beginning during startup because otherwise the user is locked out to config or do anything

**Comment by Talkless** [comment]
Ping.

**Comment by dmos62** [comment]
> 
> 
> Ping.

We don't have the resources to properly address this at the moment, which would require a hefty refactor. Doing a dirty fix isn't worth it, because affected users are few and there's a workaround (`./Bisq --ignoreLocalBtcNode=true`).

**Comment by Talkless** [comment]
> and there's a workaround (./Bisq --ignoreLocalBtcNode=true).

Ouch, sorry, missed that. Thanks!

**Comment by phenomeus** [comment]
See here https://github.com/bisq-network/bisq/issues/3820 for Solution 
append `ignoreLocalBtcNode=true` inside
`~/Library/Application Support/Bisq/bisq.properties  `
