### ISSUE TITLE
1.3.5 fails to generate data for transactions.csv file

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/bisq#4333]
### Description

`EXPORT TO CSV` tool found under `FUNDS` ---> `TRANSACTIONS` ---> `EXPORT TO CSV` returns no data in v1.3.5. 

Tested the export in v1.3.4 and export did return a .csv with data. 

#### Version

1.3.5

### Steps to reproduce

Run version 1.3.4, click `EXPORT TO CSV`, download transactions.csv, open and data is available
Run version 1.3.5, click `EXPORT TO CSV`, download transactions.csv, open and data is NOT available
Identical data directory used.

### Expected behaviour

.CSV file to be populated with transaction data.

### Actual behaviour

.CSV file has no data

### Screenshots

![photo_2020-06-23_12-40-41](https://user-images.githubusercontent.com/55212954/85436533-d42cbe00-b54e-11ea-8c29-4d3dbd71785b.jpg)

File size discrepancy between v1.3.4 & v1.3.5

#### Device or machine

Ubuntu 20.04 LTS

also experienced on

Win 10, 64 bit, AMD CPU

**Comment by ghost** [comment]
The memo field was recently added to the transaction list, in #4229.

Need to handle memo field being null.
https://github.com/bisq-network/bisq/blob/b87ba9e5ca101357462614a6843c16667116a9b5/desktop/src/main/java/bisq/desktop/main/funds/transactions/TransactionsView.java#L248

        columns[5] = item.getMemo() == null ? "" : item.getMemo();



Also the number of column headings was not updated, it should be 7 instead of 6: 

https://github.com/bisq-network/bisq/blob/b87ba9e5ca101357462614a6843c16667116a9b5/desktop/src/main/java/bisq/desktop/main/funds/transactions/TransactionsView.java#L236

@petrhejna do you want to take care of fixing this?
