### ISSUE TITLE
Bug Report: CreateMakerFeeTx

### ISSUE THREAD

**Issue by sundaywar** [bisq-network/bisq#4336]
### Description

 Funding a transaction resulted in an error, screen capture & logs attached. 

#### Version

 1.3.5

### Expected behaviour

 Fund transaction without errors

### Actual behaviour

 Fund transaction impossible 

### Screenshots

￼
<img width="706" alt="bisq error" src="https://user-images.githubusercontent.com/50192212/85774075-5c3bd080-b6d3-11ea-8afa-f7b313f76c16.png">

#### Device or machine

 macOS

#### Additional info

[log file.log](https://github.com/bisq-network/bisq/files/4833040/log.file.log)

**Comment by ghost** [comment]
Interpretation of log file events:

``10:01:26 new offer is entered, fee is estimated @ 4160 bytes (16 sats/byte)``
``10:28:26 funds received from external source``
``10:30:31 offer is confirmed by user, fee is estimated @ 4680 bytes (18 sats/byte)``
``error pops up due to insufficient funds 520 sats missing``
``4680 - 4160 = 520 (missing amount).``

Summary: fees rose in between making the offer and confirming it.  Since funding was exact amount from an external wallet, the extra sats were not available to make the transaction.

Same issue raised by others in #4227, #4278.
PR #4266 was created over a month ago to solve this issue.  ping @sqrrm / @ripcurlx
