### ISSUE TITLE
Keep SEPA information shown in Open Trades view

### ISSUE THREAD

**Issue by stevenroose** [bisq-network/bisq#435]
I recently made an offer to buy Bitcoins using SEPA. Then I also accepted an other to buy some and made the SEPA payment. After some time waiting for the seller to confirm the payment and send the Bitcoins, the same person accepted my buying offer. However, I could not verify that it was the same seller.

If the Open Trades view showed me his SEPA information, I would have waited for him to confirm our open trade before I made the second SEPA transfer. Now I have two trades open with the same person, who might not be trustworthy.

**Comment by ManfredKarrer** [comment]
You can see the network ID (onion address) with the icon displayed in the offerbook table. WIth mouse over you see the onion address. With click on the trade ID in the trade screen you see all the details (payment account, onion address). I know that is not so obvious and easy to find and needs improvement usability-wise.

I have one dispute open where one trader is not reacting. Can you email me your onion address (settings/network) and/or can you check if you have an open dispute (Support/Support tickets)? 
Also try to restart the app, to see if you get a change in the trade screen or in the support screen. 
There might be a bug in the dispute chat system...

**Comment by stevenroose** [comment]
This issue is not about my personal issue, but a general feature request
because I see value in having the SEPA information available as long as the
trade is open.
Another use case is f.e. to identify which SEPA transactions from you bank
overview correspond to which open bitsquare offers.

Are you vetoing this feature request without a discussion or other
community input?
On May 7, 2016 13:03, "Manfred Karrer" notifications@github.com wrote:

Closed #435 https://github.com/bitsquare/bitsquare/issues/435.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
https://github.com/bitsquare/bitsquare/issues/435#event-653413632

**Comment by ManfredKarrer** [comment]
As said the information is there but unfortunately a bit hard to find (click on trade ID to open details popup). In the table row there is not so much space to display all. But I can add it as a tooltip text at the payment method. Also if you have done a successful trade you see that indicated as a green ring around the icon in the offerbook.
I am aware that the current implementation of that is not optimal and it is on the todo list to improve that.

The trader need to use th trade ID as reference text in the bank transfer so you should see that in your bank statement. I got reported once that a bank does not display that, what is strange as AFAIK it is standard for SEPA to support reference text.

-> vetoing this feature request: If I close a issue it does not mean that I ignore that, the opposite, the issues is on the todo list so i dont need to keep it here as well.  I want to keep the issue list for the actual open bugs and not for all todo items, otherwise it gets too messy here...
