### ISSUE TITLE
Can't build from souce, error on "git lfs"

### ISSUE THREAD

**Issue by hrqmonteiro** [bisq-network/bisq#4399]
### Description

Trying to build from source from the .tar.gz on Downloads section, and i got git lfs error.

#### Version

Latest

### Steps to reproduce

Just trying to build from source, and got this error, follows the full log:

```
./gradlew :seednode:build
> Task :assets:compileJava
> Task :assets:processResources
> Task :assets:classes
> Task :assets:jar
> Task :proto:extractIncludeProto
> Task :proto:extractProto
> Task :proto:generateProto
> Task :proto:compileJava
> Task :proto:processResources
> Task :proto:classes
> Task :proto:jar

> Task :common:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :common:processResources NO-SOURCE
> Task :common:classes
> Task :common:jar

> Task :p2p:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :p2p:processResources FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/hrq/Downloads/bisq-1.3.6/build.gradle' line: 280

* What went wrong:
Execution failed for task ':p2p:processResources'.
> p2p data store files have not been synchronized. To fix this, ensure you have Git LFS installed and run `git lfs pull`. See docs/build.md for more information.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
13 actionable tasks: 13 executed
make: *** [Makefile:120: seednode/build] Error 1
```
### Expected behaviour

To build properly, i guess

### Actual behaviour

Just explained above.

### Screenshots

None

#### Device or machine

Void Linux

#### Additional info

None

**Comment by hrqmonteiro** [comment]
Update:

I forgot, doing the "git lfs pull" simply does nothing since it is not a git repository.

```
bisq-1.3.6 $ git lfs pull
Not in a git repository.
```

**Comment by m00nstar** [comment]
Hi!
Confirm. I have the same error. Can't build from tar.gz archive since version 1.3.5.

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :common:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :common:compileTestJava
Note: /home/ogv/bisq-1.3.6/common/src/test/java/bisq/common/app/CapabilitiesTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :p2p:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :p2p:processResources FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ogv/bisq-1.3.6/build.gradle' line: 280

* What went wrong:
Execution failed for task ':p2p:processResources'.
> p2p data store files have not been synchronized. To fix this, ensure you have Git LFS installed and run `git lfs pull`. See docs/build.md for more information.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 52s
25 actionable tasks: 25 executed

**Comment by hrqmonteiro** [comment]
> **Thanks for opening your first issue here!**
> 
> Be sure to follow the issue template. Your issue will be reviewed by a maintainer and labeled for further action.

I followed the template.

**Comment by slackmaster21** [comment]
Same problem as above. 

$ sudo ./gradlew build

> Task :assets:compileJava UP-TO-DATE
> Task :assets:processResources UP-TO-DATE
> Task :assets:classes UP-TO-DATE
> Task :assets:jar UP-TO-DATE
> Task :assets:assemble UP-TO-DATE
> Task :assets:compileTestJava UP-TO-DATE
> Task :assets:processTestResources NO-SOURCE
> Task :assets:testClasses UP-TO-DATE
> Task :assets:test UP-TO-DATE
> Task :assets:check UP-TO-DATE
> Task :assets:build UP-TO-DATE
> Task :proto:extractIncludeProto UP-TO-DATE
> Task :proto:extractProto UP-TO-DATE
> Task :proto:generateProto UP-TO-DATE
> Task :proto:compileJava UP-TO-DATE
> Task :proto:processResources UP-TO-DATE
> Task :proto:classes UP-TO-DATE
> Task :proto:jar UP-TO-DATE
> Task :cli:compileJava UP-TO-DATE
> Task :cli:processResources UP-TO-DATE
> Task :cli:classes UP-TO-DATE
> Task :cli:jar UP-TO-DATE
> Task :cli:startScripts UP-TO-DATE
> Task :cli:distTar UP-TO-DATE
> Task :cli:distZip SKIPPED
> Task :cli:assemble UP-TO-DATE
> Task :cli:compileTestJava UP-TO-DATE
> Task :cli:processTestResources NO-SOURCE
> Task :cli:testClasses UP-TO-DATE
> Task :cli:test UP-TO-DATE
> Task :cli:check UP-TO-DATE
> Task :cli:installDist
> Task :cli:build
> Task :common:compileJava UP-TO-DATE
> Task :common:processResources NO-SOURCE
> Task :common:classes UP-TO-DATE
> Task :common:jar UP-TO-DATE
> Task :common:assemble UP-TO-DATE
> Task :common:compileTestJava UP-TO-DATE
> Task :common:processTestResources NO-SOURCE
> Task :common:testClasses UP-TO-DATE
> Task :common:test UP-TO-DATE
> Task :common:check UP-TO-DATE
> Task :common:build UP-TO-DATE
> Task :p2p:compileJava UP-TO-DATE
> Task :p2p:processResources FAILED

FAILURE: Build failed with an exception. Just did it again with ./gradlew :seednode:build and same result

* Where:
Build file '/home/_nonyabiz_/Desktop/bisq.git/trunk/build.gradle' line: 280

* What went wrong:
Execution failed for task ':p2p:processResources'.
> p2p data store files have not been synchronized. To fix this, ensure you have Git LFS installed and run `git lfs pull`. See docs/build.md for more information.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
25 actionable tasks: 2 executed, 23 up-to-date
$ git lfs pull
Not in a git repository.

**Comment by freimair** [comment]
yeah, since we switched over to git lfs for the massive binary files, the source tarball created by github does not work anymore (because it does not include the binaries). Came as a surprise to us as well.

Use git's shallow clone features instead:

`git clone --depth 1 https://github.com/bisq-network/bisq.git`

if you do a `git lfs install` once, then there is no need to use `git lfs pull` anymore.

**Comment by cd2357** [comment]
Closing the issue, as @freimair provided a solution above.
