### ISSUE TITLE
WARNING ABOUT 5.46 BSQ FLOOR

### ISSUE THREAD

**Issue by zuardi** [bisq-network/bisq#4439]
### Description

Since 1.3.7, PR #4383 added a 5.46 BSQ floor amount to prevent dust errors. The problem though is the user isn't  educated about that, it only shows a insufficient BSQ warning, which worries those that have otherwise enough BSQ.
Please, just add a explanation about the floor amount when the user tries to spend it.

#### Version

1.3.7

### Steps to reproduce

Trying to spend BSQs when you have less than 5.46 

### Expected behaviour

Warning explaining you are not allowed to spend that coins.

### Actual behaviour

Just "insufficient funds" warning

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/47253594/91364862-4aef6d00-e7c5-11ea-9d4b-7fc197fa6e8a.png)

I propose including this above the last line:

`(Note: the last 5.46 BSQ in your wallet cannot be used for trade fees due to dust limits in the Bitcoin protocol)`

@m52go as the resident wordsmith, what do you think?

**Comment by m52go** [comment]
@jmacxx I suggest:
```
popup.warning.insufficientBsqFundsForBtcFeePayment=You''ll need more BSQ to do this transaction—the last \
5.46 BSQ in your wallet cannot be used to pay trade fees because of dust limits in the Bitcoin protocol.\n\n\
You can either buy more BSQ or pay trade fees with BTC.\n\n\
Missing funds: {0}
```
