### ISSUE TITLE
Cannot withdraw BTC funds

### ISSUE THREAD

**Issue by djogwe** [bisq-network/bisq#444]
When attempting to withdraw the funds in my BTC wallet on the exchange, I get the error:

java.lang.reflect.InvocationTargetException

Any assistance resolving this issue would be greatly appreciated.  Thanks!

**Comment by ManfredKarrer** [comment]
Do u have the latest version installed? v0.4.6
There was an issue in the previous version but that shoud be fixed in 0.4.6.
If you has the latest version, can you send me by email (on the webpage u find my email) the data directory including the wallet? you need to remove password protection otherwise i cannot access it. i promise that i dont steal u the btc :-).
if you dont want to do that you can try to empty the wallet with ctrl+e (or cmd+e). but that would close all open offers if you have any.

**Comment by ManfredKarrer** [comment]
I assume u used the older version where that bug was reported. If not please re-open and provide mroe info.
