### ISSUE TITLE
"shut down and start again" button doesn't start again

### ISSUE THREAD

**Issue by riclas** [bisq-network/bisq#453]
when bitsquare reaches 4 minutes trying to start, this warning window comes up with a button that says "shut down and start again". When I click it, only the shut down part happens.

as an aside, this delay trying to start usually happens after i boot by windows pc from suspended mode. I have to reboot the pc so it can connect to Tor.

**Comment by ManfredKarrer** [comment]
"shut down and start again" meant manual start again as that is a bit more complicate to restart that app by itself. Will change the wording so its becomes more clear.

Can u explain more your situation with suspended mode?
If u have offers opens you should deactivate sleep mode otherwise your offers are not available to others (they get removed and get re-added when u go online again). Monitor sleep mode i sok of course...
Even if you have suspended mode and you awake your machine or if u lose internet connection it should recover by itself, but that takes a bit (few minutes).
Do you shutdown Bitsquare after suspended mode and after that you get the timeout?

**Comment by riclas** [comment]
ok, the wording option seemed the more plausible to me too.

I shutdown bitsquare, go to suspended mode, come back of suspended mode, start bitsquare: get timeout.

today it managed to connect after 5 or 6 tries, but it is not always like this. maybe it's some problem with the underlying Tor service? i don't know.

**Comment by ManfredKarrer** [comment]
Hm strange I never saw that. Do you wait the few seconds until Bitsquare is fully shut down?
Do you have a fast and stable internet? But should not be an issue, when I was traveling I had many pretty bad internet connections in hotels and had only once issues, but there internet was not useable also for normal browser.
During testing I saw sometimes that Tor connections was very bad, but usually with a restart it should get another route and be ok again. 
If you dont have offer/trades/disputes open then you could try to manually remove (backup just in case) the tor directory inside the data dir. Then you get a new onion address and past traders where you earned some sort of reputation (green reing around icon) will see u as a new node. Maybe your onion address got somehow flagged (I am not aware of something like that though).

**Comment by riclas** [comment]
nahh i don't think that's the issue... i have only experienced this when coming out of suspension mode. but i agree it is weird. i don't know if it's a real issue, i'll make a new one for it if it keeps happening.

**Comment by ManfredKarrer** [comment]
Why u use suspension mode (sleep mode)? If u have offers they get removed....

**Comment by riclas** [comment]
because right now that's the only use for my PC during my sleep time, so i suspend it.
