### ISSUE TITLE
Unconfirmed bitcoin show up in my bitsquare wallet.

### ISSUE THREAD

**Issue by kristoffernolgren** [bisq-network/bisq#456]
I'm still struggling a little bit to figure out how bitsquare works, so I might have gotten this wrong.

I made a transaction with ID e996bd5fe24014844e50cb037f5a4e8476440740a4104d8f5fe4936aa84a2da to my bitsquare wallet. The funds now show up in my bitsquare wallet. I tried to use them to make a trade. The trade has now been blocked in the blockchain-confirmation-stage for 24 hours, canceling the trade. I believe the reason is that the initial transaction was not confirmed. I believe non confirmed bitcoins should not be concidered available funds in bitsquare.

Love the platform, this is some truly revolutinary shit going on here!

**Comment by ManfredKarrer** [comment]
Yes if the funding tx does not have sufficient fees it might get delayed too long and then blocking any follow up trade transactions. I tried to cover that issue with a fee check but that caused more problems as it solved, so I removed that fee check. Most people use the option to load up their local bitsquare wallet and even with low fees after a few hours the funds get usually confirmed. Fees of min 0.0001 bct are considered as safe to get confirmed quickly. 
I have one trade open (trade id: c28d05fd) with such a case and it might be that it is your trade :-).
If so we can just wait longer until your funding tx gets into the blockchain or we open a dispute and refund the payments. 
If that is your trade please let me know how do you prefer to proceed. For me it is ok to wait a few day more until the tx gets confirmed, otherwise we can open a dispute. Just saw that the open dispute button is not displayed in that screen. I will fix that and I can open the dispute if you want to.

What was the fee you paid when funding the Bitsquare wallet?

**Comment by kristoffernolgren** [comment]
I used the default fee that was suggested by bitsquare, 0.00000356 BTC, one mistake I did was that I accidentally used an old version of bitcoin-qt to transfer my funds (now upgraded, and I don't think that was the problem. The transaction to bitsquare is still not confirmed, closing 72 hours now I think. Yes, c28d05fd is mine.

Thank you very much for your help so far, again, a really cool project, I love the implementation from a overall design perspective and I very much concider this a core building block for bitcoin, though still a bit rough around the edges ux-wise.

**Comment by kristoffernolgren** [comment]
I'd also be happy to wait for a few days, not sure if the seller is though, specially since the price has dropped conciderably since our transaction ;)

**Comment by ManfredKarrer** [comment]
When funding the Bitsquare wallet there is no fee suggestion, the external wallet sets the fee and with an old Bitcoin core wallet the fee u mentioned is very low. 0.00001 btc ic currently a reliable fee. So with that 0.00000356 BTC fee it might take a while. We can wait for a week and if its not confirmed until next thursday we can close it with opening a dispute.

Thanks, great to hear u like the project! Yes there is still much work to be done... IF you want to contibute in any area feel free to join our forum.

**Comment by kristoffernolgren** [comment]
That sounds like a good plan!

I work as a webb-developer and UX designer (usability, not visual designer) I think I could make some contributions if the developers/developer feel like that is a priority right now.

**Comment by ManfredKarrer** [comment]
You are welcome to contribute! Though my main priority now is to work on the DAO. As soon I have a dedicated UI dev (JavaFX) there will be more space for improvements. But if you have any recommendations/suggestions let me know, if its is not much effort I might be able to squeeze it in...

**Comment by kristoffernolgren** [comment]
I totally get you!

I'll try to put together a few high-concept thoughts later on, maybe they can serve as inspiration.

A sort of low haning fruit I think is making "available balance" a more prominent concept in the design, maybe that with a dark background instead of market exchange rate. When I started using the app I didn't realize it had it's own built in bitcoin-wallet and it took me quite some time before i Realized that is what I did the purchase.

**Comment by ManfredKarrer** [comment]
Yes I agree the internal bitcoin wallet is not clear enough. If u have any graphical suggestions (best as a design suggestion) please let me know. The market rate though should be prominent as well IMO.

**Comment by kristoffernolgren** [comment]
I spent a few hours to put something together, I see that this is way more than a quickfix, but maybe it could serve as an inspiration.

https://forum.bitsquare.io/t/i-made-a-ux-concept/165

**Comment by ManfredKarrer** [comment]
Close that issues as it follows up in the forum...
