### ISSUE TITLE
Question about Bisq's SPV bloom filtering algorithm and Monero full node

### ISSUE THREAD

**Issue by scottcarter2020** [bisq-network/bisq#4570]
Hello,

As far as I know, Bisq is using SPV bloom filtering algorithm.

By using SPV bloom filtering algorithm, I'm not trusting a third party, but I'm pretty much leaking all my information to blockchain analysis and surveillance companies.

What is the team official reply to this article, https://jonasnick.github.io/blog/2015/02/12/privacy-in-bitcoinj/ ?

And does Bisq use a Monero full node by default, as if not, there must be huge network level leaks on the Monero side too.

Thanks.

**Comment by chimp1984** [comment]
That paper and the bloom filter problematic is long know to Bisq devs. The main mitigation we did was that Bisq connects only to Bitcoin nodes operated by Bisq contributors (bonded roles). Of course there is still a trust issue, but Bisq contributors have a incentive to not sell off user data to chain analysis companies and hurting their own investment. 
If users run a local unpruned node it automatically connects to that node only. This is the best option.

We investigated alternatives but at least back then (https://github.com/bisq-network/bisq/issues/1062#issuecomment-446755367) there have not been any feasible candidate. Getting away from BitcoinJ is still a goal but resource/budget restrictions are a unfortunate reality we have to deal with as well. 

See:
https://github.com/bisq-network/bisq/issues/1062
https://github.com/bisq-network/bisq/issues/414
https://github.com/bisq-network/bisq/issues/487

Regarding Monero:
I assume you refer to the auto-confirm feature. The exolorer nodes are hosted by Bisq contributors as well and they run full nodes.
Otherwise Bisq has nothing to do with the XMR blockchain. It is up the XMR trader to send XMR and check receipt.

**Comment by scottcarter2020** [comment]
Thank you for your answer, chimp1984.

Regarding Bitcoin:

What kind of information I may leak if I configured Bisq to connect to my local node ?

Regarding Monero:

Could I configure Bisq to connect to my local node ?

What kind of information I may leak if I configured Bisq to connect to my local node ?

Thanks.

**Comment by cd2357** [comment]
@scottcarter2020 There are two ways to connect to your own bitcoin node:
1. run a local unpruned node on the same host as Bisq, and
2. you can tell Bisq to only connect to one (or a list of) bitcoin nodes under your control, or that you trust. In this case, they don't have to run on the same host as Bisq. You can configure this under Settings > Network info > Bitcoin network.

Not sure what is leaked to the Bisq network if you use your own bitcoin node, I assume only the payout address and the trade-related transactions (pay deposit and fees tx, payout tx). And even then, I think this is only visible to the parties involved in the trade, plus evtl mediators. Someone with more knowledge here please correct me if I'm wrong.

**Comment by scottcarter2020** [comment]
Thank you for your answer, cd2357.

Would like to hear from @chimp1984 again.

And what @wiz and @ripcurlx could say about this ?

**Comment by wiz** [comment]
You're welcome to use my Bitcoin nodes or block explorer website, but if privacy is a concern then I would you suggest to setup a Raspberry Pi at home to run your own Bitcoin or Monero nodes, and configure your Bisq node to use those instead.

**Comment by chimp1984** [comment]
From BitcoinJ bloomfilter side you have the issues resolved  if you use a loca node. In Bisq all network traffic goes over tor (only exception is in-app download but you dont need to use that).
The main issue remaining is to not link together all your trade on the blockchain by using outputs of one trade as input for the next. This is not as trivial to achieve if you dont seperate each trade at funding and withdrawing at the end.
So if you fund a bisq trade from external wallet with untainted coins (e.g. out of wasabi) and then when trade comleted to send it out again to wasabi or a separated wallet your trades are not connected on the blockchain. 
But it is all relative, even if your trades get connected one can derive that one entity has traded x times on Bisq but does not know the identity as long you are not trading fiat where the peer will see your payment method data and thus get some link to your real life ID. But that is only visible to the peer. If you trade altcoins it depends on your behaviour on the altcoin chain as well how much the altcoin provides privacy. XMR is clearly the best in that regards.

Privacy is not a binary thing, and things get quickly pretty complex....

**Comment by cd2357** [comment]
@ManfredKarrer wrote a more comprehensive blog post about this some years ago: https://bisq.network/blog/privacy-in-bitsquare/

Closing this, as it's been answered.
