### ISSUE TITLE
Delayed payout tx is not providing tx confidence

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4650]
### Description

When the delayed payout tx gets broadcast (opening arbitration) and the tx gets confirmed (as it can be seen at receiver) the tx in the Bisq wallet does not change the confidence to type building and stays pending. The tx spends all the funds from the 2of2 multisig where both traders have been the key holders to a 3rd party address (burningman). From my understanding as the multisig is a part of the users wallet the user should receive the confidence update as its a wallet tx.
@oscarguindzberg Any idea why we don't get the confidence update? 

### Steps to reproduce

Make a trade and open mediation and later arbitrtion. On regtest it requiers 5 blocks.

**Comment by oscarguindzberg** [comment]
The bitcoinj wallet is interested in txs sending funds to/from one of the wallet addresses.
The trade p2sh-multisig address is not part of the wallet (even you do kind of a hack by taking one of the wallet keys to creating the p2sh-multisig address).
I don't know how the delayed payout tx gets into the wallet (you add it manually?)... probably the wallet ignores the tx because Wallet.isTransactionRelevant(tx) returns false.
Probably bloom filters are not updated to be notified of txs sending to/from the p2sh-multisig address.
You may ask why the problem does not happen in normal "payout tx"s? because they send funds to one of the wallet addresses.


How to solve it.

You have to get the bloom filters updated.
One way of doing it is by using the wallet's watched addresses feature. See Wallet.addWatchedAddress(). You can use that to add the p2sh-multisig address. I think that may affect the wallet balance and coin selection for changing, so I am not sure that is a good idea.
You could create a new wallet just with a watched p2sh-multisig address.
Or you can update manually the bloom filter somehow to include the p2sh-multisig address or the burningman address.
There is also the MarriedKeyChain class that also deals with p2sh-multisig, but that is not the place to look at... just telling to avoid doing useless research there.
In any case, the bisq btc wallet is not interested in the delayed payout tx, so maybe you would have to keep the tx out of that wallet and deal with updating confirmation status by other means.

I am talking from the top of my head, so consider everything I wrote as "things to evaluate".

**Comment by chimp1984** [comment]
Thanks. Just for interest: Would the legacy multisig (not P2SH MS) make a difference here? Then the keys are not hidden in the hash but are part of the tx.

Anyway not a big problem, just wanted to check if its some bug or a conceptual issue, and as you confirmed its that.
We will add API requests anyway at some points for getting mempool/confirmation info about non-wallet txs (peers trade fee tx, mediators/arbitrators to check trade txs). Then we could add that as well.

Is the watched addresses feature assuming that the watched address is a own wallet address (thus using it for input selection, balance,...)? If so its a pity as otherwise it would be more useful for easily updating the bloomfilter for wallet-foreign txs.
