### ISSUE TITLE
Disallow Transferwise from SEPA markets

### ISSUE THREAD

**Issue by getemp2020** [bisq-network/bisq#4698]
Following a private discussion with Bisq team, a consensus has been reached on temporarily disallowing Transferwise accounts from participating in SEPA markets.

## Background

Transferwise is an e-money institution that provides cross-border money transfers and SEPA IBANs to account holders. However, they appear to block sending to IBANs of some Bisq users without good explanation, which results in having to reverse a trade through mediation thus making Transferwise unreliable for trading in SEPA markets.

cc @m52go @bisq-knight

**Comment by viperperidot** [comment]
How would you 'disallow' Transferwise SEPA accounts?

**Comment by getemp2020** [comment]
> How would you 'disallow' Transferwise SEPA accounts?

The same way we do Revolut ones

**Comment by viperperidot** [comment]
Which is how? This post doesn't really explain anything.

@getemp2020

**Comment by Bisq-knight** [comment]
We discussed this sort of at length in Keybase.

My view is that I've had a few cases (3 in total) where the BIC used was Transferwise's and only 1 trade had the problem described above. I don't think we should block their BIC the way we do Revolut, but we should keep an eye out for it and be transparent with users about it. If they want to use these light fintech banks as SEPA there are also other alternatives that could work better. 

From what I can remember in dealing with cases N26, Monzo and Bunq all worked ok as SEPA accounts although I do not have personal experience with them.

**Comment by viperperidot** [comment]
I missed the Keybase discussion, if you tell me the channel and when it occurred I can try and look back at it.

None of those alternative options are available in my country, also Transferwise has a new feature where you get to create your own SEPA bank account so I don't think we will have any issues with it moving forward if people switch to that method. 

And I don't think having a few issues with a payment method is enough to justify shutting it down, you can have issues with any payment method even traditional banks. I think we need to allow good Fintech options because they will inevitably lead to more growth on Bisq as users can gain access to different liquid markets that would otherwise be unavailable to them. Bitcoin is global so I think we should keep global fiat onramps open too.

I think it just comes with the territory that every once in a while there may be an issue that is out of our control but that can be dealt with and resolved by the parties involved.

**Comment by pazza83** [comment]
I think TransferWise should be allowed on SEPA markets. 

One of the benefits of TransferWise is that it enables users not based in the Europe to trade with a SEPA account on the EUR/BTC market in Bisq, this opens up more markets to Bisq users, increase liquidity, and promotes growth.

OP has raised concerns with regards TransferWise to the mediators. I am sure it will become apparent if there are issues with multiple traders not being able to successful transact where one party is using TransferWise.

To complete a successful trade on Bisq EUR/BTC market using TransferWise a user has to set up a EU account with it's own IBAN.  This process is pretty self explanatory but not immediately obvious. Maybe a wiki guide would be useful?

**Comment by m52go** [comment]
@wiz @leo816 do you have anything to add? In your experience, do Transferwise accounts have issues sending/receiving money from traditional banks?

Of course it would be better to keep Transferwise allowed in SEPA trades, unless we _know_ there are issues with doing so. It would only make sense to take action if we can establish more evidence.

**Comment by viperperidot** [comment]
I totally agree with @pazza83, for people who live in countries where their local markets are very non-liquid Transferwise allows them to access the best markets offered on Bisq, making it a viable platform for them to trade with. A lot of users who are on the fence about adopting P2P trading platforms will not want to wait days to get an order filled or pay very high premiums on their local markets, so services like Transferwise should drive Bisq adoption. Ideally all local markets will be liquid and we will get their one day but that's not the case right now. 

I have had successful trades where only 1 party is using Transferwise, I think the key to making things smoother is using their new feature called 'Multi-currency account'. This is where you actually set up a real bank account in the country of your choice and get assigned personalized banking details, it is different than their original model where you just sent money. Because it is a new feature I think not many people know about it yet, here is a link for more details: https://transferwise.com/multi-currency-account/

I believe this method requires stricter KYC to register, which probably makes transfers go smoother after the fact. That and the fact that you are actually adding money into your own bank account and sending from there to your Bisq peer rather than the money coming from a Transferwise account.

I can volunteer to create a Wiki post about setting up this type of account if people think that would be useful.

**Comment by pazza83** [comment]
I agree the 'Multi-currency account' is currently the only way to use TransferWise successfully on Bisq and keep within the Bisq trade protocols. If TransferWise to TransferWise was set up as a payment method this may also work

From my experience using TrasferWise only setting up a New Romanian Leu account required additional KYC. 

@viperperidot I will send you a message on Keybase about trialing a TW to TW payment if you are interested. This should involve only needing to require an email address.

**Comment by viperperidot** [comment]
Yes the 'Multi-currency account' does follow the Bisq trading protocol because the account details of the bank match the account details listed on Bisq. 

I was also curious about the TransferWise to TransferWise option, this would actually be a very good payment method for Bisq to use for a couple reasons. 

1. It supports basically all fiat currencies 
2. It requires the least amount of personal information than I think most other payment methods

As pazza said, I think the only thing required for this method is an e-mail address which provides a great amount of privacy. It would take some user adoption to get the market liquid but it might take off. 

@pazza83 Sure we could try that, especially if the Bisq group is considering adding it as a payment option.

**Comment by pazza83** [comment]
@viperperidot Yes I agree.

There is a proposal about it here: [#243]( https://github.com/bisq-network/proposals/issues/243)

With regards adoption TransferWise has about 8 million users compared to Revolut's 12 million so I think there will be a good user base to begin with.

I have messaged you in Keybase

**Comment by chimp1984** [comment]
> Following a private discussion with Bisq team, a consensus has been reached on temporarily disallowing Transferwise accounts from participating in SEPA markets.

I do not see that there have been reached any consensus, quite the opposite.

**Comment by viperperidot** [comment]
> > Following a private discussion with Bisq team, a consensus has been reached on temporarily disallowing Transferwise accounts from participating in SEPA markets.
> 
> I do not see that there have been reached any consensus, quite the opposite.

Yes I kind of thought this was a bit strange, I don't know exactly how Bisq works but I thought it was weird that there was a 'private discussion' held about which payment methods would be allowed on the platform. I thought everything in Bisq including the development was supposed to happen out in the open in publi,c with discussions that included anybody who is interested in Bisq. I thought that was the point of the DAO to keep things decentralized, maybe I misunderstood and there are still items that get discussed privately like what happened here.

Also I am not sure who the OP is, it looks like they created a temp account specifically to create this post so I don't know who they are in the community like on Keybase for example. And lastly, I think it would have been good to link to the specific issues with TransferWise referenced in the OP, there must be some documentation of them to substantiate the claim that it is an unsuitable payment method. I don't actually think whoever was going to implement this did enough research on TransferWise because I don't think it is actually possible to block them similar to Revolut, like what was mentioned here. Because each user has their own unique banking details, with the new feature they implemented it essentially makes a TransferWise account no different than any other SEPA account.

**Comment by chimp1984** [comment]
@viperperidot Sure all is public, but that does not mean that any can open private chat rooms for either discussing things which include private information (e.g. details about problems with trades as in that case) or just because they had the feeling that it is not yet ready for public discussion (e.g. brainstorm ideas, get opinions,...). The initial statement of @getemp2020 was his private statement and does not reflect that this would be any "official" process. Official process is to make a proposal for any bigger change or issue if its a small issue.

**Comment by viperperidot** [comment]
Ok thanks for the clarification, I thought this was an 'Official' statement that this proposal was moving ahead.

**Comment by Bisq-knight** [comment]
upon closer review of my cases I summarize them in the following way. Which is contrary to I initially shared as they were cases that had different summary formats.

I've had 3 cases with the TW BIC as the payment details. 
* All 3 TWs were used by buyers
* 2 were small trades (0.01 BTC) and one was a tad larger (+0.03 BTC)
* 2 cases were with the same individual TW account (which is pretty old btw +100 days old at the time of the mediation case)
* All 3 buyers could not send the money to the seller and had to be reverted (or sorted through different means)

With all that in mind I can tell that we don't have enough evidence to say that it is a general issue affecting Sellers and the age of the account would hint at it actually working (why would you keep an account for so long if it didn't work?).

I suggest we:
* keep this discussion open and make it more visible to other people in Keybase >> we could actually be having such a problem, and not know about it as it can be solved by traders chatting to each other directly
* when we have a larger sample we make a call. I'd say some **10 cases with distinct buyers facing the same problem** would be enough to justify such an action. (I honestly don't know what was the rationale behind doing that to Revolut's SEPA) (and of course we can discuss the 10 cases threshold)

**Comment by Conza88** [comment]
Massive NO from me. Only issue with Transferwise is documentation and folks seemingly not marking a primary account as part of process, so you can't just use email. You tell them, they fix, and sorted.

**Comment by chimp1984** [comment]
I think this can be closed as it pretty clearly did not find support.
