### ISSUE TITLE
Add US Dollar option for european banks

### ISSUE THREAD

**Issue by AlexMinty** [bisq-network/bisq#471]
Please add USD option for Euro banks. I'm sure a fair few people in Europe, like myself, have USD accounts.

**Comment by othexmr** [comment]
i second that, i have USD accounts with german banks, it´s quiet common if you do oversees business.

**Comment by ManfredKarrer** [comment]
Do you mean for the national bank transfer or the Sepa option?
International bank transfer is not supported as it is usually too expensive and slow.

**Comment by AlexMinty** [comment]
Why not both :)

**Comment by ManfredKarrer** [comment]
I have no experience with such duo currency accounts. Can you transfer via SEPA also USD to another SEPA account or would it be treated as international transfer? International fiat transfer is very expensive and slow afaik, so that is why we did not consider to add that. If you can transfer USD inside the SEPA system I will add it. The same apply to national transfer. The only thing what needs to be avoided is that the receiver gets a bad surprise with some extra fees (or automatically exchange to his main currency). The fees for the sender of the Fiat also need to be less than 20 EUR otherwise the realtion of trade amount and fee would be to bad.

**Comment by ManfredKarrer** [comment]
@AlexMinty 
As soon as I have sufficient background info I will add that. 
At our forum we have a section regarding payment methods:
https://forum.bitsquare.io/c/payment-methods

**Comment by haiqu** [comment]
Certain bank accounts in Australia can also be denominated in foreign currencies. Being able to select one (or more) from a list of available currencies would be nice.

**Comment by ManfredKarrer** [comment]
For national bank account you can select any currency. That has been changed already a while ago. I think with SEPA account you cannot transfer USD. Will close...
