### ISSUE TITLE
BSQ Fees equivalent not correctly calulated into BTC in info tooltip

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4959]
### Description

When I am about to create trade I see this amount of fees:
![image](https://user-images.githubusercontent.com/383295/102335293-fba99400-3f8f-11eb-85d6-bede383c6b21.png)

However on the next screen, I see this:
![x](https://user-images.githubusercontent.com/383295/102335929-d2d5ce80-3f90-11eb-9e4b-c468fdb3cb67.png)

Which is currently:
![image](https://user-images.githubusercontent.com/383295/102336074-fac53200-3f90-11eb-9ef2-bf9a372ff62d.png)

#### Version

`v1.5.1`

### Steps to reproduce

See description.

### Expected behaviour

The numbers will match.

### Actual behaviour

See description.

**Comment by p2051** [comment]
It seems that the BSQ trade fee calculation is broken, a more grave example:

When I create a new trade the BSQ trade fee is calculated as 1 BSQ ~= 1.30 EUR
![bug01](https://user-images.githubusercontent.com/35586793/105431771-9b74d480-5c56-11eb-8be9-b3dd9627bb5d.png)

With BTC/EUR (24230 EUR - calculated based on the price in the screenshot above) and BSQ/BTC (0.00006900 BTC) current price being
![bug03](https://user-images.githubusercontent.com/35586793/105431842-bfd0b100-5c56-11eb-8a0e-6bb3c72e8d70.png)

and on the next step the BSQ/BTC calculation is done with 0.000001 BTC
![bug04](https://user-images.githubusercontent.com/35586793/105432023-12aa6880-5c57-11eb-815e-23dabd836998.png)

Based on the current price of BSQ the trade costs 1.67 EUR.

Therefore there are these issues:
1. [ ] The "trade fee" on the initial screen "Create Offer" screen is miscalculated; displayed as ~= 1.30 EUR instead of ~=1.67 EUR
2. [ ] The "trading fee" on the follow-up screen (in alt-text info is misrepresented and miscalculated; displayed as ~= 0.000001 BTC (0.03 EUR) instead of current pricing of ~= 0.000069 BTC (1.68 EUR)
3. [ ] Nomenclature mismatch, in the initial screen it is called "trade fee" on follow-up screen it is called "Trade fee" as label and "trading fee" in the text

**Comment by ghost** [comment]
@ripcurlx This issues seems to be outdated and could be closed - described problems was [fixed](https://github.com/bisq-network/bisq/pull/4985)
