### ISSUE TITLE
Request: Interac e-transfer

### ISSUE THREAD

**Issue by nvk** [bisq-network/bisq#500]
In Canada, all banks support sending and receiving e-interact email money transfer. It would be great if it was supported. 

Learn more here http://interac.ca/en/interac-e-transfer-consumer.html

Keep up the great work.

**Comment by ManfredKarrer** [comment]
Thanks a lot!
I added it to our payment method section in the forum.
https://forum.bitsquare.io/t/request-interac-e-transfer-for-canada/261
Hope we can investiagte and add it soon.

**Comment by nvk** [comment]
Thanks!

**Comment by gosuto-inzasheru** [comment]
Is this coming soon?

What you state on the forums is correct, all you need is someone's email address and a passphrase. An email gets sent that contains a link through which the other party logs in using online banking credentials. After providing the passphrase (to prevent MitM or just plain sending to the wrong address by accident) funds are transferred to an account of receiver's choice. Confirmed transactions are direct, definite and rollbacks are not possible. Transaction offers/links expire after 30 days.

http://interac.ca/en/interac-e-transfer-consumer.html

**Comment by ManfredKarrer** [comment]
I did not had time to add that to the current release. But put it on my hi prio todo list.

**Comment by ManfredKarrer** [comment]
@jorijnsmit 
Could you confirm that the secret question + answer in not mandatory?
See discussions here:
https://forum.bitsquare.io/t/request-interac-e-transfer-for-canada/261/9?u=manfredkarrer

If it is not required then it needs email or mobile nr. only, right? No Holder account name.

**Comment by gosuto-inzasheru** [comment]
Indeed no holder account name (or any other account information for that matter) is needed. Interac acts as an intermediary that transfers funds between two Canadian bank accounts. [Practically all banks support Interac e-Transfers](http://interac.ca/en/interac-e-transfer-consumer.html). To do this the sender logs in to his online banking space where he initiates an Interac e-Transfer. Sender is obligated to provide:
- transfer amount in CAD
- e-mail address
- security question and answer

Receiver then receives an e-mail message stating someone wants to send them money. After clicking a link in the e-mail receiver is brought to a Interac page that let's them sign in to their online banking space. After providing the security answer Interac **instantly transfers funds from one account to the other**. Sender and receiver never get to know any banking details of each other; Interac does not share any of this. Receiving e-mail address does not have to be the same as the one known by your bank. Transfer e-mails expire after 30 days. Charge-backs are not possible. No fees are charged.

My best guess to the reason for security question and answer system is that this forces the fact that there has to be some alternative way of communication between sender and receiver. Making a typo in the e-mail address therefore does not transfer your money to the wrong person since receiver can never claim the funds. **I was not able to initiate an Interac e-Transfer without providing both a security question and answer.** It appears that a secret question and answer are mandatory.

I could not find the option to send an Interac e-Transfer by providing a phone number instead of an e-mail address. My guess is that some banks do offer this (or did) and receiver would receive the login link by text message instead of by e-mail. I would suggest to support the e-mail option only.

**Comment by haiqu** [comment]
This one is in v0.4.9.7 so can be closed.
