### ISSUE TITLE
Existing installation under Ubuntu is not upgraded 

### ISSUE THREAD

**Issue by dgyg** [bisq-network/bisq#5020]
### Description

The installation of Bisq from Nautilus using the context menu _Open With Software Install_ does not upgrade an existing installation. 

Workaround: Install Bisq from the command line with 

```
sudo dpkg -i Bisq-64bit-1.5.2.deb
```

#### Version

1.5.2

### Steps to reproduce

Select _Open With Software Install_ in the context menu of Nautilus:

![bisq](https://user-images.githubusercontent.com/7886722/103289336-da5c9500-49de-11eb-883b-b9c0a904d475.png)

### Expected behaviour

The new version of Bisq is installed.

### Actual behaviour

The previous version remains.

### Screenshots

 ![bisq](https://user-images.githubusercontent.com/7886722/103289336-da5c9500-49de-11eb-883b-b9c0a904d475.png)

#### Device or machine
Ubuntu 20.04 LTS

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) and all subsequent ones. With this version, a more modern packaging mechanism is used, which should better handle upgrades, among other things.

Note that the new binary path is now `/opt/bisq/bin/Bisq`

Please try it out and let us know if it's still an issue for you.
