### ISSUE TITLE
Funds sent from Bitcoin core never showed up

### ISSUE THREAD

**Issue by jabba233** [bisq-network/bisq#5028]
On Mac Big Sur.

Funds have disappeared.  I sent funds required for a deposit from my hw wallet to bitcoin core wallet.  That worked fine.  Then I tried to send those funds to my Bisq wallet.  After an hour, even tho it was showing confirmed in bitcoin core, the funds never appeared in my Bisq wallet.  And then when I tried to restart Bisq I got hung up on the loading screen.  From there I tried many things including restarting, deleting the spv file, bringing a backup keys file up, updating to latest version of Bisq, and finally archiving the Bisq directory, starting up, and importing using my seed words.  That allowed me to run Bisq again but my wallet balance is showing as zero.  Super confusing and really sucks because it was a thousand bucks.  (Yes, I should have tested with a smaller amount first for sure).  

Any help would be very much appreciated.  I also used the QR code in Bisq to set up the transaction so I wouldn't fat finger anything.

**Comment by Jakub-CZ** [comment]
Which address did you send your BTC to?

**a)** the one shown in "Address" under "Fund your wallet", in FUNDS > RECEIVE FUNDS?
example:
![image](https://user-images.githubusercontent.com/16313562/103365477-6692b900-4ac0-11eb-859e-6ad0263fc6df.png)

or

**b)** the one shown in "BSQ wallet address", in DAO > BSQ WALLET > RECEIVE?
example:
![image](https://user-images.githubusercontent.com/16313562/103365397-4105af80-4ac0-11eb-8b48-855a9b9c3f4d.png)

---

**a)** would be correct.

**b)** may have resulted in an irreversible loss of BTC since that address is not a valid BTC address (AFAIK).
Others may have to confirm if this is your case.

**Comment by Jakub-CZ** [comment]
Actually, you mention the QR code, so it must be **a)**.

Some other thoughts:
- Have you updated to v1.5.3? If not, try that.
- Is the Bisq client synchronized with the Bitcoin network? (See the status bar at the bottom)
- Worst case, you should still be able to access your BTC by exporting the 12-word seed from Bisq and importing it into any other standard BTC wallet.

**Comment by jabba233** [comment]
Yes it was a).  I'd updated to the latest but it looks like I needed to manually resync to get everything looking right.  Took much of the day but its done now and the funds have shown up.  Thanks for your help!

**Comment by Jakub-CZ** [comment]
@jabba233
Great to hear that. If everything's OK, could you please close this issue?
