### ISSUE TITLE
java.lang.NoClassDefFoundError: joptsimple/HelpFormatter

### ISSUE THREAD

**Issue by Robert-L-Turner** [bisq-network/bisq#5034]
### Description

Bisq Desktop Fails to launch after upgrading from AUR package.

#### Version

1.5.3.1

### Steps to reproduce

JRE11 default install, Arch Linux 5.4.85-1-lts
Download latest package from AUR.  
Makepkg -si

### Screenshots

```
[rturner@SSDarchlinux ~]$ bisq-desktop
Error: Unable to initialize main class bisq.desktop.app.BisqAppMain
Caused by: java.lang.NoClassDefFoundError: joptsimple/HelpFormatter
```

No errors on build, but no local BISQ folder created so I presume no logs?  Happy to help with any other identifying / debugging information.  I've tried installing with other JRE environments with no success (JRE8, JRE10).

**Comment by Robert-L-Turner** [comment]
Confirmed still an issue with bisq-1.5.4-1.  I've read that it could be related to gradle not correctly pulling build dependencies but I'm not familiar enough with this tool to debug the error.

Installing Bisq via the AUR bisq-bin package is successful and therefore my current workaround.

**Comment by ripcurlx** [comment]
@freimair Do you have an idea what is going wrong?

**Comment by freimair** [comment]
No never saw that happening. Sorry. However, we had a similar case where the gradle directory got damaged somehow.

> not familiar enough with this tool to debug the error.

if you do not use gradle for development purposes please proceed with the steps below, else, you probably know your way around gradle anyways.


two things you can try:
- use JDK11 (yet you probably started with that) (aka make sure there is a `/usr/lib/jvm/java-11-openjdk` on your system)
- find your `.gradle` folder in your home directory and remove it
- `makepkg -i`


things to note: we are in quite a peculiar situation for arch linux with bisq, since bisq firmly asks for openjdk10, but it is not available anymore. its bisq-compatible successor, openjdk11, is on its way out as well and gradually harder to get. there are efforts to progress to a newer jdk but that is afaik a work in progress. arch users might need to fall back to the bin-package sooner or later.

**Comment by Robert-L-Turner** [comment]
@freimair Boy it doesn't get any simpler than that.  I was using jdk11 but didn't think to delete the .gradle folder.  That did the trick and bisq-desktop successfully built.  Much obliged!
