### ISSUE TITLE
Add a placeholder on the "Search Disputes" field

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/bisq#5105]
### Description

It would help inform the user what data point the field uses to look for open issues.
Currently this information is on a tooltip that only shows up after awhile and on hover.
#### Version

1.5.4

<img width="679" alt="Screen Shot 2021-01-22 at 11 07 29 AM" src="https://user-images.githubusercontent.com/807505/105564383-d9720700-5cef-11eb-9290-bfdea4b01ead.png">
<img width="466" alt="Screen Shot 2021-01-22 at 8 23 22 PM" src="https://user-images.githubusercontent.com/807505/105564385-da0a9d80-5cef-11eb-9d31-97ee52ed6764.png">

**Comment by chimp1984** [comment]
The search is done in quite a lot of different fields, but I agree that some hint would be good. Just wanted to mention that its more that the tradeId what can be searched for. Maybe a Info icon with a rollover text for the diff. search fields might be better? Otherwise it might give maybe too much weight on a side feature...
