### ISSUE TITLE
Have an option to edit offers

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#516]
Have an option to edit offers.

**Comment by haiqu** [comment]
User issue is that a fixed offer may be inappropriate if the market shifts radically. Solution already exists, use the % from market setting. Fixed price is a commitment to sell at that price. We don't want `bot wars` and constant network traffic.

**Comment by ManfredKarrer** [comment]
It might get added later, but we need to take care to not open attack surface for spammers. Offer fee is anti-span measurement.

**Comment by haiqu** [comment]
I can see the need for an option to suspend offers though. The drop in the price of Eth in the past few days would have me losing several percent if someone bought them. :(

**Comment by ripcurlx** [comment]
After some internal discussions we'll try to give this feature a shot for v0.7.0. I just want to layout the planned functionality first before I'll start conceptual work or implemention.

**Expected Behavior**
- User creates an offer
- User is able to edit amount and either percentage or fixed price depending on which offer type was created
- User is not required to pay extra trading fees for changing the price

@ManfredKarrer and @cbeams could you please confirm the requirements so we are all on the same page for this feature.

**Comment by ripcurlx** [comment]
As we are slowly running out of space, we need to use a more compressed way for enabled/disable, deleting and editing offers like following screenshot:
<img width="1312" alt="Open Offers" src="https://user-images.githubusercontent.com/170962/38419704-b7f471ae-39a1-11e8-9013-02e2a9450808.png">
