### ISSUE TITLE
More informative DAO synchronization

### ISSUE THREAD

**Issue by jorge-lavin** [bisq-network/bisq#5211]
### Description

It seems the only information that the app offers about DAO synchronization is that is actually synchronizing. It is useful to offer a progress bar or a estimated time pending.

#### Version

1.5.6

**Comment by ghost** [comment]
I agree.  Unfortunately, animated progress bars/spinners cause complaints (see below).  There was a visual indication of Synchronizing DAO on the footer bar until last release.  We disabled it (temporarily) due to complaints of Bisq being intolerably slow on certain platforms.  There is an in-progress effort to [upgrade the JavaFX UI library](https://github.com/bisq-network/bisq/pull/4242) that hopes to improve performance.

In `DAO -> Bsq Wallet -> Transactions` there is a progress bar indication of the sync.


Related:

https://github.com/bisq-network/bisq/issues/3308
https://github.com/bisq-network/bisq/issues/5112
https://github.com/bisq-network/bisq/issues/4649
https://github.com/bisq-network/bisq/issues/4370#issuecomment-773018489
