### ISSUE TITLE
Bisq stuck on 3/4

### ISSUE THREAD

**Issue by ivopashov** [bisq-network/bisq#5233]
### Description

Bisq seems stuck on startup - the 3/4 step.

#### Version

```
➜  ~ cat version 
1.5.0%   
```

### Steps to reproduce

None, just start the app

### Expected behaviour

App starts normally.

### Actual behaviour

App is stuck at 3/4 step and never starts. See screenshot below.
I have seen similar issues on that but those seem due to slow network and my network is not slow. It prompted me to delete some old Tor files. I did, restarted but same thing. Last time i left it for hours but just stays there.

### Screenshots

<img width="556" alt="Screen Shot 2021-02-24 at 12 28 25" src="https://user-images.githubusercontent.com/9412307/109000982-433d5200-769c-11eb-8ad5-28616c212185.png">

#### Device or machine

MacOS Big Sur 11.2.1

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/6035942/bisq.log)

**Comment by ivopashov** [comment]
Updating to latest app version 1.5.6 resolved it for me. Still weird that the older one was stuck. Resolving for now. Reopen if you see fit.

**Comment by ghost** [comment]
`
![16145344455541605769832](https://user-images.githubusercontent.com/78030897/109426277-cc86b880-79fd-11eb-8dc2-c44b7f46d12c.jpg)
`

**Comment by xineohp2021** [comment]
This issue is likely same as https://github.com/bisq-network/bisq/issues/2547 from 2019.

@chimp1984 If there is any hope to gain traction in Africa, this issue has to be fixed ASAP. As a rule, the Internet service here is poor. Bisq needs to work with the slowest possible service/lowest possible bandwidth. Requiring excellent Internet service will only make it an exclusive club.
