### ISSUE TITLE
SPV file is deleted after SPV resync

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#5335]
### Description

User can't complete SPV resync, after the process and restarting it keeps displaying a message that spv file has been removed.

### Version

Bisq v1.5.9 ; Arch linux 5.11.2

### Steps to reproduce

Unknown.
### Expected behaviour

SPV resync completes.

### Actual behaviour

The "SPV chain has been deleted" message appears after SPV resync restart.

### Screenshots
![paste (2)](https://user-images.githubusercontent.com/50149324/111865439-36441380-8967-11eb-99cf-23650a12afc2.png)
![paste](https://user-images.githubusercontent.com/50149324/111865436-33e1b980-8967-11eb-9652-9635a7f57da0.png)

### Additional info
@jmacxx has logs from this case and has investigated a little. The issue was solved by renaming-remove PreferencesPayload file as "there is a flag stored in user preferences that controls if the resync is initiated at Bisq startup".

**Comment by ghost** [comment]
#5280 was implemented to prevent the write of database files at shutdown if the app was never started fully, thus preventing a scenario when two simultaneous instances of Bisq overwrote all the database files.

A side effect is seen here when SPV resync is done, the preference flag `resyncSpvRequested` is not able to be cleared back to false on completion of the resync.  It says `PersistenceManager: Application has not completed start up yet so we do not flush data to disk` in the log.  The resync is started every time because the flag stays set.

I will submit a PR to use a semaphore file instead of preferences for controlling when an SPV resync is to be performed.
