### ISSUE TITLE
Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null

### ISSUE THREAD

**Issue by asolopovas** [bisq-network/bisq#5387]
### Description
Get `Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null` when trying to add new account.

#### Version
1.6.1

### Steps to reproduce

Add bank account

### Screenshots

![image](https://user-images.githubusercontent.com/6893216/113306949-84103280-92fc-11eb-9d45-0179781d5db3.png)

#### Device or machine

5.11.9-arch1-1 #1 SMP PREEMPT Wed, 24 Mar 2021 18:53:54 +0000 x86_64 GNU/Linux

#### Additional info

[bisq.log.txt](https://github.com/bisq-network/bisq/files/6244147/bisq.log.txt)

**Comment by ripcurlx** [comment]
Should be fixed when #4242 get merged.

**Comment by cd2357** [comment]
This is fixed in the most recent release (v1.6.4). Please try it out and let us know if it's still an issue for you.

**Comment by Talkless** [comment]
Just got this error in 1.9.6.

Was waiting for long time to setup Tor, got suggestion to shut down due to Tor issues, I closed that window and still waited more.

For some reason Settings window opened, and this messages was shown.

There's some strange gray placeholder elements visible:
![bisq](https://user-images.githubusercontent.com/292191/202284610-d3038b99-c80b-4048-9cfd-630713cdfedc.png)

**Comment by Talkless** [comment]
Well actually all other windows except Settings are completely blank.

**Comment by Talkless** [comment]
So Bisq just opens last window I was activated before closing Bisq. That single has some elements visible, but all other windows are completely dead.
