### ISSUE TITLE
Bitsquare is already running.  You cannot run 2 instances of Bitsquare

### ISSUE THREAD

**Issue by slabhatnik** [bisq-network/bisq#540]
The platform was running fine but now gives me the message at launch:

"Warning
Bitsquare is already running.  You cannot run 2 instances of Bitsquare"

Using OSX Yosemite 10.10.3.  
Shutting down the software or restarting the machine does not fix this loop.  

Also seeing this in the log:  

[ STARTING] ERROR i.b.a.BitsquareApp: java.io.IOException: org.bitcoinj.store.BlockStoreException: org.bitcoinj.store.BlockStoreException: File size on disk does not match expected size: 0 vs 641024

**Comment by ManfredKarrer** [comment]
Likely you have Bitsquare aleady running. Check the task explorer to see if it runs.

**Comment by slabhatnik** [comment]
I see it start to run in the activity monitor at launch and the multiple instances warning comes up.  When I shut it down, or quit from the activity monitor there is no sign of another instance running yet the error persists on each launch attempt.

**Comment by slabhatnik** [comment]
I think I'm going to reinstall... I've funded my Bitsquare wallet and will look for documentation on how to back up the private key and recover.  Thank you for building this platform though - when it was working for me, it was pretty excellent 👍

**Comment by ManfredKarrer** [comment]
If you had used it already back up the data dir!
C:\Documents and Settings\username\AppData\Roaming\Bitsquare
Do NOT uninstall it before backup because that would delete the data dir where your wallet is located! 
If you had the wallet seed words backed up though u are safe. But backup just in case...
You can also manually delete the content in the app dir not data dir):
I think it is (just look for the Bitsquare.exe): C:\Documents and Settings\username\AppData\Local\Bitsquare. And then install newly.

It can be that the lock file fo the wallet was not removed (can happen when it crashes). It is in the data dir
C:\Documents and Settings\username\AppData\Roaming\Bitsquare\mainnet\bitcoin. 
Here next to the wallet file might be a lock file (might be hidden, so look with the tereminal or change system settings to see hidden files).

Hope that helps.

**Comment by ManfredKarrer** [comment]
Could you resolve the issue?

**Comment by slabhatnik** [comment]
Sorry, can you direct me to the data dir on OSX?

**Comment by ManfredKarrer** [comment]
/Users/{USERNAME}/Library/Application\ Support/Bitsquare

**Comment by slabhatnik** [comment]
Will replacing the Bitsquare folder (path:
/Users/{USERNAME}/Library/Application\
Support/Bitsquare) on a fresh installation restore the wallet and platform
so that I can transfer my funds?

**Comment by ManfredKarrer** [comment]
Yes all data are in that dir. so if you copy that u have all again. But dont run them at the same time.

**Comment by ManfredKarrer** [comment]
Let me know if you coudl resolve the issue

**Comment by slabhatnik** [comment]
As it turns out, I haven't been able to resolve the issue.  I even tried
installing Bitsquare on a completely different machine that has never had
the application installed, then replaced the Bitsquare folder in
home/Library/Application Support with the backup copy I made.  I still get
the error message that I cannot run two instances of the Bitsquare
application at the same time.  I suppose the error might be coming from
something in a log file within the Bitsquare folder.  Thanks for following
up with this too, I appreciate the help.

**Comment by ManfredKarrer** [comment]
Seems the wallet file is locked. Did you have BTC in the wallet? if not simply delete the wallet file or whole bitcoin directory. Otherwise if you trust me send me the data dir and i will have  a look.

**Comment by slabhatnik** [comment]
Let me know your personal email and I'll send over the data dir.  I have no
reason to not trust you.  Yes there are some BTC funds in the wallet.  I'll
compensate for your efforts if a recovery can be made.

**Comment by ManfredKarrer** [comment]
manfred[at]bitsquare[dot]io

**Comment by ManfredKarrer** [comment]
Could be resolved with seed words. Wallet got currupted at first startup, so the auto-backups did nto help.
