### ISSUE TITLE
pop up window does not scroll in bisq, cant do anything

### ISSUE THREAD

**Issue by sunlover860** [bisq-network/bisq#5471]
The pop up window in the bisq app does not scroll. My screen resolution is 1920 X 1080, so screen resolution is not the issue. I have tried every possible combination of up and down arrows and using my mouse to get it to scroll. My computer is microsoft windows 10. I will admit that initially there was some problem using that program to verify the program is legit, but after I did install it without verifying it, I went back to the file, and it did verify that same file, I don't know if it was changed ... the problem happened because I could not find the file ending in asc, even though I downloaded that file, all that showed up according to my computer was the one ending in exe, but when I tried to verify  that file after a number of attempts and then gave up and just installed the exe file, I went back and verified the exe file, which I believe is not even supposed to be possible, possibly my computer was just not showing the asc part on the end for something maybe to do with what files my computer sees. Help!

**Comment by ripcurlx** [comment]
@sunlover860 Could you please provide a screenshot of the Window you are not able to scroll? Thanks!

**Comment by cd2357** [comment]
@sunlover860 

To make sure you download both the installer (`Bisq-64bit-1.6.4.exe`) and the PGP signature (`Bisq-64bit-1.6.4.exe.asc`) go to https://bisq.network/downloads/ and use the 2 links in the Windows section.

Windows 10 will by default "hide" the ending of certain file types. For example, after you download `Bisq-64bit-1.6.4.exe` you might only see it in Windows Explorer as `Bisq-64bit-1.6.4` (without the `.exe` ending), which can cause confusion. Anyway, to tell Windows to always show you the full file names, use the steps described [here](https://www.tenforums.com/tutorials/62842-hide-show-file-name-extensions-windows-10-a.html).

As mentioned above, please provide a screenshot of the popup window that's causing you trouble. See [here](https://www.tenforums.com/tutorials/6102-take-screenshot-windows-10-a.html) for different ways how to do that. Otherwise we can't know which popup you mean and can't help.

**Comment by sunlover860** [comment]
The problem with the pop up was fixed I believe because I bought a new laptop. I had previously been using a large screen led monitor. I don't know for sure, but the problem just went away when I started from the beginning with the laptop, something you might want to remember if this problem comes up for someone else as a possible solution.

Also I think you need to stress in your video where you are starting out and downloading files and confirming things, that the viewer needs to really be focused on what is being done, if they are not very careful through the whole process it is not that hard to get one thing wrong which screws everything up. Thanks for your help.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
