### ISSUE TITLE
[1.6.4] Issues with update on Windows

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5474]
As we saw some messages with people having issues when updating on Windows, I created this issue to collect further details so we are able to address them as good as possible. I'll update the issue as soon as we have more details.

**Comment by mlewk** [comment]
I installed the update both from the pop up installer and manually from the website but I am getting an error. Windows says failed to find JVM. No one responded on Keybase so and I have an open trade so I tried uninstalling Bisq and reinstalling but now I am getting another error. Windows says
![image](https://user-images.githubusercontent.com/30084414/117454384-15824e00-af14-11eb-8d2f-c357e51537a8.png)
and 
![image](https://user-images.githubusercontent.com/30084414/117454428-203ce300-af14-11eb-8f05-d47488de0c8c.png)

How do I fix this issues?

**Comment by 58gems** [comment]
Description
_Error Updating Bisq from v 1.6.3 to 1.6.4_
Version
_Windows 10 Home ver 1909 64 bit_
Steps to reproduce
_When starting Bisq application, error occurs "Failed to find JVM in "C:\Users\<name>\AppData\Local\Bisq\app\runtime" directory." This error is quick, no loading time._
Expected behaviour
_Bisq runs, I see my offers and wallet funds._
Actual behaviour
_Bisq no run_
Screenshots
![bisq exe error](https://user-images.githubusercontent.com/83825306/117462253-50c85100-af03-11eb-974b-29f92c1bda58.jpg)
Device or machine
_Lenovo T440p_
Additional info
_Tried moving runtime, bin folders into app folder, because the path didn't look right, but didn't work and I undid changes.
Also tried installing java per Keybase recommendation, also didn't work.  I think it did change these icons in app folder, I think the icon was blank before java update:
![app folder java](https://user-images.githubusercontent.com/83825306/117463570-abae7800-af04-11eb-9715-b20ba1826c79.jpg)
I wouldn't mind reverting to an earlier Bisq version to get it working temporarily.  Luckily I don't have any open trades, but do have 5 open offers and of course wallet balance._

**Comment by cd2357** [comment]
@mlewk @58gems Is your Windows up-to-date with all the Windows updates, patches, etc?

**Comment by 58gems** [comment]
Yeh, windows seems to have an update every day, and they take like an hour now, but I do them.  Did another windows update this morn after Java install, just so I could reboot, even though had one yesterday.  Fcuk Bill Gates.

Lemme know what else u want to try, but at the same time I'd like to get back to Bisq-ing, and request advisement where/how to install an earlier version that works.  Tks

**Comment by mlewk** [comment]
Yes, my Windows is up to date. What I did was uninstall Bisq, reboot then I ran the Windows Troubleshooter to clean up the Registry from the previous install and then I was able to successfully install Bisq 1.6.4 and then I replaced my data folder with my back up.
https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d

**Comment by cd2357** [comment]
> Yes, my Windows is up to date. What I did was uninstall Bisq, reboot then I ran the Windows Troubleshoot to clean up the Registry from the previous install and then I was able to successfully install Bisq 1.6.4 and then I replaced by data folder with my back up.
> https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d

Good idea @mlewk .

@58gems can you please try the same and see if it works? (Make sure to first [backup your Bisq data](https://bisq.wiki/Backing_up_application_data))

**Comment by 58gems** [comment]
![uninstall Bisq](https://user-images.githubusercontent.com/83825306/117489171-289c1a80-af22-11eb-849e-a1c7a73bbb53.jpg)

I seem to have both versions 1.6.2 and 1.6.4 installed.  Uninstall which, or both?

I backed up Roaming Bisq folder, incl. everything in Btc_mainnet, But since Bisq isn't running, I can't Export Payment Accounts separately.  Assuming these stay intact.

**Comment by mlewk** [comment]
I uninstalled both versions and then I ran the troubleshooter.  The payment accounts should be part of that backup you made,  Meaning if you copy the entire folder it will be included.

**Comment by 58gems** [comment]
Full re-install seems to have worked, thanks u guys.  Opened application with all old data / offers intact!

**Comment by mlewk** [comment]
Boom! Glad it working!!!
