### ISSUE TITLE
Uphold payment method issues to fix

### ISSUE THREAD

**Issue by pazza83** [bisq-network/bisq#5493]
### Description

The Uphold payment method could do with a couple of tweaks to make it a smoother trading experience.

- Add 'Account owner full name' field
- Fix error showing a 4 day trade period to 1 day trade period

When payment is received from an Uphold member an email is received to show the full name of the payee. This is also shown in the app when clicking on the payment details. 

There is no way to identify payee from the current field of 'Username or email or phone no'. You can use the payment amount / currency to link payment , but when multiple trades are made this makes it difficult / impossible to achieve. Adding an 'Account owner full name'  field would fix this.

The trade screen also shows the payment time as 4 days. This is incorrect. It should be 1 day. See screen shot below:

![uphold bisq](https://user-images.githubusercontent.com/66367547/118380090-45e28000-b5d7-11eb-9d31-910133f59356.PNG)

#### Version

1.6.4

### Steps to reproduce

1. Add Uphold as a payment method. There is no field to add 'Account owner full name'. This should be a required field.
2. Start a trade with Uphold. The UI will show 'Max. trade allowed period' as 4 days. It should be 1 day (the actual remaining time and actual trade window is correct at one day' so I think the 4 day is just a typo.

### Expected behaviour

1. Add Uphold as a payment method. User see a field to add 'Account owner full name'. This should be a required field.
2. Start a trade with Uphold. The UI should show 'Max. trade allowed period' as 1 day.

**Comment by BtcContributor** [comment]
Hi @pazza83, I can handle this issue.

**Comment by BtcContributor** [comment]
@pazza83 I finished the implementation of this fix.

Now it looks like this:

<img width="1237" alt="pazza_uphold_fix3" src="https://user-images.githubusercontent.com/79100296/118395263-9bf00b80-b649-11eb-9336-c8040101523d.png">

<img width="1397" alt="pazza_uphold_fix" src="https://user-images.githubusercontent.com/79100296/118395247-91357680-b649-11eb-8b68-3ae1e1f8f676.png">

<img width="1418" alt="pazza_uphold_fix2" src="https://user-images.githubusercontent.com/79100296/118395257-95fa2a80-b649-11eb-9d10-779619e94f42.png">


Unfortunately I was not be able to reproduce in any way the 4 days issue on latest Bisq version (maybe has it been fixed just recently?). I also checked on code and it seems ok to me.
Could you please recheck the issue, please? Otherwise, it seems good to me.

Also, are there any input constraints on the Account owner full name? Length for example, etc.

Once I have this information, I can release a PR.

Thanks!

**Comment by pazza83** [comment]
Thanks @BtcContributor that is great, very speedy!

I will keep an eye out on trades after the PR.

There are no restrictions on 'Account owner full name' it is based on what is entered when the user completes KYC with Uphold.
