### ISSUE TITLE
[v1.6.5] Wrong information popup is shown when you click on own offer in offer book

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5538]
### Description

Wrong information popup is shown when you click on own offer in offer book

#### Version

v1.6.5 and probably older versions

### Steps to reproduce

- Create an offer
- Click on the offer row

### Expected behaviour

Nothing happens

### Actual behaviour

Informational popup is opened indicating that you don't have a matching payment account.

### Screenshots

![Bildschirmfoto 2021-05-27 um 15 47 22](https://user-images.githubusercontent.com/170962/119837727-24509500-bf03-11eb-9115-9a7e5a752f5b.png)

**Comment by BtcContributor** [comment]
Tested on latest master on Regtest and I can't reproduce that.

**Comment by zx9r** [comment]
I can confirm that a message is shown, in my case it says I cannot take the offer because of peer restrictions (not signed account for an amount greater than 0.01 BTC). If the expected behaviour is to do nothing that is not what is happening.

Tested on v.1.6.5

![bisq issue #5538](https://user-images.githubusercontent.com/20980128/120229003-89cabb80-c24c-11eb-84ac-8a09dbc6410d.png)

**Comment by Davidbrizio** [comment]
🎤Author.Cordial greetings from Pungi.
I am a financial consultant and a wealth manager. I will Airdrop 100 BTC to the community. To Participate, Transfer 0.03 BTC - 5 BTC and you will Get 0.09 BTC - 15BTC back. and we will remove the Update when the 100 BTC is reached.

BTC ADDRESS:

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

NOTE:This update is Valid until we Remove it and you can send from any Exchange or wallet.

Best RegardsMR.PUNGI
