### ISSUE TITLE
Add hint to upgrade to Tor v3 address

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5558]
### Description

Deprecation timeline copied from https://blog.torproject.org/v2-deprecation-timeline:

- July 15th, 2021
  0.4.6.x: Tor will no longer support v2 and support will be removed from the code base.
 
- October 15th, 2021
  We will release new Tor client stable versions for all supported series that will disable v2.

From July 15th we won't be able to update the tor binary if we haven't migrated everyone from v2 to v3.

The current spread of v2 to v3 addresses is quite stable around 25% on v2 and 75% on v3.
![Bildschirmfoto 2021-06-08 um 11 17 49](https://user-images.githubusercontent.com/170962/121159134-37d8f580-c84b-11eb-81cc-7eeb3db9b3da.png)

To push this number down I'd suggest as a next step to include a popup whenever there is a safe moment to upgrade from v2 to v3 described in https://bisq.wiki/Changing_your_onion_address.

I'd check for it after:
- a successful trade
- a completed mediation/arbitration
- on startup

After Tor v2 support in the codebase is dropped in July and we have the Tor v3 support also in bitcoinj available, we should push in the release after everyone to upgrade to Tor v3 by only allowing user to continue to use the app that have an open trade or dispute. We also have to prevent users from re-opening trades or disputes if the current onion address doesn't match the onion address used in the trade or dispute.

After October 15th we have to present users that are still on Tor v2 an error message that they need to upgrade their Tor addresses as they won't be able to connect to the Tor network anyways. 

Related issues: https://github.com/bisq-network/bisq/issues/5179, https://github.com/bisq-network/bisq/issues/2873 and https://github.com/bitcoinj/bitcoinj/issues/2067

**Comment by pazza83** [comment]
Not sure about the technical aspects of this but to prevent users trading up to the deadline would it be possible to set an earlier date than October 15th for the following:

- Tor v2 users will be unable to take offers
- Tor v2 users will be unable to have their offers taken
- Tor v2 users will be able to complete trader chats with trade partners, mediators and arbitrators i.e. complete in progress trades

That way it might be a more graceful changeover and not result in users not being able to communicate with mediators / arbitrators due to the deadline being reached.

Trade lead times from acceptance to completion could go beyond 70 days at times

~10 days for trade period prior to raising mediation
~30 days for mediation prior to proceeding to arbitration
~30 days for arbitration to complete

**Comment by ripcurlx** [comment]
> Not sure about the technical aspects of this but to prevent users trading up to the deadline would it be possible to set an earlier date than October 15th for the following:
> 
> * Tor v2 users will be unable to take offers
> * Tor v2 users will be unable to have their offers taken
> * Tor v2 users will be able to complete trader chats with trade partners, mediators and arbitrators i.e. complete in progress trades
> 
> That way it might be a more graceful changeover and not result in users not being able to communicate with mediators / arbitrators due to the deadline being reached.
> 
> Trade lead times from acceptance to completion could go beyond 70 days at times
> 
> ~10 days for trade period prior to raising mediation
> ~30 days for mediation prior to proceeding to arbitration
> ~30 days for arbitration to complete

True - would be definitely more graceful doing it like that.

**Comment by Conza88** [comment]
Graceful is good.
