### ISSUE TITLE
Trades doesn't update 

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#560]
Hi,

When I Close the notebook cover, the Ubuntu 64 goes to standby mode. So when I reopen the notebook cover, the system go out of standby mode.
I see that when I reopen the notebook cover, Bitsquare doesn't update the Trades information. If I restart Bitsquare, the Trades are updated.

**Comment by ManfredKarrer** [comment]
Did you observe it for a while? After network disconnection it will take a but until the peer is fully connectd again. After a few minutes it should be ok.

**Comment by MarcSte** [comment]
I experienced non-updating trades as well in a different situation but I think it fits here:

Win10 x64

4 of my sell offers were taken yesterday. I went afk. 

This morning I saw my buy offer that was taken last night. I saw it 9 hours after it was taken and it was still stuck in 'wait for blockchain confirmation'. I followed the deposit tx ID and saw it had 50 confirmations.

I restarted the client and several trades from yesterday as well as the newest one updated.

Edit: These were all EUR-BTC trades.

**Comment by ManfredKarrer** [comment]
Hm... are yoou connected via Tor for BitcoinJ? Was your client offline when u where afk?

**Comment by MarcSte** [comment]
<img width="855" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/9436375/17320722/3cf2198c-5895-11e6-83ef-8efcba06f3ba.PNG">

This is how it's set up at the moment. 

On rare occasions I see 'You lost connection to the p2p...' I don't think I saw it this morning but I'm not sure.

**Comment by bitcoinuser** [comment]
I tested today again and the trades are not updated (after hours). So I closed and reopen Bitsquare and I see the new trades.
My network is is marked with (Use Tor for Bitcoin network).

Thanks.

**Comment by ManfredKarrer** [comment]
When you switch screens (not only tab bit another main menu item like portfolio) then you see the updates, right? At least for me I get the updates. Only the chart does not update the time scale by itself. Will fix that for the next version.
Otherwise if you miss data even after screen change then it is because you have been offline and missed the data propagation. Other then offers the trade statistics don't get published periodically. Only at startup you load all. But I will change that as well, so that at least the trades from the last day get periodically re-published. I just dont want to send too much as it produces too much load for the P2P network.

**Comment by bitcoinuser** [comment]
(When` you switch screens (not only tab bit another main menu item like portfolio) then you see the updates, right?)

For me no. Only update when restarting bitsquare

Yes, when I close notebook cover, the WIFI turn OFF. When I reopen, WIFI  turn ON

**Comment by ManfredKarrer** [comment]
ok, then your app was offline. but good that u pointed me to that problem, will fix it in the next version.

**Comment by haiqu** [comment]
See also #351 & #358

**Comment by ripcurlx** [comment]
@ManfredKarrer This is already fixed in the current version, isn't it?

**Comment by ManfredKarrer** [comment]
Reconnect works as far I am aware. We can close that.
