### ISSUE TITLE
Allow 1 sat/vbyte fee

### ISSUE THREAD

**Issue by kilrau** [bisq-network/bisq#5633]
If there is a really good reason, fine. If not, I propose to allow 1 sat/vbyte tx when withdrawing funds.

**Comment by Liisachan** [comment]
~1.01 sat/vB works perfectly and quickly when mempool is not crowded; supported by e.g. Electrum too. Although the difference between 2 sats and 1 sat is so small, probably it'd be a good feature request.

**Comment by pazza83** [comment]
@kilrau and @lichuan please see the proposal here if you would like to add your comments: https://github.com/bisq-network/proposals/issues/343

**Comment by cd2357** [comment]
Some people use withdrawals to fund their next trade. For a long while, Bisq allowed 1sat/vB withdrawals. However, Mempool got crowded for a few weeks and these 1 sat/vB transactions then resulted in stalled / expired trades, support tickets, and generally a lot of unnecessary disruption.

See the link above from pazza for a more detailed discussion.

The difference from 1 sat/vB to 2 is so small, that its not worth the risk.

FYI there are ways to make up for that difference (and more) :
- for all your trades, pay the trading fees in BSQ instead of BTC (about 50% savings)
- become a market maker, instead of a taker (those who create offers pay much smaller trading fees)
- try to create trade offers when the mempool is free (lower estimated mining fees for both trade participants)
- instead of many trades with small amounts, go for fewer trades with higher amounts
