### ISSUE TITLE
Security deposit is calculated from the Max trade amount

### ISSUE THREAD

**Issue by Premik** [bisq-network/bisq#5664]
### Description
Tried to take an offer in a local currency which has big trading range: `0.015-0.15BTC`. 
When trying to take the minimal amount `0.015BTC` the security deposit required is `~0.0226 BTC`. Ie **150%**. Of the trading amount instead of the `15%` advertised.

#### Version

bisq 1.7.2-1

### Expected behaviour

Deposit to be calculated from the actual trade amount. And not the from maximal one.

### Actual behaviour

Deposit always calculated from the max. trade value.

**Comment by pazza83** [comment]
Hi @Premik, thanks for the post.

I believe it is not possible in the current trade protocol for your expected behavior to be achieved.  

The security deposit has to be a fixed amount and this is set by the Maker at the time of the offer. It is not possible for the security deposit to be proportional to the btc trade amount set by the Taker.

**Comment by ripcurlx** [comment]
Closing based on https://github.com/bisq-network/bisq/issues/5664#issuecomment-899128241.
