### ISSUE TITLE
Locked balance amount in menu bar is not consistent with "Locked Funds" tab

### ISSUE THREAD

**Issue by misch2** [bisq-network/bisq#5703]
### Description

The "Locked BTC" in the upper right corner permanently shows amount of 0.006 BTC to me although I don't have any open trades neither do I have any open offer and nothing is shown in the "Locked Funds" tab. 
See the discrepancy on the screenshot:

![image](https://user-images.githubusercontent.com/16558674/133887826-999d9269-fc4e-45fe-8362-7d6791790815.png)

#### Version

1.7.3

### Steps to reproduce

Alas I can't provide the steps for reproducing this because I don't know them. But it *might* possibly be related to the fact that once I had a failed transaction?

![image](https://user-images.githubusercontent.com/16558674/133887889-cdc71460-75b2-4d41-a567-88895af70076.png)

But I'm not very confident that this is related, because if I move that failed transaction back to the open ones and then I click the "Details" icon, I get this message which clearly states that no funds have been locked:

![image](https://user-images.githubusercontent.com/16558674/133894518-184d52bf-4b30-483b-9c9a-6e375bee073b.png)

### Expected behaviour

I would expect that
 - either the "Locked" amount in the top right corner is an exact sum of the partial amounts on the "Locked Funds" tab.
 - or the "Locked Funds" tab lists all the sources which the "Locked" amount in the top right corner consists of.

### Actual behaviour

I see a mysterious 0.006 BTC value as the Locked amount and I don't know it thats a visual-only bug OR if I there is really 0.006 BTC locked which I could somehow reclaim.

#### Device or machine

Windows 10

**Comment by ripcurlx** [comment]
@misch2 Could you please try to open the [Emergency wallet](https://bisq.wiki/Emergency_wallet#Emergency_wallet) to see if the balance there includes your locked funds or not? Thanks!

**Comment by misch2** [comment]
Hi @ripcurlx, the Emergency wallet shows this:
![image](https://user-images.githubusercontent.com/16558674/133994229-3427517e-23ba-4ad4-ab8c-7eaa0574f576.png)

while in the top right I see this
![image](https://user-images.githubusercontent.com/16558674/133994157-704f805c-3348-4b51-bba4-88319b9c1ccb.png)

So the Emergency wallet value (0,03825153) is the exact sum of the Available Balance + Reserved.

If I understand it right then this is just a visual issue, no funds are really locked. Is that so?

**Comment by ripcurlx** [comment]
> Hi @ripcurlx, the Emergency wallet shows this:
> ![image](https://user-images.githubusercontent.com/16558674/133994229-3427517e-23ba-4ad4-ab8c-7eaa0574f576.png)
> 
> while in the top right I see this
> ![image](https://user-images.githubusercontent.com/16558674/133994157-704f805c-3348-4b51-bba4-88319b9c1ccb.png)
> 
> So the Emergency wallet value (0,03825153) is the exact sum of the Available Balance + Reserved.
> 
> If I understand it right then this is just a visual issue, no funds are really locked. Is that so?

Seems so, but kind of weird. This behavior stays across app restarts?

**Comment by misch2** [comment]
Yes, it's persistent across restarts, across the backup/restore to a different PC and it also persists after across SPV resync (I've tried that just now).

**Comment by pazza83** [comment]
@ripcurlx this issue is very common.

Usually happens as a result of a failed trade.

The GUI shows locked funds that do not exist. These funds are usually what would have been locked if the deposit transaction was successful. When the deposit transaction fails the GUI shows as locked fund.

Sometime moving the failed trade to failed and doing an SPV Resync helps. Most of the time it does not.

@jmacxx and myself spoke about this on a recent support call. It makes for a frustrating experience for Bisq users when there wallet shows locked funds that do not actually exist.  

If these cases could be reduced that would be great.

@misch2 if you want to see where your wallet thinks it has locked funds you can press 'Ctrl + j' or 'alt + j' or 'cmd + j' to access the wallet details screen. There you will be able to see the trade and deposit transaction id associated with the 'locked' funds. If you follow the funds you will find they are either available funds for you to use, or they have been spent on another trade or withdrawal.

**Comment by pazza83** [comment]
Hi @jmacxx with regards the GUI issue for Bisq showing incorrect locked funds. Is it possible for the GUI to take the total from what is displayed in 'locked funds' in the app. This is pretty much always correct. I think when it tries to calculate it based on other wallet data CoinLockedinMultiSig= is when it displays incorrectly? 

Not sure the reason for the discrepancy in the two totals but just wanted to share the observation that for every case I have helped a user with the incorrect account is the amount shown in the top right under 'locked' and the Funds > Locked Funds amount is always correct (at least after an spv resync.

I am assuming the information for locked funds in the top right is calculated by taking into account the trades in progress rather than the amounts of btc in mutli-sigs? I think sometimes the Bisq wallet gets corrupted about what trade are / are not in progress (especially when trades fail).

**Comment by pazza83** [comment]
Related to the above, here is an example of a trade that lead to a user having both:

- Locked funds shown in the GUI that were available in Funds > send funds
- Lost maker and miner fees when the reason for failure was taker tx id failing

<img width="845" alt="Screenshot 2021-11-07 at 11 45 33" src="https://user-images.githubusercontent.com/66367547/140663569-94efa6f3-2305-454d-9a85-d87348afdb05.png">

- Maker fee tx e50f64c325d63a0c2a2535c9cbc094322b102340d3246dc34ee8649c37d6eb31 on the chain
- Taker fee tx id is 08f13361a3780bd78ae800dfef6f7e1d890dcfd6ab9cf914f8d2539de46105dd  never made it to the 
- Deposit tx c9a1ff6ebc4e9a0a0b26ba6a5659e172cc0a32aa76f4f41f2d6e27192ce08182 never made it to the blockchain

I am hypothesizing that the creation of the deposit transaction ID leads Bisq to display Locked Funds incorrectly and also causing the loss of the maker / miner fees (when these could be reused for another trade).

I am assuming in the instance of taker transaction failing no deposit transaction would be created, trade would fail, no funds would be displayed as locked in GUI and trade would still be available for another user to take. 

Would it be possible so trades to fail due to a problem with the taker transaction to fail in the latter rather than former way?

**Comment by ghost** [comment]
@pazza83 At some stage during the several seconds of trade initialization the offer is removed from bisq.  As far as Bisq knows, everything is good once the deposit tx has been published.  But then if the blockchain rejects the deposit tx (due to bad taker wallet state) that is only known about much later when the deposit tx fails to confirm.  So yes, maker fees will be lost in the case of bad taker state.  The solution there is to strive for a better wallet that does not get out of sync so easily.

#5813 is a clean solution for correcting the display of locked funds.  (**confirmed** deposit == locked funds).
