### ISSUE TITLE
Failed trade

### ISSUE THREAD

**Issue by rumil2** [bisq-network/bisq#5751]
I would label this thread better, but I am pretty ignorant about guidelines. Please let me know if I need to add anything else. Thank you!

### Description

Went to buy BTC, timed out after 60 seconds and gave me an error message.

#### Version

1.7.4

### Steps to reproduce

n/a

### Expected behaviour

I wanted to buy bitcoin.

### Actual behaviour

timed out, bisq failed, no bitcoin happened.
Error message:

> "Timeout reached. Protocol did not complete in 60 sec."

### Screenshots

![Untitled](https://user-images.githubusercontent.com/92396757/137011497-0e666fef-89c1-461d-825b-40e8b68aafcf.png)
![Untitled2](https://user-images.githubusercontent.com/92396757/137011505-7cad7686-ef7d-4372-98e0-8502f35a1d9d.png)

#### Device or machine

desktop, Windows 10

#### Additional info

[bisq.log](https://github.com/bisq-network/bisq/files/7332467/bisq.log)

**Comment by ghost** [comment]
Hi @rumil2.  As Bisq is a P2P trading system, the two parties need to agree on the parameters of the trade.

In this case they could not come to an agreement on the current BTC market price.  The maker said 58861; the taker said 58176.  Since they were more than 1% different the maker aborted the trade, and the taker timed out.  Price differences can happen due to each peer checking individually.

Such is the difficult reality of distributed P2P trading.  It can be messy.

No funds left your wallet, and it should be ok to try again.

I noted down this problem in our [todo list](https://github.com/bisq-network/bisq/discussions/5668) of issues to try and improve.

**Comment by rumil2** [comment]
Thank you for the reply. 
That seems ridiculous, but it makes sense. If I had to make a thread like this every time such a thing happened, I think Bisq would be rendered unusable. This was the first time I ever attempted a trade and now I'm wary about the whole Bisq system.

**Comment by pazza83** [comment]
Hi @rumil2 it is rare for this to happen. I think your got a little unlucky on your first trade. Hope your second trade goes more successful.

The P2P nature of Bisq does cause some challenges but the trade offs are worth it for the decentralized platform users can access. 

Feel free to reach out on [Keybase](https://keybase.io/team/bisq) if you have any future support needs.
