### ISSUE TITLE
Disable GUI animations does not stick

### ISSUE THREAD

**Issue by phosphorit** [bisq-network/bisq#579]
After a restart animations are activated again though checkbox is still off. After yet another restart also the box is on again. I would suggest to always disable animations and remove the checkbox. But maybe I am just too old for this :)

**Comment by ManfredKarrer** [comment]
Hm... just tested and fro me it worked. Which animations are u referring? when changing the checkbox state it might take a second until it gets persisted.

**Comment by rsnel** [comment]
I can reproduce the problem.

When the Preferences are read from disk, then setUseAnimations is used to set  useAnimationsProperty based on the boolean flag useAnimations from disk. The flag itself is not updated (and the Listener to do that automatically is not yet setup). 

The first time, the correct value is saved, because clicking the checkbox updates `private boolean useAnimations`, but in the second run (when the correct flag is read from the disk) the flag does not get updated so that is writes the wrong value when the preferences  are saved to disk again.

So a quick fix would be to add  `useAnimations = persisted.useAnimations;` at line 171 of Preferences.java.

This does not solve the problem completely. There is also a  `private static boolean staticUseAnimations = true;`, of which the value can't be changed at runtime. This flag seems to be needed by the Overlay class which doesn't always have access to the the instance of the Preferences class which contains the user's preferences. Why Overlay sometimes has access to the preference instance and why not is currently beyond my understanding of java...

Edit for clarity.

**Comment by phosphorit** [comment]
I noticed animations when clicking the colored buttons like "Create new offer for selling bitcoin" - the popup will "grow" and the smoothing effect on the background will go away quicker. Just kick it out always deactivated and have one option less. :)

**Comment by ManfredKarrer** [comment]
@rsnel Thanks! Found the bug, the listeners need to be registered before the persisted objects gets applied.

The static staticUseAnimations field I need in all popups for animations but I don't want to pass the preferences over to all popups, so that is why I added that. There are some popups which uses the "Don't show again" checkbox and there the preferences is already passed (was implemented earlier, thats why I did not us the static).
