### ISSUE TITLE
ticker and orderbook api

### ISSUE THREAD

**Issue by IdoKrauss** [bisq-network/bisq#586]
creating a webpage which returns json for allMarketsTicker, marketTicker and orderBookPerMarket could help promote the exchange and simplify the procedure of adding the exchange to sites like coinmarketcap and coinhills

Sample for required info - allMarketsTicker , marketTicker :
https://poloniex.com/public?command=returnTicker

Sample for required info - orderBookPerMarket  :
https://poloniex.com/public?command=returnOrderBook&currencyPair=all

info can also be parse to market page (https://market.bitsquare.io/?market=lsk_btc)

**Comment by ManfredKarrer** [comment]
We ae working on it. 
See: https://github.com/bitsquare/bitsquare/issues/544

**Comment by dan-da** [comment]
hmm, this issue/request is related but distinct from #544 because this request is about a public webservice hosted by the bitsquare project.

It should be noted first that sites such as coinmarketcap could _right now_ run the bitsquare software with the --dumpStatistics flag.  This will cause 4 json files to be created: 

```
~/.local/share/Bitsquare/mainnet/db/crypto_currency_list.json
~/.local/share/Bitsquare/mainnet/db/fiat_currency_list.json
~/.local/share/Bitsquare/mainnet/db/offers_statistics.json
~/.local/share/Bitsquare/mainnet/db/trade_statistics.json
```

In particular, the trade_statistics.json and offers_statistics.json have all the necessary data.  Everything on the markets.bitsquare.io page comes from these json files.  A ticker would require processing/summarizing all trades.

---

It is true that we could create a public webservice.   It could be as simple as hosting the raw .json files, though it would be better with an API to filter by market, perform ticker (hi, low,open,close) calcs, etc.  The effort required is not that great, given what is already in place.

Indeed, the hloc API used by the market graph is already public (though undocumented) here:
https://market.bitsquare.io/api/hloc/?market=btc_eur

It is perhaps a project philosophy question if we want to expose a centralized webservice for a decentralized application.

It may be better from a decentralized viewpoint to implement a ticker as part of #544 and advise developers to always run bitsquare locally.  Though that might discourage app development vs the ease-of-use of a public webservice.   Certainly we can do both... 

@ManfredKarrer what do you think?

**Comment by ManfredKarrer** [comment]
I don't have any problem to offer an easy to use API. As long the code is open source everyone can run that by himself as well.

**Comment by artursapek** [comment]
Hi guys - we're waiting for you to release a public API like this so we can list you on Cryptowatch.

**Comment by dan-da** [comment]
ok, I'll come up with something.

**Comment by dan-da** [comment]
Public webservice API is live.  It is complete enough that it should be possible to generate a page just like market.bitsquare.io page with it.

See docs at:

https://market.bitsquare.io/api/

This version (0.9.0) should be considered alpha level.  When I receive feedback that third parties are using it successfully I will bump the API version to 1.0.0.

Feedback appeciated.  Let me know if anything is unclear or doesn't work as expected.

For anyone that cares, I did a bit more cache optimization and the APIs are relatively performant at present.  eg:

```
ab -n 20 -c 2 "https://market.bitsquare.io/api/markets/" | grep "per second"
Requests per second:    198.76 [#/sec] (mean)

ab -n 20 -c 2 "https://market.bitsquare.io/api/hloc/?market=btc_eur" | grep "per second"
Requests per second:    103.38 [#/sec] (mean)

ab -n 20 -c 2 "https://market.bitsquare.io/api/trades/?market=btc_eur" | grep "per second"
Requests per second:    126.40 [#/sec] (mean)

ab -n 20 -c 2 "https://market.bitsquare.io/api/depth/?market=btc_eur" | grep "per second"
Requests per second:    188.33 [#/sec] (mean)

ab -n 20 -c 2 "https://market.bitsquare.io/api/ticker/" | grep "per second"
Requests per second:    81.30 [#/sec] (mean)

ab -n 20 -c 2 "https://market.bitsquare.io/api/ticker/?market=btc_eur" | grep "per second"
Requests per second:    136.74 [#/sec] (mean)
```

The speed will likely degrade over time as more trades pile up, and further optimizations or bigger hardware become necessary.

**Comment by dan-da** [comment]
Also, the webservice API docs are not linked to from the main site yet.   @ManfredKarrer please do so once you've had a chance to review them.

**Comment by artursapek** [comment]
Awesome, thanks! FYI, you have a typo in the `/api/trades` section - the example URL is `/api/depth`.

**Comment by dan-da** [comment]
@artursapek thanks.  fixed now.

**Comment by dan-da** [comment]
I just added a new offers API method, improved the docs a bit more, and bumped the version to 0.9.1.

**Comment by DanielFragaBR** [comment]
Would it be possible to add a "last" field in the ticker API call? This field should display the last price regardless of the time the trade was done (persistent last price). For example: if the last trade occured 10 days ago, the last price will show on this ticker.

https://market.bitsquare.io/api/ticker

Is it possible? Thanks.

Ps: I ask this because I added Bitsquare to my site for comparison between exchanges and the last price is important, even if the volume is zero ;)
https://exchangewar.info/#bitsquare
https://exchangewar.info/coinprice?XMR_BTC#bitsquare
https://exchangewar.info/coinprice?BTC_EUR#bitsquare

Ps2: I hope it helps to spread the message about Bitsquare ;)

**Comment by dan-da** [comment]
@DanielFragaBR thanks for the feedback.

I updated the ticker API to include last column and behave a bit differently (more similar to other exchanges).   Please let me know if that works better or any issues.

docs: https://market.bitsquare.io/api/#ticker

notes from API doc:
- the response data can indicate the following market states: never traded, traded prior to 24 hours, traded within 24 hours
- a null value for a market key indicates 'never traded'
- volume_left or volume_right is 0 indicates 'traded prior to 24 hours'
- volume_left or volume_right is > 0 indicates 'traded within 24 hours'
- buy represents the highest buy offer at present, sell represents the lowest sell offer at present
- either buy or sell may be null if there are not presently any respective offers

**Comment by dan-da** [comment]
One thing I was debating about:  the way I have the ticker API right now, if there were no trades in past 24 hours then last, high, and low are all set to the value of last. 

Alternatively, I could make it so that high and low are null in this case.

If anyone cares or has a good reason (use case) why they should be null instead, speak up.   Otherwise I guess I'll leave it as-is.

anyway it is always possible to determine if they are stale by checking if either volume field is 0.

**Comment by DanielFragaBR** [comment]
@dan-da thank you very much! Now it's perfect. :)

**Comment by dan-da** [comment]
@DanielFragaBR glad it's working.  Nice site, btw.  I didn't realize there are so many active exchanges!

**Comment by DanielFragaBR** [comment]
@dan-da yes, but I'm happy to add Bitsquare. When the trade API is available, I think the Bitsquare volume will be much higher ;)

**Comment by artursapek** [comment]
@dan-da - we've listed a handful of Bitsquare's higher volume markets.

https://cryptowat.ch/bitsquare/btceur
https://cryptowat.ch/bitsquare/btcusd
https://cryptowat.ch/bitsquare/btcaud
https://cryptowat.ch/bitsquare/ltcbtc
https://cryptowat.ch/bitsquare/ethbtc
https://cryptowat.ch/bitsquare/etcbtc

Bitsquare is an interesting project and I'm happy to be supporting you guys in this small way. Good luck, and feel free to reach out if you need anything.

**Comment by ManfredKarrer** [comment]
@artursapek Great thanks!!!

**Comment by IdoKrauss** [comment]
great job, thank you all
i have requested from coinmarketcap and coinhills to get bitsquare listed

are there any limitation for api calls? such as x calls per seconds/hours/24hour ?

**Comment by ManfredKarrer** [comment]
@IdoKrauss I don't know the details there, maybe @mrosseel knows.

**Comment by dan-da** [comment]
@ldoKrauss  If any IP makes too many requests per minute, it will be blocked/banned for a period of time.

I do not want to publish the exact number, but please keep the API calls under 10 per minute to avoid stressing the server.

**Comment by haiqu** [comment]
Issue closed?
