### ISSUE TITLE
Unable to create new offer selling BTC in USD

### ISSUE THREAD

**Issue by shubrich76** [bisq-network/bisq#593]
v. 0.4.9.5
I have three accounts for USD transactions set up in Bitsquare:
1. Transfers with specific banks
2. National Bank Transfer
3. Cash Deposit

All three go to my checking account.

And I am unable to create an offer to sell BTC for USD. I am only able to trade BTC for ETH or STEEM, which I do not want. I want to trade for USD. I hadn't had this problem before update to 0.4.9.5

Any help is appreciated. Thanks in advance.

**Comment by MarcSte** [comment]
Transfer with specific banks and national bank transfer is disabled for USD since v. 0.4.9.5. This is due to either easy chargebacks (ACH) or crazy expensive fees (wire transfer).

Cash deposit should be possible, so should USP money order and clearXchange.

ClearXchange is an instant payment service supported by the following banks:

Bank of America
Capital One P2P Payments
Chase QuickPay℠
FirstBank Person to Person Transfers
Frost Send Money
U.S. Bank Send Money
Wells Fargo SurePay℠

ClearXchange have several advantages: Instant transfer, No chargebacks, No fees

You might want to check it out: https://www.clearxchange.com/

**Comment by shubrich76** [comment]
Unfortunately I bank with BB&T, I'll try the US Money order option

**Comment by MarcSte** [comment]
I see offers for US money order where you can get a nice discount. Please give feedback how you like the process. You could do this at the forum: https://forum.bitsquare.io/

**Comment by MarcSte** [comment]
Cool, please give feedback how you like the process. You can do so at the forum: https://forum.bitsquare.io/

**Comment by ManfredKarrer** [comment]
I think that issue comes when you have selected another currency like EUR and want to create a new offer. The a popup has a misleading information. If you select Show all you can create a new offer though.

I changed the misleading popup when creating an new offer for the new version.
So that issue should be fixed with that.

Improvements to trade between diff. payment accounts (national, same bank, spec. bank) is planned or later releases.
