### ISSUE TITLE
Bisq doesn't save Tor settings

### ISSUE THREAD

**Issue by skaunov** [bisq-network/bisq#5937]
### Description

This issue is a result of support discussion at <https://bisq.community/t/snap-ends-up-in-prepare-stage/11266/15>.

Bisq offers Tor settings button after some time since it started, then user switch settings to use bridges, close settings window, correctly shut down Bisq. Bisq restart shows that it still doesn't set to use bridges.

#### Version

1.8.0

### Steps to reproduce

Install <Ubuntu 21.04 Desktop>, Install <Bisq-64bit-1.8.0.deb>, next steps are in descr.

### Expected behaviour

Use bridges.

### Actual behaviour

Settings reseted.

#### Device or machine

```console
...:~$ uname -a
Linux ... 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
...:~$ sudo lshw
[sudo] password for ...: 
...
    description: Computer
    product: Standard PC (Q35 + ICH9, 2009)
    vendor: QEMU
    version: pc-q35-6.0
    width: 64 bits
    capabilities: smbios-2.8 dmi-2.8 smp vsyscall32
...
```
#### Additional info

Logs of both run: <https://pastebin.com/MM6sYpHk>. First is initial when the setting is set, and other one is second when setting expected to take effect.

**Comment by ghost** [comment]
The user preferences are saved at shutdown, but Bisq has a problem at startup whereby Tor is invoked before user preferences are retrieved from disk.  Preferences retrieval is asynchronous within the startup procedure; it is very involved and I did not see an easy way to fix.  Perhaps someone with more experience of the startup intricacies could suggest a solution. ping @chimp1984

**Comment by chimp1984** [comment]
Data which are required before persisted data are read need to be written to the properties files. We do that for some filter data (e.g.. banned seed nodes). 
In that case the NetworkNodeProvider creates the TorMode which requires the tor config data and that is called by Guice at the startup before persisted data are read. 
So either refactor the way how TorMode is provided so that this happens later or write the data to the properties file. I think refactoring the TorMode setup is the better option as that is done in a weird way anyway.

I think it should not be too hard. Just move it inside TorNetworkNode and create just when Tor is required. At that moment the preferences are read. It just requires to pass over all the params to TorNetworkNode, best by packing the params into a config data object so the API does not get polluted by tons of params.

**Comment by ghost** [comment]
re: "_Just move it inside TorNetworkNode and create just when Tor is required_"  Looks like its already implemented that way unless I misunderstood you.

Tor (`NetworkNodeProvider.get`) is requested very early in startup, via injection from:

https://github.com/bisq-network/bisq/blob/5c26c635e5f4f07209a77e6a6f7819dc30e7e13e/core/src/main/java/bisq/core/setup/CorePersistedDataHost.java#L64

**Comment by chimp1984** [comment]
No, it gets called very early if you put a breakpoint into it you see it. But yes it probably could be changed to a lazy supplier which gets only called once its used in the TorNetworkNode

**Comment by skaunov** [comment]
Is it ok to ask here on a workaround? Can I manually put some config data in a file? (And thanks for paying attention to this issue!)

**Comment by ghost** [comment]
@skaunov there is a PR #5966 submitted to fix this, it needs to go through the review process so at least 1 month before reaching a release.  If you can [build bisq from source](https://github.com/bisq-network/bisq/blob/master/docs/build.md), you're welcome to try it out.
