### ISSUE TITLE
error when opening the Bisq application: heightOfLastBlock must match chainHeight

### ISSUE THREAD

**Issue by RayHawi** [bisq-network/bisq#6016]
### Description

 when i open the application I recieve this error message "heightOfLastBlock must match chainHeight"

**Comment by ghost** [comment]
What version of Bisq are you on?  

There's a workaround fix described here: https://github.com/bisq-network/bisq/issues/5917#issuecomment-994911406

**Comment by loadedmodg** [comment]
I'm not OP but am experiencing the same issue.  I'm on version 1.8, Windows 10. 

I attempted the fix in #5917, restarted, same error.
[bisq.log](https://github.com/bisq-network/bisq/files/7978326/bisq.log)


Deleted outdated TOR files and restarted, same error.

Deleted the newly created DaoStateStore and BsqBlocks files, still same error.

**Comment by ghost** [comment]
@loadedmodg 

Looking at your log, I can see you tried this multiple times already, without success.  Comparing your log with mine after deleting DaoStateStore and BsqBlocks, I would expect to see the following messages showing it re-create BsqBlocks:

    INFO  b.c.d.s.s.BsqBlocksStorageService: Copying 143 resource files took 3173 ms 
    INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=DaoStateStore_BTC_MAINNET, destinationFile=/home/x/.local/share/Bisq/btc_mainnet/db/DaoStateStore 
    INFO  b.c.p.PersistenceManager: Reading DaoStateStore completed in 933 ms 
    INFO  b.c.d.s.s.BlocksPersistence: Reading 141494 blocks took 3729 msec 
    INFO  b.c.d.s.s.BsqBlocksStorageService: Reading and deserializing 141494 blocks took 5737 ms 

But your log shows it reading **already existing** BsqBlocks:

    INFO  b.c.d.s.s.BlocksPersistence: Reading 142254 blocks took 1112 msec 
    INFO  b.c.d.s.s.BsqBlocksStorageService: Reading and deserializing 142254 blocks took 1582 ms 
    ERROR b.c.s.CommonSetup: Uncaught Exception from thread Read-BsqBlocksStore 
    ERROR b.c.s.CommonSetup: throwableMessage= heightOfLastBlock must match chainHeight 

There must be some problem with the way you are deleting BsqBlocks, because Bisq is still finding them at startup, as if they weren't deleted.  Maybe try `shift-Delete` of the BsqBlocks directory and empty wastebasket if appropriate.  Also check you're deleting from the correct location?  Check the timestamp of the BsqBlocks directory.  If Bisq is creating the BsqBlocks directory at startup, it will have a current timestamp.
![image](https://user-images.githubusercontent.com/47253594/151992537-9e5195d7-17c7-418e-92f9-6ab296bef0cd.png)

**Comment by loadedmodg** [comment]
Perfect - worked flawlessly after shift-delete.  Thanks for the help!
