### ISSUE TITLE
cant create market with verge

### ISSUE THREAD

**Issue by vergecurrency** [bisq-network/bisq#603]
i went into settings, and added verge/xvg to my displayed altcoins, however, it never becomes an option to sell/buy in the offer book. i've tried a few things, but seemed to have no luck. also, would it be ok to add a bittrex api? i can make a pr for it, as ive already cloned bitsquare to the verge repo

**Comment by ManfredKarrer** [comment]
That is a known usability issue introduced in the last version.
The currency list in the offerbook only displays the currencies which are used in open offers. But you can add your offer as long u havve setup an account for tha taltcoin. Just click create offer and ignore the info popup, or select "show all" (not displaying the info popup).
I know that is bad UX and will fix that in upcoming versions, was pushed in too quickly into the latest version...

Re Bitrex: 
You mean the to get the marketprice from bitrex?
We would like to have several market price providers to be more resiliant and it is on the todo list, though it has some complexities (% price is derived from those, so if we create an average and if one is not available for one user the traders have a different view on the market price).
But current situation is even worse, if poloniex is offline all percentage based offers dont display a price.
You are welcome for a PR to add bitrex as provider and we need to find a good way how to make an average (based on volume).

**Comment by haiqu** [comment]
I can confirm that Verge can be traded if the currency is first added to Altcoin Accounts. But there is no guide price because Verge is not on Poloniex, which is why our friend is asking to get prices from Bittrex.

I think as a second source of prices, especially for minor altcoins, Bittrex is a great choice.

![verge](https://cloud.githubusercontent.com/assets/13131219/18906626/9f280db2-85ab-11e6-85e8-49d43fe7c783.png)

**Comment by ManfredKarrer** [comment]
Yes I agree. If you like to work on this is a pretty isolated area. 
Check out PriceProvider and see how PoloniexPriceProvider is used. 
We just need to think out well the situations when one is not available or u don't get updates. The calculated % price need to be very close for offerer and taker otherwise the offerer rejects the take offer attempt. So if offerer only gets poliniex price and taker only bitrex and the price is too far away it will not work.
Also we should check the volumes to get a good balance (like bitcoinavage does) and avoid attack possibilities with low volume currencies (move the price in bitrex and influence the price in bitsquae with that....).
So all in all its more complex as it seems initially. Though a first step might be to fill up only those altcoins which are not listed on poloniex.

**Comment by haiqu** [comment]
OK, I'll take a look at that one. I guess you'll need to instruct me on how to do this so that I don't screw up the github database, I've never used it. Already have the code checked out (and built) but pull requests are new to me because I've usually been the admin (using svn) and had tiny teams that were easy to synchronize.

Title of this issue could be changed to 'Add Bittrex exchange for altcoins' or similar.

**Comment by ManfredKarrer** [comment]
When you fork the project you can do whatever you want there. Best is to create a branch with the feature and once it is ready you make a pull request. I get then the info and check if it ready for merging.

**Comment by haiqu** [comment]
All-righty then.

edit: New fork at haiqu/bitsquare contains work so far. Includes some language fixes and work on the 1024x768 monitor issue. I'm finding it more usable already.

My approach to the Bittrex price feed will simply be to get prices that Poloniex doesn't carry. Simplest solution is usually the best.

**Comment by ManfredKarrer** [comment]
Before using Bittrex please check which altcoin price providers are the most relevants and the most stable ones. I am not soo familiar with the market to know if Bittrex is the best option. Though adding more then 1 is an option as well but as said before we need som caution on that...

**Comment by haiqu** [comment]
After Poloniex, Bittrex is the best source of altcoin volume and they have a great many coins that Polo don't carry. Verge is on a few other exchanges but I have no experience with most of them and the ones I have used are much smaller (e.g. C-Cex).

For some other coins - like for instance HOdlcoin, which I suggested to add - we may have to pick up a price feed from their market browser, which already averages several smaller exchanges. In this case it's OK, I know the dev personally, and the guy who wrote the market browser.

**Comment by ManfredKarrer** [comment]
Maybe its good to start a small discussion on the forum to get input from other users as well?

I will add the requested coins once i am back...

But we will not add custom price feeds for an altcoin. That would add too much effort/costs. 99% of the not relevant top 10 coins have close zero trade activity. At some point those which are not traded will get removed again as well. 
So we need to keep the effort to add a new coin as low as it is atm, otherwise we need higher requirements to add a coin or they have to pay for it (like done at some exchanges).

To add too many small exchanges which might not be stable, could add more troubles than it helps. So I want to be rather conservative with that. Better to not support some altcoins market price (which is probably not traded anyway) than to risk problems for all users if the data view of the offerer and taker does not match because of some issues with some exchange data, or if soemone figure out how to trick the system on low volume exchanges for price manipulations.

**Comment by haiqu** [comment]
OK, so in a nutshell, we can add it if it's on Polo or Bittrex but not otherwise.

Major exchanges tend to delete any coin that doesn't have sufficient trading volumes so this makes perfect sense. In fact it even applies to some minor fiat currencies, I notice someone wanted Kenyan Shillings recently. Dafuq.

To be totally consistent I think we should also start paring down the minor and unused alts before the next release. Candidates for removal are:

bitUSD, bitAUD, bitGBP, bitCNY, bitHKD, etc etc. In fact take out all the BitShares derivatives, it's a total scam.

Are you starting to see my point?

Just because a coin is on a major exchange and people trade it in volume doesn't make it any better or worse than any other. People are sheep and they don't investigate the code, the backers, the internet reports or the security aspects. And then they will scream blue murder when someone takes their money.

It comes down to this: Do we want to _look_ legitimate by acting as a pseudo-government "nanny" and trying to protect the buyers, or do we simply supply the facilities and let the market decide?

I know what my preference is, but then I'm a libertarian and have an IQ in the genius range.

And even then I get conned.

**Comment by ManfredKarrer** [comment]
No a coin which is not on any exchange can be added as well, you only cannot use the %based price and dont see the market price.

Fiat we should support all, as long a country has banks (US seems to be the worst regarding banks, prob. even north korea is better ;-)). If a currency is not supported its a software issue which coudl be easily solved (there is a github low hanging fruit for that - the country list is not very complete atm...)

I don't want to remove coins yet as specially for new coins Bitsquare might be a good starting help.
I also intentionally don't apply my opinion / politics on the selection. There are just very rough requirements.
There have been even requests to make it completely open (free text edit field) but I rejected that for several reasons, but I want to be as close as reasonable to that. I don't it our role to protect users from pump coins, if they are a clear scam we dont add it (remove it).

**Comment by haiqu** [comment]
I discovered today that CoinMarketCap has a ticker feed. This is a great place to get a centralized price for the smaller altcoins. That way we don't need to learn the API for a hundred different small exchanges.

**Comment by ManfredKarrer** [comment]
Good idea!

**Comment by haiqu** [comment]
In progress. CMC's ticker feed is in the wrong format but I think it may be usable. I'll also try to find an alternative that does have the right format. I'm thinking this might also be useful:

https://github.com/timmolter/XChange

It has a MIT licence. Stallman might argue that is incompatible with GPL but who cares.

**Comment by ManfredKarrer** [comment]
Ah XChange is in deed a good candiate!

**Comment by haiqu** [comment]
Glad you like it as much as I do. It's missing a few exchanges but the bones are good. I already have it cloned.

**Comment by haiqu** [comment]
Progress report: XChange is a pig to use, despite their claims of a simple interface. I have yet to get a demo program to actually work.
