### ISSUE TITLE
Incoming funds spent before blockchain verification

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#606]
Last night I sent myself some funds and immediately spent them on a listing. The data at blockchain.io showed a negative amount and no verifications of the transfer appeared for more than an hour.

THIS IS A CRITICAL BUG!!!! Funds should not be allowed to be used until we have at least ONE blockchain verification for BTC and possibly more with any other currencies introduced in future.

**Comment by ManfredKarrer** [comment]
You mean you did an intentional double spend? The deposit multisig tx will not be valid because your input was double spent. So the other peers input is not spent as well.
Usually wallets do not allow double spend and I did not had a single case yet. If a user is doing it intentionally the worst thing is that the other peer get a bit troubles to get his funds correctly displayed in the wallet UI and he need to use the hidden double spend feature to allow in such cases to double spend his inputs to get it available again, but that is just a wallet UI issue (BitcoinJ does not support well such double spend cases, and my implemention is kind of rough/experimental and not much tested). I just needed it in one dispute case where a user funded his wallet with 1 satoshi minging fee (seems to have been caused by a crash of his external wallet), so the deposit tx never got confirmed and it required a double spend to unlock the inputs of both users.

To force waiting for 1 confirmation would decrease usability a lot and as explained above, zero conf tx does not carry a risk.
In the trade process though before doing the fiat (or altcoin) transfer the user has to wait for at least 1 confirmation to avoid double spend by the peer.

If you meant something else please let me know.

**Comment by haiqu** [comment]
No, it was quite unintentional. I didn't do a 'double spend' of the source funds, what I did was spend unverified funds in the Bitsquare account. It wasn't until much later that I realized what had happened. If someone had taken my offer in that hour it would have caused some havoc, no?

Decreased usability is the fault of the slow btc blockchain, not Bitsquare. I wouldn't try to hide their inefficiencies for the sake of user convenience if there's any chance of an error needing arbitration happening as a result. But if I understand what you're saying, all this does is shift the delay on down the line to the buyer. I don't like that because we're essentially working on credit and exposing a weak point, but at this point our exposure is small and if you say it's safe I'll let it rest for now.

**Comment by haiqu** [comment]
Including snapshot of actual transaction as it now stands. For over one hour there were zero confirmations of the incoming funds at 16HGy4EQWtnFko44vCmXqVxHZm1HFbWik3 and it was finally confirmed when a burst of five blocks were found in quick succession. The transaction didn't have a dust fee, it was normal.

![zeroconf](https://cloud.githubusercontent.com/assets/13131219/18807896/a2405d50-8296-11e6-85f3-8cb53379d7ed.png)

**Comment by ManfredKarrer** [comment]
I still don't understand how you could spend funds which have been reserved for an offer. If that happened it is a bug. Once u create an offer the funds get into a reserved state in the Bitsquare wallet, so there is no way from the UI to spend those funds. Sure u can hack it by changing the code but then again nothing critical can happen as explained above.

The reason why your tx was so long waiting for a confirmation was because the mining fee at the desposit tx was only 0.00010669 BTC. 0.0002 BTC is reommended to get quickly into the blockchain.
Unfortunately we cannot force easily users to use the right fee as that comes from any external wallet, some old ones even don't support to set the fee.
We display a popup with info, but people tend to not read that (too many popups i know,...)
I added once a fee check to reject txs too low fees but that did not work out well. The best solution would be to check the fee and if it is too low we keep the deposit in a blocked state until it get confirmed, and only then it can be used for offers/trades. Though that is a bit of effort (u need to check the whole chain back until u dont have any unconfirmed inputs...) and this is the reason why its not impl. yet.
I got sometimes disputes because of that fee issue but not too many. Usually the trade gets delayed a few hours, or max. days and then can be resolved.

**Comment by haiqu** [comment]
The 0.00010669 fee is the standard fee selection from a Ledger wallet, which is the middle of three possibilities. Maybe I need to set it to the high fee setting.

My concern is not for a hacked Bitsquare wallet. But these 'reserved funds' you speak of don't exist until the incoming transaction has at least one confirmation. I should not have been able to reserve anything at all.

**Comment by ManfredKarrer** [comment]
Yes many wallets have not adopted well to the fee market...
See http://www.cointape.com, https://tradeblock.com/blockchain, http://p2sh.info/dashboard/db/fee-estimation or https://bitcoinfees.github.io/#1d for current fees.

The offer transaction is published even the funding tx is not confirmed yet, they might get into the same block. We have a chain of unconfirmed transactions (the create offer fee tx is another) which is not a problem as long the minign fee is not super low.
As described above it should be improved that way to check the fee and if it is too low to block that funding tx until it gets confirmed but that is quite a bit of work... and the pain from all that is limited. worst case is that i get a dispute and need to show the people the hidden double spend feature...

**Comment by haiqu** [comment]
Sure. I'm just trying to save the poor arbitrators some work here ... :)

**Comment by ManfredKarrer** [comment]
Its less then impl. that fee handling :-) But as said its planned just not top prio....

**Comment by haiqu** [comment]
Having now completed a trade I see that the BTC buyer cannot withdraw until blockchainconfirmations have been given. A hacked version of the client software might change that but it's a minor issue.

Closing bug.
