### ISSUE TITLE
bsq take offer timed out

### ISSUE THREAD

**Issue by Wilford888** [bisq-network/bisq#6066]
[bisq.log](https://github.com/bisq-network/bisq/files/8105113/bisq.log)

**Comment by ghost** [comment]
Hi @Wilford888 thanks the log was helpful.  Your take offer request was rejected by the peer - the issue seems to be that your Bisq DAO state is out of sync.  I propose the solution is go to Settings -> Preferences screen and click on `Rebuild DAO State From Resources` as shown in the screenshot below.  After doing so the Bisq app needs a restart.

![image](https://user-images.githubusercontent.com/47253594/154879075-57bd64dc-9007-425e-8e96-df509186c963.png)

If the problem still persists after doing that, let us know.

---

### Background:


This problem has been happening to several users recently, as a response we are improving the error message to give some advice to the users about checking and re-syncing their app state.  Reference: https://github.com/bisq-network/bisq/pull/6063

The advice given is:

  _Trade failures with BSQ swaps are rare, in cases like this it is worthwhile checking if:
    ● your DAO state is synced without error.
    ● your SPV wallet is functioning well._

  _DAO state can be checked by navigating to DAO -> Network Monitor -> DAO State.  It can be resynced by
  pressing the button "Rebuild DAO State From Resources" under Settings -> Preferences._

  _SPV status is harder to determine, usually a resync is necessary whenever you experience problems transacting
  on the blockchain. More info at https://bisq.wiki/Resyncing_SPV_file_
