### ISSUE TITLE
Data volume unacceptable

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#614]
There is FAR too much data volume on the network, and with more users it will just get worse. I suggest we start looking at compression of the data stream, restriction to country by IP address and enabling the user to turn of the price feed when it's unused.

I'm on 4G mobile internet and the costs are killing me.

**Comment by ManfredKarrer** [comment]
I tried already to reduce the traffic but it is a complex part to change. The flooding network creates too much noise at the moment, but simply reducing redundancy leads easily to missing data if not doen properly. So that needs some time for anylsysis and testing.
The amount of users does not influence but the amount of offers. I tested once with 1000 offers online and it was working well. But that was a while back and thing has changed in the meantime.
Restriction by country/IP does not works it is over Tor.
You can tune a bit with just connecting to a few peers. MAX_CONNECTIONS is 12 peers by default, so if u cange that to 4 or so you use less bandwidth but take care that you still are well connetected. That is specially in the dispute case important (if a msg is not well distributed the arbitr. might not get it).
MAX_CONNECTIONS is a prog arg u can set.

**Comment by haiqu** [comment]
OK I will try reducing that and watch the effects on bandwidth. Thanks.

**Comment by ManfredKarrer** [comment]
Just checked the Poloniex feed. A data response with all prices has 27 kb (https://poloniex.com/public?command=returnTicker).  We request it all 3 minutes.
The BTCAverage is requesting all 70 sec. the selected fiat currency and all 3 min all currencies.
The all data request has 33 kb (https://api.bitcoinaverage.com/ticker/global/all), the single request has 180 bytes (https://api.bitcoinaverage.com/ticker/global/USD/).
So roughly 1,2MB are downloaded per hour. I think that is probably not worth the effort to optimize. The P2P network generates much more traffic.

**Comment by ManfredKarrer** [comment]
As said before changing MAX_CONNECTIONS to a lower level might be dangerous (messages not distributed reliably). So that would need proper tests and simulation to optimize.

**Comment by haiqu** [comment]
I'm leaving it off a lot now. Maybe that's why there are so few users?

But I did make another trade. :)

**Comment by haiqu** [comment]
I just set MAX_CONNECTIONS_DEFAULT to 6. But I only have two onion connections right now and it's still working. Bandwidth is also much lower than usual.

**Comment by ManfredKarrer** [comment]
Yes, but if u have trades u might get problems that the messages (if the peer if offline) will not get distributed well enough in the P2P network, so I would not recommend that.

**Comment by haiqu** [comment]
I've set it back to 12 for now. Data usage has become more acceptable recently, only about 50MB in 8 hours, so I may have just struck a period earlier where there was a bit of noise on the channel or something.

Regardless of the cause, it seems there's not a lot can be done about it. Closing.
