### ISSUE TITLE
Multiple offers with same offer ID

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6276]
There may be a bug in Bisq that allows multiple offers to be created with the same ID.

See:
https://github.com/bisq-network/support/issues/1116
https://github.com/bisq-network/support/issues/1115
https://github.com/bisq-network/support/issues/1114
https://github.com/bisq-network/support/issues/1113
https://github.com/bisq-network/support/issues/1112

@Akira45-0 could you outline the steps taken to make these 5 offers?

**Comment by Akira45-0** [comment]
1. Somebody took my offer.
2. I right clicked on the taken offer in Portfolio/Open trades screen and chose "Create a new offer like this...".
3. I took the usual steps until "Confirm:Place offer..."
4. It looks that I have pressed the "Confirm:Place offer..." multiple times, because I was using remote desktop on my smartphone so I did not see the window that the offer has been published and I assumed that nothing was happening.

I was using Bisq 1.9.2 running on linux as a full DAO node with Bitcoin Core 22.0
I can provide the relevant logs, but I don't want to post them in public.

**Comment by ghost** [comment]
Following those steps I'm unable to get multiple offers by repeat clicking on "Confirm:Place offer...".
Thanks for the offer of logs, could you DM them to me on Matrix?  Thanks!

**Comment by ghost** [comment]
To reproduce issue:

- Click on duplicate offer icon.  The offer details are shown.
- Switch to a different top-level menu (e.g. Funds)
- Switch back to the Portfolio top-level menu.  The offer details are shown.
- Proceed all the way with the duplication, pressing "Confirm" to duplicate the offer.
- Oddly, you are returned back to the offer details, rather than getting notification of the offer creation.
- Press "Confirm" again.  You will be returned to the offer details (while you now have two offers with same ID).
- Press "Confirm" again.  You will be returned to the offer details (while you now have three offers with same ID).
- Press "Confirm" again.  You will be returned to the offer details (while you now have four offers with same ID).
- etc...


I'm working on a fix.  It is due to loss of event listener after tab switch.
