### ISSUE TITLE
Altcoin "Payment account" unclear when buying Bitcoin

### ISSUE THREAD

**Issue by jonathancross** [bisq-network/bisq#631]
When a user is selling an Altcoin to buy Bitcoin, the transaction info dialog lists a **"Payment account**" of the same type as the Altcoin being sold.  This is confusing because it _suggests_ that somehow that address is involved in the transaction, but it is not necessarily.

Screenshot:
![bitsquare-transaction](https://cloud.githubusercontent.com/assets/5115470/19174393/ba0312f6-8c2e-11e6-8df6-cdaf302c7d04.png)

Looking at the panel above, it is easy to misunderstand and think that 10.11 DASH need to be transferred to that "Payment account".

Questions:
1. Is that altcoin address used somehow by arbitrators? Perhaps as a "Refund" account?
2. Is there graphical documentation somewhere explaining this and other UI elements? (if not, we can create a new issue for that)

**Comment by ManfredKarrer** [comment]
Ok. maybe to rename Payment account to "My payment account" might make it more clear.
It is expected that the users use the defined altcoin address both for sending and receiving, though it is not required and some users don't do that (as far I saw in disputes).
To set up the account with 2 different addresses might be an option as well, but not sure...
- The altcoin address is not actively used. The altcoin sender can use also another address without issues (with fiat that is not allowed because of scam risks).
  But if both use the defined address it is easier to look up in the block explorer for both sides.
- No there is no doc.

**Comment by ManfredKarrer** [comment]
Renamed to "My payment account"...

**Comment by haiqu** [comment]
I thought about this matter when I first set up to sell ETH. I created a special account just for use with Bitsquare and expect that the buyer can look up that address to make sure I have funds available before completing the transaction. I think this is the only honest way of selling.

For buying, if the coins come from a different account and the receiver is a heavy trader it will become difficult to tell if he received the coins from Bitsquare or some other source.

So I think this should be made clear in the transaction popup information. We should treat it the same way a bank account is treated. After all, the coins can be immediately removed to another account easily.

In the case of the title, I would prefer "My trading account" rather than "My payment account".

**Comment by ManfredKarrer** [comment]
I think the senders altcoin address is not that relevant as long the coin arrives. I am not aware of any fraud risk (like wiht fiat). To restrict that would just cause more unnecessary disputes.

Re renaming: Not so sure if trading account is really better. For me payment account carries more information. We use the term payment method, so the account for a method is the payment account. But I am not english native...

**Comment by haiqu** [comment]
Payment account to me implies the account that I will send from. Trading account (similar to the bank use of the term) implies two-way flow, a business account.

As long as the trading is low volume it will be easy enough to see that the payment arrives, no matter from which source.

**Comment by ManfredKarrer** [comment]
Changed: https://github.com/bitsquare/bitsquare/commit/90b17eb8569d9c825af846852d2e236cb4b025d3

**Comment by jonathancross** [comment]
Sorry I disappeared after creating this.
I agree that users should not be forced to reuse addresses - with bitcoin and many altcoins (Monero being an exception), users are [strongly discouraged from reusing addresses](https://bitcoin.stackexchange.com/questions/20621/is-it-safe-to-reuse-a-bitcoin-address/42376#42376) for both privacy and security reasons.  Additionally, payments often come from multiple addresses so listing a single one does not make sense.

Even with the new name, the UI still suggests this "Payment account" is linked to this trade somehow where in actuality there is no direct connection (other than some traders perhaps reusing addresses, which should be discouraged).

**Comment by haiqu** [comment]
The trouble is that in order to fulfil the contract, both seller and buyer have to know the address of the other before the trade can be agreed to otherwise the contract is useless. There's nothing to stop the security conscious user from changing that address on a regular basis, or using a single address (i.e. a trading account) as a catchment point then re-routing the funds elsewhere.

The security issue in doing that is unclear, although a determined agency could no doubt eventually break privacy by knowing it. Bitcoin was never designed for anonymity and the only person who gets to see it is your trading partner so I'd consider using a single address safe within the context of Bitsquare.

**Comment by ManfredKarrer** [comment]
@jonathancross Do you have an idea how to support multiple addresses in a user friendly way? We don't have any integration with the altcoin wallets (maybe in future with selected coins). So beside offering a list of addresses what the user can pre-fill I don't see a good way to achieve that. But that is prob. not a good solution usability-wise.

**Comment by jonathancross** [comment]
@haiqu 

> both seller and buyer have to know the address of the other before the trade can be agreed to otherwise the contract is useless

Only the destination address for each coin need be specified (and ideally also be unique), but not the source address.  The funding source can (and should) be dozens of UTXO as in privacy improving techniques like CoinJoin.  In the current UI, "Payment account" (now "Trading account") is an implied single source address, but it is not enforced in any way and suggests the wrong mental model.

@ManfredKarrer 

> Do you have an idea how to support multiple addresses in a user friendly way?

I'd suggest removing the address for now (see explanation below).

> altcoin wallets...

Yeah, it would be great if there were integrated altcoin wallets, would allow so much to be automated! But until those are implemented (if ever), I'd suggest simply removing the field in cases like this where it gives the user an imprecise picture of what is going on.  We want to remove all information that could contribute to a faulty mental model of they transaction they are creating.

**Comment by ManfredKarrer** [comment]
There is an problem: If you don't have the senders altcoin address and you have 2 trades with the same amount and ucrrecny open then you don't know who was the sender as we don't have a reference text field like it is used in fiat tx to identify a receipt.
I know that some (or many?) traders don't follow the model that the account address should be used for sending the altcoin and then we could have the same situation.

I agree to your argumentation but I don't see a simple solution atm.

**Comment by jonathancross** [comment]
> you have 2 trades with the same amount... you don't know who was the sender

The best solution is to create a separate address **on the recipient side** for every trade you open.  Then you know which of the trades was completed (even if amounts are the same).  You don't literally know who the sender is, but you know that _someone_ sent you the correct amount to the correct address that only that trading partner knew about it.  That should be good enough (this is how all bitcoin payment processors work).

Or maybe I am misunderstanding something here?

**Comment by ManfredKarrer** [comment]
Yes good idea. For the offerer when he is the BTC buyer (altcoin sender) he though need to set up his altcoin address already at offer creation time, as his offer will be taken without his interaction.
I think we should offer both, so default it takes the 1 address used in the account (for those who prefer convenience) and for those who want better control they can specify a specific address for each trade.

**Comment by haiqu** [comment]
I think Jonathan is trying to solve a problem with Bitcoin, not with Bitsquare. The sending address is available on the blockchain so hiding it is pointless.

I don't want to know that _someone_ sent me the correct amount, I want to know that the person I'm trading with sent me the correct amount. I don't want to be involved with devious money laundering schemes on any level.

**Comment by jonathancross** [comment]
Hi @ManfredKarrer 

> BTC buyer (altcoin sender) he though need to set up his altcoin address already at offer creation time, as his offer will be taken without his interaction.

Sounds like you are talking about a future scenario where Bitsquare is changed to support altcoin wallets directly? Then yes -- the software could automatically confirm you have the required balance, send automatically at the appropriate time and confirm when altcoins are received.

Would allow secure altcoin => altcoin trades which would be nice.

It might even be feasible to construct the transaction in a trustless manner (meaning no risk, no arbitrator needed) using some type of [atomic swap](https://en.bitcoin.it/wiki/Atomic_cross-chain_trading).  This would be dramatic improvement over the current (very manual) process.

@haiqu 
Sorry for the misunderstanding, but as I mentioned, this is just how bitcoin works... Bitpay, Coinbase, All exchanges, etc. (clearly not "involved with devious money laundering schemes") never ask for a "sending address" but rather they _**create a receiving address**_ and tell the user what to send. They _assume_ the bitcoin they receive there came from the correct person and simply check the amount. This is the norm for how bitcoin (and most altcoins) are used.

> The sending address is available on the blockchain so hiding it is pointless.

I was simply suggesting that the sending address be omitted from Bitsquare UI because it is confusing.  Use of a "Sending address" doesn't fit with how people use bitcoin.

**Comment by haiqu** [comment]
In my experience that generated receiving address is rarely changed once created, which brings us back to an analogous situation. You can manually ask for a new one, but I never have.

I can't see any value in the added complexity of adding code that can generate valid receiving addresses for 100 altcoins. A regular exchange has to keep coins in escrow - and they do a fairly poor job of that - which is why they need to generate new addresses. I imagine they have a bank of servers running wallets for each of them.

Nominating your own account also avoids double handling, and the associated fees.

If we're just talking about bitcoin, we already have the capability to generate those addresses.

**Comment by jonathancross** [comment]
> I can't see any value in the added complexity of adding code that can generate valid receiving addresses for 100 altcoins.

@haiqu Yes, adding wallets for all supported altcoins is probably infeasible right now.  It _would_ solve a lot of problems and make Bitsquare much better than all other "trusted" options out there and could eventually be a much bigger win than fiat <=> crypto exchange as there is almost no competition in this area.

Getting back to the original issue... the "Payment account":

When selling bitcoin (buying an altcoin), Bitsquare can force a user to "spend" from an particular address it controls.  However the other trading partner (Selling altcoin to buy bitcoin) is a different model because Bitsquare does not control the altcoin source wallet and should therefore not make assumptions about how the altcoin will be sent.  The term "Trading account" or "Payment account" are both inaccurate as this is just an imported address that the user _presumably_ owns.  There is no valid reason to require that funds be sent from the single imported address and in fact Bitsquare does not require this (luckily).  The field is just a distraction and perpetuates a very common misunderstanding about bitcoin and related cryptocurrencies.  Addresses are not "accounts" and should not be confused for such.  In modern wallet software, the term "account" is used to refer to a collection of addresses (a tree) which are only used once.  Recipients never assume anything about the sending address as there may be many.

> A regular exchange has to keep coins in escrow... which is why they need to generate new addresses.

Any institution or individual that wants to properly distinguish between incoming payments should be creating a new receiving address for each transaction.

> In my experience that generated receiving address is rarely changed once created

Address reuse _may work for some people in some situations_, but this is a bad idea and no reasonably professional wallet, exchange or payment processor does this anymore.  Thinking of a single address as an "account" is convenient, but inaccurate. Your personal habits should not be confused with industry best practices, especially when less secure & less private.

Feels like we are going in circles a bit here, so I'll leave it at that (bug is closed anyway :-)

**Comment by haiqu** [comment]
Thanks for the thoughtful comments, I've certainly learned some things from this exchange. As you say,

`In modern wallet software, the term "account" is used to refer to a collection of addresses (a tree) which are only used once.`

and this is certainly true of my Ledger Wallet(s). The only thing that feels as safe as a bank to me is having coins in encrypted hardware that I can physically control. It's unfortunate that there are such a small number of coins for which this can be done, limited mainly by the requirement for a back-end centralized wallet to be running somewhere on the 'net.

**Comment by jonathancross** [comment]
> I've certainly learned some things from this exchange.

I'm very happy to hear that  :-)
I am still learning myself, so I'm grateful for the opportunity to explain what I understand so far to others.
