### ISSUE TITLE
Offer Book view - "Sum" column is redundant

### ISSUE THREAD

**Issue by haiqu** [bisq-network/bisq#633]
The column "Sum in BTC" in the offer book view doesn't really tell the user anything useful. The data is available in the Spreads view if he's curious about that. In search of a cleaner UI this probably should go.

At the very least it could be reduced to a single line with the overall sum, one each for Sell and Buy.

**Comment by ManfredKarrer** [comment]
Its the accumulated sum. Most exchanges use that so u can see if u want a larger trade what the price will be to get all your trades fulfilled. Of course as we do nto do automatic order matching that is a bit different, but I think it is still useful. I added it because Dan added it to the market webpage.

**Comment by haiqu** [comment]
I've never seen that on any of the five exchanges I've used. It would be handy there, but not in Bitsquare because we don't take groups of offers.

**Comment by ManfredKarrer** [comment]
Kraken, Bitstamp and Poloniex use it at least...
I think it still has soem information for some traders. If the best price has only very thin volume it is not so interesting if u need to trade higher volume.
But agree it is not too useful in context of not autom. order matching. But that might come in future...

**Comment by haiqu** [comment]
Hah! I didn't notice that before, yes Poloniex do have it. That will be useful for me in future.
