### ISSUE TITLE
Error - no value present

### ISSUE THREAD

**Issue by jshoyes** [bisq-network/bisq#637]
When opening the application, I get an "Error - No value present" window prompting me to report the bug here. Here is a screenshot:

![screenshot 2016-10-09 10 29 08](https://cloud.githubusercontent.com/assets/5262529/19221152/8ad82028-8e0b-11e6-8b46-2951b4924579.png)

**Comment by haiqu** [comment]
Thanks Shaun. If you can upload the bitsquare.log it will help as well. Can't tell you where to look for it because it depends on the OS but doing a global search should find it.

In Windows 7 mine was at C:\Users\Rob\AppData\Roaming\Bitsquare\bitsquare.log

Note that AppData is a hidden directory and you need to make it visible, so the fastest method is to do a search in Drive C: then double-click on the found file and it will come up in notepad.

I assume you're using v0.4.9.6 ?

**Comment by jshoyes** [comment]
I'm actually using v.0.4.8.1. Maybe that's the problem. 

I'm using the MacOS Sierra - I'll try to locate it for you if I can.

**Comment by ManfredKarrer** [comment]
Thats an old version, please update to the newest version.

**Comment by jshoyes** [comment]
Just updated. No problems now. Thanks!

**Comment by ManfredKarrer** [comment]
Cool!

**Comment by haiqu** [comment]
Another happy customer. :)
