### ISSUE TITLE
[v1.9.6] Show different badge and peer info for personal avatar

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#6380]
### Description

Not sure why I haven't recognized that so far, but I think we should handle your own avatar differently (see screenshot)

#### Version

All versions until now

### Steps to reproduce

Create a dispute or create an offer and click your own avatar icon.

### Expected behaviour

Give user a hint that it is her she was clicking at.

Maybe have a `ME` badge in a different color than the tag badge for your personal avatar and when you click on your avatar hide in peer info:
- field number of completed trades
- option to tag this peer

### Actual behaviour

It shows that you haven't traded with this peer and gives you the option to tag this peer.

### Screenshots

![Bildschirmfoto 2022-10-17 um 13 54 15](https://user-images.githubusercontent.com/170962/196170665-cfaebc40-e6c8-4771-8209-5f3ac8bab07f.png)
![Bildschirmfoto 2022-10-17 um 13 56 01](https://user-images.githubusercontent.com/170962/196171069-114bc067-fcc1-4621-9b6b-530ec1007a19.png)

**Comment by Android-X13** [comment]
@ripcurlx and @jmacxx, regarding the badge specifically:

After trying various things I realize there's a possibility that a `ME` badge could maybe create problems (in OfferBookView). While in English it could look nice because it is a two-letter word and could fit well in the avatar column, if it's translated it could become a three- or even more-letter word (I think the word in most languages is two characters but I'm not sure). The avatar column is intended to have a short fixed width by definition to look nice. If the badge gets too long, then one of the following can happen:
1) The badge will be truncated (but badges are not meant to be truncated)
2) The avatar should move to the left to make room for the badge (but the non-alignment with the other icons will be noticeable)
3) Align all avatars (this will be new behavior, as avatars with tags are not currently aligned) and make the column larger to give room for the longer badge (but the column won't look nice if it gets large enough)

One solution that could work well is to have the "ME" label hard-coded in English and not allow it to be translated.

Otherwise perhaps the badge should be some kind of icon or textual symbol, so that it's always of fixed size, but something non-linguistic. It might also be difficult to find a proper icon for denoting a person (ourselves) and have it as a badge on another icon that denotes a person as well (the avatar).

Another way could be to not use a badge but change the current user's avatar altogether so that it's easily distinguishable from the other avatars (but still make it non-taggable). Maybe a black-and-white avatar, or something other that seems different enough. It should still be of same shape though like the others and inside the ring, so the user can still identify from its color the signed status of his account. But he won't be able to see anymore his real avatar, i.e the one that other peers see when the user publishes an offer.

What do you think?

### Alignment examples

2-letter badge with current behavior (no alignment):

![notAligned1](https://user-images.githubusercontent.com/76814540/197369307-f3568b5c-8912-4006-89b3-8bf9db8e72f3.jpg)

3-letter badge with current behavior (no alignment):

![notAligned2](https://user-images.githubusercontent.com/76814540/197369308-9658dac3-ba46-4014-b311-979a5f2fa339.jpg)

2-letter badge with alignment:

![aligned1](https://user-images.githubusercontent.com/76814540/197369305-7d506902-74f5-4f68-8bc2-fd9974f8357e.jpg)

3-letter badge with alignment:

![aligned2](https://user-images.githubusercontent.com/76814540/197369306-a0e7dc19-550d-480d-8624-55b5d8fd30de.jpg)

The last two show a vertical scrollbar by coincidence.

The badge's style is for demonstration only. I don't think it should be red because users have associated badges with that color to notifications ("new" badge, numerical badges for open trades, chat messages, etc). So when you're looking at the screen and you catch the red "ME" badge with the corner of your eyes you keep having the impression that there's a pending notification of some sort.

**Comment by ghost** [comment]
The precedent for displaying `Me` has already been set with #6188.
I suppose the same can be done in the Buy/Sell and dispute screens.

**Comment by Android-X13** [comment]
I don't think a plain label will work in this case especially since in the dispute screen the avatar is immediately followed by additional text... anyway I'll see if I can come up with something
