### ISSUE TITLE
bitsquare on arm / oDroid

### ISSUE THREAD

**Issue by Onefox** [bisq-network/bisq#644]
i am trying to get bitsquare to run on my oDroid c2.

I started with this script:
https://github.com/SjonHortensius/BitSquareOnRpi/blob/4154260cb302b479c84b3ff56fb78cb7fb2fe219/bitsquare.sh

But the patch files are missing.

Anyway bitsquare is starting but that when i should give him a tor relay it crashes.
I don't know if the crash report is useful for you guys:
http://pastebin.com/BSwEdf0h
This is the console output:
http://pastebin.com/gR3FjTHL

**Comment by haiqu** [comment]
This question should be addressed to - I think - Sjon Hortensius. Apparently that's a fork of the project, we don't support Android builds directly (at this stage).

**Comment by Onefox** [comment]
Its not anroid, its something like a raspberry pi. (With Ubuntu Mint)
Also no fork code is used. Only the code from this repo.

**Comment by haiqu** [comment]
:) We still don't support it. That's a purely experimental build, you're on your own I'm afraid.

**Comment by mrosseel** [comment]
You could try the Oracle jvm

**Comment by haiqu** [comment]
I could easily run up Linux Mint under VirtualBox. The trouble is it's not x86 hardware so unless you have an Arm version of Mint and the actual oDroid hardware to test it with the result is inconclusive.

I could possibly try it on a spare Nexus 7 when the new LCD screen arrives. That will eliminate the OS anyhow. There is a Raspberry Pi around here somewhere too but I killed the memory card driver chip.

**Comment by haiqu** [comment]
Or if I were running Linux I could use this:

http://odroid.us/mediawiki/index.php?title=Step-by-step_Using_qemu_to_Boot_an_Emulated_Odroid

**Comment by haiqu** [comment]
I've just ordered a Raspberry Pi 3 off eBay on the weekend. Meanwhile I found the old dead Pi 2 and tried it, and bless me the thing booted! I'll give Mint Linux a try and see if I can solve this issue.

**Comment by Onefox** [comment]
Thank you :)

**Comment by haiqu** [comment]
I'll have to wait for the Pi 3 because the Pi 2 stopped booting again. Can you tell me exactly which distro you're running on the oDroid? Linux Mint official website doesn't have Arm builds and there are four different desktops available. A link would be useful. ;)

**Comment by Onefox** [comment]
Its Ubuntu mate for aarch64 from here:
http://odroid.in/ubuntu_16.04lts/
ubuntu64-16.04lts-mate-odroid-c2-20161017.img.xz
(http://odroid.com/dokuwiki/doku.php?id=en:c2_release_linux_ubuntu)
(http://forum.odroid.com/viewtopic.php?f=136&t=18709)

**Comment by haiqu** [comment]
Ah, it's Ubuntu Mate. There is a distro for the Pi as well. 

I reported the missing file to Sjon Hortensius and he has fixed that. If you do a `git pull` and use his patch it might actually work now. Meanwhile I got the Pi 2 to run again with Raspbian. Very dodgy system, it overwrites manually written config files. Finally got the wifi to work on a headless system after 4 hours. :)

**Comment by haiqu** [comment]
Making progress, I got Wheezy to boot and upgraded it. I forgot how much fun these toys are.

![raspi](https://cloud.githubusercontent.com/assets/13131219/19671217/8a712cc2-9ab0-11e6-8f5a-52deef17f8a9.png)

**Comment by haiqu** [comment]
Gone as far as I can go here. Ubuntu Mate for RasPi won't allow access via SSH to set up unless there's a monitor and keyboard attached. I don't have them here on the yacht, and I normally run headless.

Hope that patch helps you out anyhow. You might also find the second bounty thread useful, since it expands on the original patch:

https://forum.bitsquare.io/t/2-btc-bounty-for-improving-performance-of-bitsquare-on-raspberry-pi/295

**Comment by Onefox** [comment]
Thanks for the link, I am getting the es2, sw Graphics error now.
The problem is that the openjfx is missing for aarch64 i guess.
There is only the one for the 32 bit pi:
http://chriswhocodes.com/

**Comment by haiqu** [comment]
That's a very old version. RasPi has a lot more Java options: https://www.raspberrypi.org/forums/viewtopic.php?f=81&t=27805

**Comment by haiqu** [comment]
My new Pi 3 model B has arrived! Woo-hoo! But no new SD Cards yet. :(

I was surfing the 'net with Firefox on it today and couldn't tell the difference between that and my Core Duo laptop. It's a really nice board and great value at AU$56.00

**Comment by haiqu** [comment]
I think I can see the issue, apart from the lack of Openjfx. Your `uname -m` command is returning the wrong string. It's an OS issue, should be something like `armv8` but instead it's returning the OS string `aarch64`. The `-m` means `gimme the machine name`.

I finally got it to build today only to find out that I can't view it running without a monitor attached. VNC doesn't show anything but text. Most disappointed here. I used Oracle jdk-8u65 with the OpenJFX-8u60 from ChrisWhoCodes. Anyhow it does appear to be working.

**Comment by haiqu** [comment]
BTW I thought it worthwhile to make the comment that after spending two days wading through all the threads and changes made to get this going on the Raspberry Pi for the prizes offered, only one code contribution actually made any difference to the performance. That was Sjon's use of a direct link to the `/usr/bin/tor` directory, something that is usually frowned upon in Java because it isn't portable. But it sure did work.

The other contributions were all related to local setups rather than code changes. e.g. more memory to the GPU and stack and so on. So most of the code in those scripts can be ignored if you follow the manual build procedures.

If you could find (or build) a 64-bit version of Openjfx I think it will work fine.

**Comment by haiqu** [comment]
OK, just did some more reading. Sorry if this is getting tedious but you got me curious. The armv8 reports either aarch64 or aarch32 which is an armv7 compatibility mode. So you may be able to actually use the armv7 version of Openjfx if you have a 32-bit toolchain installed. In other words you'd probably need to be running a 32-bit version of Ubuntu Mate for oDroid, if such a thing exists.

These are the official JDK ports for the armv8, which are nowhere near complete yet.

Ref: http://openjdk.java.net/projects/aarch32-port/
Ref: http://openjdk.java.net/projects/aarch64-port/

**Comment by haiqu** [comment]
So, the answer to your original question (finally - and that's an in-joke for Java programmers) is that the oDroid does not yet have a proper Java version available because it uses the armv8 chip, so anything you do with it in Java will be a kludge and most likely won't work.

Probably not what you wanted to hear.

I'll leave this issue open for reference purposes.

**Comment by leshik** [comment]
I was able to install BellSoft JRE 10.0.2 on the RPi 3B+, as well as Gluon OpenJFX SDK (11.0.2)
When I execute the app, there are no errors in the console, even Bisq icon appears in system tray, but the main window never comes up. I wonder what might be the issue here?

**Comment by leshik** [comment]
Well, turned out, I was unable to view the main window through VNC. After I connected the TV to HDMI, I'm able now to see Bisq agreement. Seems JFX works directly on RPi `dispmanx`.

**Comment by haiqu** [comment]
Awesome!
