### ISSUE TITLE
payout tx failures

### ISSUE THREAD

**Issue by alberto-spain** [bisq-network/bisq#6526]
### After upgrading to v1.9.9 some trades fail. could be corrupted files. I have tried restoring from backup but problem still there so not sure if it is a bug.

Error
An error occurred at task: SignMediatedPayoutTx
Exception message: myMultiSigPubKey from AddressEntry must match the one from the trade data. trade id =45070-48dd354b-6eb3-4b57-b248-7d82ac053b36-199

An error occurred at task: SellerSignAndFinalizePayoutTx
Exception: java.lang.NullPointerException

### Steps to reproduce

I am going to try with a fresh install just in case is file corruption.

**Comment by ghost** [comment]
Thanks for reporting.  Your mediator can help by doing a manual payout.  After your open trade(s) have completed, please take steps to start a [fresh database instance](https://bisq.wiki/Switching_to_a_new_data_directory) in order to avoid further issues.

----

The issue has been reported [several times](https://github.com/bisq-network/bisq/issues?q=is%3Aissue++myMultiSigPubKey+from+AddressEntry+must+match).  In one case where it was possible to analyze the problem, it was due to database files getting corrupted.  It may be due to low disk space, or an [as-yet unknown reason](https://github.com/bisq-network/bisq/issues/6261#issuecomment-1174439971).

**Comment by alberto-spain** [comment]
Thank you!!
