### ISSUE TITLE
Ok to run multiple instances of bisq?  Same bisq wallet on 2 computers?

### ISSUE THREAD

**Issue by kryptosader** [bisq-network/bisq#6592]
Trying to run bisq on 2 different laptops, one for home, one for travel/work...backup.
I've managed to transfer/import bisq wallets (btc/bsq-alt) and fiat currency info, account age into new computer....but

but if i do any trades on one, the balance and history gets screwed up on the other.
Do i need to do a spv resync on the unused computer for every time i use the other computer?? 

Thanks IA....

**Comment by ghost** [comment]
Please do not run the same data directory on 2 machines at the same time, even if you don't run both instances at the same time, as data may get corrupted in strange ways. 

https://bisq.wiki/Restoring_application_data

**Comment by pazza83** [comment]
@kryptosader 

Best to have 2 separate Bisq instances for both computers.

You can backup your payment accounts from the old one and import them to the new instance so that both instances have the same payment accounts (should also copy over the signed status of any accounts).

https://bisq.wiki/Backing_up_application_data#Back_up_payment_accounts
