### ISSUE TITLE
ProcessOfferAvailabilityResponse error when taking offer.

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisq#6610]
### Description

![image](https://user-images.githubusercontent.com/50149324/226470844-368ca34c-ebd9-4f24-99b0-77caf07c92a9.png)

An error occurred at task: ProcessOfferAvailabilityResponse
Cannot take offer because snapshot height does not match. Probably your DAO data are not synced.

#### Version

1.9.9

### Steps to reproduce

Taking an offer.

### Expected behaviour

Offer is taken.

### Actual behaviour

Offer cannot be taken, pop-up is displayed. _DAO - Network_ does not show DAO out of sync.

#### Additional info

This issue occurred to 3 different users in the last days. One of the users could provide logs if necessary.

**Comment by CygnusGt** [comment]
Since yesterday I also receive this very error. I can no longer take any offers.

I did a complete DAO resync and checked that at least 1 inbound connection is active.
But the error message is still the same.

I am using v1.9.9 on macOS 13.2.1.
I can provide logs if needed.

**Comment by ghost** [comment]
@CygnusGt I've not come across this error before, so please provide logs through one of the support staff, thanks!  (Matrix is the best way to contact them).

**Comment by CygnusGt** [comment]
I have just sent a ZIP with the two latest logfiles (from this afternoon) through a DM on Matrix (different name there).

BTW: I am not one of the 3 users mentioned in the first entry of this thread.

And one more information: after not being able to take any offer since yesterday, this late afternoon it suddenly worked again. The error message did not show up.

**Comment by CygnusGt** [comment]
It seems to me that this problem occurs only occasionally - but then for all offers from the same seller.

Yesterday I was able to accept some (sales) offers, for others the error message came up. I then tried around and saw that the message came up for all offers of the same seller.

**Comment by ghost** [comment]
Thanks, that makes a lot of sense, the error message is coming from the counterparty. https://github.com/bisq-network/bisq/pull/6546 in the next release should help, as it will notify the maker that their offer could not be taken.

**Comment by wagfeliz** [comment]
I sorry to reopen, but I am getting this error on linux and there is no way to fix it, still an serious issue that prevents the app usage.

**Comment by pazza83** [comment]
Had another user report this when trying to take any offer. They have resynced their DAO and deleted outdated Tor files and are still getting this error. Any ideas of a fix?

**Comment by ghost** [comment]
@pazza83 The message means that one of the trading parties DAO is not in sync.  

- If it happens **consistently** when interacting with **any** makers it means the taker is out of sync.  
- If it happens to a taker only with some makers but not all, means the specific maker(s) are out of sync.
- The log file should contain a message about what the maker and taker block heights are.

I have a hunch that if the bitcoin node is no longer connected (configuration issues), it may cause this.  But would need to verify with users that are experiencing the problem.  Logs could help.

**Comment by Ven32123** [comment]
@jmacxx  What logs do you need and how could I run the report.
I don't know what happened. but my open trade has just been filled and I am able to now click on other's offers.

**Comment by ghost** [comment]
Log files can be accessed via the Account -> Backup screen in Bisq.  `Zip Log Files` will create a zip file named `BisqLogsArchive_[datetime].zip` and open an explorer window to the directory containing that zip archive.  Logs can be sent on Matrix to bisq support staff (via Direct Message attachment).

At this time I must admit to being in the dark as to why your issue resolved by itself.  Logs should provide an explanation.

**Comment by stamatefcristian** [comment]
I'm having the same issue on windows 10, bisq 1.9.14 .  The only thing that I did was canceling an offer to take another. Everything went fine with the cancelation now I'm not able to take any offer because of this.
The DAO is synced because the DAO state is "Your local node is in consensus with the network". Also everything is green there and I have a bunch of block heights with Peer 1 and green.
I looked up the logs and they are not very useful I basically get the same error as in the interface:
Feb-09 14:06:58.692 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: ProcessOfferAvailabilityResponse
Cannot take offer because snapshot height does not match. Probably your DAO data are not synced. 
Any advice other than delete all and re-install ?
I already did restart and "DELETE SPV FILE AND RESYNC" without success.
Edit the problem went away by itself 2 days after, which is very weird. From my point of view it is suspicious that these problems occur when there are a lot of offers and a high rise in bitcoin price. As if it just isn't able to handle enough offers from peers, becoming useless exactly when you need it most.

**Comment by martinbarilik** [comment]
I get this now as well, what does you dao state says ? 

Mine seems fine
`Your local node is in consensus with the network`

Syncing DAO takes 4 hours already after rebuilding DAO state. I am patient ATM.

**Comment by Rav3nPL** [comment]
When trying to accept offer getting warn in log:
```
WARN  b.c.o.OpenOfferManager: 
Received AckMessage with error state for OfferAvailabilityRequest with offerId [redacted] 
and errorMessage=We got a handleOfferAvailabilityRequest but our DAO is not synced.
```
GUI shows "chcecking offer is still valid" then timeout after some time.
Tried few offers from apparently different users, but it is the same.

Seems like peers can make offers w/o fully synced node?

Yes, resynced my DAO from scratch.
