### ISSUE TITLE
Offer keeps being disabled

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/bisq#6669]
### Description
A created offer is being disabled after a few seconds from enabling it, with the message:
` [JavaFX Application Thread] INFO  b.c.o.b.TriggerPriceService: Deactivating open offer xxxx due to mempool validation`

#### Version

1.9.10

### Steps to reproduce

1. Create an offer. Not every offer will behave like this.

### Expected behaviour

Enabled offer should stay enabled.

### Actual behaviour

Enabled offer disables itself after a few seconds. Sometimes a dozen or so.

#### Device or machine

Linux

#### Additional info

I can send logs in a private message, I'm "akira45" on Matrix.

**Comment by darawhelan** [comment]
Thanks for posting.

Wondering if this might have something to do with the increase in trade fees needing the trade fee filter to be correctly set.

Not sure who would know about this maybe @ripcurlx ?

**Comment by ghost** [comment]
I think it looks like this:

- Higher fees were voted in by the DAO yesterday.
- The filter which specifies fees to use at order entry was updated some hours later.
- Offers created during that brief time window paid using (stale) fee rate from the filter.
- They are flagged because the DAO thinks they should have used the appropriate (new) fee rate.
- I see no other option than the affected offers to be canceled, unless the team wants to disable fee validation again.

The manual filter setting was [added](https://github.com/bisq-network/bisq/pull/5826) because some users' DAOs were out of sync, and  some did not have the DAO enabled.

Inadvertently, having two separate sources of information has caused this new type of out of sync issue, a manual one.

I know it seems we're going back and forth a lot on this, but filter setting was added as a stopgap fix and this issue was not considered.  Plus, the DAO sync reliability has been improved a lot in the meantime.  Perhaps, now that the DAO sync issue is no longer (or much less of) a problem, the filter setting should be discontinued.

--- 
[EDIT] Offers created between approximate block heights 787016 (DAO result) and 787176 (filter update) would have been affected --> 160 blocks, just over a day.  Please could the support team make the call whether to temporarily disable fee validation or ask affected users to cancel their offers.

**Comment by Akira45-0** [comment]
Of course I can cancel the offer, but what about the maker fee? Should I ask for reimbursement the usual way?

**Comment by pazza83** [comment]
I would be favor of discontinuing the fee validation.

Trade fees paid for specific trades can always be manually checked in mediation if their are any concerns a user is trying to circumnavigate fees, which usually indicates they are trying to do other things against Bisq trading rules.

**Comment by ghost** [comment]
> Trade fees paid for specific trades can always be manually checked in mediation if their are any concerns a user is trying to circumnavigate fees, which usually indicates they are trying to do other things against Bisq trading rules.

I agree, but Bisq fee validation also prevents [offers/trades with invalid maker fee txs](https://github.com/bisq-network/bisq/issues/6603).

**Comment by pazza83** [comment]
Could the parameters of the check be changed to just check that a fee has been paid (maybe given a much wider margin for success).

That way it would still enable failed trades not be shown and for changes in fees between cycles not to cause offers to be disabled.

Maybe filter could be 50% below current rate to 100% above current rate.

**Comment by Akira45-0** [comment]
What's the ETA for disabling the filter/implementing new one (or whatever the solution may be)?
