### ISSUE TITLE
Investigate and fix blocking of UI thread at startup

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq#6704]
The UI thread gets sometimes blocked at blockchain/DAO sync. It seems that there is some blocking thread causing it. Also at shutdown I observed sometimes that the graceful shutdown does not finish and the app need to get killed. Maybe its a related issue. Might have been introduced by the thread changes in Broadcaster or other areas in connection and/or in DAO data processing.

**Comment by helixx87** [comment]
Hi @HenrikJannsen
I predict this issue occurs quite rarely and it will be hard to reproduce it consistently. I wonder what tools we can use to collect  necessary information (logs, stack traces) that could provide valuable insights into the root cause - do you have any idea here? 
Did you noticed any patterns or specific steps that trigger the issue (does it occur after a certain period of time, when performing a particular operation, or in response to specific user interactions)?

**Comment by HenrikJannsen** [comment]
I get it quite often when starting up an app i have not used for days or weeks. I think the combination of BitcoinJ wallet sync and DAO data sync triggers the issue. It could be some edge cases of those 2 parallel and dependent streams (e.g. DAO sync takes the most recent bitcoinj block head height but that might be older then the shipped DAO data).
Or the load on processing btc data and dao data.
