### ISSUE TITLE
Bisq does not run in latest Tails release 5.13

### ISSUE THREAD

**Issue by 402PaymentReq** [bisq-network/bisq#6707]
"Running Bisq on Tails" guide stopped working after latest Tails upgrade.
https://bisq.wiki/Running_Bisq_on_Tails

Bisq v1.9.10
Tails 5.13

A fix would be greatly appreciated.
Thanks!

![bisq_tails_error](https://github.com/bisq-network/bisq/assets/124446805/70404c13-c264-442e-9d68-39b49d95e017)

**Comment by ghost** [comment]
Tails release 5.13 changed the tor control port!  Could not find any documentation, but here's the commit:

[onion-grater: Use port 951 instead of 9051 as control port](https://gitlab.tails.boum.org/tails/tails/-/commit/50afb92b71fadc03984853d10bda61a2ba2fd9f4)

To run Bisq in tails 5.13 the command would be:

    /opt/bisq/bin/Bisq --torControlPort 951 --torControlCookieFile=/var/run/tor/control.authcookie --torControlUseSafeCookieAuth

The `install-bisq` script can be adapted by replacing 9051 with 951.
