### ISSUE TITLE
Transaction Fee gone after failing to put a sell order on the market

### ISSUE THREAD

**Issue by SymmetryStan** [bisq-network/bisq#6779]
I recently tried to put a sell order on the market. Unfortunately it failed. I was using version 1.9.10 and have since upgraded to 1.9.12 (after getting the error).

After reloading BISQ, unfortunately my transaction fee has gone. Is there any way to get this back?

Thanks

**Comment by ghost** [comment]
1. What was the error message?
2. Did the transaction show up on the blockchain?

Perhaps you need to do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)?

**Comment by SymmetryStan** [comment]
hi,

The error message in the logs is:

Jul-24 09:45:58.454 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: AddToOfferBook
Please update to the latest Bisq version. A mandatory update was released which disables trading for old versions. Please check out the Bisq Forum for more information. 

There are 5 or 6 instances of that.

The transaction does indeed show up in the blockchain. It is strange though, in my transaction history, it shows my initial deposit to my BISQ wallet (0.005), then shows a withdraw from wallet for 0.00006750 (this was the tx fee for the failed transaction). The link it has for the blockchain is showing as confirmed, but it shows the input as 0.005 and the tx fee as 1750 sats.

I have tried an SPV resync but it doesn't appear to have changed anything, it still shows the same information above.

It's not the end of the world (it's around £1.50), i'm just wondering what has happened and how to avoid it in the future. Obviously using the latest version seems to help!

**Comment by ghost** [comment]
@SymmetryStan Thanks for explaining the issue.  It looks like someone flipped a switch at Bisq HQ making the latest release mandatory.  I think that should have been handled a bit differently, perhaps with a system alert asking users to upgrade and giving them at least a week to do so.  As it stands, this config change seems to have caused your offer to fail.  Your loss as reported is 6750 sats (5000 sats Bisq [maker fee](https://bisq.wiki/Trading_fees) & 1750 sats miner fee).

For fee reimbursements (due to failed trades, bugs etc..) we do have a procedure, details here: https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees

**Comment by SymmetryStan** [comment]
Hi,

Thanks very much for your quick reply and explanation. I think your idea is good, perhaps in the future this can be implemented to help prevent this kind of thing from happening again. 

I'll be sure to check out the fee reimbursements link.
