### ISSUE TITLE
can't install on arch

### ISSUE THREAD

**Issue by ralyodio** [bisq-network/bisq#6951]
```
==> Validating source files with sha256sums...
    bisq-1.9.14.tar.gz ... Passed
    bisq-1.9.14.tar.gz.asc ... Skipped
    bisq.desktop ... Passed
:: Remove make dependencies after install? [y/N] 
:: (1/1) Parsing SRCINFO: bisq
gpg: error reading key: No public key

 :: PGP keys need importing:
 -> B493319106CC3D1F252E19CBF806F422E222AA02, required by: bisq
:: Import? [Y/n] 
:: Importing keys with gpg...
gpg: keyserver receive failed: Server indicated a failure
 -> problem importing keys
```

**Comment by kiocos** [comment]
perhaps a DNS issue?
You could try to edit your `/etc/resolv.conf` to
```
nameserver 1.1.1.1 # Cloudflare
``` 
in order to use a different DNS server and see if it helps.

Alternatively, you could try to download it manually from here: https://keys.openpgp.org/search?q=B493319106CC3D1F252E19CBF806F422E222AA02 (this is the key you provided in your issue, change it if necessary) 

Then run `gpg --import B493319106CC3D1F252E19CBF806F422E222AA02.asc`.

After that, try to install bisq again and it should have the key imported already.
