### ISSUE TITLE
Bisq software keeps failing at launch on macOS Monterey

### ISSUE THREAD

**Issue by Jayboi23** [bisq-network/bisq#7062]
### Description
After upgrading my macOS to Monterey, I installed the Bisq software but it keeps quitting at launch.

#### Version
1.9.14

### Steps to reproduce
Not sure

### Expected behaviour
I was expecting the software to start the normal way so i can import my wallet and continue using the software the normal way like before.

### Actual behaviour
It keeps quitting on its own at launch

### Screenshots
![Screenshot 2024-03-20 at 15 30 53](https://github.com/bisq-network/bisq/assets/126802382/869d5d6d-482b-46e4-9875-045ee6f434fe)

#### Device or machine
Macbook air (11-inch, Mid 2011), running macOS Monterey

#### Additional info
[Error Logs.pdf](https://github.com/bisq-network/bisq/files/14668291/Error.Logs.pdf)

**Comment by ghost** [comment]
[A JFX bug reported and fixed in 2021](https://bugs.openjdk.org/browse/JDK-8275723) matches this excerpt from your `Error_Logs.pdf`:

    4 libjvm.dylib 0x106bbc876 VMError::report_and_die(int, char
    5 libjvm.dylib 0x1066633d8 report_fatal(VMErrorType, char const*,int, char const*, ...) + 188
    6 libjvm.dylib 0x106a92db6 SafepointSynchronize::block(JavaThread*) + 472
    7 libjvm.dylib 0x106a949a1 SafepointMechanism::block_if_requested_slow(JavaThread*) + 29
    8 libjvm.dylib 0x106b74dde JavaThread::check_safepoint_and_suspend_for_native_trans(JavaThread*) + 156
    9 libjvm.dylib 0x1067eaca5 jni_DeleteGlobalRef + 145
    10 libglass.dylib 0x1262e6fe8 -[GlassRunnable dealloc] + 40



From a `bisq.log` received a few days ago via @pazza83, the Java used is Azul: `os.name=Mac OS X; os.version=12.7; os.arch=x86_64; sun.arch.data.model=64; JRE=11.0.20+8-LTS (Azul Systems, Inc.); JVM=11.0.20+8-LTS (OpenJDK 64-Bit Server VM)`


---

- You could [build from source](https://github.com/bisq-network/bisq/blob/master/docs/build.md) with a newer/different JDK.
- Perhaps @alvasw can look into the issue further.

**Comment by Jayboi23** [comment]
But to my surprise, Bisq 2 works perfectly fine on the same machine. I I guess the issue is with the Java JDK I have running on my system, i I will be downgrading it to JDK 11 to see if it will work.

**Comment by Jayboi23** [comment]
Building from source works, Thanks
