### ISSUE TITLE
Option to withdraw an exact amount excluding transaction fee

### ISSUE THREAD

**Issue by LuccoJ** [bisq-network/bisq#713]
When sending coins to other people or services, it is often required to send a very exact amount. However, the Bitsquare wallet only lets you specify the total amount that will be deduced from you, including any transaction fees. This way, it seems very hard to know with absolute certainty how much the recipient will get exactly, which could result in problems and actual losses.

Could an option be provided to withdraw a specified amount not including the transaction fee to be paid?

**Comment by ManfredKarrer** [comment]
Yes that feature is on the todo list. I will try to get it into the next release.

**Comment by ManfredKarrer** [comment]
If anyone would work on that please use the DAO branch as there are many changes in the wallet code base and they way how fees are handled.

**Comment by jomuel** [comment]
Is this still open? If so I would try it tomorrow or on Monday...

**Comment by ManfredKarrer** [comment]
Great! Yes it is still open. In the DOA branch we use protobuffer so you need a bit extra setup (described under the doc folder). You also need to run all locally (regtest with local seednode) because there is no seednode deployed yet (or if so it is not well maintained with code changes). Instructions are in the GH wiki.

**Comment by ManfredKarrer** [comment]
Implemented now with https://github.com/bisq-network/exchange/commit/52d6d8adc69f59d3e039d9f32d72a3345e5e27d6

**Comment by cbeams** [comment]
Excellent!
