### ISSUE TITLE
Erro ao tentar abrir o bisq "Connection failed to mainnet de bitcoin (via Tor)

### ISSUE THREAD

**Issue by filli4n** [bisq-network/bisq#7212]
### Description

![Captura de tela 2024-07-22 130558](https://github.com/user-attachments/assets/af94d353-a1f0-4340-913c-277d3ea439d4)
já atualizei o Tor para a nova versão e pelo que vi não há uma nova versão para o bisq, Já tentei trocar o código tor, O que pode ser e como posso resolver??

**Comment by kiocos** [comment]
(English below)
:brazil:  @filli4n De acordo com o [código fonte](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/wallet/DeterministicUpgradeRequiredException.java) do bitcoinj, esse erro acontece quando "foi feita uma tentativa de usar recursos de carteira HD em uma carteira que foi desserializada de uma carteira aleatória antiga, pré-HD sem chamar upgradeToDeterministic() previamente".

Você pode tentar renomear a pasta onde a carteira da Bisq é guardada. Minha sugestão é renomeá-la para que a Bisq gere uma nova pasta **e uma nova carteira.** 

:warning:  **Não exclua** a pasta se você possui saldo em sua carteira da Bisq!! 

A depender do seu sistema operacional, pode encontrá-la em:
```
macOS: /Users/<username>/Library/Application Support/Bisq
Linux: /home/<username>/.local/share/Bisq
Windows 7+: C:\Users\<username>\AppData\Roaming\Bisq
Windows XP: C:\Documents and Settings\<username>\Application Data\Bisq
```
Renomeie a pasta Bisq para algo como "Bisq_old" e tente novamente.

---
:gb: @filli4n According to the bitcoinj [source code](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/wallet/DeterministicUpgradeRequiredException.java), this error occurs when "an attempt was made to use HD wallet features on a wallet that was deserialized from an old,
 * pre-HD random wallet without calling upgradeToDeterministic() beforehand."

You can try renaming the folder where the Bisq wallet is stored. My suggestion is to rename it so that Bisq generates a new folder and **a new wallet**.

⚠️ **Do not delete** the folder if you have funds in your Bisq wallet!!

Depending on your operating system, you can find it in:
```
macOS: /Users/<username>/Library/Application Support/Bisq
Linux: /home/<username>/.local/share/Bisq
Windows 7+: C:\Users\<username>\AppData\Roaming\Bisq
Windows XP: C:\Documents and Settings\<username>\Application Data\Bisq
```
Rename the Bisq folder to something like "Bisq_old" and try again.
