### ISSUE TITLE
Variable deposit based on volatility

### ISSUE THREAD

**Issue by ulrichard** [bisq-network/bisq#723]
For as long as the prices are relatively stable, the fixed deposit is perfectly fine.
But when it is highly volatile, the incentives can change.
Suppose the BTC price just plunged, and I think it will go up again soon. In the time needed to wire fiat money to a centralized exchange, the price might have recovered already.
So, I accept a SEPA offer on bitsquare. Effectively I locked the price. Two days later the price didn't go up as I expected, but it plunged further. If the price difference is higher than the deposit, the incentive flipped, and I might be tempted not to wire the money.
I think most people using the platform so far want it to succeed, and add this and their reputation into the equation. But that might not stay that way when more people enter.

**Comment by ManfredKarrer** [comment]
Yes it is an open issue and already solved for the next (big) release. We will make the deposit customizable when you create the offer, so traders can adjust it to the current market situation and their requirement for hedging against volatility. There will be a trade-off as a very high deposit protects better but u will find less traders who will take it. So the market will find the best values (hopefully).
Luckily it does not happen too often but in times of high volatility I get disputes because of that. With BTC/fiat trades it was rare, just the last weeks with happened a few. With altcoins it happened when the altcoin was too volatile. 
I find it a pity also that traders abuse that current weakness and instead of supporting the platform use it to cheat the peer in such situations. But that's reality and we need to fix that of course.
On the other side u can see it positive as a hedge where the BTC buyer cannot lose more then the security deposit. As it is one-sided it will probably lead to a price bias in favor to the seller as he takes a higher risk. But that can open up interesting arbitrage with other exchanges :-)

**Comment by ManfredKarrer** [comment]
We will use customizable security deposit in the next version, so the offer maker can decide it in between a range.
