### ISSUE TITLE
ClearXchange Chargebacks?

### ISSUE THREAD

**Issue by FMJ62** [bisq-network/bisq#734]
I live in the U.S., so when I try to select "Bank Transfer" as a form of payment, I get a message that says...

"Bank transfers are not supported in the US because WIRE transfers are too expensive and ACH has a high chargeback risk. Please use ClearXchange, US Postal Money Order, or Cash/ATM Deposit instead."

This message makes me think that ClearXchange transfers are not at risk of chargebacks. But I was told that ClearXchange transfers can be charged back (transaction reversed).

So I called ClearXchange and the representative told me YES, some banks will reverse charges if the customer claims fraud or sent to the wrong email address.

If this is true, ClearXchange is NOT a good way to accept payment for selling bitcoin.

I guess it would depend on how easy is it to claim fraud and receive a chargeback. How long do they have to claim fraud? How often does a fraud claim get approved? Is the other party (the person who received the funds) contacted during the fraud claim process?

I'd like to know the answers to these questions before I accept payment through ClearXchange.

**Comment by MarcSte** [comment]
Thanks for your interest and critical remarks.

Next time please consider posting to the [Bitsquare forum](https://forum.bitsquare.io/) as Github is Dev territory and you'll get better feedback over there.

You know, payment methods are a mixture of  thourough research and a little bit of trial and error. Banks write so much shit in their terms of service, faqs and everywhere, but still do different stuff in reality. We can't know for sure. For example, rumors say that SEPA chargebacks can happen, but in more than thousand (?) Bitsquare trades, there's not a single chargeback.

Your call at cXc is a single, unofficial voice and diametrically contradicts the cXc faq, which is why, at the moment, I'd go ahead recommending  them for US traders. I cannot know for sure, of course. There's no one in charge of Bitsquare, it's just a platform for people, who should at all times stay critically and keep questionning stuff. Make your own rational decision based on your knowledge and you should be fine.

Right now we've had more than 150 successful cXc trades on Bitsquare without a single chargeback. I can't answer your questions regarding cXc directly.

So, in your case, I'd recommend starting with small amounts and make yourself familiar with the process. On localbitcoins, traders offer paypal (trivial to chargeback) as payment method and charge a very high extra on their btc to make up for fraudsters.

Please close this, as it's not directly relevant here and let's discuss over at the message board for more opinions. Your voice is very welcome there!

**Comment by FMJ62** [comment]
Sorry for posting in the wrong place.
