### ISSUE TITLE
Confirmations taking very long time

### ISSUE THREAD

**Issue by HSB65** [bisq-network/bisq#742]
Why are my transactions taking so very long to confirm?

I have one transaction from February 2 at 10:06:15 which still hasn't been confirmed.

https://www.blocktrail.com/BTC/tx/37a5cb02d417e52dcaa2d9d96a873b97f34c02df1b3cb53e5d4a564bb3f33935

**Comment by ManfredKarrer** [comment]
Seems the blockchain backlog is very large again. We use a fixed fee which is in such stress times (spam attacks) unfortunately a bit too low. In the next release we will use a dynamic fee so that should not happen anymore then. 
See: https://tradeblock.com/bitcoin/
70k unconfirmed txs in backlog. Normally it is about a 5k-20k.
And f***ing AntPool is mining still empty blocks...

If the tx does not get confirmed in the trade period and one of the peer opens a dispute there will be no loss of the security deposit. The arbitrator will check and do the payout then.

**Comment by ManfredKarrer** [comment]
Btw: Better use the Forum for such, Github is mainly for development stuff. I close here, feel free to join the Forum if you have more questions.
