### ISSUE TITLE
Zonealarm deletes program before it can run

### ISSUE THREAD

**Issue by Hermetic** [bisq-network/bisq#788]
Zonealarm Extreme Security treats Bitsquare as malware on Windows 7 64 bit.

After I installing Bitsquare, and while I was reading the disclaimer before clicking on the "I agree" link to start the program, everything disappeared. A Zonealarm alert soon popped up and said it had detected some malware on my system and I would need to restart my system to complete the disinfection process. 

Is this a known issue? Is there any way for me to install this on Windows 7 with Zonealarm?

Thanks

**Comment by ManfredKarrer** [comment]
I assume you have downloaded it form our webpage (https://bitsquare.io/) or Github (https://github.com/bitsquare/bitsquare/releases/tag/v0.4.9.9.1). You can additionally make a signature check to be sure that the downloaded files are not tampered.

If that is the case then it is a false positive. 
We got it reported with other AV software as well and I investigated but it is for sure a false positive. It is because we use Tor and hidden services and they flag that. Our Tor binary was cross checked and it was all correct (used form official Tor browser).
Can you contact them to report it and that they remove/fix it?

**Comment by Hermetic** [comment]
I downloaded from Github. 
I verified the signature.

I will contact ZA and try and get them fix the issue with this program.

In the meantime I wonder if I turn ZA off temporarily and install it whether it will delete it again, or give me a chance to whitelist it or something...

Thanks

**Comment by ManfredKarrer** [comment]
Thanks. You can also try out another AV software like AVG. I use that on my windows VM and there is no issue. McAffe and Kaspersky also delivered FP. At Kaspersky we filed a request for the FP.

**Comment by Hermetic** [comment]
I reported the FP on the ZA forums(couldn't find much info on any better way to do it at the time.)

After some more research I found out that ZA uses the same signatures as Kaspersky so by submitting a virus or FP to Kas, if they fix the problem it will be fixed for ZA as well.

**Comment by ManfredKarrer** [comment]
Ah thanks! Best AV is to not use Windows ;-)

**Comment by Hermetic** [comment]
Just another follow-up with the relevant thread from the ZA forums:
https://www.zonealarm.com/forums/showthread.php/70505-How-to-diagnose-and-or-report-antivirus-antispyware-false-positives

It confirms that ZA uses the same sigs as Kaspersky.
