### ISSUE TITLE
Add custom market data sources

### ISSUE THREAD

**Issue by FrancisPouliot** [bisq-network/bisq#807]
My OTC exchange does not use Bitcoin Average. We have our own data source which integrates a dynamic algorithm which calculates an index and build-in spread according to volatility. Instead of charging (x)% over the Bitcoin Average price, I would like to have the ability to get my own price via my public API.

**Comment by ManfredKarrer** [comment]
That would be theoretically possible to offer user defined price feed sources but it will fragment the market because the 2 peers need to agree on the same price feed. It would make it also less transparent as users need to understand the difference of the different price feeds. So I fear that is nothing what makes sense to integrate.
