### ISSUE TITLE
seem to have lost 3btc in Bitsquare client

### ISSUE THREAD

**Issue by hadvocacy** [bisq-network/bisq#834]
hi, i deposited twice as shown in attached transaction log: 3.09 BTC and 3.05
BTC.  I then bought one SF for 3 BTC. I should have 3.2 BTC left.  Instead I
have 0.2 BTC left according to my BTC balance. The 3 BTC has disappeared.

I received a weird error message dialog from the Bitsquare client saying that
"no money had left my wallet" twice even though when I posted an offer for 3BTC
for 1 SF it gave me a network client error twice. Now it seems like the 3 BTC
is gone.  Transaction log posted below.

Date/Time,Details,Address,Transaction ID,Amount in BTC,Confirmations
"Jun 17, 2017 3:17:04 PM",Withdrawn from wallet,Sent to: 1FdFzBazmHQxbUbdCUJwuCtR37DrZrEobu,0a231bd395b999778720bc7901c8a0e8b5767d30bf7384c75a8fa5a6ef4750da,-0.0018,24
"Jun 17, 2017 3:13:07 PM",MultiSig payout: WFDTNKIB,Received with: 1LALYaXf3ULTqvDggzuPkjYNTDmLvYqKaP,03c97fcfb23d28ac310f2f1a5ca6c881ba3785cc266aa6576b0d091da6d92d02,0.03,24
"Jun 17, 2017 3:11:45 PM",Received funds,Received with: 1P6k9Ftge8vB6P6keCWW7rrcwm1dQA9bYZ,81849aa623a3d32698129964f82e3ab593964ba07a9b9c53b2196124735965f8,3.05626943,24
"Jun 17, 2017 2:32:41 PM",MultiSig deposit: WFDTNKIB,Sent to: 355qraqhAvX24aQk7BviLSgNyoYdXg9Tar,c4948e7c5a3b39b17c40c401583185e1ab996b456c803a311c200402be3c81d7,-3.0315,26
"Jun 17, 2017 1:48:07 PM",Create offer fee: WFDTNKIB,Sent to: 19xdeiQM2Hn2M2wbpT5imcYWzqhiSDHPy4,b554400df968735e10a1c87afe090c22236ae1614e5790ff909d16605320c214,-0.0018,27
"Jun 17, 2017 1:46:35 PM",Received funds,Received with: 1P6k9Ftge8vB6P6keCWW7rrcwm1dQA9bYZ,31eb71e9a0c9777297a52198b85560f3156a002f54b11caf65a12aaba561b9dd,3.09196723,27
"Jun 17, 2017 1:43:08 PM",Received funds,Received with: 1P6k9Ftge8vB6P6keCWW7rrcwm1dQA9bYZ,0fe60fa6a64eb57e6fcdb8553d83d387f186325eccfbc31423a63e7d018551e9,0.10,29

**Comment by hadvocacy** [comment]
I got an error message something like:
A timeout occurred.

No funds have left your wallet yet.
Please try to restart you application and check your network connection to see if you can resolve the issue.Please try to restart you application and check your network connection to see if you can resolve the issue.

But it looks like (from the Bitsquare balance indicator etc) that the funds are gone.

**Comment by hadvocacy** [comment]
![badbalance](https://user-images.githubusercontent.com/29513629/27257614-aa7c0c2c-5391-11e7-89fb-7cc641f0a40e.png)

**Comment by mrosseel** [comment]
Manfred might know what's going on, but usually people don't lose their
funds so don't despair yet. The wallet is probably in a confused state but
if that's the case there are procedures to recover it.

**Comment by hadvocacy** [comment]
Thank you, this eases my mind further although I am not despairing; indeed I am also a (minor) blockchain developer and happily trying to deduce/debug the logic flaw now. I tried restoring using my seed words + recovery date on another computer and believe I may have discovered another bug. After restoring with date 6/17 in the wallet dialog it showed the correct seed words but the NEXT day not the one i remember restoring with (clicking on the calendar GUI!) .. so it looks as if there is a timezone translation error related to the date used in wallet seed recovery backup restore. probably related to different timezones or local vs UTC etc. just guessing hope this helps good luck my friends and i look forward to seeing your progress at this exciting time

**Comment by ManfredKarrer** [comment]
Due the timeout error the internal wallet DB got probably out of sync. The UI does not reflect the real balance then. You can check the real balance with cmd+e (ctrl+e) or alt+j (alt+j) which displays all wallet detail data (keyd, txs,...). 
If you have open offers related to that failed offer please remove it as it is likely that it will fail in case someone takes it. If you dont have any offers/trades/disputes open i recommend to withdraw all to an external wallet (by cmd+e). adjust the tx fee in the settings first, must be >100 sat/byte.
Follow the instructions here to set up a new data directory:
https://forum.bitsquare.io/t/switching-to-a-new-data-directory/1697

**Comment by ManfredKarrer** [comment]
@hadvocacy 
Ah good that you are a dev and thanks that u are helping with debugging!


Regarding the date: the date for the wallet recovery is just for optimisation (sync from that data on when the wallet was created). as many people forget to write up the data i disabled a strict check int he ui so u can set any date, but best is the real data as otherwise the resync takes longer. the data must not be younger then the wallet creation data as u might miss then txs... maybe i should add a check for that so u can only use older dates...

The wallet error:
Just a bit of background: The internal DB maps addresses to offers/trades. so the BTC for an offer gets reserved so it cannot be used for something else, otherwise nobody could take the offer if the btc is not there. this is done by a internal DB structure. u can see that in the wallet tool details (alt+j). there are offer IDs and 4 addresses attached to it (context, offer funding, reserved, deposit/MS, payout). If due an error the update of that data structure fails the display of the balance might get wrong. there are known bugs in that area when u have a timeout at a take offer or create offer attempt. as we are working on a new version with 100s of changes i dont want to spend time to debug that old issue and hope it is solved anyway in the new version.
But as long the user has not lost access to the wallet (backups, pw not forgotten) there is no risk that funds can be lost.

**Comment by hadvocacy** [comment]
yes that is what it was; i had an offer in stage 3/4 (everything done but final confirm) and i tried to start a second one before the last was finished. i think it was before 24 hours was up before the last trade so maybe that had something to do with it (maximum 1 trade / 24 hours). so i think it accidentally tried to make two new offers while the first was still in phase 3/4. then both got removed automatically but the balance went wrong as you thought.  thanks for the command e it worked perfectly to recover all the missing funds. i appreciate the help. cheers, -hadvoc
