### ISSUE TITLE
Signing key 404

### ISSUE THREAD

**Issue by TheButterZone** [bisq-network/bisq#837]
On https://github.com/bitsquare/bitsquare/releases

> Url of the signing key (Manfred Karrer): https://bitsquare.io/pubkey/F379A1C6.asc

404 ^

**Comment by mrosseel** [comment]
All domains have switched to bisq.io after that release happened, try the
same link with bisq.io it might work.

On Jun 22, 2017 06:37, "Alwin Roe" <notifications@github.com> wrote:

On https://github.com/bitsquare/bitsquare/releases

Url of the signing key (Manfred Karrer): https://bitsquare.io/pubkey/
F379A1C6.asc

404 ^

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitsquare/bitsquare/issues/837>, or mute the thread

**Comment by TheButterZone** [comment]
Could you have? 

Not Found

The requested URL /pubkey/F379A1C6.asc was not found on this server.
Apache/2.4.25 (Debian) Server at bisq.io Port 443

**Comment by mrosseel** [comment]
OK then it's a bug during domain migration.

**Comment by jonathancross** [comment]
I think it is just an error in the release notes as the key file (F379A1C6.asc) is part of the release itself[1].

Seems this was intentional as the [Bisq download page](https://bisq.io/downloads/) also links to the same F379A1C6.asc file in the release[1].

[1] https://github.com/bitsquare/bitsquare/releases/download/v0.4.9.9.3/F379A1C6.asc

**Comment by ManfredKarrer** [comment]
Yes there are some issues with the server migration that some files are not copied over. Will try to fix that asap.

**Comment by ManfredKarrer** [comment]
Fixed. the key is on the server now. Thanks for reporting!
