### ISSUE TITLE
Redesign bitsquare.io site

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#84]
This is a placeholder issue for the moment, capturing the fact that we'd like to build out the http://bitsquare.io website to something more than the basic one-pager that it is today.

The repository for the current site is at http://github.com/bitsquare/bitsquare.io

**Comment by cbeams** [comment]
@ManfredKarrer, anything more specific here, or shall we close this?

**Comment by ManfredKarrer** [comment]
I dont have much specific description here as I left it also open to Lloyd to come up with conecpt and content. Just wanted to have it in the issue list so it is visible that somebody is working on it.

**Comment by cbeams** [comment]
I see, thanks. I've updated the description and title accordingly.

**Comment by joachimneumann** [comment]
I do not know if you plan to use the roles of Alice and Bob in the communication to non-developers. I fear that these names might sound more mathematical than we think, because they typically pop up in very technical talks. Also, during the demos with Manfred, there were moments of confusion "Wait, who wanted to buy Bitcoins, Alice or Bob?" Maybe a more realistic example would be better like a Filipino or Argentinian sending remittance to his home country.

**Comment by ManfredKarrer** [comment]
@joachimneumann: No we don't want to use Alice/Bob in Hi-level docs or communication. Remittance to home country" could be a nice example!

**Comment by cbeams** [comment]
FYI, I'm using Alice and Bob in the _Use Cases_ section of the user guide (#91), but I'd be happy to see that reworked later. Agree in any case that it's a good idea to avoid geeky inside references on the bitsquare.io website.
