### ISSUE TITLE
.sortType : A bound value cannot be set.

### ISSUE THREAD

**Issue by psyantyst** [bisq-network/bisq#869]
Got this issue while sorting buy offers.

[bisq.log.txt](https://github.com/bitsquare/bitsquare/files/1149413/bisq.log.txt)

**Comment by emisolo** [comment]
Same thing happens to me using Bisq on Ubuntu. When trying to sort available offers by price, I get the message: 
.sortType : A bound value cannot be set

**Comment by ManfredKarrer** [comment]
Thanks for reporting.
Fixed with https://github.com/bitsquare/bitsquare/commit/5af504095e96a807e2b78a8b12520d430af4312c

**Comment by emisolo** [comment]
Great !


2017-07-27 0:10 GMT+01:00 Manfred Karrer <notifications@github.com>:

**Comment by ghost** [comment]
Hello, i am getting this error when i tried sorting EUR (min - max) column, now i try going back to sort by "Price in EUR for 1 BTC" and then it throws this error.   The other columns i can sort. But no longer the first column.   still a bug

**Comment by ManfredKarrer** [comment]
I assume you have the the latest version 0.55.3, right?

**Comment by ghost** [comment]
yes definitely. v0.5.3

**Comment by ManfredKarrer** [comment]
Just tried to reproduce but could not. Can you reproduce it? If so can you post exact steps? Thanks.

**Comment by ghost** [comment]
Im using it in Ubuntu 16.04 by the way.
Ive reproduced it numerous times doing this:
I open Bisq, and whether i go to Buy or Sell (it doesnt matter which)  I sort one of the columns other than "Price in EUR for 1 BTC", then i go back quickly to sort "Price in EUR for 1 BTC" and it immediately throws the error.

It also doesnt matter which columns other than "Price in EUR for 1 BTC" i sort first, when i go back to it thats when it throws the error.
I usually have to close Bisq so that it can auto-sort everything out.

**Comment by ManfredKarrer** [comment]
Ah now with the release version I could reproduce. Tested before with my dev version where that bug is already fixed.

**Comment by ghost** [comment]
oh good, im glad! thank you!

**Comment by emisolo** [comment]
@emisolo  Deleted spam. Maybe you have some malware on your system... Also got an email...

**Comment by ghost** [comment]
??? @ManfredKarrer seems like you have a stalker spammer lol
