### ISSUE TITLE
Fasterpayments dispute upens automatically after 24h, deposit stolen! 

### ISSUE THREAD

**Issue by bisqsux** [bisq-network/bisq#944]
_No name and surname was provided by bisq to be able to pay. Etay away from Bisq as this is buggy Windows only app and you Will easily loose your security deposit!_

**Comment by cbeams** [comment]
I was the arbitrator on this trade. Here is the write-up I provided to both buyer and seller when closing this trade's dispute ticket:

![image](https://user-images.githubusercontent.com/301810/30962131-ed073730-a448-11e7-9d1c-c9607fc64734.png)

Notice the `UPDATE` section in which I re-opened and re-closed the ticket. This was because the deposit transaction did not get paid out as expected the first time. When this happens, we re-open and re-close the ticket in a way that coordinates signing the multi-sig payout transaction with the other party.

In this case, the payout transaction still did not occur. I know, because I've been monitoring the multi-sig address in question, waiting for it to happen. **Your security deposit has not been lost or stolen.** This is a p2p networking issue that we see very occasionally, and it is one with a clear path to resolution.

@bisqsux, I will re-open the dispute ticket in Bisq, and I will ask you to work with me to follow the instructions at https://github.com/bisq-network/docs/blob/master/exchange/howto/manual-dispute-payout.adoc. I will provide you there with the information you need to do that.
