### ISSUE TITLE
Get Bisq with JDK9 working

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#966]
Using JDK9 seems to break Lombok. At compilation with maven it fails at core module as it cannot find the setters/getters. Inside IntelliJ it works though.

**Comment by ManfredKarrer** [comment]
I also don't get protobuffer files recognized inside IntelliJ after updating to latest IntelliJ and JDK9. 
Not sure if thats a JDK9 issues as well or cuased form changes in the latest IntelliJ.
Got similar problems reported from another dev who started with JDK9 and failed to get Bisq compiled.

**Comment by mrosseel** [comment]
There's a new Lombok version, if I recall correctly it has jdk9 fixes

**Comment by ManfredKarrer** [comment]
I installed via IntelliJ latest version (did not check if there was a new nightly build version)...

**Comment by mrosseel** [comment]
that's for the lombok plugin, but did you also update the lombok version in the pom?

**Comment by ManfredKarrer** [comment]
Ah, no. Maybe that's the issue....

**Comment by mrosseel** [comment]
I tried in my branch, had some maven issues:
https://github.com/mrosseel/bisq-exchange/tree/java9

**Comment by sqrrm** [comment]
When I compiled with jdk9 I had to use a newer version of lombok and do some surgery on libraries that no longer exist in jdk9. I could then compile from this branch https://github.com/sqrrm/exchange/tree/compile-jdk9 but I don't know exactly what the changes break.

With these changes it won't compile with jdk8. There is however a new multi release feature in jdk9 that should make it possible to build for both versions so that we could maintain support for both jdk8 and jkd9 without maintaining separate branches for each. I couldn't get that to work nicely though.

**Comment by ManfredKarrer** [comment]
Lets wait a bit until jdk9 support is better. would hurt devs who want to build from source if its not working without much troubles.

**Comment by mrosseel** [comment]
if you could make it work for both jdk9 and jdk8 that would be interesting, otherwise it's a barrier for new contributors.

**Comment by sqrrm** [comment]
I agree that it's a requirement that building for jdk8 doesn't break or get overly complicated. From what I have understood though it might be possible to get maven to choose which version it compiles for automatically and use the specific source files when they differ.

If that doesn't work maybe a jdk9 branch could work as a solution for those that require jdk9, knowing that it wouldn't be well maintained. Could cause more issues in the end though with an unmaintained branch.

**Comment by eigenwillig** [comment]
What's the progress?

**Comment by ManfredKarrer** [comment]
We don't have the dev resources atm to work on the transition to jdk9...
