### ISSUE TITLE
No Transactions available

### ISSUE THREAD

**Issue by tkemmere** [bisq-network/bisq#983]
I opened up Bisq v0.5.3 after quite a few months. It was June. Under Funds > Transactiosn it says "No transactions available". I'm sure there should be quite a list. All Balances, Available, Reserved and Locked are also on zero.
I was able to open Bisq using the password, and even took it off. So it is correct. I wanted to check whether I left some small change in this wallet, I can't see anything, so unclear.

I wonder why is this...?

Thanks for the support. Regards.

**Comment by ManfredKarrer** [comment]
I assume you updated from pre 0.5 to 0.5.3. that was a not abckward compatible update and all the data and wallet are separated. you can still start up the old 0.4.9 app to get out your funds. but u cannot import the seed words to the new app because the wallet format changed, so u need to send it by a btc tx.

**Comment by tkemmere** [comment]
Hi Manfred,
Sorry I left this open for so long. Life is too busy.
I found it! 0.5.3 and 0.4.9 were both still on my machine! Hidden in users/.../appdata/...
I saw all the Tx again and the balance I had left was already so small it could be emptied no further.
Thanks again, case closed.
Regards, Thomas.
