### ISSUE TITLE
Create docker bootstrap node config

### ISSUE THREAD

**Issue by notmandatory** [bisq-network/bisq#99]
**Motivation**

It should be easy for new users to deploy a test Bitsquare bootstrap node.  Docker is a good way to package our bootstrap node application for easy deployment to a cloud host provider or on a local host.

**Goals**
- must be checked into new GitHub bitsquare/bootstrap-node sub-project 
- must include Bitsquare DHT bootstrap node
- should include instructions for deploying on example cloud host provider (ie. Digital Ocean)
- could include instructions for deploying to local Linux, MacOSX, or Windows host
- could include bitcoind testnet node 

**Related Links**

Docker is a technology for developing, shipping, and running applications.  
https://docs.docker.com/userguide/dockerizing/

**Comment by btcll** [comment]
It would be wonderful if the seed node was queryable via RPC or something similar. It would be great to give a sneak peak of the order book on the website eventually :)

**Comment by ManfredKarrer** [comment]
I would separate that form the seed nodes. Any node connected to the network, could serve for that. Should not be too hard to add that when we are a bit futher with the core problems.

**Comment by ghost** [comment]
I will accept this assignment.

**Comment by notmandatory** [comment]
Updated description, replaced seed node with bootstrap node to align with description of Kademlia protocol:
http://en.wikipedia.org/wiki/Kademlia#Joining_the_network

**Comment by ghost** [comment]
I am currently working this issue using a command line to launch the app. 

java -cp "build/libs/bitsquare-0.1.0-SNAPSHOT.jar:build/install/bitsquare/lib/*" io.bitsquare.Bitsquare -s -p 5001 

Can someone please advise me on the best and proper way to launch this?

**Comment by cbeams** [comment]
Use `./gradlew shadowJar` to produce an executable jar. You can then run it more easily, like this:

```
java -jar build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar -s -p 5001
```

Please note recent changes to the command line arguments however (and a few more are on the way right now). Just update to the latest from master and run the command above with `--help` for details.

**Comment by ghost** [comment]
Thanks.  I will try using the shadow jar technique.

How can I tell it is working correctly when it is running in the docker
image or any place for that matter?  I can see the process running using ps
-ef and find it that way, I can save the PID to a /tmp file and I guess
check on the logs.   I have a bash script to start it as a service from
init.d as well.

Ivan S Kirkpatrick, PE ivank2139@tessaract.net
Tessaract Productions LLC http://www.tessaract.net

**Comment by ManfredKarrer** [comment]
Hi @ivank2139,

There have been a lot of recent changes, so update all and refresh gradle.

The create a jar for the Bitsquare app use:
cd /path_to_your_project_dir/
./gradlew clean shadowJar
 java -jar build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar

We dont have a separate gradle taks for building the BootstrapNode jar yet, but you can simply rename the main class in the build.gradle file then it creates you a jar for the Bootstrap node.

Instead of :
mainClassName = "io.bitsquare.app.gui.BitsquareAppMain"
use:
mainClassName = "io.bitsquare.app.cli.BootstrapNodeMain"

Then run the jar with a UID used for that bootstrap node. When testing locally just use localhost, for the serverside nodes we use at the moment a namespace scheme, eg. digitalocean1.bitsquare.io... 
java -jar build/libs/bitsquare-0.1.0-SNAPSHOT-all.jar --name localhost

If its correctly started up it should log something like:
16:06:11.436 [main] INFO  net.tomp2p.connection.PeerCreator - Status of external search: Discover status:  ++en0( /fe80:0:0:0:d69a:20ff:feff:6557%en0,/192.168.1.33), ++lo0( /fe80:0:0:0:0:0:0:1%lo0,/0:0:0:0:0:0:0:1,/127.0.0.1). 
16:06:11.440 [main] INFO  net.tomp2p.connection.PeerCreator - Visible address to other peers: paddr[0x334389048b872a533002b34d73f8c29fd09efc50[/192.168.1.33,7366]]/relay(false)/slow(false) 
16:06:11.498 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on broadcast address: /192.168.1.255 on port udp: 7366 
16:06:11.601 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /fe80:0:0:0:d69a:20ff:feff:6557%en0 on port udp: 7366 and tcp:7366 
16:06:11.611 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /192.168.1.33 on port udp: 7366 and tcp:7366 
16:06:11.612 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /fe80:0:0:0:0:0:0:1%lo0 on port udp: 7366 and tcp:7366 
16:06:11.613 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /0:0:0:0:0:0:0:1 on port udp: 7366 and tcp:7366 
16:06:11.613 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /127.0.0.1 on port udp: 7366 and tcp:7366 
16:06:11.647 [main] DEBUG io.bitsquare.app.cli.BootstrapNode - started 

To connect a local Bitsquare client to your local bootstrap node you can pass those program args:
--bootstrap.node.ip=127.0.0.1 --bootstrap.node.port=7366 --bootstrap.node.name=localhost --port=7367 --bitcoin.network=regtest

7366 is the default port
in --bitcoin.network you can defien regtest or testnet

Starting the Bitsquare client without any args will connect to a serverside bootstrap node.
If you have a server where you want to put the bootstrap node you can config it with the --bootstrap.node.\* properties.

To config a docker instance for a bootstrap node we need basically the ip, port and UID.

**Comment by ghost** [comment]
Thanks for your help.   I have most of the Docker file in place and
working.  A few more refinements and it will be ready for my local testing
as you have noted.

Ivan S Kirkpatrick, PE ivank2139@tessaract.net
Tessaract Productions LLC http://www.tessaract.net

**Comment by ghost** [comment]
The startup has some error messages.  

I updated the project files. and built the new shadowJar after editing the build.gradle to specify mainClassName = "io.bitsquare.app.cli.BootstrapNodeMain".

I am getting messages that indicate the tomp2p cannot connect.
I note that this issue of errors from tomp2p existed before this change.  Is there some command I can use to insure that tomp2p is properly updated?

18:10:52.007 [pool-1-thread-1] INFO  net.tomp2p.connection.ChannelServer - Listening on address: /127.0.0.1 on port udp: 5001 and tcp:5001 
18:10:52.008 [pool-1-thread-1] DEBUG net.tomp2p.connection.ChannelServer - binding not successful java.net.BindException: Address already in use

I tried it without specifying the --port first and got the same response. As far as I know (I checked with netstat -tapen | grep ":5001 ", etc ) these ports are free.

**Comment by ManfredKarrer** [comment]
That is strange as the current code base does not use that port anymore. Are you sure you have the lastest master version?
