### ISSUE TITLE
Impossible to erase the file of chain SPV

### ISSUE THREAD

**Issue by mdefrancis** [bisq-network/bisq#996]
Attached the log file.
Problem only using Litecoin.
[bisq.log](https://github.com/bisq-network/exchange/files/1447468/bisq.log)

**Comment by ManfredKarrer** [comment]
Can you try again. the seednode was not running.

**Comment by mdefrancis** [comment]
After 24h running, problem still visible.
Are not enough peers in TOR?

**Comment by ManfredKarrer** [comment]
I will look later into it. Busy with release preparation atm.... Btw: there is anyway basically zero activity on Litecoin and Dash.

**Comment by mdefrancis** [comment]
Yes. I see zero activity on Litecoin. I was not sure if it was a problem in my network or in the software.

**Comment by ManfredKarrer** [comment]
The networks was running without issues for months. Just recently I stopped monitoring and taking effort in it because of the lack of interest. Doge we have already stopped - there was really zero activity. Dash and LTC have been at least a few trades. We keep them as backup if the BTC chain got attacked so hard that it becomes un-usable (not assuming but good to have).

**Comment by ManfredKarrer** [comment]
LTC is not supported anymore. So I close that issue.
